### ISSUE TITLE
Wrong Apple ProRes Profile

### ISSUE THREAD

**Issue by sevsh** [Xaymar/obs-StreamFX#100]
First of all: Thank you for your great work!
![2019-12-04 16_31_52-Aktuelle Medieninformationen](https://user-images.githubusercontent.com/1125206/70157032-1ecf1180-16b5-11ea-9a3d-491a1a4997ff.png)
![2019-12-04 16_32_01-Settings](https://user-images.githubusercontent.com/1125206/70157033-1f67a800-16b5-11ea-968b-f5a07451d2eb.png)

### Description
If I use your encoder to record in Apple ProRes, the final file will have the wrong profile "Apple ProRes 422 HQ (apch)" in the codec- / metainfo regardless my profile selection in OBS (e.g LT, Standard, etc.). That's why my Adobe Premiere Pro 2019 crashs if I try to import the file with the wrong profile in the codec-/metainfo. I tried it on 2 different systems with the same settings and the same result.

### Expected Behavior
File with the selected profile in the codec-/metainfo.

### Reproduction Steps
OBS 24.0.3 with OBS ffmpeg Encoder 0.4.0
Output => Recording
Format: mov
Encoder: Apple ProRes (prores_aw)
Profile: 422 Light/LT (APCS)
Resolution: 3840x2160@29.97fps

FFMPEG OPTIONS
no custom settings
GPU: 0
Override Color format: yuv422p10le
number of threads: 0
Standard Compliance: Normal

### System Information
- Software Version: OBS 24.0.3 with OBS ffmpeg Encoder 0.4.0
- Operating System: Windows 10
- Kernel Version: 1903 Windows 10
- CPU: AMD Ryzen 9 3900X
- GPU: ASUS RTX 2080 Ti
- RAM: 32GB (2x16GB) G.Skill Trident Z RGB 3000MHz CL14

### Checklist:
- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
Not fixed by the latest obs-studio update. In fact it is now worse, as color range is also not working anymore.

**Comment by Xaymar** [comment]
This is effectively outside of my control from what I can tell. I have no way to affect the OBS muxer in any useful way.
