### ISSUE TITLE
Some text tooltip labels are missing

### ISSUE THREAD

**Issue by UserNaem** [Xaymar/obs-StreamFX#101]
### Checklist:

- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.

![image](https://user-images.githubusercontent.com/21028464/68080127-7d834000-fe16-11e9-91ae-365bb854dceb.png)

**Other Options**
B-Frame Reference Mode
**Key Frames**
Interval (hover the 2.00 seconds default)

**H264 and HEVC encoders:**
**H264 and HEVC**
Preset
Profile
Level
**HEVC**
Tier
**Rate control options**
Rate control mode
**Bitrate limits**
Target Bitrate
Maximum Bitrate

**ProRes encoder**
Profile

If you didn't come up with any text for these labels, I can do them and submit a PR

**Comment by Xaymar** [comment]
Tool-Tips have been completely removed in favor of a Open Manual button.
