### ISSUE TITLE
StreamFX 0.12.0 Beta 164 doesn't work on OBS 29.0.0 stable

### ISSUE THREAD

**Issue by KaleidonKep99** [Xaymar/obs-StreamFX#1011]
### OBS Studio Logs

11:05:40.506: CPU Name: AMD Ryzen 9 5900X 12-Core Processor            
11:05:40.506: CPU Speed: 3700MHz
11:05:40.506: Physical Cores: 12, Logical Cores: 24
11:05:40.506: Physical Memory: 32689MB Total, 23909MB Free
11:05:40.506: Windows Version: 10.0 Build 22621 (release: 22H2; revision: 963; 64-bit)
11:05:40.506: Running as administrator: true
11:05:40.507: Windows 10/11 Gaming Features:
11:05:40.507: 	Game Bar: Off
11:05:40.507: 	Game DVR: Off
11:05:40.507: 	Game DVR Background Recording: Off
11:05:40.507: 	Game Mode: Probably On (no reg key set)
11:05:40.507: 	Hardware GPU Scheduler: Off
11:05:40.511: Sec. Software Status:
11:05:40.513: 	Windows Firewall: enabled (FW)
11:05:40.513: Current Date/Time: 2023-01-09, 11:05:40
11:05:40.513: Browser Hardware Acceleration: true
11:05:40.513: Hide OBS windows from screen capture: false
11:05:40.513: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
11:05:40.513: Portable mode: false
11:05:42.071: OBS 29.0.0 (64-bit, windows)
11:05:42.071: ---------------------------------
11:05:42.072: ---------------------------------
11:05:42.072: audio settings reset:
11:05:42.072: 	samples per sec: 48000
11:05:42.072: 	speakers:        2
11:05:42.072: 	max buffering:   960 milliseconds
11:05:42.072: 	buffering type:  dynamically increasing
11:05:42.073: ---------------------------------
11:05:42.073: Initializing D3D11...
11:05:42.073: Available Video Adapters: 
11:05:42.082: 	Adapter 0: NVIDIA GeForce GTX 1660 SUPER
11:05:42.082: 	  Dedicated VRAM: 1975517184
11:05:42.082: 	  Shared VRAM:    4253552640
11:05:42.082: 	  PCI ID:         10de:21c4
11:05:42.082: 	  Driver Version: 31.0.15.2756
11:05:42.082: 	  output 0:
11:05:42.082: 	    name=LG ULTRAGEAR
11:05:42.082: 	    pos={0, 0}
11:05:42.082: 	    size={2560, 1440}
11:05:42.082: 	    attached=true
11:05:42.082: 	    refresh=180
11:05:42.082: 	    space=RGB_FULL_G22_NONE_P709
11:05:42.082: 	    sdr_white_nits=80
11:05:42.082: 	    nit_range=[min=0.391500, max=408.760010, max_full_frame=408.760010]
11:05:42.082: 	  output 1:
11:05:42.082: 	    name=SyncMaster
11:05:42.082: 	    pos={1188, -1080}
11:05:42.082: 	    size={1920, 1080}
11:05:42.082: 	    attached=true
11:05:42.082: 	    refresh=60
11:05:42.082: 	    space=RGB_FULL_G22_NONE_P709
11:05:42.082: 	    sdr_white_nits=80
11:05:42.082: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
11:05:42.082: 	  output 2:
11:05:42.082: 	    name=HP 23xi
11:05:42.082: 	    pos={-1920, 339}
11:05:42.082: 	    size={1920, 1080}
11:05:42.082: 	    attached=true
11:05:42.082: 	    refresh=75
11:05:42.082: 	    space=RGB_FULL_G22_NONE_P709
11:05:42.082: 	    sdr_white_nits=80
11:05:42.082: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
11:05:42.082: 	Adapter 1: NVIDIA GeForce GTX 750 Ti
11:05:42.082: 	  Dedicated VRAM: 4248764416
11:05:42.082: 	  Shared VRAM:    4253552640
11:05:42.082: 	  PCI ID:         10de:1380
11:05:42.083: 	  Driver Version: 31.0.15.2756
11:05:42.086: Loading up D3D11 on adapter NVIDIA GeForce GTX 1660 SUPER (0)
11:05:42.140: D3D11 loaded successfully, feature level used: b000
11:05:42.140: DXGI increase maximum frame latency success
11:05:42.140: D3D11 GPU priority setup success
11:05:43.151: ---------------------------------
11:05:43.151: video settings reset:
11:05:43.151: 	base resolution:   2560x1440
11:05:43.151: 	output resolution: 2560x1440
11:05:43.151: 	downscale filter:  Bilinear
11:05:43.151: 	fps:               60/1
11:05:43.151: 	format:            NV12
11:05:43.151: 	YUV mode:          Rec. 709/Partial
11:05:43.151: NV12 texture support enabled
11:05:43.151: P010 texture support not available
11:05:43.153: Audio monitoring device:
11:05:43.153: 	name: Headphones (Realtek(R) Audio)
11:05:43.153: 	id: {0.0.0.00000000}.{7377f0e9-60db-4297-a5e7-9fcdc4cd5082}
11:05:43.153: ---------------------------------
11:05:43.154: Skipping module '../../obs-plugins/64bit/advanced-scene-switcher-lib.dll', not an OBS plugin
11:05:43.158: [adv-ss] version: 1.19.2
11:05:43.158: [adv-ss] version: 9bcced524bc456f3095b977f3af5966dfe14703e
11:05:43.160: [adv-ss] curl loaded successfully
11:05:43.160: [adv-ss] found curl library
11:05:43.160: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.dll"
11:05:43.164: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.dll"
11:05:43.164: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-openvr.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-openvr.dll"
11:05:43.166: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d460.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d460.dll"
11:05:43.166: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core460.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core460.dll"
11:05:43.166: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d460.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d460.dll"
11:05:43.166: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann460.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann460.dll"
11:05:43.166: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc460.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc460.dll"
11:05:43.166: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect460.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect460.dll"
11:05:43.166: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/openvr_api.dll"
11:05:43.166: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/openvr_api.dll"
11:05:43.211: No AJA devices found, skipping loading AJA UI plugin
11:05:43.211: Failed to initialize module 'aja-output-ui.dll'
11:05:43.212: No AJA devices found, skipping loading AJA plugin
11:05:43.212: Failed to initialize module 'aja.dll'
11:05:43.212: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
11:05:43.220: [CoreAudio encoder]: Adding CoreAudio AAC encoder
11:05:43.221: Failed to load 'en-US' text for module: 'decklink-captions.dll'
11:05:43.222: Failed to load 'en-US' text for module: 'decklink-output-ui.dll'
11:05:43.223: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
11:05:43.223: Failed to initialize module 'decklink.dll'
11:05:43.252: [AMF] Unable to load 'amfrt64.dll', error code 126.
11:05:43.253: [AMF] AMF Test failed due to one or more errors.
11:05:43.253: Failed to initialize module 'enc-amf.dll'
11:05:43.260: [Python] Could not load library: C:/Users/bribi/AppData/Local/Programs/Python/Python36/
11:05:43.261: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
11:05:43.261: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
11:05:43.262: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
11:05:43.311: [obs-browser]: Version 2.19.0
11:05:43.311: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2591+g4204d54+chromium-103.0.5060.134 (compiled)
11:05:43.315: NVENC supported
11:05:43.493: [NVENC] AV1 is not supported
11:05:43.495: [noise suppress]: NVIDIA denoiser disabled, redistributable not found or could not be loaded.
11:05:43.497: Failed to get NVVideoEffects.dll version info size
11:05:43.500: [NVIDIA VIDEO FX]: FX disabled, redistributable not found or could not be loaded.
11:05:43.543: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1)
11:05:43.543: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1
11:05:43.543: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
11:05:43.549: [obs-websocket] [obs_module_load] Module loaded.
11:05:43.556: [vlc-video]: VLC 3.0.18 Vetinari found, VLC video source enabled
11:05:43.558: Failed to load 'en-US' text for module: 'win-capture-audio.dll'
11:05:43.558: [win-capture-audio] Version 2.2.3 (74323e6)
11:05:43.568: Module 'C:\ProgramData\obs-studio/plugins/StreamFX/bin/64bit/StreamFX.dll' not loaded

### Current and Expected Behavior

Current behavior:
- StreamFX won't load on OBS 29.0.0, even though it is marked as the recommended version.

Expected behavior:
- StreamFX is expected to be loaded properly and work.

### Steps to Reproduce the Problem

Steps:
- Install OBS 29.0.0 beta 3
- Install StreamFX 0.12.0 Beta 164
- Test, StreamFX will work as expected
- Update to OBS 29.0.0 stable
- StreamFX quits working

**Comment by Xaymar** [comment]
What a way to ignore multiple warnings about everything. Great job, try reading the release notes and the text on the new issues page next time.
