### ISSUE TITLE
Reduced color opacity

### ISSUE THREAD

**Issue by Dydimoshn** [Xaymar/obs-StreamFX#104]
### Description
Good night / days

In previous versions, the 3D effect that was applied in this other plugin worked perfect (The yellow color looks great).
https://imgur.com/aD4G64d (The image corresponds to a video from 6 months ago.)

But in this latest version ... the yellow color is blurred ... or with the reduced opacity ... is there any solution to this?
https://imgur.com/Abtemwv (The image is from today)

### Expected Behavior
That the current version works like version 0.7.1.0

### Reproduction Steps

1. Open a portal to the Infinite Void
2. Summon an ancient God
3. Realize your mistake

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: Win 10 x64
- Kernel Version: 1909 (Windows)
- CPU: Intel i5 3570, 
- GPU: Nvidia GTX950, 
- RAM: 12GB 1333 mhz

### Checklist:

- [x ] I have read the contribution guidelines.
- [ ] I can reproduce the issue with the exact reproduction steps I have provided.
- [ ] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
This will likely be fixed if I ever figure out how to do the entire 3D transform stuff without the need of an additional texture.

**Comment by Xaymar** [comment]
You can find binaries that fix the issue here: https://github.com/Xaymar/obs-StreamFX/actions/runs/51139414 (or wait for a future release).

**Comment by Dydimoshn** [comment]
Thank you very much, but I don't know what to do with the link you've posted.

I think I'll wait and be aware of a new update

**Comment by Xaymar** [comment]
There's two artifacts shown in the link, "windows" and "windows-speed" which contain bleeding-edge builds of the plugin.
