### ISSUE TITLE
Source mirror flickfer, skip frame, black screen

### ISSUE THREAD

**Issue by Danjuanlab** [Xaymar/obs-StreamFX#106]
V0.8.0 Use source mirror to copy the same scene camera in different scenes, screen flickering, frame skipping, black screen for a short time will appear.

V0.7.1 It is fine.

 OBS Studio V24.0.3
win10 64bit

I use source mirror in different scenes to duplicate the same camera scene, and the above problem occurs. I have attached a video of the problem in the attachment.

[0.7.1 version.zip](https://github.com/Xaymar/obs-StreamFX/files/4250460/0.7.1.version.zip)
[0.8.0 version skip frame.zip](https://github.com/Xaymar/obs-StreamFX/files/4250461/0.8.0.version.skip.frame.zip)

[filcker and black screen.zip](https://github.com/Xaymar/obs-StreamFX/files/4250485/filcker.and.black.screen.zip)

**Comment by Xaymar** [comment]
Known issue in 0.8, unfortunately nobody has tested the fix yet. See #99 for the fix.

**Comment by Danjuanlab** [comment]
> Known issue in 0.8, unfortunately nobody has tested the fix yet. See #99 for the fix.

After 5 tests, none of the above bugs appear in this fixed version.
