### ISSUE TITLE
Bitrate is restricted in CQ mode with no limit present in config

### ISSUE THREAD

**Issue by Vrael0n** [Xaymar/obs-StreamFX#108]
Build: CI #450
Hardware: R9 3950X, 1080 Ti, 32GB RAM
Software: Windows 10 Pro (1909), OBS x64 24.0.3

I am recording at 4K 60FPS with "H.265/HEVC Nvidia NVENC (Hardware)" at CQP 16 and my bitrate will not exceed 7Mbps. This issue is not present in the standalone obs-ffmpeg-encoder where I can get peeks in excess of 150Mbps with CQP 16.

Here is my recordEncoder.json:
{
    "AQ.Spatial": 0,
    "AQ.Temporal": 0,
    "H265.Tier": 1,
    "Other.BFrames": 0,
    "Preset": 4,
    "RateControl.QP.B": 16,
    "RateControl.QP.I": 16,
    "RateControl.QP.P": 16
}

Here is a screenshot of my in program config:
<img width="492" alt="streamfx" src="https://user-images.githubusercontent.com/61518774/75727394-b2ef4b80-5c99-11ea-9c60-7f61b50000a3.png">

**Comment by Xaymar** [comment]
![image](https://user-images.githubusercontent.com/437395/76133043-76fc1380-6016-11ea-9324-d5b103a46912.png)

Fixed by f2913685edc71375928a57217cae679d996571fe
