### ISSUE TITLE
Detect if necessary Visual C++ Redistributables have been installed during install

### ISSUE THREAD

**Issue by LucasParsy** [Xaymar/obs-StreamFX#114]
# Description
On windows 10, I installed OBS Studio, then StreamFX. 
I didn't correctly read the Wiki, and forgot to install the Microsoft Visual C++ 2019 Redistribuables.

At run time, the plugins did not appear.
In the logs the following info appeared:
```
LoadLibrary failed for '../../obs-plugins/64bit/StreamFX.dll': The specified module could not be found.
(126)
Module '../../obs-plugins/64bit/StreamFX.dll' not loaded
```
### Expected Behavior
  Download the installer, and just have StreamFX working, or warn me of the missing dependency.

### proposed solution:
  Add a warning in the StreamFX installer when the redistribuables are not present on the user machine, and redirect on a way to install them.
If possible, embed a copy of the redistribuable in the installer?

Or add a warning at the bottom of the release notes, next to the download link, saying that the redistribuables are required and provide a link to them.

**Comment by Xaymar** [comment]
It is not possible to embed the redistributables due to the GPL license. [The Installer guide already links to them as required.](https://github.com/Xaymar/obs-StreamFX/wiki/Installation)

**Comment by Xaymar** [comment]
Pushed this forward to the 0.9.0 release, as reading is apparently a difficult thing.

**Comment by Xaymar** [comment]
I'm now testing the [solution I came up with](https://github.com/Xaymar/msvc-redist-helper), which will be in 0.9.0a2 if it ends up working fine.

**Comment by Xaymar** [comment]
Implemented in future versions.
