### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Xaymar/obs-StreamFX#115]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like in [the function “_destroy”](https://github.com/Xaymar/obs-StreamFX/blob/403aae4eb95e03f6bce8d0575aa18de245cdcfda/source/obs/obs-source-factory.hpp#L235 "Update candidate").

**Comment by Xaymar** [comment]
There's probably more places like that in the source code. I haven't run a validator over it for a while now.

**Comment by Xaymar** [comment]
Closing due to this not being a pull request. I can run a static code analyzer myself once it is actually time to do so, so this issue is _not helpful_.
