### ISSUE TITLE
[Linux] Some features fail to compile

### ISSUE THREAD

**Issue by kaiserschwarcz** [Xaymar/obs-StreamFX#119]
### Description 

During installation _make -j4_ step some error messages regarding _source/util-profiler_ file are shown and the installation process can't continue.

> <directory>/obs-studio/plugins/StreamFX/source/util-profiler.cpp:77:1: **error: ‘double_t’** does not name a type; did you mean **‘double’**?
   77 | **double_t** util::profiler::average_duration()
        | ^~~~~~~~
        | **double**
<directory>/obs-studio/plugins/StreamFX/source/util-profiler.cpp:102:26: **error: ‘std::chrono::nanoseconds util::profiler::percentile’** is not a static data member of **‘class util::profiler’**
  102 | std::chrono::nanoseconds **util**::profiler::percentile(double_t percentile, bool by_time)
      |                          ^~~~
<directory>/obs-studio/plugins/StreamFX/source/util-profiler.cpp:102:53: **error: ‘double_t’** was not declared in this scope; did you mean **‘double’**?
  102 | std::chrono::nanoseconds util::profiler::percentile(**double_t** percentile, bool by_time)
      |                                                     ^~~~~~~~
      |                                                     double
<directory>/obs-studio/plugins/StreamFX/source/util-profiler.cpp:102:74: **error**: expected primary-expression before **‘bool’**
  102 | std::chrono::nanoseconds util::profiler::percentile(double_t percentile, bool by_time)
      |                                                                          ^~~~
<directory>/obs-studio/plugins/StreamFX/source/util-profiler.cpp:103:1: **error:** expected **‘,’** or **‘;’** before **‘{’** token
  103 | {
      | ^

### Expected Behavior

Normal finishing of installation  

### Reproduction Steps

1. wget https://cdn-fastly.obsproject.com/downloads/cef_binary_3770_linux64.tar.bz2
2. tar -xjf ./cef_binary_3770_linux64.tar.bz2
3. git clone --recursive https://github.com/obsproject/obs-studio.git
4. Download obs-StreamFX
5. copy obs-StreamFX to plugins directory
6. Add _add_subdirectory(obs-StreamFX)_ to CMakeLists.txt
7. go to obs-studio/build 
8. cmake -DUNIX_STRUCTURE=1 -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_3770_linux64" .. 
9. make -j4

### System Information

- Software Version: 25.0.3-14-gb9f77023 (64 bit)
- Operating System: Fedora 31
- Kernel Version: 5.5.9-200.fc31.x86_64
- CPU: Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
- GPU: VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35) (prog-if 00 [VGA controller])
- RAM: 4 GB

### Checklist:

- [X] I have read the contribution guidelines.
- [X] I can reproduce the issue with the exact reproduction steps I have provided.
- [X] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
I added a new include to the file which should hopefully resolve the issue.

**Comment by kaiserschwarcz** [comment]
Xaymar, it solves the previous bug, but now it stops in another issue.

> /home/kaiserschwarcz/Documentos/obs-studio/plugins/obs-StreamFX/source/util-threadpool.hpp:35:8: **error:** ‘condition_variable’ in namespace ‘std’ does not name a type
   35 |   std::**condition_variable**                                            _tasks_cv;
      |        **^~~~~~~~~~~~~~~~~~**

Should I open another thread for this one?

Thanks.

**Comment by Xaymar** [comment]
It's fine to reuse this thread as it's a generic issue with the code itself. I've committed another fix for that one.

**Comment by Gleapsite** [comment]
I'm compiling under Ubuntu,  Used gitclone instead of wget for obs source, but followed the same steps otherwise.   Here's the compilation error I received:

`obs-studio/plugins/obs-stream-effects/source/obs/gs/gs-effect-parameter.cpp:110:25: error: ‘strnlen_s’ was not declared in this scope; did you mean ‘
strnlen’?
  110 |  size_t      name_len = strnlen_s(name_c, 256);`

**Comment by kaiserschwarcz** [comment]
After the fix of the last error (**‘condition_variable’ error**)  I'm stucked in this one: 

> /obs-studio/plugins/obs-StreamFX/source/obs/gs/gs-effect-parameter.cpp:110:25: **error: ‘strnlen_s’** was not declared in this scope; did you mean ‘strnlen’?

>  110 |  size_t      name_len = **strnlen_s**(name_c, 256);
      |                         **^~~~~~~~~**
      |                         **strnlen**

> make[2]: *** [plugins/obs-StreamFX/CMakeFiles/StreamFX.dir/build.make:167: plugins/obs-StreamFX/CMakeFiles/StreamFX.dir/source/obs/gs/gs-effect-parameter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1655: plugins/obs-StreamFX/CMakeFiles/StreamFX.dir/all] Error 2

It occurs still during the make -j4 command

**Comment by kaiserschwarcz** [comment]
> EDIT: strnlen_s Compilation Error I'm encountering is covered in another issue.

Which issue, @Gleapsite ? There is an specific theard for that?

**Comment by Gleapsite** [comment]
Its discussed here https://github.com/Xaymar/obs-StreamFX/issues/98#issuecomment-569267251

**Comment by Xaymar** [comment]
Since newer VS versions now have strnlen, this commit should fix that one: 451d31546f120f53c73b267fd77effc1c695fc21

**Comment by kaiserschwarcz** [comment]
This one was near the end.

> /obs-studio/plugins/obs-StreamFX/source/encoders/ffmpeg-encoder.cpp:1088:16: **error: ‘GS_INVALID_HANDLE’** was not declared in this scope
 1088 |  if (handle == **GS_INVALID_HANDLE**) {
      |                ^~~~~~~~~~~~~~~~~

**Comment by Xaymar** [comment]
Automated CI builds for linux are now working-ish on the `linux` branch. Will fix every error that appears and then merge back into master.

**Comment by Xaymar** [comment]
Linux builds currently disable obs-ffmpeg-encoder and filter-nv-face-tracking. Some other features may still be unimplemented at the current time.

**Comment by Xaymar** [comment]
This should now be fixed by #122.

**Comment by Xaymar** [comment]
FFmpeg Encoder is now available on Linux. Since Mipmapping is tracked by a different bug, and the underlying issue has been fixed, I'm closing this for tracking purposes.
