### ISSUE TITLE
Please rename libStreamFX.so -> StreamFX.so

### ISSUE THREAD

**Issue by yurivict** [Xaymar/obs-StreamFX#135]
Plugins aren't supposed to have the ```lib``` prefix. With the prefix they are recognized as shared libraries, for example by the FreeBSD ports framework.

**Comment by Xaymar** [comment]
I don't know what the FreeBSD ports framework is - not to mention that the plugin currently only supports ubuntu. As for the lib prefix, that is added by CMake - if you know how to remove it, consider making a PR for it.

**Comment by yurivict** [comment]
You need to add:
```
set_target_properties({target-name} PROPERTIES PREFIX "")  
```
