### ISSUE TITLE
Fails to find dll

### ISSUE THREAD

**Issue by javaarchive** [Xaymar/obs-StreamFX#138]
### Description
The StreamFX dll doesn't get loaded correctly on a non-admin installation of obs(I've checked and it's 64 bit because the bin folder only has a 64 bit directory). 
```
16:26:32.196: LoadLibrary failed for '../../obs-plugins/64bit/StreamFX.dll': The specified module could not be found.
16:26:32.196:  (126)
16:26:32.196: Module '../../obs-plugins/64bit/StreamFX.dll' not loaded
```
### Expected Behavior
Log file doesn't show errors about StreamFX, and I am able to find new effects

### Reproduction Steps

1. Download a zip file of 64 bit OBS Studio 25.0.1 and extract it
2. Download the zip of StreamFX and extract it to the newly downloaded OBS Studio installation
3. Run it and check the logs
### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

### Checklist:

- [x] I have read the contribution guidelines.
- [ ] I can reproduce the issue with the exact reproduction steps I have provided.
Currently cannot do this
- [ ] The issue appears on all of my systems that can run this software.
Haven't tested on my desktop yet

**Comment by Xaymar** [comment]
Hi, please fill out the entire template next time, including the system information. Anyway, your issue can likely be resolved by installing a more recent version of the Microsoft Visual C++ 2019 Redistributables: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by Xaymar** [comment]
~30 days have passed with no reply from the original reporter, and the original reporter has also not filled out the template. Therefore: Closing.
