### ISSUE TITLE
Endless recording stop

### ISSUE THREAD

**Issue by Ilya87** [Xaymar/obs-StreamFX#144]
### Description
I use OBS 25.0.1 with plugin version 0.8.0 alpha4 with attached settings. When I press stop recording button - it writes that recording is stopping endlessly.

### Expected Behavior
The recording should ends normally

### Reproduction Steps
Chose capture window, set the same settings as I and start recording (container for video - mkv). After about half of a minute press stop recording. 

### System Information
Windows 10, Nvidia Geforce 1070 Ti, Intel Core i5 8600K

### Checklist:

- [ ] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [ ] The issue appears on all of my systems that can run this software.
![Снимок экрана (728)](https://user-images.githubusercontent.com/1446573/78472006-41923500-773e-11ea-8c0f-f9f57271836f.png)

**Comment by Ilya87** [comment]
Need to mention - size of file, show by Properties dialog - 2 333 162 bytes, on disk size - 4 063 232 bytes. So, something is broken in here.

**Comment by Xaymar** [comment]
Please attach a log file, without a log file I can't help you.

**Comment by Ilya87** [comment]
[2020-04-05 13-15-23.txt](https://github.com/Xaymar/obs-StreamFX/files/4433328/2020-04-05.13-15-23.txt)

**Comment by Xaymar** [comment]
Managed to reproduce the issue, but this is most likely a user configuration error and unfixable from my end.

**Comment by Ilya87** [comment]
> Seeking to every 50th second is probably way out of spec too
50 second with 3 fps capture = one I-frame every 250 frames. Also remember - this settings are able to encode video.

**Comment by Xaymar** [comment]
Unable to repro this on the current version. The recording stops as expected after two keyframes have been written, and OBS waits until an additional keyframe is encoded before actually stopped encoding.

**Comment by Xaymar** [comment]
Still unable to repro this on any system. Therefore, closing.

**Comment by Xaymar** [comment]
Actual bug is from upstream FFmpeg, and outside of my control. Workaround is to disable "B-Frame Reference Mode" for recording - after all my optimized settings are for _streaming only_. See #260.
