### ISSUE TITLE
Installs the plugin into a wrong location

### ISSUE THREAD

**Issue by yurivict** [Xaymar/obs-StreamFX#151]
Version ```0.8.0b1```.
obs-studio-25.0.4
FreeBSD 12.1

### Description
Installs the plugin into a wrong location obs-plugins/bit64/StreamFX.so

See here: https://github.com/Xaymar/obs-StreamFX/blob/master/CMakeLists.txt#L993

### Expected Behavior
Should install into ```lib/obs-plugins```, because this is where all other plugins are installed.

There is no need to keep the bits information at all, because it should just build a correct version for the platform.

**Comment by Xaymar** [comment]
There is no Linux installer, and the "INSTALL" target is only used for building release archives - or installing locally. You should have a ".config/obs-studio" direcfory in your home folder.

**Comment by led78** [comment]
After extracting archive to ".config/obs-studio" directory, the plugin is still not showing in OBS 25. Normally all OBS plugins are actually installed in /usr/lib/obs-plugins.

**Comment by yurivict** [comment]
There is an ```install``` target in CMakeLists.txt

**Comment by Xaymar** [comment]
The install target is used to build release archives, not for direct installation - though on some platforms that does work. Please note that the _only_ supported Linux distribution currently is Ubuntu, which has the `/home/user/.config/obs-studio/` structure.

**Comment by yurivict** [comment]
> Please note that the only supported Linux distribution currently is Ubuntu, which has the /home/user/.config/obs-studio/ structure.

It is very easy to support other systems:
```
@@ -990,8 +990,8 @@ else()
 	else()
 		install(
 			TARGETS ${PROJECT_NAME}
-			RUNTIME DESTINATION "./obs-plugins/${BITS}bit/" COMPONENT Runtime
-			LIBRARY DESTINATION "./obs-plugins/${BITS}bit/" COMPONENT Runtime
+			RUNTIME DESTINATION "lib/obs-plugins" COMPONENT Runtime
+			LIBRARY DESTINATION "lib/obs-plugins" COMPONENT Runtime
 		)
 		if(MSVC)
 			install(
@@ -1003,7 +1003,7 @@ else()
 	
 		install(
 			DIRECTORY "data/"
-			DESTINATION "./data/obs-plugins/${PROJECT_NAME}/"
+			DESTINATION "share/obs/obs-plugins/${PROJECT_NAME}/"
 		)
 		
 		add_custom_target(
```

This patch installs plugins to the same location where other obs-* projects install them.

**Comment by Xaymar** [comment]
That patch doesn't add support for other systems, it replaces local installs for global installs. Does the platform you are trying to use the plugin on not have any way to locally store settings for each app? No hidden configuration directory?

**Comment by yurivict** [comment]
> Does the platform you are trying to use the plugin on not have any way to locally store settings for each app? No hidden configuration directory?

Your question implies that the user would build it manually. Software should be installed via package managers, and locally installed plugins wouldn't fix in this environment.

You should install plugins to the same location where OBS Studio itself looks for them.

Many systems have packages for OBS Studio: https://repology.org/project/obs-studio/versions Likewise, they would all support additional plugins installed into the same location.

**Comment by Xaymar** [comment]
Currently the only platforms supported are Windows and Ubuntu. Windows does not have a way to do local installs as far as I can tell, while Ubuntu does - and on Ubuntu that is the only way to install it. For any other platforms, you will indeed have to build it yourself - or submit PRs and actively become a maintainer. I can't provide support for other platforms, especially if people expect me to provide support.

> You should install plugins to the same location where OBS Studio itself looks for them.

On Ubuntu it is looking into `~/.config/obs-studio/plugins`, as shown by [this code](https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main.cpp#L141). Looking at it, it seems that other platforms also support local installs, so perhaps I can finally add that to Windows too - if it works it probably solves a lot of installation issues..

> Many systems have packages for OBS Studio: https://repology.org/project/obs-studio/versions Likewise, they would all support additional plugins installed into the same location.

As the plugin is not even 1.0, there is no reason to even have it in a package manager yet.

**Comment by yurivict** [comment]
> On Ubuntu it is looking into ~/.config/obs-studio/plugins

No, on all UNIX-like systems it also looks into ```$(PREFIX)/lib/obs-studio```:
```
$ ls -l /usr/local/lib/obs-plugins/
total 3016
-rwxr-xr-x  1 root  wheel  212848 Apr  8 23:46 decklink-ouput-ui.so
-rwxr-xr-x  1 root  wheel  404880 Apr  8 23:46 frontend-tools.so
-rwxr-xr-x  1 root  wheel   37368 Apr  8 23:46 image-source.so
-rwxr-xr-x  1 root  wheel   78368 Apr  8 23:46 linux-capture.so
-rwxr-xr-x  1 root  wheel   19368 Apr  8 23:46 linux-jack.so
-rwxr-xr-x  1 root  wheel   28208 Apr  8 23:46 linux-pulseaudio.so
-rwxr-xr-x  1 root  wheel   40344 Apr  8 23:46 linux-v4l2.so
-rwxr-xr-x  1 root  wheel  116856 Apr  8 23:46 obs-ffmpeg.so
-rwxr-xr-x  1 root  wheel  100832 Apr  8 23:46 obs-filters.so
-rwxr-xr-x  1 root  wheel   27216 Apr  8 23:46 obs-libfdk.so
-rwxr-xr-x  1 root  wheel  147856 Apr  8 23:46 obs-outputs.so
-rwxr-xr-x  1 root  wheel   38424 Apr  8 23:46 obs-transitions.so
-rwxr-xr-x  1 root  wheel   31632 Apr  8 23:46 obs-x264.so
-rwxr-xr-x  1 root  wheel   44416 Apr  8 23:46 rtmp-services.so
-rwxr-xr-x  1 root  wheel   56608 Apr  4 15:02 spectralizer.so
-rwxr-xr-x  1 root  wheel   36816 Apr  8 23:46 text-freetype2.so
-rwxr-xr-x  1 root  wheel   44200 Apr  8 23:46 vlc-video.so
```

That's where your plugin should also go by default. The patch above does this.

**Comment by yurivict** [comment]
> Currently the only platforms supported are Windows and Ubuntu.

There should be no need to make such statement. This is a cmake-based project, which means that it supports a wide variety of systems in a unified way.

**Comment by Xaymar** [comment]
> That's where your plugin should also go by default. The patch above does this.

That is a matter of preference, as OBS Studio supports both local and global plugin installations. If you wish to have it globally installed, you will either have to add an option to the CMake file and PR it, or continue using it as a local plugin install.

Official releases will always use the most ideal way for the platform, which on Windows is currently a global install, and on Ubuntu is a local install.

> There should be no need to make such statement. This is a cmake-based project, which means that it supports a wide variety of systems in a unified way.

Once again, I can't offer support for other platforms than Windows or Ubuntu as I do not use them. This has nothing to do with it being a CMake-based project at all, as I just would not be able to help users when they run into a problem. Please understand this.

Unless you are willing to step up as the official maintainer for the operating system that you want, this will not change.

**Comment by yurivict** [comment]
Example of the correct behavior: https://github.com/Palakis/obs-ndi/blob/master/CMakeLists.txt#L170

**Comment by Xaymar** [comment]
@yurivict Unless you are stepping up to add this to the CMake, the current local installation method will not change. There's no reason to change it as it works fine and does not require root rights to install.

**Comment by yurivict** [comment]
> Unless you are stepping up to add this to the CMake, the current local installation method will not change.

I would just keep a patch in the FreeBSD port patching ```CMakeLists.txt``` to have a correct behavior.

Other OSes didn't even make packages for your project (https://repology.org/project/obs-streamfx/versions). They will all have the same issue once they try.

**Comment by Xaymar** [comment]
Note, the current behavior **is already correct**. What you're asking for is that the plugin supports global installations, which is an extra. I will be closing this now as we are clearly getting nowhere with this.
