### ISSUE TITLE
GLIBCXX_3.4.26 not found for StreamFX 0.8.0 Beta 1

### ISSUE THREAD

**Issue by maxdrash** [Xaymar/obs-StreamFX#155]
On the latest SFX 0.8.0 beta 1 picked from your releases, i have a library error when loading OBS 25.0.5 on Ubuntu 18.04.

`11:58:29.979: os_dlopen(/home/maxime/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so->/home/maxime/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/maxime/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so)`

Theres no GLIBCXX_3.4.26 in the latest libstdc+++6 from repository.

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIB
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.14
GLIBC_2.4
GLIBC_2.18
GLIBC_2.16
GLIBC_2.3.4
GLIBC_2.17
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Can you tell me if a solution exists for ubuntu 18.04 ?

Thank you.

**Comment by Xaymar** [comment]
Running `sudo apt install libstdc++6` in a Terminal should fix it.

**Comment by maxdrash** [comment]
I have libstdc++6 8.4.0-1ubuntu1~18.04 already (from ubuntu repo), look at my strings part i've writed before.
I downloaded streamfx-ubuntu1804-0.8.0.0b1-771f4138.7z for ubuntu 18.04.

**Comment by romainrossi** [comment]
I can confirm that, exactly the same problem here.
I tested both binary release (for Ubuntu 18.04 and Ubuntu 19.10) on my Ubuntu 18.04; both are giving the same error as GLIBCXX_3.4.26 is not found.

**Comment by Xaymar** [comment]
As my 18.04 install currently Kernel Faults on boot, I can't verify what's causing the issue yet.

**Comment by spigot** [comment]
FYI building obs (25.0.5) & StreamFX (tried both master from today and 0.8.0b1) on Debian buster with libstdc++6 8.3.0 - not getting the same GLIBC error, but I don't see 3.4.26 in libstdc++.so.6 either (highest is 3.4.25 which matches with gcc-8 according to [this ABI doc](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)), and the error I do get when trying to add a blur filter is

obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/StreamFX.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv

**Comment by Xaymar** [comment]
> obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/StreamFX.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv

This usually indicates that the compiler does not fully support the C++ standard, or requires extra libraries to be linked in. I know that clang-9 no longer requires stdc++fs, but maybe it's still a requirement on gcc-8.

**Comment by misterinterrupt** [comment]
I don't really know, but I think this means the streamFX.so is looking for glibcxx version 3.4.26
that version is in g++9
https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04
I'm on Ubuntu and installing g++-9, made it load for me
but trying to add the effects themselves caused obs to crash
> Segmentation fault (core dumped)

**Comment by BrynGerard** [comment]
I can verify that I have experienced all that has been mentioned here with regards to Linux.  I compiled the package and there were no errors and the plugin is loaded by OBS at startup without errors. But if I select one of the effects, after naming it,  OBS crahes with no error message but via the console I get this "obs: symbol lookup error: /home/bryn/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv"

**Comment by BrynGerard** [comment]
I compiled it with g++8 on Ubuntu 18.04 after following the compile instructions to the letter.

**Comment by spigot** [comment]
> > obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/StreamFX.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv
> 
> This usually indicates that the compiler does not fully support the C++ standard, or requires extra libraries to be linked in. I know that clang-9 no longer requires stdc++fs, but maybe it's still a requirement on gcc-8.

from my research, that is correct. [this doc](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017) states "GCC 8.x requires linking with -lstdc++fs" and I can find the missing symbol in the output of strings run on libstdc++fs.a. also see [this cmake discussion](https://gitlab.kitware.com/cmake/cmake/issues/17834).

as a very crude hack to test, I added "stdc++fs" to the list of target_link_libraries in the CMakeLists.txt (just added stdc++fs after line 836), rebuilt the plugin with gcc 8.3.0, libstdc++6 8.3.0 and libstdc++-8-dev 8.3.0 (where libstdc++fs.a is found), and can successfully add a blur filter.

the reason I piggy-backed on this issue is because it looked like the missing symbol was added in 3.4.26(gcc-9).

**Comment by BrynGerard** [comment]
I have GCC 8.4.0. I tried to perform this hack myself but the compiler just seems to hang at "-- Build files have been written to: /home/bryn/Downloads/obs-StreamFX/build/flux/libobs-download". when I compiled it originally, It took a long time to complete so I will wait but it seems to be an excessive amount of time. (30 mins+ already). Where do I get stdc++fs?

**Comment by BrynGerard** [comment]
This did finally compile, I don't know how long it took but it looked like a lot of ugly messages on the screen :) when I returned to it. It did however work. I'm not sure about the Shader as I'm probably not using it right. Time to have a play.

**Comment by MarioMey** [comment]
> This did finally compile, I don't know how long it took but it looked like a lot of ugly messages on the screen :) when I returned to it. It did however work. I'm not sure about the Shader as I'm probably not using it right. Time to have a play.

Could you share with us the compiled file?

**Comment by Xaymar** [comment]
Try these binaries and see if they work.
[streamfx-ubuntu1804-0.8.0.23b1-91462cda.zip](https://github.com/Xaymar/obs-StreamFX/files/4519494/streamfx-ubuntu1804-0.8.0.23b1-91462cda.zip)

**Comment by romainrossi** [comment]
Running this give me this error :
`info: [StreamFX] Loading Version 0.8.0.23b1-91462cda
obs: symbol lookup error: /home/user/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so: undefined symbol: _ZN8streamfx2ui23qInitResources_streamfxEv
`

**Comment by MarioMey** [comment]
I know it was compiled in/to Ubuntu 18.04 but I wanted to give it a try here, Debian Buster. But no... I also have this error:

```
info: [StreamFX] Loading Version 0.8.0.23b1-91462cda
obs: symbol lookup error: /usr//lib/obs-plugins/StreamFX.so: undefined symbol: _ZN8streamfx2ui23qInitResources_streamfxEv

```

**Comment by BrynGerard** [comment]
I think Xaymar has resolved this so I would rather you get files from him. There could still be errors in the one I have compiled and I wouldn't want it to circulate it and muddy the waters for him.

**Comment by MarioMey** [comment]
> I think Xaymar has resolved this so I would rather you get files from him. There could still be errors in the one I have compiled and I wouldn't want it to circulate it and muddy the waters for him.

I tried the one from Xaymar.

**Comment by Xaymar** [comment]
[streamfx-ubuntu1804-gcc8-0.8.0.40b1-9f96c82e.zip](https://github.com/Xaymar/obs-StreamFX/files/4526442/streamfx-ubuntu1804-gcc8-0.8.0.40b1-9f96c82e.zip)

**Comment by MarioMey** [comment]
`obs: symbol lookup error: /usr//lib/obs-plugins/StreamFX.so: undefined symbol: _ZN8streamfx2ui23qInitResources_streamfxEv`

¯\\_(ツ)_/¯

Remember that I use Buster. I would like to use StreamFX... but it is not a big need for me. So, I'm just trying if these files work. If they don't, I don't have time to try different things... and less to use another distro.

Anyway, thanks for your time.

**Comment by Xaymar** [comment]
Debian Buster should be able to use the Ubuntu 19.10 binaries, or at least the ubuntu1910-clang10 ones. That missing symbol seems to be from Qt, which is very odd.

**Comment by Xaymar** [comment]
Please test the bleeding-edge binaries resulting from #193: https://github.com/Xaymar/obs-StreamFX/actions/runs/87189199

Choose the correct archive for your distro:
- ubuntu1910-gcc9: Ubuntu 19.10 (Eoan) and Ubuntu 20.04 (Focal) with official OBS Studio PPA.
- ubuntu1804-gcc8: Ubuntu 18.04 (Bionic) with official OBS Studio PPA.
- ubuntu####-clang#: For custom builds with clang which might have vastly better performance on some CPUs. For example, clang-10 can optimize towards AMD Zen2 can get up to 60% better performance than clang9. Official releases though are optimized towards a "generic" x86_64 CPU.

**Comment by romainrossi** [comment]
I tested the ubuntu18.04-gcc version and can confirm : IT WORKS !!
Thank you very much @Xaymar !

**Comment by MarioMey** [comment]
> I tested the ubuntu18.04-gcc version and can confirm : IT WORKS !!
> Thank you very much @Xaymar !

I'm glad it worked for you. It didn't for me :(. But remember, it's not a big need right now. Thanks.

**Comment by maxdrash** [comment]
For the best optimization and stability: should we use clang or gcc ?

**Comment by maxdrash** [comment]
> Please test the bleeding-edge binaries resulting from #193: https://github.com/Xaymar/obs-StreamFX/actions/runs/87189199
> 
> Choose the correct archive for your distro:
> 
>     * ubuntu1910-gcc9: Ubuntu 19.10 (Eoan) and Ubuntu 20.04 (Focal) with official OBS Studio PPA.
> 
>     * ubuntu1804-gcc8: Ubuntu 18.04 (Bionic) with official OBS Studio PPA.
> 
>     * ubuntu####-clang#: For custom builds with clang which might have vastly better performance on some CPUs. For example, clang-10 can optimize towards AMD Zen2 can get up to 60% better performance than clang9. Official releases though are optimized towards a "generic" x86_64 CPU.

Theses builds works ! Thank you, we have to test for bugs.
For optimization and performance: should we prefer clang or gcc ?

**Comment by maxdrash** [comment]
Got a OBS crash on adding Dynamic Mask filter

`23:13:06.453: User added filter 'Masque dynamique' (obs-stream-effects-filter-dynamic-mask) to source 'Image 2 2'`

Trying to add a shader transition, close the transition window and click on "don't save changes" and got a obs crash:
```
23:24:08.163: Out of space trying to render glyphs
23:24:08.180: Out of space trying to render glyphs
23:24:29.372: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: 26, Serial: 51581
23:24:29.372: Failed to make context current.
23:24:29.372: Failed to fetch parent window geometry!
23:24:29.373: X Error: BadDrawable (invalid Pixmap or Window parameter), Major opcode: 151, Minor opcode: BadLength (poly request too large or internal Xlib length error), Serial: 51583
23:24:29.373: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 51584
23:24:29.373: X Error: GLXBadContextTag, Major opcode: 151, Minor opcode: 26, Serial: 51586
23:24:29.373: Failed to make context current.
23:24:29.378: X Error: GLXBadContextTag, Major opcode: 151, Minor opcode: BadAtom (invalid Atom parameter), Serial: 51597
23:24:29.378: Failed to reset current context.
23:24:29.379: X Error: GLXBadContextTag, Major opcode: 151, Minor opcode: BadAtom (invalid Atom parameter), Serial: 51598
23:24:29.379: Failed to reset current context.
```

**Comment by Xaymar** [comment]
For unrelated issues, please open new bug reports
