### ISSUE TITLE
Barrel distortion of a video source

### ISSUE THREAD

**Issue by IceMac76** [Xaymar/obs-StreamFX#158]
Hi Michael!

Here you write about suggestion on GitHub:
https://obsproject.com/forum/threads/streamfx-for-obs-studio.76619/post-399954

I was wondering if it would be hard to support barrel distortion of a video source.

[mheyman] wrote:

> Something like this:
> https://stackoverflow.com/questions/6199636/formulas-for-barrel-pincushion-distortion
> Where you could have separate controls on the x and y axes.
> 

### Description
I'm finding algorythm for Barrel distortion on GitHub.
http://marcodiiga.github.io/radial-lens-undistortion-filtering
WebGL demo: http://marcodiiga.github.io/lens_distortion_filtering/

This is a good idea for to apply distortion the video source during panoramic broadcasting.

Maybe you will come in handy. Good luck

Picture of about my idea.
![image](https://user-images.githubusercontent.com/63796964/79467303-51472e80-8006-11ea-98ea-3ef0772365d4.png)
![image](https://user-images.githubusercontent.com/63796964/79467533-83f12700-8006-11ea-87f5-8c8bdbce2bd9.png)

### Checklist:

- [ ] I have read the contribution guidelines.
- [ ] This feature is necessary and can't be done through other means.
- [ ] This feature does not break existing functionality.
- [ ] This feature may be useful in the future.

**Comment by IceMac76** [comment]
I found a closed issue, but unfortunately did not understand how to resolve the issue. https://github.com/Xaymar/obs-StreamFX/issues/54

**Comment by Xaymar** [comment]
Per my previous statement in #54, you can do this entirely in the Shaders. No additional implementation from my side is required. If you need help learning how to write HLSL shaders, or want to know what inputs StreamFX offers, I can help.

**Comment by skeletonbow** [comment]
StreamFX now has CRT simulation shader, so this can probably be closed as implemented.  Incidentally, the shader works amazingly good, with or without the provided CRT scanline shader also.  <3

**Comment by Xaymar** [comment]
CRT curvature doesn't do what this user wants to do.

**Comment by ApplySci** [comment]
> Per my previous statement in #54, you can do this entirely in the Shaders. No additional implementation from my side is required. If you need help learning how to write HLSL shaders, or want to know what inputs StreamFX offers, I can help.

@Xaymar  Is there a list of inputs StreamFX offers, somewhere?

**Comment by Xaymar** [comment]
The [wiki](https://github.com/Xaymar/obs-StreamFX/wiki/Source-Filter-Transition-Shader#predefined-parameters) has everything for that.
