### ISSUE TITLE
GUI settings for adaptive I-Frames and B-Frames do not change encoder settings correctly.

### ISSUE THREAD

**Issue by cs9kc** [Xaymar/obs-StreamFX#191]
### Description
1. GUI lookahead settings now pass correctly to the encoder.
2. When lookahead is set to > 0, the logs indicate that adaptive I-frames are enabled, as they should be.
2a. The script that runs before the encoder initializes, doesn't show that adaptive I-frames are enabled, but I'm not sure that it can read the encoder after the encoder initializes.
3. The GUI settings for Adaptive B-Frames and Adaptive I-Frames do not work for both 265 and 264. I still have to pass -b_adapt=0 to 265, and -b_adapt=0 -no-scenecut=1 to 264, regardless of gui input.

### System Information
DXDIAG attached.
[DXDIAG for Xaymar bug report April-24-2020.txt](https://github.com/Xaymar/obs-StreamFX/files/4531353/DXDIAG.for.Xaymar.bug.report.April-24-2020.txt)
[OBS LOGS Xaymar bug report April-24-2020.txt](https://github.com/Xaymar/obs-StreamFX/files/4531308/OBS.LOGS.Xaymar.bug.report.April-24-2020.txt)

**Comment by Xaymar** [comment]
Found the issue for "Adaptive B-Frames" not working right. [Instead of checking "is this h264_nvenc" I'm checking "is this not h264_nvenc".](https://github.com/Xaymar/obs-StreamFX/blob/c5cd855c11760c3d440626510472640440d25aa4/source/encoders/handlers/nvenc_shared.cpp#L595-L599).

**Comment by Xaymar** [comment]
With the fix applied:

* Look-Ahead set to value greater than 0:
  ```
  [StreamFX] [h264_nvenc]       Look-Ahead: 26 Frames
  [StreamFX] [h264_nvenc]       Adaptive I-Frames: Enabled
  [StreamFX] [h264_nvenc]       Adaptive B-Frames: Disabled
  ```
* Look Ahead set to 0 [(encoder ignores b_adapt and no-scenecut)](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/nvenc.c#L917-L925):
  ```
  [StreamFX] [h264_nvenc]       Look-Ahead: 0 Frames <Default>
  [StreamFX] [h264_nvenc]       Adaptive I-Frames: Disabled <Default>
  [StreamFX] [h264_nvenc]       Adaptive B-Frames: Enabled <Default>
  ```
* Look Ahead set to -1 (default):
  ```
  [StreamFX] [h264_nvenc]       Look-Ahead: 0 Frames <Default>
  [StreamFX] [h264_nvenc]       Adaptive I-Frames: Enabled
  [StreamFX] [h264_nvenc]       Adaptive B-Frames: Disabled
  ```

**Comment by cs9kc** [comment]
According to the output in FFMPEG (ffmpeg -h encoder=nvenc (or hevc_nvenc), this is how it -should- work:

"nvenc" h264 encoder: When lookahead is > 0 will enable adaptive I and B frames.  Those must be switched off by their respective commands (-no-scenecut=1 and -b_adapt=0, or by setting lookahead to 0).

"nvenc" h265 encoder: When lookahead is > 0 will enable adaptive I frames.  It must be switched off by its respective command, or by setting lookahead to 0. (265 HEVC isn't capable of adaptive b-frames using nvenc)

[ffmpeg 4.2.2 NVENC and HEVC_NVENC output.txt](https://github.com/Xaymar/obs-StreamFX/files/4531812/ffmpeg.4.2.2.NVENC.and.HEVC_NVENC.output.txt)

I think there's also some confusion with NVENC and ffmpeg.  It's silly.  Bare with me... from my testing (and my notes; forgive the caps)

Custom ***FFMPEG*** output type in ***OBS*** - 
"no-scenecut=1" MEANS *NO* ADAPTIVE I-FRAMES!  "no-scenecut=0" *YES* ADAPTIVE I-FRAMES!

Custom ***FFMPEG*** output type in ***FFMPEG CLI*** - 
"-no-scenecut" 0 MEANS *NO* ADAPTIVE I-FRAMES!  "-no-scenecut 1" *YES* ADAPTIVE I-FRAMES!

It's dumb.  I confirmed these findings peeking at frame type using "ffprobe -show_frames -show_entries frame=pict_type filename.mkv > outputfile.txt"

Using your encoder and ffprobe in OBS Studio 25.0.4 and StreamFX beta1, I have found that: 

Custom ***XAYMAR*** output type in ***OBS***
"no-scenecut=1" MEANS *NO* ADAPTIVE I-FRAMES!  "no-scenecut=0" *YES* ADAPTIVE I-FRAMES!

**Comment by Xaymar** [comment]
> Custom FFMPEG output type in FFMPEG CLI -
> "-no-scenecut" 0 MEANS NO ADAPTIVE I-FRAMES! "-no-scenecut 1" YES ADAPTIVE I-FRAMES!

That should not be the case. The source code for nvenc in FFmpeg does not invert the functionality of the parameter based on CLI or not. `-no-scenecut 1` should result in no adaptively inserted I-Frames in all cases.

**Comment by Xaymar** [comment]
Please test the bleeding-edge binaries that result from #194: https://github.com/Xaymar/obs-StreamFX/actions/runs/87192631

**Comment by cs9kc** [comment]
Adaptive B-Frames follow "disabled" and "enabled" properly, from gui to log to output, and function as expected when B-Frames are set to > 0.  Adaptive B-Frames are good to go

Adaptive I-Frames follow "disabled" and "enabled" _**inversely**_ when lookahead is > 0.
- I output a file with adaptive I-Frames "disabled" in the gui, "disabled" shows in the log, but the output contained **many** i-frames (it should have only had 3-4).  
- Likewise, I selected "enabled" in the gui, "enabled" shows in the log, but the output contained I-Frames at the start of each GOP (120 frames in this case)

Your gui and the script in the log match, but the encoder is doing the opposite for adaptive I-Frames.

**Comment by Xaymar** [comment]
I've pushed a new fix, please try the resulting binaries: https://github.com/Xaymar/obs-StreamFX/actions/runs/87405015

**Comment by cs9kc** [comment]
Good morning!  I checked both H264 and H265, and everything seems to be in order.

Adaptive I and B frames are reported as enabled when they are > 0, and your GUI settings work correctly to enable/disable those settings to the encoder itself.

Awesome work!  Thank you again!  This can be closed :3
