### ISSUE TITLE
Missing Qt symbol on Arch Linux

### ISSUE THREAD

**Issue by ThePooN** [Xaymar/obs-StreamFX#192]
### Description
StreamFX builds fine but fails to load properly, since commit `f58ce9f421223934a41bc77312c30c2489c21ad7`.

Build script: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=obs-streamfx&id=9236d793b6f6ecdbea5b890319bd4d0777a04bd9

### System Information
- Software Version: 0.8.0b2hf2 (tested on OBS git master, 25.0.3, 25.0.7, Qt 5.14.2)
- Operating System: Arch Linux

**Comment by Xaymar** [comment]
Please test the patch applied in #193.

**Comment by ThePooN** [comment]
it works :white_check_mark:
