### ISSUE TITLE
[Feature] Cineform Support

### ISSUE THREAD

**Issue by jreben** [Xaymar/obs-StreamFX#196]
I was wondering if you would have any  interest in adding Cineform support.
https://github.com/gopro/cineform-sdk

**Comment by Xaymar** [comment]
At the current time I do not. Also please do not create feature requests without following the template.

**Comment by Xaymar** [comment]
Does someone have actual performance number comparisons to Apple ProRes encoding? It's not worth it to spend time even considering implementing this without any actual data.

**Comment by Xaymar** [comment]
Opting against this due to lack of information.
