### ISSUE TITLE
It no work on Linux mint 19.3

### ISSUE THREAD

**Issue by gabfus1973** [Xaymar/obs-StreamFX#198]
Hi I have a problem with your plugin

### Description
I have download the zip and extracted on my ~/.config/obs-studio/ folder, but on the tools menu' its not show!
Why?

### System Information
- Software Version: OBS-Studio 25.0.7
- Operating System: Linux Mint 19.3

**Comment by Xaymar** [comment]
Version 0.8.0b2hf2 contains a bug that makes the plugin not load on Linux. It has been fixed already and a future update will should start working.
