### ISSUE TITLE
error: no matching function for call to 'gs_debug_marker_begin'

### ISSUE THREAD

**Issue by yurivict** [Xaymar/obs-StreamFX#203]
Build failure:

Log: http://beefy10.nyi.freebsd.org/data/113i386-default/532991/logs/obs-streamfx-0.8.0.b2.h2.log
OS: FreeBSD 12.1
Version: 0.8.0.b2.h2

```
/wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.8.0b2hf2/source/obs/gs/gs-helper.cpp:48:2: error: no matching function for call to 'gs_debug_marker_begin'
        gs_debug_marker_begin(color, _name.c_str());
        ^~~~~~~~~~~~~~~~~~~~~
/usr/local/include/obs/graphics/graphics.h:823:13: note: candidate function not viable: no known conversion from 'const float_t *' (aka 'const long double *') to 'const float *' for 1st argument
EXPORT void gs_debug_marker_begin(const float color[4], const char *markername);
            ^
```

**Comment by Xaymar** [comment]
Out of curiosity, what architecture are those builds for? FLT_EVAL_METHOD should be defaulting to 0 on x86_64, which is the only architecture the plugin supports.

**Comment by yurivict** [comment]
All failing builds are on the i386 archutecture.

**Comment by Xaymar** [comment]
Yeah that explains it. i386 is not supported because the plugin requires a lot of memory for many of the filters to even run. Supporting 32-bit releases will just be an endless amount of crashes as neither physical or virtual memory can exceed 4GB (or 7.5GB with extended memory layout awareness).

**Comment by yurivict** [comment]
Ok, thanks.

**Comment by yurivict** [comment]
The error message
> error: no matching function for call to 'gs_debug_marker_begin'
doesn't immediately suggest that the limited memory is a problem.

Is this symbol missing really because of the lack of memory?

**Comment by Xaymar** [comment]
No, that symbol expects a float but a float_t is given. The problem is mainly SDF (GPU usage/virtual memory exceeds ~500MB per use), encoders (virtual memory usage exceeds 3GB - soon to be supported on linux) and OBS Studio itself, which often ends up using 2GB just by itself. Overall a 4GB memory limit is kind of problematic, and was the cause of around 80% of crashes reported before 32-bit support was dropped.
