### ISSUE TITLE
Add an animation system for Sources, Filters, Properties and more

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#204]
### Description
Animating properties of sources, filters and transitions has been a much requested feature, similar to what motion-effect does, except that it animates _everything_ instead of just elements. The trigger for such animations could be a timer, hotkey, elgato stream deck button, or anything really.

Animations should be available for Integers and Floats, and perhaps later Strings. The animation system should be based on time with a keyframe system. Perhaps a visual scripting system will be necessary. Initial target is to have the ability to animate the properties of any source.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [x] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
In order to have this work, the animation system would need to have several tracks, each with their own keyframes. Values in the keyframe should be able to interpolate in several ways, such as constant, linear, cubic and curve. The ideal value types to support would be Booleans, Integers, Floating Points and Strings, as they pretty much represent the entirety of available options. The animations should also support various types of playback, such as once, bounce (play forward, then backward, then forward, ...) and repeat.

In order to enhance the feature set of the system, variables should also be supported. These can either be set at the time of starting the animation itself, or be set during the animation and used as reference. Exact implementation details are left open in order to not make this impossible, and they are optional for the first implementation. Variables can be also be interpolated, so they are excellent options for dynamic changes.

There should be a trigger system which can tie in other services, such as an Elgato Stream Deck or alerts, directly into the system. Triggers can set variables in the animation to be played which can greatly enhance the feature, allow for queueing triggers and other kinds of interesting things. Triggers should also be available to the animation itself to create cascading animations far beyond anything we have today.

Finally the following extra things should be available for scene items: visibility, position, size, bounding box, and any other scene item setting that is reasonable. Filters should also have the ability to be toggled off entirely.

This system would straight up make Motion Effect and Move Transition completely obsolete, if used properly, similar to the way the shader integration in StreamFX pretty much outclassed other shader implementations at the time.

**Comment by skeletonbow** [comment]
Bunch of easing algos on https://easings.net that are likely useful.  I've made a shader library out of them for my own tinkering although haven't tested it widely yet.

**Comment by exeldro** [comment]
Simple animation like that can be done with the move value filter of my move transition filter. It uses the easings @skeletonbow mentioned.  A more advanced system as described above is still on my wish list.

**Comment by Xaymar** [comment]
Found two callback functions that may be useful for this: `obs_add_tick_callback` and `obs_remove_tick_callback`

**Comment by WilliamAHuston** [comment]
I really love "3D Transform". I was going to open another issue, but this may be related. 

I'm not sure what is meant by "animation system", but what I would like is a way to control and query effect parameters via a locally attached MIDI controller (like a Korg nanoKontrol) or (ideally) OSC: Open Sound Control (similar to MIDI 1.0, but a more refined standard). 

I've made some neat demos using 3D Transform, but find it awkward to modify each individual parameter. Sometimes more than one parameter needs be adjusted simultaneously to keep a certain feature in view. 

With OSC support, I could use a tool like Max/MSP or Pure Data to manipulate groups of controls together in complex ways. It would really be wonderful. 

What may be needed is general OSC support for *all* of OBS, and then hooks for plugins... 

Thanks, BH

**Comment by Xaymar** [comment]
#### Rejected
This is better as a new plugin or a completely new software. Adding this to StreamFX would drastically increase complexity and maintenance cost of the plugin far beyond what is reasonable.
