### ISSUE TITLE
Not working on Pop_OS 18.04

### ISSUE THREAD

**Issue by elpagano3** [Xaymar/obs-StreamFX#205]
Hi,

Plugin is not loading when launch OBS and show this error on log:

> config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/binary/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so)

**System and software Info:**
- streamfx-ubuntu1804-clang9-0.8.0.0b2hf2-c5cd855c.zip
- OBS 25.0.8
- OS: Pop_OS 18.04
- Kernel Version: 5.3.0-7648-generic
- CPU: Intel Core i7-9750H
- GPU: Nvidia 1660 TI
- RAM: 16GB

Thanks in advance.

**Comment by Xaymar** [comment]
This is fixed in current master.

**Comment by Xaymar** [comment]
See other issues:
- https://github.com/Xaymar/obs-StreamFX/issues/192
- https://github.com/Xaymar/obs-StreamFX/issues/155

**Comment by elpagano3** [comment]
Excellent. 
Thanks.
