### ISSUE TITLE
NVIDIA Face Tracking filter doesn't support iGPUs

### ISSUE THREAD

**Issue by ctlaltdefeat** [Xaymar/obs-StreamFX#207]
### Description
I've installed the NVIDIA AR SDK and the Nvidia face tracking filter is still not showing up as an available filter to use. Happy to provide any debug info.

### System Information
- Software Version: StreamFX 0.8.0 Beta 2 (Hotfix 2)
- Operating System: Windows 10
- Kernel Version: 1909
- CPU: i7 8750H
- GPU: Nvidia RTX 2060 (laptop version)
- RAM: 32GB

**Comment by Xaymar** [comment]
Please provide a log file from OBS Studio.

**Comment by ctlaltdefeat** [comment]
https://obsproject.com/logs/U-b6H_IPSsgPq2pW

The relevant line is 
```[StreamFX] <Nvidia Face Tracking Filter> Failed to get device index for device.```
Maybe this is because OBS itself is running on the iGPU, and only "turns on" the nvidia device if necessary (say, when encoding using nvenc)?

**Comment by Xaymar** [comment]
You need to have OBS Studio running on the dedicated GPU, the plugin does not attempt software transfer between GPUs. This is due to the ridiculous performance hit this would cause, and also because this would further complicate the logic behind the filter.

**Comment by ctlaltdefeat** [comment]
I understand the problem.
Keep in mind that this essentially prevents using this plugin in conjunction with display capture on laptops, because most laptops have the display hardware-connected to an iGPU.

**Comment by Xaymar** [comment]
While that is true, that does not sound like a problem for the target demographic of the filter. An integrated GPU simply does not have the bandwidth to push frames across the PCIE layer, especially when trying to hit a power target that is effectively nothing, and it would drastically reduce tracking quality and increase code complexity if I were to add support for it.

I'm leaving this open for the future, but I'm not making any promises on ever adding this - I have no need for this myself, so it would either be comissioned work or someone submitting their time to add this.

**Comment by Xaymar** [comment]
Closing as there are no plans to support dual-GPU systems for this.
