### ISSUE TITLE
FFmpeg Encoders: Add AMD VCE/VCN H.264/H.265

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#210]
### Description
Implement an FFmpeg integration for the AMD VCE/VCN H.264 and H.265 encoders for use in OBS Studio. This should not be a replacement for obs-amd-encoder, but it should complement it. Similar to the NVENC ones, options should be neatly grouped and no option should be hidden.

No fixes or workarounds should be applied on StreamFX's side - all fixes and workarounds should be done in FFmpeg itself in order to not bloat the code needlessly.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
Due to a lack of an AMD GPU, this is porbably being pushed back to a later release. Maybe when AMD is actually competetive again in the encoding sector.

**Comment by ImportTaste** [comment]
@Xaymar I would be interested in having this for a Ryzen CPU with Vega iGPU so the iGPU could handle all of the video encoding by itself.

**Comment by skeletonbow** [comment]
@ImportTaste  That involves copying data over the PCIE bus between GPUs back and forth which more or less negates any theoretical performance benefits which is why it isn't done.

**Comment by ImportTaste** [comment]
I see, alright then.

**Comment by Xaymar** [comment]
Yeah, what skeletonbow said. Moving encoding off of the actual GPU that is doing the rendering absolutely trashes any performance gains there might have been.

**Comment by Xaymar** [comment]
Support for AMD AMF will be in the next StreamFX version, once people actually test it. You can find binaries here: https://github.com/Xaymar/obs-StreamFX/actions/runs/200761078

**Comment by zapoqx** [comment]
Hey Xaymar, I decided to try the FFmpeg encode on my RX 580 in the actions build.  I am unsure if I got it right as it looked like there were code issues for descriptions, but everything seemed to work, although bitrate seemed slightly all over the place at times and I'm not sure if the upper limit bitrate had something to do with it (3200/12000) but in general, all seemed good!
