### ISSUE TITLE
SDF Effects not working

### ISSUE THREAD

**Issue by liquidignition** [Xaymar/obs-StreamFX#213]
OBS 25.0.8 64bit

![2020-05-07](https://user-images.githubusercontent.com/20179384/81194630-39a90780-9000-11ea-86ae-52023d182fb8.png)

Currently the SDF Effects don't seem to work, regardless of any setting applied.

Tried restarting after install and applying the effect to different sources.

DXDIAG:
Time of this report: 5/7/2020, 01:10:18
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
Language: English (Regional Setting: English)
System Manufacturer: ASUS
System Model: All Series
BIOS: 2302 (type: UEFI)
Processor: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 CPUs), ~3.5GHz
Memory: 16384MB RAM
Available OS Memory: 16320MB RAM
Page File: 4991MB used, 13759MB available
Windows Dir: C:\Windows
DirectX Version: DirectX 12
DX Setup Parameters: Not found
User DPI Setting: 96 DPI (100 percent)
System DPI Setting: 96 DPI (100 percent)
DWM DPI Scaling: Disabled
Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
DirectX Database Version: Unknown
DxDiag Version: 10.00.18362.0387 64bit Unicode

**Comment by Xaymar** [comment]
I don't know what you're expecting them to do on a source with no transparency?!

**Comment by liquidignition** [comment]
Ah i see, just tested it with an transparent image. Seems to work.

I was trying to get it to work with a Game Capture source (cropped) thinking it would bleed out of the sources cropped area. But as you mentioned seems that Game Capture layer doesnt have any alpha when cropped.

Below is showing where i was hoping it would work. 
![2020-05-07 (2)_LI](https://user-images.githubusercontent.com/20179384/81201249-6a8d3a80-9008-11ea-8dcf-d6e34ac68270.jpg)

Thanks anyways. I'll have to use a png for the effect by the looks of it.

**Comment by Xaymar** [comment]
If you want things to appear "outside" of something, use the Pad filter and add padding to it. No filter can really render outside of the actual source boundary, so nothing will happen until you do that.
