### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by dkorzhevin** [Xaymar/obs-StreamFX#224]
Hello,

Does this plugin works correctly with latest LTS Ubuntu 20.04 ?

Thanks

**Comment by Xaymar** [comment]
It probably does if you use the gcc9 (19.10) builds.

**Comment by dkorzhevin** [comment]
Thank you. I will try and back with feedback

**Comment by dkorzhevin** [comment]
Works with 20.04, I took latest build for 19.10, gcc9

Thank you!
