### ISSUE TITLE
OBS Crashes when enabling Nvidia Face Tracking Filter

### ISSUE THREAD

**Issue by jaswope** [Xaymar/obs-StreamFX#225]
### Description

Very simply, when attempting to enable the Nvidia face tracking filter on a source, OBS freezes and then crashes. The crash happens immediately after pressing "OK" on the "Filter Name" dialog box

Unfortunately, it does not seem to produce a crash report nor anything interesting in the log file, however I have still attached the log file if it's useful. I have debugging tools available locally and will gladly help to provide more information if it is at all helpful.

Log File: [2020-05-19 17-46-40.txt](https://github.com/Xaymar/obs-StreamFX/files/4653397/2020-05-19.17-46-40.txt)

### System Information
- Plugin Version: 0.8.0 beta 3
- OBS Version: 25.0.8 x64
- Operating System: Windows 10
- Kernel Version: 1909
- CPU: Intel i5 6500
- GPU: Nvidia GTX 1080 Ti
- Driver Version: 445.87
- RAM: 16 GB

**Comment by Xaymar** [comment]
You don't have an RTX GPU.

**Comment by jaswope** [comment]
Thanks! Didn't realize it was a requirement.
