### ISSUE TITLE
OBS Freezes when audio source is mirrored and filters are accessed on original source

### ISSUE THREAD

**Issue by bryhun** [Xaymar/obs-StreamFX#228]
### Description
When an audio source (like a microphone) is mirrored in a scene, the filter interface for the original audio source is unstable, and often causes OBS to freeze (but not crash).  When the audio source mirror is removed, the freezing does not happen.

This bug is challenging as it does not always happen, but usually after making some changes to the filters on the audio device, upon closing and opening the filter interface is usually when the freeze occurrs.

### System Information
[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/4697450/DxDiag.txt)

**Comment by Xaymar** [comment]
Please don't paste the DxDiag into the bug report form, instead save it to a txt file and attach that by dragging it into the text field.

**Comment by Xaymar** [comment]
Might be a reoccurence of an earlier bug: #61

**Comment by bryhun** [comment]
Understood--since OBS is freezing I'm unlcear how to get a proper crash report but if there is debugging I can do, I think I can re-create this crash pretty regularly as it happens within the first few times opening the filter dialog.  Let me know if there is a way to get you more info.

**Comment by Xaymar** [comment]
Can be triggered by the 'Compressor' filter, which enumerates sources in the UI logic. Likely also triggered by other sources doing this.
