### ISSUE TITLE
macOS building from source: clang: error: invalid argument '-compatibility_version 0.8.0' only allowed with '-dynamiclib'

### ISSUE THREAD

**Issue by pbakaus** [Xaymar/obs-StreamFX#230]
### Description

Hi, I'm trying to compile on MacOS as per your instructions, and `make` fails with the following error:

```
[ 99%] Building CXX object UI/frontend-plugins/streamfx/CMakeFiles/StreamFX.dir/source/gfx/shader/gfx-shader-param-matrix.cpp.o
[ 99%] Building CXX object UI/frontend-plugins/streamfx/CMakeFiles/StreamFX.dir/source/gfx/shader/gfx-shader-param-texture.cpp.o
[ 99%] Building CXX object UI/frontend-plugins/streamfx/CMakeFiles/StreamFX.dir/source/UYX5XTB5RZ/qrc_streamfx.cpp.o
[100%] Linking CXX shared module StreamFX.so
clang: error: invalid argument '-compatibility_version 0.8.0' only allowed with '-dynamiclib'
make[2]: *** [UI/frontend-plugins/streamfx/StreamFX.so] Error 1
make[1]: *** [UI/frontend-plugins/streamfx/CMakeFiles/StreamFX.dir/all] Error 2
```

I'm not sure if at all related to #229 as the errors are completely different, but it is suspicious that we seem to be having problems around similar system conditions. Let me know if I can provide any more info!

### System Information

- Software Version: 0.8.0 (I think?)
- Operating System: MacOS 10.15.5 (Catalina)
- XCode: 11.5

**Comment by realdannys** [comment]
I did see this error too I believe at one point.

**Comment by Xaymar** [comment]
Please try the patch in #235.

**Comment by pbakaus** [comment]
thank you, that worked!
