### ISSUE TITLE
Look into a Parsec output integration

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#232]
### Description
Parsec is an easy to use streaming software that allows remote friends to play local only games together. It could be used for low-latency stream to other broadcasters or co-hosts, while keeping the main stream delayed. 

SDK: https://github.com/parsec-cloud/parsec-sdk

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [x] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
License seems to be incompatible with GPLv2. Too many restrictions. Contacted them to hopefully get a GPL compatible header and binary, or at least a header with a redistributable.

**Comment by Xaymar** [comment]
Alternative to integrating this would be to use DataPath, but that is still in development with an unknown completion date.

**Comment by ThePooN** [comment]
can you clarify what DataPath is? googling doesnt give much results as its pretty... ambiguous

**Comment by Xaymar** [comment]
https://github.com/Xaymar/datapath

**Comment by Xaymar** [comment]
Parsec has yet to reply to any of my inquiries, despite multiple attempts to contact them.

**Comment by Xaymar** [comment]
Since Parsec continues to ignore my attempts to contact them via any media, closing this as "Denied".
