### ISSUE TITLE
Dynamic Mask - Question

### ISSUE THREAD

**Issue by StrikerFRFX** [Xaymar/obs-StreamFX#244]
### Description

I'm looking for a way to achieve the result attached on my stream. This is using some sort of blend, I don't know how it works. Is this Dynamic Mask?
### System Information

- Software Version: [25.0.8? unsure]
- Operating System: [Windows 10]
- Kernel Version: [1909]
- CPU: [Intel Core i9]
- GPU: [RTX 2080ti]
- RAM: [16GB]

**Comment by StrikerFRFX** [comment]
![image](https://user-images.githubusercontent.com/34070194/84596781-95fd1380-ae57-11ea-943b-8396bc17c185.png)

**Comment by Xaymar** [comment]
Dynamic Mask can achieve similar results to Overlay, Multiply and Mix blending. For any other kind of blending, you would likely want to use shaders.

**Comment by StrikerFRFX** [comment]
Okay, I'm pretty sure this one is addition. So how would I be able to achieve the effect of the album art being added to the text but slightly blurred at the same time? Is it possible I can use shaders from a source already existing (that I can apply a blur to that I'm happy with)? 

Ty

**Comment by StrikerFRFX** [comment]
Nvm it's multiply.

**Comment by StrikerFRFX** [comment]
So my friend sent me a list of what he did but I just dunno the settings for it and can't get the same effect [](https://media.discordapp.net/attachments/618531497133080576/721797906247581746/unknown.png)

**Comment by Xaymar** [comment]
You will probaly have to ask your friend on how he did it. This issue tracker is more meant for support in using the features, not in generic support for using OBS.

**Comment by Xaymar** [comment]
Closing as there has been no further activity.
