### ISSUE TITLE
SDF Effects - Outside effects affecting transparent border

### ISSUE THREAD

**Issue by reteo** [Xaymar/obs-StreamFX#245]
### Description
When using the SDF filters on transparent elements, such as the "Text" source, it seems to consider the border of the element as opaque for the purpose of generating outer shadows, outer glows, or outlines.  This results in a transparent element showing a border around it when all that's wanted is to have the effect surround the internal elements, such as the aforementioned text.

### System Information

- Software Version: 0.8.0 as well as current Github source
- Operating System: Gentoo Linux
- Kernel Version: 5.4.13-rt (realtime kernel)
- CPU: AMD Ryzen 5 1600 Six-Core Processor
- GPU: GeForce GTX 1050 Ti
- RAM: 16GB

![SDF Effects Issue - 2020-06-14 @ 10-32-43](https://user-images.githubusercontent.com/11682197/84596304-e27e2a00-ae2a-11ea-89bf-57cd7d56781d.png)
![SDF Effects Issue - 2020-06-14 @ 10-34-13](https://user-images.githubusercontent.com/11682197/84596305-e316c080-ae2a-11ea-8857-5a61eac96286.png)
![SDF Effects Issue - 2020-06-14 @ 10-35-03](https://user-images.githubusercontent.com/11682197/84596306-e316c080-ae2a-11ea-945b-c4a42968377f.png)

**Comment by Xaymar** [comment]
Which Graphics driver are you using? The outside is supposed to be treated as "infinite distance", instead of "zero distance" which is the default when a graphics driver does not support border sampling.

**Comment by reteo** [comment]
I'm using the nVidia proprietary driver, version 440.82.

**Comment by tofutim** [comment]
I'm on a Macbook Pro 2019.

![image](https://user-images.githubusercontent.com/157766/87387514-b9e76e00-c557-11ea-8762-4221f76901bc.png)

![image](https://user-images.githubusercontent.com/157766/87387484-ad631580-c557-11ea-8c2d-20d01fa3f4da.png)

![image](https://user-images.githubusercontent.com/157766/87387551-ca97e400-c557-11ea-9e02-c3244b01f10e.png)

**Comment by Xaymar** [comment]
I've looked into the OBS code, the OpenGL subsystem in OBS does not set the border color at all. This is an upstream bug that I can't fix, but it might be possible to have a workaround.

**Comment by Xaymar** [comment]
This is still an upstream libOBS issue, the plugin uses the proper libOBS APIs but gets a different result on OpenGL only.

**Comment by Xaymar** [comment]
Upstream bug report: https://github.com/obsproject/obs-studio/issues/3794

**Comment by Xaymar** [comment]
Closing as a fix has been submitted upstream.
