### ISSUE TITLE
OBS Crashes on filter selection for any target source

### ISSUE THREAD

**Issue by ComradeCourtesy** [Xaymar/obs-StreamFX#250]
### Description
I posted a request for help in the Discord, but submitting I'm here for posterity until the issue is addressed.
I installed the lasted MSVC redist, and then the plugin. When I select a source, and then apply a StreamFX filter, OBS crashes immediately. I used the .exe installer and when that failed, I removed the .dll and tried via the 7zip file with the same issues.

Any help is appreciated,

Thanks!!

(Adding this here just in case: https://obsproject.com/logs/9JBMMiV8Yfp_-S8_)
[OBSCrashDump.txt](https://github.com/Xaymar/obs-StreamFX/files/4795576/OBSCrashDump.txt)

**Comment by skeletonbow** [comment]
As per our discussion in Discord, both Stream Effects 0.7.1 and StreamFX 0.8.0 are installed which are likely conflicting with each other.  StreamFX 0.7.x must be uninstalled before installing 0.8.0, so uninstalling both of them and reinstalling 0.8.0 may resolve the issue.  I'd recommend trying that.

**Comment by Xaymar** [comment]
```
00000071D56F4090 00007FFCD716EE63 0000017AEF0613C0 0000017AD8DB9B80 000000000000001F 0000017AD83AB760 obs-stream-effects.dll!0x7ffcd716ee63
00000071D56F43B0 00007FFCD71A9A66 0000017AEF061370 0000017AD87ABC80 0000017AD83ABFC0 0000017AD83ABEC8 obs-stream-effects.dll!0x7ffcd71a9a66
00000071D56F4460 00007FFCD71AA55C 0000017AD83AB760 0000017AD83AB760 0000017AEF061370 0000017AC52EEB40 obs-stream-effects.dll!0x7ffcd71aa55c
```
Crash is from old plugin. Please make sure to remove the old version first.

**Comment by Xaymar** [comment]
Closing as solved.
