### ISSUE TITLE
Displacement Map filter documentation

### ISSUE THREAD

**Issue by 2rs2ts** [Xaymar/obs-StreamFX#253]
### Description

I would like for some documentation on the Displacement Map filter.

As someone who does not have a background in computer graphics I don't really know how to construct a map to do the things I want, and when you google "displacement map" you get the wikipedia page and then mostly tutorials for Photoshop and Blender. I would not expect someone to write up full tutorials for this filter but ideally the documentation should include:

* A basic explanation of its parameters (this is a must)
* An explanation for how the map image is interpreted
* Some example maps and what their result is at various ratios

Since I don't have the background to be able to communicate what I'd like to see in the docs in more detail I will just explain something that's puzzling me, and say that if the docs were to cause me to stop being puzzled by it, then that would probably be good for a lot of other users too.

The plugin ships with two masks:
* `neutral.png`: ![neutral](https://user-images.githubusercontent.com/578891/85185317-5c0d8200-b248-11ea-8ce8-2fe065c5024a.png)
* `disp-stretch-middle.png`: ![disp-stretch-middle](https://user-images.githubusercontent.com/578891/85185319-5dd74580-b248-11ea-9636-dfe25380ed8e.png)

Questions I have about these are:
* Why is `neutral.png` just a dark yellow square? Is that color a "no-op"?
* Why is `disp-stretch-middle.png` a bunch of shades of red and green and not other colors?
* What effect does the color of a pixel have, e.g. what does a red pixel do compared to a green pixel?
* How does the mask map onto an image that does not share its aspect ratio? Is it simply stretched? What color are the pixels created as a result given?

It would be great if these questions could get answered in the documentation, though I realize that this may be something that I should be expected to just read a book to understand instead, so in the event that I am asking too much, documentation that at least links to sources that would answer my questions would be good. The wikipedia article is not helping :)

One more thing: the wiki links to a documentation page for the filter that is, of course, missing.
![image](https://user-images.githubusercontent.com/578891/85185041-1bf9cf80-b247-11ea-923e-adfd3058c4fe.png)
So just to make sure I don't leave it unsaid, once the documentation is written, this link should also be fixed.

### Checklist

- [x] I am willing to pay someone to implement this feature.
  (If the documentation was really excellent I would gladly send a tip to let the author get some fancy coffee)
- [x] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
Displacement filter takes normal maps as an input (just like written in the description) and uses them to move the sampling point for each pixel. You can find plenty of resources online that explain normal maps, and even resources on how to create them: [1](https://en.wikipedia.org/wiki/Normal_mapping), [2](https://learnopengl.com/Advanced-Lighting/Normal-Mapping), [3](https://cpetry.github.io/NormalMap-Online/), [4](http://wiki.polycount.com/wiki/Normal_map). 

The meaning of the normal map is mostly still the same, but in the filter the X/Y/Z (R/G/B) channels are used as offsets. 0 (0) is -1, 0.5 (127, 128) is 0, 1.0 (255) is +1. The settings in the filter control how strong the offset is, which is described by the hover text.

Note that this filter will be removed once shaders have the ability to use textures as parameters.

**Comment by Xaymar** [comment]
Closing this, since the filter will be marked as deprecrated in the next version.
