### ISSUE TITLE
Shaders: Add support for texture2d parameters

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#254]
### Description
Implement support for 2d textures, for both files (images) and the spout/sink system to bring in source data. This functionality will allow a massive increase in possible shaders, enabling effects such as SMAA, 3D scenes, particles, and more.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [x] This feature absolutely can't be done with already existing features.

**Comment by skeletonbow** [comment]
I've got a folder full of Shadertoy bookmarks to test this when it's avail in the future.  Will probably tinker with some of them using a hack to combine multiple sources into one before then just for fun.

Will this work with cubemaps etc. also or would that be a separate feature?

**Comment by Xaymar** [comment]
Closing as this is already tracked in #5.
