### ISSUE TITLE
FFMPEG x265 colors washed out

### ISSUE THREAD

**Issue by meezits** [Xaymar/obs-StreamFX#255]
Recording in 1440p with x265 and the colors are representing "like" HDR.  Profile is set to main, not "main 10". And it looks like 10 bit footage or HDR when watching back. Blacks are completely black almost and anything on the lighter side is washed.

The source is not in HDR or 10bit, and x265 Main is 8 bit from reading x265 documentation. I've tried changing almost all the settings with the same results. x264 does not have this issue.

Settings are as follows for recording FFMPEG HVECx265.

Preset: High Quality
Profile: Main
Tier: High
Level: Auto

Mode: HQ CBR
Two Pass: Default
Look Ahead: 20 frames
Adaptive I-Frames: Enabled
Buffer: 60,000

Target: 30000

SPQ: Enabled
Strength: -1 (testing this setting)
Temporal: Enabled

(tried different combinations, same results)
Maximum B-frames: 2 Frames
B-Frame: Default
Zero Lat: Default
Weighted Prediction: Disabled
Non-reference P Frames: Default
Access Unit Delimiter: Default
Decoded Picture Buffer: 0

Key: 2 seconds
Override Color Format: Auto or YUV420p or NV12
Compliance: Strict

StreamFX Version: 0.8.00-e343e4cb
Obs 25.0.08

**Comment by Xaymar** [comment]
Please correctly follow the template for reporting bugs and do not delete it.
