### ISSUE TITLE
blurry and pixelated "3d transformed" source in OBS

### ISSUE THREAD

**Issue by ddylard** [Xaymar/obs-StreamFX#256]
### Description
I have a folder inside OBS sources that contains 2 sources, one is my camera and the other is an overlay for the cam wich is an animated overlay in form of a .mov file seted as a loop.
the bug happens when i 3d transform this sources as they become blurry and pixelated no matter what settings i choose whereas if i 3d transform this sources separatedly the result is great, the problem is its really hard to allign the sources this way. I hope i made myself clear enough as i dont have a screenshot right now but i could get one if really needed. Thanks a lot!

### System Information

- Software Version: [OBS 23.3.22.6.13 StreamFX version 08.0.0-e343e4cb
- Operating System:  Windows 7 ultimate  64bits ]
- Kernel Version:  
- CPU: [ AMD FX8350 stock]
- GPU: [AMD Radeon RX 570 8 GB Vram]
- RAM: [8 GB]

**Comment by Xaymar** [comment]
I think a screenshot is necessary here. I have no idea what you're trying to describe.

**Comment by Xaymar** [comment]
I assume that you've been able to fix the problem yourself, given that no screenshot of the issue has appeared.

**Comment by Xaymar** [comment]
Closing this in 3 days due to lack of further user input.

**Comment by Xaymar** [comment]
No further user input given, closing.
