### ISSUE TITLE
Ability to changing audio codec and quality

### ISSUE THREAD

**Issue by megapro17** [Xaymar/obs-StreamFX#257]
### Description
When you select `Custom Output (FFmpeg)` in obs, it is possible to use any audio codec that ffmpeg supports. But when StreamFX is selected this ability is lost. I think i'll be very useful to select different audio codec, instead of aac that used by default, and it shouldn't be too hard.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
"Custom Output (FFmpeg)" is not added by StreamFX, and there is no way to add audio codec selection to OBS Studio as a plugin.

**Comment by Xaymar** [comment]
Closing as this is not feasible with the way OBS is designed.

**Comment by megapro17** [comment]
If you have so much experience in obs, maybe you can change it there?

**Comment by Xaymar** [comment]
[See the entry "Why are you not submitting fixes to OBS Studio?" on my website.](https://blog.xaymar.com/about-me/) It's also simply a waste of time if the PR gets zero comments, and then is eventually either closed with no comment, or never looked at in the first place.
