### ISSUE TITLE
OBS crashes on closing and switching scene collections

### ISSUE THREAD

**Issue by FreshFatih** [Xaymar/obs-StreamFX#258]
### Description

Since updating StreamFX, my OBS crashes whenever I close it, which in itself is not that problematic, I can close it properly in the task manager. But I've also encountered another problem - whenever I switch the scene collection, OBS crashes.

I don't know if there is a correlation, but it's better to consider every option.

[2020-06-24 17-57-25.txt](https://github.com/Xaymar/obs-StreamFX/files/4826581/2020-06-24.17-57-25.txt)
[Crash 2020-06-24 17-57-42.txt](https://github.com/Xaymar/obs-StreamFX/files/4826584/Crash.2020-06-24.17-57-42.txt)

### System Information

[DxDiag2.txt](https://github.com/Xaymar/obs-StreamFX/files/4826578/DxDiag2.txt)

**Comment by skeletonbow** [comment]
OBS has several bugs with regards to using Scene Collections which can not only crash the program but also completely corrupt the Scene Collection JSON files.  You can find out more about them in the OBS issue tracker.  Likewise the "Groups" feature can cause massive corruption of OBS Scene data also and is recommended to be avoided.

**Comment by Xaymar** [comment]
```
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
000000DCAC7A8CE0 00007FFCE385E294 000002A047CB04A0 000002A0356C0000 0000000000000001 0000000000000000 pitchproof-x64.dll!0x7ffce385e294
000000DCAC7A8D10 00007FFCE38732FD 0000000000000000 0000000000000001 000002A0355B02A8 000002A03F7FB101 pitchproof-x64.dll!0x7ffce38732fd
000000DCAC7A8D40 00007FFCE386BDCF 000002A03F7FB1C0 0000000000000000 0000000000000000 0000000000000020 pitchproof-x64.dll!0x7ffce386bdcf
000000DCAC7A8D70 00007FFCE386D997 000002A045F8E050 000002A000000007 0000000000000018 0000000000000000 pitchproof-x64.dll!0x7ffce386d997
000000DCAC7A8DC0 00007FFCE386BACC 0000000000000001 00007FFCE28B245B 0000000000000000 0000000000000000 pitchproof-x64.dll!0x7ffce386bacc
```

'pitchproof-x64.dll' is not part of StreamFX.

**Comment by Xaymar** [comment]
Reported to OBS here: https://github.com/obsproject/obs-studio/issues/2638

Not an issue in StreamFX, closing.
