### ISSUE TITLE
does this work on ubuntu 16.04 (xenial)?

### ISSUE THREAD

**Issue by explodersname** [Xaymar/obs-StreamFX#259]
### Description

I am not sure if the plugin is available for 16.04 so I am just asking_
### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
0.8.0
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
ubuntu 16.04
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
4.19
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
Intel i7-8700K
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
Nvidia gtx 1060
- RAM: [e. g. 16GB, 32GB, 64GB, ...]
8 gb

**Comment by Xaymar** [comment]
Minimum supported Ubuntu is 18.04, which will soon be replaced by 20.04.
