### ISSUE TITLE
Weird behavior with Source Mirror (see description)

### ISSUE THREAD

**Issue by Wolfi0ne** [Xaymar/obs-StreamFX#273]
### Description

I created a scene (scene A) with just a "Media Source" (Nested Media as Name). Neither on the Scene or the Source a Filter is assigned/set.
I created another scene (scene B), and with "Source Mirror" I create 2 Source Mirror from "Nested Media". Scene B only contains this 2 Source Mirror sources.

The Top Mirror has no Filters, is cut on top and bottom 80px and is assigned to be centered vertically.
The Bottom Mirror has a color correction filter, and also the blur-filter assigned - Dual Filtering / Area / Size 3,0.

The reason is to create a top and bottom darker blured "glass effect, for stream infos (the "Media Source" is just a test for now.

All works fine (performance is good, even on my weak notebook here), but the strange behavior: OBS is stopped, I start OBS again, suddenly the top layer acts like it has the blur-filter set. This is not only in the preview, if I record it, its in the recording.

It doesn't matter if I switch between scenes, the blur is still there. The solution is to go into the properties of the top scene (just to see that there is no filter set), and as soon as the preview in the properties is shown, it is fixed as long as this OBS-session is running.

After stopping OBS and starting again, the blur in the top scene is there again.

I also tried to change the Source Mirrors, so that both doesn't use the Nested Media Source, but the whole Scene A - the result (blur in the top scene is there, till you open the properties of the top scene, to see the preview that "cleans" the blur).

I uninstalled and installed StreamFX again, just to exclude if it is a mismatch during an update or so.... Didn't change the phenomen.

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

Windows 10 - 1909
OBS 25.0.8
Intel i3 5005u, Intel  HD 5500 GPU
8 GB RAM

Extra Addons installed is OBS-NDI, but not active in this Scene or enabled in the general settings.

**Comment by Xaymar** [comment]
This might be fixed in the current dev build.

**Comment by Wolfi0ne** [comment]
Sorry for the delayed answer (had a busy week at work).

I can confirm, with 0.9.0a1 the weird behaviour is fixed.

**Comment by Xaymar** [comment]
Sweet, then i can close this as fixed.
