### ISSUE TITLE
How to disable the About dialog from showing on startup?

### ISSUE THREAD

**Issue by unfa** [Xaymar/obs-StreamFX#279]
### Description
Once I installed StreamFX and run OBS I saw an about screen pop up.
I thought it's just a one-time thing, but it shows up every time I start OBS, which is really annoying.

### System Information
Manjaro Linux, installed StreamFX from AUR: https://aur.archlinux.org/packages/obs-streamfx

**Comment by Xaymar** [comment]
Check your user configuration directory (usually `~/.config/obs-studio/plugin_config/StreamFX/`) for a file called `config.json`. In my case, the contents of the file are:

```
{
    "UI.HaveShownAboutStreamFX": true,
    "Version": 38654705665
}
```

This file and the content needs to be present for the check to not fail.

**Comment by unfa** [comment]
Thanks, so I guess if I have this file present, StreamFX will stop showing the About dialog at each run?

**Comment by unfa** [comment]
Ok, the `StreamFX` subdirectory wasn't present. I've added it and the json file, restarted OBS and no more About dialog - thank you!

**Comment by Xaymar** [comment]
> Thanks, so I guess if I have this file present, StreamFX will stop showing the About dialog at each run?

Yes. It's supposed to automatically create it, but something seems to have prevented that from happening.
