### ISSUE TITLE
RFE: Corner Pin filter

### ISSUE THREAD

**Issue by skeletonbow** [Xaymar/obs-StreamFX#281]
### Description

Request for a new _Corner Pin_ filter similar to what is available in video and image editing/compositing software would be a nice addition to the StreamFX repertoire, for ease of reshaping rectangular sources into irregular rectangular shapes such as to fit a 16:9 input onto a 16:9 computer monitor or TV set which is rotated in 3D space in the input.

This was suggested as an alternative to a feature I had requested in a previous bug report and later separate feature request, which I did not at the time fully understand the terminology for having not encountered the corner pin feature in other software before.  This replaces the previous requests now that I've done my homework and understand what was being suggested better.  :)

[This video](https://www.youtube.com/watch?v=2yAP35xaMsc) illustrates the corner pin feature as I now understand it, which would make a tonne of visual FX things greatly simplified.

Bonus feature:  I'd also like to suggest having the corner pin filter having an integrated crop/pad as a convenience, which would make it easier to divide a source into multiple rectangles with different corner pin settings and place them side by side to wrap them around certain shapes like a curved video wall area for example using only a single filter.  I can try to find a visual example of what I mean by this if it isn't clear.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

**Comment by skeletonbow** [comment]
This request obsoletes and replaces #272.

**Comment by skeletonbow** [comment]
Some ideas for further enhancement come from this video comparing _Corner pin_ with a filter called _CC Power Pin_, which does the same thing but has additional enhanced powerful controls worth looking at also.

[After Effects Tutorial : Distort: Difference between Corner Pin & CC Power Pin](https://www.youtube.com/watch?v=Xy_GbHNHVHY)

**Comment by Xaymar** [comment]
Please note that there is no way to do user interactivity with this filter. OBS does not support this at all, though there are ways to hack it into OBS - which will just increase crashing.

**Comment by Xaymar** [comment]
Also seems like this would be easily possible as a shader with no additional work necessary, since the UI would just be identical. Might be better as that.

**Comment by skeletonbow** [comment]
Ya, I implemented a Corner Pin shader a day after my last comment after googling around a bit. :)  It has problems with scale filtering that I haven't yet figured out, but it does work.  Main problem it has now is that at certain angles you can see the 2 triangles show and scale differently, distorting the image horribly.  I found pages talking about bilinear vs. cubic vs perspective filtering and the pros and cons but couldn't make heads or tails out of how to include it in my code to get this working for arbitrary usage.  Going to study up some more and try to sort it out, as well as improve the controls to be more user friendly.

**Comment by skeletonbow** [comment]
Submitted issue #565 as a proper feature request, obsoleting this issue request.
