### ISSUE TITLE
Linux local installation is not supported

### ISSUE THREAD

**Issue by catb0t** [Xaymar/obs-StreamFX#30]
**Describe the bug**
with `CMAKE_INSTALL_PREFIX=/home/cat/.config/obs-studio/plugins`, `make install` (or `make install/local`) the plugin isn't loaded because its installation is not correct. 

The actual tree in `.config/obs-studio/plugins`:
```
~/.config/obs-studio/plugins
├── data
│   └── obs-plugins
│       └── obs-stream-effects
│           ├── effects
│           │   ├── blur.effect
│           │   ├── color-conversion.effect
│           │   ├── displace.effect
│           │   ├── mask.effect
│           │   ├── mipgen.effect
│           │   ├── sdf-generator.effect
│           │   └── sdf-shadow.effect
│           ├── filter-displacement
│           │   ├── disp-stretch-middle.png
│           │   └── neutral.png
│           ├── locale
│           │   ├── en-US.ini
│           │   └── zh-CN.ini
│           ├── shaders
│           │   └── filter
│           │       └── example.effect
│           └── white.png
├── obs-plugins
│   └── 64bit
│       └── libobs-stream-effects.so
```

The correct tree that results in the plugin loading is 
```
~/.config/obs-studio/plugins
├── obs-stream-effects
│   ├── bin
│   │   └── 64bit
│   │       └── libobs-stream-effects.so
│   └── data
│       ├── effects
│       │   ├── blur.effect
│       │   ├── color-conversion.effect
│       │   ├── displace.effect
│       │   ├── mask.effect
│       │   ├── mipgen.effect
│       │   ├── sdf-generator.effect
│       │   └── sdf-shadow.effect
│       ├── filter-displacement
│       │   ├── disp-stretch-middle.png
│       │   └── neutral.png
│       ├── locale
│       │   ├── en-US.ini
│       │   └── zh-CN.ini
│       ├── shaders
│       │   └── filter
│       │       └── example.effect
│       └── white.png
```

**To Reproduce**
1. `cmake ..; make; make install`
4. Start OBS 
3. See the plugin isn't loaded 

**Expected behavior**
```
info: [Stream Effects] Loading Version 0.4.2 (Build 144)
info: ---------------------------------
info:   Loaded Modules:
info:     libobs-stream-effects.so
```

**Desktop:**
 - Operating System: Ubuntu 18.10
 - Kernel Version: Linux 4.18
 - Plugin Version:  clang-compatibility https://github.com/Xaymar/obs-stream-effects/commit/e921e10b5b362a65a3d6e015434514e1b32fd2d1 (0.4.2)
 
Not a huge problem as long as the user knows what the file structure has to be, but it will require distinguishing between a "home folder" installation in `.config/obs-studio` and an OBS system folder installation.

**Comment by Xaymar** [comment]
Not sure how to reproduce the local installation structure. I tried -DUNIX_STRUCTURE=1 without result, and even without -DUNIX_STRUCTURE i still got the same.

**Comment by Xaymar** [comment]
@catb0t I can't figure out how you got that obs-studio installation path. When running cmake on obs-studio, I always get the obs-plugins + data layout.

**Comment by catb0t** [comment]
Sorry, I should explain `.config/obs-studio` is *only* my user's local configuration directory, and it's created at runtime (if nonexistent) by the Linux (packaged?) version of OBS Studio

OBS Studio is installed systemwide at `/usr/bin/obs`, `/usr/share/obs/obs-studio` (locales and themes etc), and `/usr/local/obs-plugins`, but I don't normally want a plugin to install globally.

**Comment by Xaymar** [comment]
I wasn't aware of a local installation method, a new cmake option might be useful for this case.

**Comment by catb0t** [comment]
Ah, I thought that's what `install/local` is for, but maybe that was just part of the template and hasn't been changed.

**Comment by Xaymar** [comment]
I've finally managed to get a CPack libobs package, which paves the way for Linux releases - at least for Ubuntu. If anyone wishes to test these, contact me on Discord: https://discord.gg/DaeJg7M

**Comment by Xaymar** [comment]
Supported by 0.8.0a4, building on linux now by default results in a local install.
