### ISSUE TITLE
Crash after updating to 0.8.2

### ISSUE THREAD

**Issue by TheRealDadbeard** [Xaymar/obs-StreamFX#305]
### System Information

- Software Version: 0.8.2
- Operating System: Windows
- Kernel Version: 2004
- CPU: Ryzen 3700x 
- GPU: RTX 2070
- RAM: 16GB

I was using the .9 alpha fine and then this got released but after I tried to start my stream it would just straight crash OBS

https://pastebin.com/t5a1AaXq Crashlog that OBS let me copy

And this the log that OBS could write itself up to the point where it crashed https://pastebin.com/AxUqxQrw

**Comment by Vrael0n** [comment]
Same crash after upgrading to 8.2 from 8.1, never used .9 though.

**Comment by skeletonbow** [comment]
As a datapoint, I went from 0.8.0 to 0.8.1 to 0.9.0a1 back to 0.8.1 then to 0.8.2 all from the EXE installers, no crashes or noticeable problems here just a a datapoint.
