### ISSUE TITLE
Stream FX is not showing up!

### ISSUE THREAD

**Issue by calledMonkey** [Xaymar/obs-StreamFX#309]
Hey, Stream FX is not showing up in OBS :/ Can you Help? 
Bye

`21:56:09.997: CoInitializeEx succeeded: 0x00000001
21:56:09.997: CPU Name: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
21:56:09.997: CPU Speed: 1992MHz
21:56:09.997: Physical Cores: 2, Logical Cores: 4
21:56:09.997: Physical Memory: 3981MB Total, 1790MB Free
21:56:09.997: Windows Version: 10.0 Build 19041 (release: 2004; revision: 388; 64-bit)
21:56:09.997: Running as administrator: false
21:56:09.997: Aero is Enabled (Aero is always on for windows 8 and above)
21:56:09.997: Windows 10 Gaming Features:
21:56:09.997: 	Game DVR: On
21:56:10.001: Sec. Software Status:
21:56:10.004: 	Microsoft Defender Antivirus: enabled (AV)
21:56:10.005: 	Windows-Firewall: enabled (FW)
21:56:10.006: Current Date/Time: 2020-08-06, 21:56:10
21:56:10.006: Browser Hardware Acceleration: true
21:56:10.006: Portable mode: false
21:56:11.281: OBS 25.0.8 (64-bit, windows)
21:56:11.281: ---------------------------------
21:56:11.332: ---------------------------------
21:56:11.332: audio settings reset:
21:56:11.332: 	samples per sec: 44100
21:56:11.332: 	speakers:        2
21:56:11.335: ---------------------------------
21:56:11.335: Initializing D3D11...
21:56:11.335: Available Video Adapters: 
21:56:11.345: 	Adapter 0: Intel(R) HD Graphics 520
21:56:11.345: 	  Dedicated VRAM: 134217728
21:56:11.345: 	  Shared VRAM:    2087411712
21:56:11.345: 	  PCI ID:         8086:1916
21:56:11.346: 	  Driver Version: 26.20.100.7325
21:56:11.346: 	  output 0: pos={0, 0}, size={1440, 900}, attached=true, refresh=60, name=HW191D
21:56:11.346: 	  output 1: pos={-1366, 119}, size={1366, 768}, attached=true, refresh=60, name=
21:56:11.346: 	Adapter 1: Intel(R) HD Graphics 520
21:56:11.347: 	  Dedicated VRAM: 134217728
21:56:11.347: 	  Shared VRAM:    2087411712
21:56:11.347: 	  PCI ID:         8086:1916
21:56:11.347: 	  Driver Version: 26.20.100.7325
21:56:11.356: Loading up D3D11 on adapter Intel(R) HD Graphics 520 (0)
21:56:11.425: D3D11 loaded successfully, feature level used: b000
21:56:11.425: DXGI increase maximum frame latency success
21:56:12.617: ---------------------------------
21:56:12.617: video settings reset:
21:56:12.617: 	base resolution:   1920x1080
21:56:12.617: 	output resolution: 1152x648
21:56:12.617: 	downscale filter:  Bicubic
21:56:12.617: 	fps:               30/1
21:56:12.617: 	format:            NV12
21:56:12.617: 	YUV mode:          601/Partial
21:56:12.617: NV12 texture support not available
21:56:12.619: Audio monitoring device:
21:56:12.619: 	name: Standard
21:56:12.619: 	id: default
21:56:12.619: ---------------------------------
21:56:12.628: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
21:56:12.632: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
21:56:12.726: [AMF] Unable to load 'amfrt64.dll', error code 126.
21:56:12.731: [AMF] AMF Test failed due to one or more errors.
21:56:12.731: Failed to initialize module 'enc-amf.dll'
21:56:12.798: [obs-browser]: Version 2.8.6
21:56:12.800: [obs-browser]: Blacklisted device detected, disabling browser source hardware acceleration.
21:56:12.877: VLC found, VLC video source enabled
21:56:12.891: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
21:56:12.894: No blackmagic support
21:56:12.909: ---------------------------------
21:56:12.909:   Loaded Modules:
21:56:12.909:     win-wasapi.dll
21:56:12.909:     win-mf.dll
21:56:12.909:     win-dshow.dll
21:56:12.909:     win-decklink.dll
21:56:12.909:     win-capture.dll
21:56:12.909:     vlc-video.dll
21:56:12.909:     text-freetype2.dll
21:56:12.909:     rtmp-services.dll
21:56:12.909:     obs-x264.dll
21:56:12.909:     obs-vst.dll
21:56:12.909:     obs-transitions.dll
21:56:12.909:     obs-text.dll
21:56:12.909:     obs-qsv11.dll
21:56:12.909:     obs-outputs.dll
21:56:12.909:     obs-filters.dll
21:56:12.909:     obs-ffmpeg.dll
21:56:12.909:     obs-browser.dll
21:56:12.909:     image-source.dll
21:56:12.909:     frontend-tools.dll
21:56:12.909:     enc-amf.dll
21:56:12.909:     decklink-ouput-ui.dll
21:56:12.909:     coreaudio-encoder.dll
21:56:12.909: ---------------------------------
21:56:12.909: ==== Startup complete ===============================================
21:56:12.925: All scene data cleared
21:56:12.925: ------------------------------------------------
21:56:13.060: WASAPI: Device 'Lautsprecher (Skiller SGH2)' [48000 Hz] initialized
21:56:13.061: [Loaded global audio device]: 'Desktop‐Audio'
21:56:13.063: [WASAPISource::TryInitialize]:[Mikrofon (3- Auna Mic CM900)] Failed to activate client context: 88890004
21:56:13.063: [WASAPISource::WASAPISource] Device '{0.0.1.00000000}.{46404481-5694-4850-9630-44c07bab9617}' not found.  Waiting for device
21:56:13.063: [Loaded global audio device]: 'Mikrofon/AUX‐Audio'
21:56:13.065: [Media Source 'Loading...']: settings:
21:56:13.065: 	input:                   G:/Mathis/Twitch/Dateien/Font.mov
21:56:13.065: 	input_format:            (null)
21:56:13.065: 	speed:                   100
21:56:13.065: 	is_looping:              yes
21:56:13.065: 	is_hw_decoding:          no
21:56:13.065: 	is_clear_on_media_end:   yes
21:56:13.065: 	restart_on_activate:     yes
21:56:13.065: 	close_when_inactive:     no
21:56:13.066: [Media Source 'LoadingBar']: settings:
21:56:13.066: 	input:                   G:/Mathis/Twitch/Dateien/LoadingBar (PP).mov
21:56:13.066: 	input_format:            (null)
21:56:13.066: 	speed:                   100
21:56:13.066: 	is_looping:              yes
21:56:13.066: 	is_hw_decoding:          no
21:56:13.066: 	is_clear_on_media_end:   yes
21:56:13.066: 	restart_on_activate:     yes
21:56:13.066: 	close_when_inactive:     no
21:56:13.204: WASAPI: Device 'Mikrofon (5- Auna Mic CM900)' [48000 Hz] initialized
21:56:13.248: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Audioeingabeaufnahme)
21:56:13.248: 
21:56:13.759: [Media Source 'BG1']: settings:
21:56:13.759: 	input:                   G:/Mathis/Twitch/Dateien/y2mate.com - Synthwave Animation Loop - Creative Commons_1eHwlmn_Mps_1080p.mp4
21:56:13.759: 	input_format:            (null)
21:56:13.759: 	speed:                   100
21:56:13.759: 	is_looping:              yes
21:56:13.759: 	is_hw_decoding:          no
21:56:13.759: 	is_clear_on_media_end:   yes
21:56:13.759: 	restart_on_activate:     yes
21:56:13.759: 	close_when_inactive:     no
21:56:14.170: [Media Source 'Stinger (Stinger)']: settings:
21:56:14.170: 	input:                   G:/Desktop/Stinger/Fsports.webm
21:56:14.170: 	input_format:            (null)
21:56:14.170: 	speed:                   100
21:56:14.170: 	is_looping:              no
21:56:14.170: 	is_hw_decoding:          no
21:56:14.170: 	is_clear_on_media_end:   yes
21:56:14.170: 	restart_on_activate:     yes
21:56:14.170: 	close_when_inactive:     no
21:56:14.171: Switched to scene 'Starting'
21:56:14.171: ------------------------------------------------
21:56:14.171: Loaded scenes:
21:56:14.171: - scene 'Starting':
21:56:14.171:     - source: 'Background' (group)
21:56:14.171:         - source: 'BG1' (ffmpeg_source)
21:56:14.171:             - monitoring: monitor and output
21:56:14.171:     - source: 'Loading Bar' (group)
21:56:14.171:         - source: 'Loading...' (ffmpeg_source)
21:56:14.171:         - source: 'LoadingBar' (ffmpeg_source)
21:56:14.171:     - source: 'Facecam 3' (group)
21:56:14.171:         - source: 'Webcam' (dshow_input)
21:56:14.171:             - filter: 'LUT anwenden' (clut_filter)
21:56:14.171:         - source: 'Bild' (image_source)
21:56:14.171: - scene 'Game':
21:56:14.171:     - source: 'Games' (group)
21:56:14.171:     - source: 'Widgets' (group)
21:56:14.171:         - source: 'Last Follower' (browser_source)
21:56:14.171:         - source: 'Last Donation without Name' (browser_source)
21:56:14.171:         - source: 'Chat' (browser_source)
21:56:14.171:     - source: 'Facecam 1' (group)
21:56:14.171:         - source: 'Webcam' (dshow_input)
21:56:14.171:             - filter: 'LUT anwenden' (clut_filter)
21:56:14.172:         - source: 'Bild' (image_source)
21:56:14.172:     - source: 'Audioeingabeaufnahme' (wasapi_input_capture)
21:56:14.172:         - filter: 'Noise Suppression' (noise_suppress_filter)
21:56:14.172:         - filter: 'Expander' (expander_filter)
21:56:14.172:         - filter: 'Noise Gate' (noise_gate_filter)
21:56:14.172:         - filter: 'Kompressor' (compressor_filter)
21:56:14.172:         - filter: 'Gain' (gain_filter)
21:56:14.172:         - filter: 'Limiter' (limiter_filter)
21:56:14.172:         - filter: 'Equalizer' (vst_filter)
21:56:14.172: - scene 'Facecam Talk':
21:56:14.172:     - source: 'Facecam 2' (group)
21:56:14.172:         - source: 'Webcam' (dshow_input)
21:56:14.172:             - filter: 'LUT anwenden' (clut_filter)
21:56:14.172:     - source: 'Widgets 2' (group)
21:56:14.172:         - source: 'Last Donation' (browser_source)
21:56:14.172:         - source: 'Last Follower' (browser_source)
21:56:14.172:         - source: 'Chat 2' (browser_source)
21:56:14.172:     - source: 'Audioeingabeaufnahme' (wasapi_input_capture)
21:56:14.172:         - filter: 'Noise Suppression' (noise_suppress_filter)
21:56:14.172:         - filter: 'Expander' (expander_filter)
21:56:14.172:         - filter: 'Noise Gate' (noise_gate_filter)
21:56:14.172:         - filter: 'Kompressor' (compressor_filter)
21:56:14.172:         - filter: 'Gain' (gain_filter)
21:56:14.172:         - filter: 'Limiter' (limiter_filter)
21:56:14.172:         - filter: 'Equalizer' (vst_filter)
21:56:14.172:     - source: 'Header' (image_source)
21:56:14.172: ------------------------------------------------
21:56:14.199: warning: Could not update timestamps for skipped samples.
21:56:14.255: [Media Source 'Stinger (2) (Stinger)']: settings:
21:56:14.255: 	input:                   
21:56:14.255: 	input_format:            (null)
21:56:14.255: 	speed:                   100
21:56:14.255: 	is_looping:              no
21:56:14.255: 	is_hw_decoding:          no
21:56:14.255: 	is_clear_on_media_end:   yes
21:56:14.255: 	restart_on_activate:     yes
21:56:14.255: 	close_when_inactive:     no
21:56:14.447: adding 23 milliseconds of audio buffering, total audio buffering is now 69 milliseconds (source: LoadingBar)
21:56:14.447: 
21:56:14.494: adding 69 milliseconds of audio buffering, total audio buffering is now 139 milliseconds (source: BG1)
21:56:14.494: 
`

**Comment by Xaymar** [comment]
Do you mind _NOT_ deleting the template next time? It's there for a reason.

As for your log file, StreamFX is not actually installed. If you have moved your OBS Studio installation, make sure to uninstall StreamFX manually first, and then reinstall it to the new location.

**Comment by calledMonkey** [comment]
Hey, Stream FX is in My OBS Folder, Sometimes StreamFX is available in OBS and sometimes not. Can you help me?
![Unbenannt](https://user-images.githubusercontent.com/65130981/89713189-746f6280-d996-11ea-8470-c81e3b227879.PNG)

**Comment by calledMonkey** [comment]
[2020-08-08 16-44-55.txt](https://github.com/Xaymar/obs-StreamFX/files/5045403/2020-08-08.16-44-55.txt)
[2020-08-08 16-38-29.txt](https://github.com/Xaymar/obs-StreamFX/files/5045404/2020-08-08.16-38-29.txt)
One log of StreamFX was showing up and one of StreamFX was not showing up! It was only a restart :/
Bye

**Comment by skeletonbow** [comment]
![image](https://user-images.githubusercontent.com/49483514/89715112-8d195180-d971-11ea-8142-fa0c1d1bbfb9.png)

**Comment by Xaymar** [comment]
From the log files provided, I see no issue. StreamFX is loading fine, but it is sometimes just not loaded by OBS itself. This is outside of the control of the plugin, and you should consult the OBS Studio forums for a solution - my guess is that you forgot to add OBS Studio to the whitelisted directories in your AV and it is making the plugin loading fail.

**Comment by Xaymar** [comment]
Since this is not a problem with StreamFX, I am cosing this report.
