### ISSUE TITLE
StreamFX is loaded but no options appear

### ISSUE THREAD

**Issue by starman2k01** [Xaymar/obs-StreamFX#314]
### Description
StreamFX shows up in menu next to "Help". Pull down just shows help menu, Discord, about, etc. but no other options.
How do I access StreamFX options? AMD encoder does not appear in Output for example.

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Do you mean Filters, Sources, Transitions and Encoders? You access those like you would with any other Filter, Source, Transition and Encoder.

**Comment by Xaymar** [comment]
More than 14 days have passed with no reply, so I'm closing this.
