### ISSUE TITLE
Shader Filter not active until Filter menu opened

### ISSUE THREAD

**Issue by mutilator** [Xaymar/obs-StreamFX#315]
### Description
Using OBS websocket I added 2 shader filters + a few other OBS built-ins to a scene. The scene is black until you simply open the filter menu for the scene. Switching between scenes doesn't resolve the issue. So far the only fix was manually opening the filter menu.

This does only appear to be limited to the shader filter. Other filters such as Blur from StreamFX worked fine using this method.

Linked is a short video of the behavior. When I don't use a shader filter there is no issue. For instance I tested with just the color filter to make it black and white and the effect was immediate.

https://www.dropbox.com/s/oybn7mpefbavfux/OBS~3.mp4?raw=1

### System Information
- Software Version: OBS 25.0.8 - StreamFX 0.8.3
- Operating System: Windows 10 Pro
- Kernel Version: 2004
- CPU: I7-7700k @ 4.2ghz
- GPU: NVIDIA GTX 1080
- RAM: 32gb

**Comment by Xaymar** [comment]
This is probably already fixed in 0.9.

**Comment by mutilator** [comment]
Tested 0.9 release, issue persists
