### ISSUE TITLE
OBS Crashes on 'Start Recording' with StreamFX encoders in 0.9.0.0a2, but works fine in 0.8.3.0

### ISSUE THREAD

**Issue by NikkoToska** [Xaymar/obs-StreamFX#318]
### Description

0.9.0.0a2 crashes when I use the FFMPEG encoders that are included in StreamFX.  When I click 'Start Recording' there's a short delay (2 to 3 seconds) while it seems to try and start, then OBS crashes.  I uninstalled 0.9.0.0a2 and reinstalled 0.8.3.0 and the encoders work without an issue.  I then installed 0.9.0.0a2 again and it crashes.

None, just crashes without any visual artifacts.

Attached below.

### System Information

DxDiag file attached below.
- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5106265/DxDiag.txt)
[Crash 2020-08-21 10-23-18.txt](https://github.com/Xaymar/obs-StreamFX/files/5106266/Crash.2020-08-21.10-23-18.txt)

**Comment by Xaymar** [comment]
This has already been fixed in the current master/0.9 branch. The public alpha releases are delayed by two weeks, so they aren't representations of the current code. v0.8 actually got its fixes backported from v0.9.
