### ISSUE TITLE
Scale and aspect ratio of the OBS application in general

### ISSUE THREAD

**Issue by jandres4444** [Xaymar/obs-StreamFX#319]
### Description
-The problem is that I have the FULL HD screen resolution (1920x1080) configured in my operating system, at the top of the taskbar you can see the size related to this resolution, however, in the application menus, that is, the ITEMS transition, cut, fade, scenes, sources, audio mixer. Even the text of the settings themselves are highly altered.

Any recommendation on this problem? Thank you

![Pantalla OBS](https://user-images.githubusercontent.com/51652340/91210548-071c3b00-e6d3-11ea-8290-5382e61e6111.PNG)

![image](https://user-images.githubusercontent.com/51652340/91210782-5bbfb600-e6d3-11ea-9ea0-d72b40e2039c.png)

![image](https://user-images.githubusercontent.com/51652340/91210846-6ed28600-e6d3-11ea-8033-d0401c393e4c.png)

### System Information

-Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
-Language: Spanish (Regional Setting: Spanish)
-System Manufacturer: HP
-System Model: HP ProBook 440 G5
-BIOS: Default System BIOS (type: BIOS)
-Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 CPUs), ~1.8GHz
-Memory: 16384MB RAM
-Available OS Memory: 15796MB RAM
-Page File: 8129MB used, 30097MB available
-Windows Dir: C:\WINDOWS
-DirectX Version: DirectX 12
-DX Setup Parameters: Not found
-User DPI Setting: 96 DPI (100 percent)
-System DPI Setting: 144 DPI (150 percent)
-DWM DPI Scaling: Disabled
-Miracast: Available, with HDCP
-Microsoft Graphics Hybrid: Not Supported
-DirectX Database Version: 1.0.8
-DxDiag Version: 10.00.19041.0084 64bit Unicode

**Comment by Xaymar** [comment]
This is not related to StreamFX at all.
