### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by PQCraft** [Xaymar/obs-StreamFX#321]
### Description
OBS doesn't see the plugin in Linux compatibility mode and tells me I need a newer version of Windows in Windows compatibility mode.

### System Information
- Software Version: 25.0.8
- Operating System: UMOS v0.4 w/ UBASIC v2.5.1
- Kernel Version: UMOSKRNL.BIN v0.0.34.7 w/ UMLNXCL.BIN, UMWINCL.BIN and DEVEMU.BIN
- CPU: Enhanced PQWare Interlaced Computing (EPIC) CPU D4 1.2 GHz 2 Mb FastRAM Bank Select Support (emulated architecture)
- GPU: T5 intergrated (16 processing cores, 2 output cores, 1 sprite output core)
- RAM: 2 GB exRAM (DDR2 compatibility mode), 16 MB DRAM (not used due to DDR2 comatibility mode)

**Comment by Xaymar** [comment]
So first off, before anything else, I'd like to insert a quote here:

> What the actual living fuck?!

**Comment by Xaymar** [comment]
1. I couldn't find any information about the Operating System you are using. Therefore, this is an unsupported operating system.
2. Officially only Debian/Ubuntu, Windows 10, and related forks of either are supported. Emulation layers are not officially supported.
3. Your System specs don't even meet half of the minimum requirements.

I'm honestly confused by what you expect me to do here.

**Comment by PQCraft** [comment]
Sorry, that was autofilled. I made a custom architecture and OS to along with it. I was testing some stuff and I used the wrong script. It was supposed to output the report to a file not fill out the report online.

**Comment by PQCraft** [comment]
It runs becuase I translated a small linux kernel and an old windows kernel to epic (machine language like x86 and arm) and I got OBS to run using less RAM and I was testing plugin support. It uses the disk more than the RAM now and is slow af. It also can't do any capturing or rendering due to the proprietary ge im using (truƐd instead of opengl).
