### ISSUE TITLE
OBS Window Broken

### ISSUE THREAD

**Issue by einfachama** [Xaymar/obs-StreamFX#326]
Hello. My OBS looks like this (Look Screenshot)
One Hour Ago it worked fine, but now half of the Window is transparent and the whole text is to small to read. How can i fix this?

- Software Version: 25.0.5
- Operating System: Linux
- Kernel Version:  ZorinOS Lite
- CPU: Intel i5-5200U 4x2.2GHz
- GPU: Nvidia GTX 960M
- RAM: 8GB

![Bildschirmfoto vom 2020-09-10 02-31-34](https://user-images.githubusercontent.com/70332613/92668142-4622d100-f30e-11ea-99cf-ee3f3f2327d7.png)

**Comment by Xaymar** [comment]
Your operating system is not officially supported. Only Ubuntu, Debian and related forks of it are supported. You will have to ask the support of that OS or the maintainer of the package on that OS for help.

**Comment by zenny** [comment]
@einfachama Small fonts could be HiDPI issue if you are using a 4K screen. In that case you may have to run your xserver at a higher DPI like 192 (it was so in my 4K laptop).

The transparency issue could be your opengl issue, but I am not sure.

**Comment by einfachama** [comment]
Ok thanks for help 👍

**Comment by Picoseconds** [comment]
I think it may be that the PC has switched to using Wayland. Can you verify this?

**Comment by Xaymar** [comment]
Closing this as it is an OBS Studio problem:

- https://github.com/obsproject/obs-studio/pull/2478
- https://github.com/obsproject/obs-studio/pull/2482
- https://github.com/obsproject/obs-studio/pull/2484
