### ISSUE TITLE
About StreamFX Window: Wrong Icons used

### ISSUE THREAD

**Issue by SDUX1s44c** [Xaymar/obs-StreamFX#329]
Instead of a YouTube icon being shown, the Twitch icon is shown. (OS is Pop_OS! based on Ubuntu 20.04, with StreamFX 0.8.3 clang10 on OBS 25.0.3)
![Screenshot from 2020-09-12 12-26-17](https://user-images.githubusercontent.com/62861466/93003404-44fec900-f4f3-11ea-872b-b629765712db.png)

**Comment by Xaymar** [comment]
Classic copy & paste error: https://github.com/Xaymar/obs-StreamFX/blob/master/source/ui/ui-about.cpp#L61
