### ISSUE TITLE
Apply blur to sources underneath parent

### ISSUE THREAD

**Issue by Toasty27** [Xaymar/obs-StreamFX#333]
### Description

I have a source that I want to apply a blur _behind_. As in, Source A is a ring in the foreground. Source B is the background. I want to blur the background, but only inside the Source A ring.

Currently I do this with source mirrors. I take any objects I want to have a blur behind and add them to a new scene ('temp sources' in the video). I then create an additional scene that mirrors this ('temp mask' in the video), and add a color correction/grading filter to the mask scene which effectively makes everything in the scene a solid color (say, #00FF00) unless it has 0 opacity. I then add a blur filter to Source B ('temp image' in the video) and select the 'temp mask' scene as the blur mask source. I now add 'temp sources' as a source to my original scene.

So now I have my sources in the foreground as a source mirror, and the background is blurred everywhere a source exists in 'temp sources'.

If I need to move sources around, I do so inside of 'temp sources', and those movements are automatically reflected in the mask scene, which keeps the blurring in the main scene aligned to the sources.

Video example of how this works:
https://imgur.com/8eCcfXE

(temp is the main scene, 'temp sources' has the "lens" that I'm moving around, 'temp mask' is where I convert the sources to a usable mask using color grading and luma key filters)

This has an obvious limitation in that if you want your blur to affect multiple sources behind it, those sources need to be put in a separate scene, and you need to use that scene as the background source in your main scene (where you would then apply the blur filter). This method also requires _three times as many scenes at minimum_ if you want this blurring effect (even more if you want multiple layers of bluring).

This would be way more convenient if it were possible to apply a filter to Source A (the lens in my video) which blurred anything behind it. A feature that enabled this kind of functionality would probably also enable other filters to affect sources in the background.

Maybe this is possible with a shader, but I don't think there's a way for a shader to get information about the position or shape of sources in a scene (though admittedly I know little about writing shaders).

----
P.S.
I don't expect this to be easy to implement. In fact, it's even possible my guess is it would require major changes to how OBS handles sources. I know we can adjust opacity for sources, but that's the only way I know currently where one source can have any kind of affect on the source behind it.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

**Comment by Toasty27** [comment]
So this can be simplified by using the mask color filter to select all channels, which reduces the required scenes from three to two (unless you have multiple layers you want to blur), but that doesn't enable you to apply a filter's effects to the sources behind the source where the filter is added, which is what I'm really looking to do. It would be nice if we didn't have to split our scenes up in to two different parts for effects like these.

This can probably be done using groups as sources instead of scenes, and applying filters to groups. Although groups introduce their own problems.

**Comment by skeletonbow** [comment]
Beware of using the Groups feature in OBS 25.0.x and older as it can corrupt and destroy your OBS Scene Collection irrecoverably.  Fixes for a number of problems related to that are present in 26.0.x release candidate but it's not clear yet if all of the corruption issues are finally fixed so be cautious with using Groups.  I recommend sticking with nested scenes for anything production until the fixes for the corruption are confirmed to be reliable.  Nothing is worse than having dozens of duplicated sources/scenes showing up that can't be reliably fixed/removed.

**Comment by Xaymar** [comment]
**Declining this feature, based on the fact that it is impossible to implement as a plugin.**

This feature is not only theoretically impossible, it is also physically impossible. The way libOBS was designed by @jp9000 (and other contributors) does not allow for this kind of interaction, since all Sources and Filters are acting independently. The only Source that knows about other sources is a scene.

Implementing this would require completely redesigning scenes from the ground up to work completely different (and likely require 2-10x the amount of processing power), redesign the entire filters and sources to work with the new scene, and other nonsense changes. This is not a task I'm willing to undertake, since this really is just a niche use case - especially because it is already possible in a different way.

Therefore, this is a hard no.
