### ISSUE TITLE
About Link points to wrong url

### ISSUE THREAD

**Issue by luisalvarado** [Xaymar/obs-StreamFX#334]
The website link in the about section points to the wrong url 

![image](https://user-images.githubusercontent.com/29236/94033407-295eb280-fd7e-11ea-8279-739024919853.png)

It points to: https://streamfx.xaymar.com/ which is broken.

**Comment by Xaymar** [comment]
That is the correct URL.

**Comment by Xaymar** [comment]
FYI the website is still not publicly ready. but I am already linking to it. I could probably put a work in progress page there given how many people message me _every day_ about this.

**Comment by luisalvarado** [comment]
AAA ok. Got it Thank you @Xaymar
