### ISSUE TITLE
OBS Studio not hiding in system tray after installing StreamFX 0.9.0

### ISSUE THREAD

**Issue by Seamas73** [Xaymar/obs-StreamFX#343]
### Description
After I've installed StreamFX 0.9.0 I cannot hide OBS Studio in system tray by clicking on system-tray OBS icon or by right click on icon and choosing "hide" item of the context menu. When I click on icon I just turn off the preview mode In OBS Studio. When I use StreamFX 0.9.0 alpha 3 or 0.8.3 I can hide OBS Studio in system tray by clicking on OBS icon or choosing "hide" in context menu
[2020-09-28 11-09-50.txt](https://github.com/Xaymar/obs-StreamFX/files/5290860/2020-09-28.11-09-50.txt)

### System Information
[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5290862/DxDiag.txt)

**Comment by Xaymar** [comment]
I can confirm the "Hide" option not working, but it also does not work without StreamFX for me.

**Comment by Seamas73** [comment]
> I can confirm the "Hide" option not working, but it also does not work without StreamFX for me.

Another plugin, which braked "hide" option in my obs studio, is obs-ndi v.4.9.0 and below. I had to delete it to use "hide" option. Now I have to use v.0.9.0 alpha 3 of StreamFX to use "hide" option.

**Comment by Xaymar** [comment]
Confirmed and [reported upstream](https://github.com/obsproject/obs-studio/issues/3518). Working on a workaround.
