### ISSUE TITLE
implicit instantiation of undefined template 'std::__1::vector<char, std::__1::allocator<char> >'

### ISSUE THREAD

**Issue by mtrpires** [Xaymar/obs-StreamFX#348]
## Description
[Version 26](https://github.com/obsproject/obs-studio/releases/tag/26.0.0) brought a new type of error when building StreamFX with OBS in macOS X 10.15.5. Configuring is fine, but when I run `make` it stops at ```util-curl.cpp.o``` with the following error:

`error: implicit instantiation of undefined template 'std::__1::vector<char, std::__1::allocator<char> >'`

This error seems to be related to #341 

I've done some digging and tried adding headers into the files, but everything seems fine as far as having the right headers (stream, sstring etc).

See [log](https://paste.ofcode.org/DcEjEPGSFgrZqT6Hy4UrMS).

### System Information

> info: CPU Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
> info: CPU Speed: 2600MHz
> info: Physical Cores: 6, Logical Cores: 12
> info: Physical Memory: 16384MB Total
> info: OS Name: Mac OS X (NSMACHOperatingSystem)
> info: OS Version: Version 10.15.5 (Build 19F101)
> info: Kernel Version: 19.5.0
> info: [StreamFX] Version 0.9.0.2-4ed1f3d4

**Comment by joerice** [comment]
Adding `#include <vector>` to util-curl.hpp fixed this for me.
