### ISSUE TITLE
Rename the shader filter to "StreamFX shader" or similar

### ISSUE THREAD

**Issue by shleeable** [Xaymar/obs-StreamFX#350]
### Description
I've installed streamfx and the obs-shaderfilter at the same time... and if i add a filter, both plugins share the same name in the obs source filter list.

Thanks.

**Comment by skeletonbow** [comment]
OBS Shaderfilter shows up as "User-defined Shader" in the OBS Filter list.

**Comment by Xaymar** [comment]
Declined, this is not a problem with StreamFX. StreamFX has _always_ used "Shader" or "Custom Shader" since the initial release of the feature.
