### ISSUE TITLE
obs-studio does not load plugin after building from source

### ISSUE THREAD

**Issue by qwarlock** [Xaymar/obs-StreamFX#351]
### Description
I downloaded and built the StreamFX plugin from source in the obs-studio/UI source.  When I compile I see it compile without issue.  In installs into /usr/plugins/StreamFX/bin/64bit/StreamFX.so . in my distro the .so files are normally installed into /usr/lib64/obs-plugins.  When I start obs it loads the other plugins but there is no log of StreamFX.  When I look at the interface there is no mention of StreamFX anywhere.
.  

### System Information

- Software Version: github master  

- Operating System: slackware linux current
- Kernel Version: 5.4.61
- CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

- GPU: NVIDIA Corporation GP104M [GeForce GTX 1070 Mobile]
- RAM: 16G

**Comment by Xaymar** [comment]
I can't provide further help without a build log, or a log file of obs-sutdio.

**Comment by qwarlock** [comment]
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
info: CPU Speed: 3299.846MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 15882MB Total, 10299MB Free
info: Kernel Version: Linux 5.4.61
info: Distribution: Slackware 14.2
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.9
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
info: OBS 26.0.0-rc3-10-ge5d8f345-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 450.66, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
        base resolution:   1920x1080
        output resolution: 1280x720
        downscale filter:  Bicubic
        fps:               30/1
        format:            NV12
        YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: FFMPEG VAAPI supported
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.15.0 ; qt version (run-time): 5.15.0
info: [obs-websocket] module loaded!
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: Switched to Preview/Program mode
info: ------------------------------------------------
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.0'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
info: [obs-websocket] Update << '{
    "sourceKind": "pulse_output_capture",
    "sourceName": "Desktop Audio",
    "sourceSettings": {
        "device_id": "default"
    },
    "sourceType": "input",
    "update-type": "SourceCreated"
}'
info: [obs-websocket] Update << '{
    "sourceName": "Desktop Audio",
    "update-type": "SourceVolumeChanged",
    "volume": 0.074585564434528351
}'
info: [obs-websocket] Update << '{
    "sourceName": "Desktop Audio",
    "syncOffset": 0,
    "update-type": "SourceAudioSyncOffsetChanged"
}'
info: [obs-websocket] Update << '{
    "muted": false,
    "sourceName": "Desktop Audio",
    "update-type": "SourceMuteStateChanged"
}'
info: pulse-am: Prevented feedback-loop in 'default'
info: [Loaded global audio device]: 'Desktop Audio'
info:     - monitoring: monitor and output
info: pulse-input: Server name: 'pulseaudio 13.0'
info: [obs-websocket] Update << '{
    "sourceKind": "pulse_input_capture",
    "sourceName": "Mic/Aux",
    "sourceSettings": {
        "device_id": "alsa_input.usb-046d_HD_Pro_Webcam_C920_C1631CDF-02.analog-stereo"
    },
    "sourceType": "input",
    "update-type": "SourceCreated"
}'
info: [obs-websocket] Update << '{
    "sourceName": "Mic/Aux",
    "update-type": "SourceVolumeChanged",
    "volume": 0.13278894126415253
}'
info: [obs-websocket] Update << '{
    "sourceName": "Mic/Aux",
    "syncOffset": 0,
    "update-type": "SourceAudioSyncOffsetChanged"
}'
info: [obs-websocket] Update << '{
    "muted": false,
    "sourceName": "Mic/Aux",
    "update-type": "SourceMuteStateChanged"
}'
info: [Loaded global audio device]: 'Mic/Aux'
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 640x480
info: v4l2-input: Pixelformat: VYUY
info: v4l2-input: Linesize: 1280 Bytes
info: v4l2-input: Framerate: 30.00 fps
info: [obs-websocket] Update << '{
    "sourceKind": "v4l2_input",
    "sourceName": "Video Capture Device (V4L2)",
    "sourceSettings": {
        "device_id": "/dev/video0",
        "input": 0,
        "pixelformat": 1448695129
    },
    "sourceType": "input",
    "update-type": "SourceCreated"
}'
info: [obs-websocket] Update << '{
    "sourceName": "Video Capture Device (V4L2)",
    "update-type": "SourceVolumeChanged",
    "volume": 1.0
}'
info: [obs-websocket] Update << '{
    "sourceName": "Video Capture Device (V4L2)",
    "syncOffset": 0,
    "update-type": "SourceAudioSyncOffsetChanged"
}'
info: [obs-websocket] Update << '{
    "muted": false,
    "sourceName": "Video Capture Device (V4L2)",
    "update-type": "SourceMuteStateChanged"
}'
info: [obs-websocket] Update << '{
    "filterName": "Color Correction",
    "filterSettings": {
        "brightness": 0.059999999999999998,
        "contrast": -0.13,
        "gamma": 0.089999999999999997,
        "hue_shift": 5.9800000000000004,
        "saturation": 1.3600000000000001
    },
    "filterType": "color_filter",
    "sourceName": "Video Capture Device (V4L2)",
    "update-type": "SourceFilterAdded"
}'
info: [obs-websocket] Update << '{
    "sourceKind": "scene",
    "sourceName": "FrontCameraScene",
    "sourceSettings": {
        "custom_size": false,
        "id_counter": 6,
        "items": [
            {
                "align": 5,
                "bounds": {
                    "x": 0.0,
                    "y": 0.0
                },
                "bounds_align": 0,
                "bounds_type": 0,
                "crop_bottom": 0,
                "crop_left": 0,
                "crop_right": 0,
                "crop_top": 0,
                "group_item_backup": false,
                "id": 1,
                "locked": false,
                "name": "Video Capture Device (V4L2)",
                "pos": {
                    "x": 153.0,
                    "y": -57.0
                },
                "private_settings": {},
                "rot": 0.0,
                "scale": {
                    "x": 2.3684210777282715,
                    "y": 2.3687500953674316
                },
                "scale_filter": "disable",
                "visible": true
            }
        ]
    },
    "sourceType": "scene",
    "update-type": "SourceCreated"
}'
info: [obs-websocket] Update << '{
    "sourceName": "FrontCameraScene",
    "update-type": "SourceVolumeChanged",
    "volume": 1.0
}'
info: [obs-websocket] Update << '{
    "sourceName": "FrontCameraScene",
    "syncOffset": 0,
    "update-type": "SourceAudioSyncOffsetChanged"
}'
info: [obs-websocket] Update << '{
    "muted": false,
    "sourceName": "FrontCameraScene",
    "update-type": "SourceMuteStateChanged"
}'
info: [obs-websocket] Update << '{
    "sourceKind": "scene",
    "sourceName": "TheatreDB_Map",
    "sourceSettings": {
        "custom_size": false,
        "id_counter": 1,
        "items": [
            {
                "align": 5,
                "bounds": {
                    "x": 0.0,
                    "y": 0.0
                },
                "bounds_align": 0,
                "bounds_type": 0,
                "crop_bottom": 0,
                "crop_left": 0,
                "crop_right": 0,
                "crop_top": 0,
                "group_item_backup": false,
                "id": 1,
                "locked": false,
                "name": "Window Capture (Xcomposite)",
                "pos": {
                    "x": 0.0,
                    "y": 0.0
                },
                "private_settings": {},
                "rot": 0.0,
                "scale": {
                    "x": 1.0,
                    "y": 1.0
                },
                "scale_filter": "disable",
                "visible": true
            }
        ]
    },
    "sourceType": "scene",
    "update-type": "SourceCreated"
}'
info: [obs-websocket] Update << '{
    "sourceName": "TheatreDB_Map",
    "update-type": "SourceVolumeChanged",
    "volume": 1.0
}'
info: [obs-websocket] Update << '{
    "sourceName": "TheatreDB_Map",
    "syncOffset": 0,
    "update-type": "SourceAudioSyncOffsetChanged"
}'
info: [obs-websocket] Update << '{
    "muted": false,
    "sourceName": "TheatreDB_Map",
    "update-type": "SourceMuteStateChanged"
}'
info: [obs-websocket] Update << '{
    "sourceKind": "xcomposite_input",
    "sourceName": "Window Capture (Xcomposite)",
    "sourceSettings": {
        "capture_window": "85983834\r\nMap\r\nsun-awt-X11-XFramePeer"
    },
    "sourceType": "input",
    "update-type": "SourceCreated"
}'
info: [obs-websocket] Update << '{
    "sourceName": "Window Capture (Xcomposite)",
    "update-type": "SourceVolumeChanged",
    "volume": 1.0
}'
info: [obs-websocket] Update << '{
    "sourceName": "Window Capture (Xcomposite)",
    "syncOffset": 0,
    "update-type": "SourceAudioSyncOffsetChanged"
}'
info: [obs-websocket] Update << '{
    "muted": false,
    "sourceName": "Window Capture (Xcomposite)",
    "update-type": "SourceMuteStateChanged"
}'
info: [obs-websocket] Update << '{
    "item-id": 1,
    "item-name": "Video Capture Device (V4L2)",
    "scene-name": "FrontCameraScene",
    "update-type": "SceneItemAdded"
}'
info: [obs-websocket] Update << '{
    "item-id": 1,
    "item-name": "Video Capture Device (V4L2)",
    "scene-name": "FrontCameraScene",
    "transform": {
        "bounds": {
            "alignment": 0,
            "type": "OBS_BOUNDS_NONE",
            "x": 0.0,
            "y": 0.0
        },
        "crop": {
            "bottom": 0,
            "left": 0,
            "right": 0,
            "top": 0
        },
        "height": 0.0,
        "locked": false,
        "position": {
            "alignment": 5,
            "x": 153.0,
            "y": -57.0
        },
        "rotation": 0.0,
        "scale": {
            "x": 2.3684210777282715,
            "y": 2.3687500953674316
        },
        "sourceHeight": 0,
        "sourceWidth": 0,
        "visible": true,
        "width": 0.0
    },
    "update-type": "SceneItemTransformChanged"
}'
info: [obs-websocket] Update << '{
    "item-id": 1,
    "item-name": "Window Capture (Xcomposite)",
    "scene-name": "TheatreDB_Map",
    "update-type": "SceneItemAdded"
}'
info: [obs-websocket] Update << '{
    "item-id": 1,
    "item-name": "Window Capture (Xcomposite)",
    "scene-name": "TheatreDB_Map",
    "transform": {
        "bounds": {
            "alignment": 0,
            "type": "OBS_BOUNDS_NONE",
            "x": 0.0,
            "y": 0.0
        },
        "crop": {
            "bottom": 0,
            "left": 0,
            "right": 0,
            "top": 0
        },
        "height": 0.0,
        "locked": false,
        "position": {
            "alignment": 5,
            "x": 0.0,
            "y": 0.0
        },
        "rotation": 0.0,
        "scale": {
            "x": 1.0,
            "y": 1.0
        },
        "sourceHeight": 0,
        "sourceWidth": 0,
        "visible": true,
        "width": 0.0
    },
    "update-type": "SceneItemTransformChanged"
}'
info: Switched to scene 'FrontCameraScene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'FrontCameraScene':
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info:         - filter: 'Color Correction' (color_filter)
info: - scene 'TheatreDB_Map':
info:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
info: ------------------------------------------------
info: [obs-websocket] Update << '{
    "scene-name": "FrontCameraScene",
    "sources": [
        {
            "alignment": 5,
            "cx": 0.0,
            "cy": 0.0,
            "id": 1,
            "locked": false,
            "muted": false,
            "name": "Video Capture Device (V4L2)",
            "render": true,
            "source_cx": 0,
            "source_cy": 0,
            "type": "v4l2_input",
            "volume": 1.0,
            "x": 153.0,
            "y": -57.0
        }
    ],
    "update-type": "SwitchScenes"
}'
info: [obs-websocket] Update << '{
    "scene-name": "FrontCameraScene",
    "sources": [
        {
            "alignment": 5,
            "cx": 0.0,
            "cy": 0.0,
            "id": 1,
            "locked": false,
            "muted": false,
            "name": "Video Capture Device (V4L2)",
            "render": true,
            "source_cx": 0,
            "source_cy": 0,
            "type": "v4l2_input",
            "volume": 1.0,
            "x": 153.0,
            "y": -57.0
        }
    ],
    "update-type": "PreviewSceneChanged"
}'
info: [obs-websocket] WSServer::start: Locked to IPv4 bindings
info: [obs-websocket] server started successfully on port 4444
info: [obs-websocket] io thread started
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
info: [obs-websocket] Update << '{
    "item-id": 1,
    "item-name": "Video Capture Device (V4L2)",
    "scene-name": "FrontCameraScene",
    "transform": {
        "bounds": {
            "alignment": 0,
            "type": "OBS_BOUNDS_NONE",
            "x": 0.0,
            "y": 0.0
        },
        "crop": {
            "bottom": 0,
            "left": 0,
            "right": 0,
            "top": 0
        },
        "height": 1137.0,
        "locked": false,
        "position": {
            "alignment": 5,
            "x": 153.0,
            "y": -57.0
        },
        "rotation": 0.0,
        "scale": {
            "x": 2.3684210777282715,
            "y": 2.3687500953674316
        },
        "sourceHeight": 480,
        "sourceWidth": 640,
        "visible": true,
        "width": 1515.78955078125
    },
    "update-type": "SceneItemTransformChanged"
}'
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)

info: ==== Shutting down ==================================================
info: [obs-websocket] Update << '{
    "update-type": "Exiting"
}'
info: [obs-websocket] Update << '{
    "sourceKind": "scene",
    "sourceName": "FrontCameraScene",
    "sourceType": "scene",
    "update-type": "SourceDestroyed"
}'
info: [obs-websocket] Update << '{
    "sourceKind": "scene",
    "sourceName": "TheatreDB_Map",
    "sourceType": "scene",
    "update-type": "SourceDestroyed"
}'
info: [obs-websocket] Update << '{
    "sourceKind": "xcomposite_input",
    "sourceName": "Window Capture (Xcomposite)",
    "sourceType": "input",
    "update-type": "SourceDestroyed"
}'
info: [obs-websocket] Update << '{
    "filterName": "Color Correction",
    "filterType": "color_filter",
    "sourceName": "Video Capture Device (V4L2)",
    "update-type": "SourceFilterRemoved"
}'
info: [obs-websocket] Update << '{
    "sourceKind": "v4l2_input",
    "sourceName": "Video Capture Device (V4L2)",
    "sourceType": "input",
    "update-type": "SourceDestroyed"
}'
info: v4l2-input: Stopped capture after 186 frames
info: [obs-websocket] Update << '{
    "sourceKind": "pulse_output_capture",
    "sourceName": "Desktop Audio",
    "sourceType": "input",
    "update-type": "SourceDestroyed"
}'
info: pulse-input: Stopped recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
info: pulse-input: Got 2215 packets with 475841 frames
info: [obs-websocket] Update << '{
    "sourceKind": "pulse_input_capture",
    "sourceName": "Mic/Aux",
    "sourceType": "input",
    "update-type": "SourceDestroyed"
}'
info: All scene data cleared
info: ------------------------------------------------
[2020-10-02 23:37:54] [fail] WebSocket Connection Unknown - "" - 0 asio.system:125 Operation aborted.
info: [obs-websocket] io thread exited
info: [obs-websocket] server stopped successfully
info: [obs-websocket] goodbye!
info: [Scripting] Total detached callbacks: 0
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 468.571 ms
info:  ┣OBSApp::AppInit: 1.626 ms
info:  ┃ ┗OBSApp::InitLocale: 0.64 ms
info:  ┗OBSApp::OBSInit: 435.464 ms
info:    ┣obs_startup: 13.105 ms
info:    ┗OBSBasic::OBSInit: 360.117 ms
info:      ┣OBSBasic::InitBasicConfig: 0.078 ms
info:      ┣OBSBasic::ResetAudio: 0.087 ms
info:      ┣OBSBasic::ResetVideo: 59.591 ms
info:      ┣OBSBasic::InitOBSCallbacks: 0.004 ms
info:      ┣OBSBasic::InitHotkeys: 0.03 ms
info:      ┣obs_load_all_modules: 104.052 ms
info:      ┃ ┣obs_init_module(decklink-ouput-ui.so): 0.68 ms
info:      ┃ ┣obs_init_module(frontend-tools.so): 29.933 ms
info:      ┃ ┣obs_init_module(image-source.so): 0.005 ms
info:      ┃ ┣obs_init_module(linux-alsa.so): 0.001 ms
info:      ┃ ┣obs_init_module(linux-capture.so): 0.488 ms
info:      ┃ ┣obs_init_module(linux-decklink.so): 0.19 ms
info:      ┃ ┣obs_init_module(linux-jack.so): 0.001 ms
info:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0.001 ms
info:      ┃ ┣obs_init_module(linux-v4l2.so): 0.001 ms
info:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0.107 ms
info:      ┃ ┃ ┗nvenc_check: 0.072 ms
info:      ┃ ┣obs_init_module(obs-filters.so): 0.048 ms
info:      ┃ ┣obs_init_module(obs-outputs.so): 0.001 ms
info:      ┃ ┣obs_init_module(obs-transitions.so): 0.006 ms
info:      ┃ ┣obs_init_module(obs-websocket.so): 3.024 ms
info:      ┃ ┣obs_init_module(obs-x264.so): 0.002 ms
info:      ┃ ┣obs_init_module(rtmp-services.so): 0.471 ms
info:      ┃ ┣obs_init_module(text-freetype2.so): 0.007 ms
info:      ┃ ┣obs_init_module(v4l2sink.so): 0.663 ms
info:      ┃ ┗obs_init_module(vlc-video.so): 0.415 ms
info:      ┣OBSBasic::ResetOutputs: 0.109 ms
info:      ┣OBSBasic::CreateHotkeys: 0.031 ms
info:      ┣OBSBasic::InitService: 0.972 ms
info:      ┣OBSBasic::InitPrimitives: 0.153 ms
info:      ┗OBSBasic::Load: 138.218 ms
info: obs_hotkey_thread(25 ms): min=0.038 ms, median=0.107 ms, max=4.198 ms, 99th percentile=0.567 ms, 100% below 25 ms
info: audio_thread(Audio): min=0 ms, median=0.021 ms, max=0.123 ms, 99th percentile=0.069 ms
info: obs_graphics_thread(33.3333 ms): min=0.195 ms, median=0.812 ms, max=111.409 ms, 99th percentile=4.127 ms, 99.7416% below 33.333 ms
info:  ┣tick_sources: min=0 ms, median=0.006 ms, max=111.105 ms, 99th percentile=0.028 ms
info:  ┣output_frame: min=0.095 ms, median=0.327 ms, max=2.72 ms, 99th percentile=0.85 ms
info:  ┃ ┗gs_context(video->graphics): min=0.095 ms, median=0.327 ms, max=2.719 ms, 99th percentile=0.85 ms
info:  ┃   ┣render_video: min=0.04 ms, median=0.2 ms, max=2.52 ms, 99th percentile=0.387 ms
info:  ┃   ┃ ┗render_main_texture: min=0.033 ms, median=0.183 ms, max=2.492 ms, 99th percentile=0.38 ms
info:  ┃   ┗gs_flush: min=0.004 ms, median=0.006 ms, max=0.79 ms, 99th percentile=0.059 ms
info:  ┗render_displays: min=0.044 ms, median=0.281 ms, max=12.808 ms, 99th percentile=1.515 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.06 ms, median=25.169 ms, max=29.264 ms, 87.234% within ±2% of 25 ms (0% lower, 12.766% higher)
info: obs_graphics_thread(33.3333 ms): min=21.858 ms, median=33.334 ms, max=111.412 ms, 99.4819% within ±2% of 33.333 ms (0.259067% lower, 0.259067% higher)
info: =================================================
info: Number of memory leaks: 0
bash-5.0# 


That what you are looking for?

**Comment by Xaymar** [comment]
What does your build log look like? That log only shows that OBS doesn't have any streamfx.so file at all to find.

**Comment by qwarlock** [comment]
Ok let me try and recompile and generate a log file

**Comment by qwarlock** [comment]
[build.LOG](https://github.com/Xaymar/obs-StreamFX/files/5321234/build.LOG)

that help?

**Comment by qwarlock** [comment]
it installed in sort of an add spot.. /usr/plugins/StreamFX .  I tried copying it to /usr/lib64/obs-plugins/ but was ignored.  The only thing there are just...  the raw .so files.  What is on my system is StreamFX.so down 3 deep in directories.  it os sort of like though it was compiled together... OBS has no idea it is there.

**Comment by qwarlock** [comment]
Hey Rock star... I did a git checkout tags/0.9.0 and built it independently.  Popped it into /usr/lib64/obs-plugins/ and it popped open like a champ.  Anyway, so those are my build files of the master version against the master obs-studio.   Thanks for looking around at this stuff with me.  It nudged me in the right direction.  So thanks!  You rock!

**Comment by qwarlock** [comment]
oooo I spoke too soon!  Filters are in the menu but have no properties.  So I am chewing on that one.  Anyway still looks really cool!

**Comment by Xaymar** [comment]
Found a bug in the CMake file that passed over my head. Right now it's treating a native build as a standalone build - not what it should be doing.

**Comment by qwarlock** [comment]
Cool ... will try it and then send a note back  Thanks!

**Comment by joerice** [comment]
Same issue here – building OBS on macOS from master, and StreamFX from the patch-351 branch with the updated CMakeLists.txt. 

Have previously built StreamFX and had it work fine as a plugin (end of August), and that build still works as a plugin with current OBS source.

I notice that StreamFX.so is not listed as a loaded module in the OBS app log.

[Here](https://github.com/Xaymar/obs-StreamFX/files/5331382/CMakeOutput.log) is the log of the OBS build. 

(I changed CMakeLists.txt:129 to "Darwin" from "Mac" in order to detect the platform properly – this probably deserves a new issue.)

**Comment by joerice** [comment]
More details from further testing:

- The 0.9.0a3 tag builds fine and the plugin loads with the current OBS source 
- The patch-351 branch builds successfully, but the plugin does not load
- The 0.9.0 tag does not build:
```[ 56%] Building CXX object plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser_autogen/mocs_compilation.cpp.o
In file included from /Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/plugin.cpp:72:
/Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/updater.hpp:24:10: fatal error: 'nlohmann/json.hpp' file not found
#include <nlohmann/json.hpp>```

Don't have time at the moment to crawl commit-by-commit, so sticking with 0.9.0a3, but lmk if there's anything specific you can think of.

**Comment by Xaymar** [comment]
nlohmann/json is a submodule. Make sure to initialize submodules.

**Comment by joerice** [comment]
Thanks! That resolved that error on the 0.9.0 tag, although it still fails:

```In file included from /Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.cpp:21:
/Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.hpp:93:9: error: implicit instantiation of undefined template
      'std::__1::vector<char, std::__1::allocator<char> >'
                        value.resize(buffer_len);
                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from /Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.cpp:21:
/Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.hpp:95:16: error: implicit instantiation of undefined template
      'std::__1::vector<char, std::__1::allocator<char> >'
                        memcpy(value.data(), buffer, value.size());
                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from /Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.cpp:21:
/Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.hpp:95:38: error: implicit instantiation of undefined template
      'std::__1::vector<char, std::__1::allocator<char> >'
                        memcpy(value.data(), buffer, value.size());
                                                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from /Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.cpp:21:
/Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.hpp:101:22: error: implicit instantiation of undefined template
      'std::__1::vector<char, std::__1::allocator<char> >'
                        std::vector<char> buffer;
                                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
[ 55%] Built target text-freetype2
[ 55%] Building CXX object plugins/streamfx/CMakeFiles/StreamFX.dir/source/plugin.cpp.o
/Users/joe/obs-workspace-vanilla/obs-studio/plugins/streamfx/source/util/util-curl.cpp:142:21: error: implicit instantiation of undefined template
      'std::__1::vector<char, std::__1::allocator<char> >'
        std::vector<char>  buffer;
```

Maybe I should open a new issue for this, although I now get the same error on `patch-351` so I wonder if for some reason it was silently failing there before?

**Comment by Xaymar** [comment]
That error seems to be #348 .

**Comment by joerice** [comment]
Thanks - can build successfully with submodules now, but the plugin still doesn't load when using the `patch-351` branch. (Does work from the `0.9.0` tag) Here's the build output: [build-log-streamfx-patch-351.txt](https://github.com/Xaymar/obs-StreamFX/files/5362050/build-log-streamfx-patch-351.txt)

**Comment by joerice** [comment]
@Xaymar, plugin still fails to load on macOS after pulling from master and building with OBS 26.0.2 tag. Shall I open a new issue? (Plugin does load if building from StreamFX 0.9.0 tag)

e.g. 

`13:55:30.201: Source ID 'streamfx-filter-transform' not found`

**Comment by Xaymar** [comment]
```
CMake Warning at plugins/streamfx/CMakeLists.txt:416 (message):
  Front-End requires Qt5 and OBS Frontend API.
Call Stack (most recent call first):
  plugins/streamfx/CMakeLists.txt:633 (resolve_components)
```

From your last build log, it seems to be a different issue entirely.

**Comment by joerice** [comment]
Ah, even though now StreamFX builds and StreamFX.so is successfully generated and included with OBS?

**Comment by Xaymar** [comment]
The original issue is with Linux and wrong placement of binaries, your issue is something else entirely.
