### ISSUE TITLE
Version Update to 0.9.0 causes "Sliding Bars Transition Effect" to stop working

### ISSUE THREAD

**Issue by SPIKEYPUP** [Xaymar/obs-StreamFX#356]
### Description
After updating from 0.8.3 to 0.9.0 the "sliding-bars.effect" (transition shader) does not load properly and prevents the shader from functioning properly/at all.  Loading the effect file in question produces the window result posted below, no options populate and the preview shows a blank screen, using the actual transition also results in a blank screen instead of the expected sliding bars transition.  Other transition types seem to be working as intended...

Uninstalling 0.9.0 and reverting to 0.8.3 fixes the issue.

Thanks in advance for your time...

![image](https://user-images.githubusercontent.com/27184427/95661165-110ec780-0ae2-11eb-8a21-24a2ad3397fb.png)

### System Information
See attached DXDIAG.
[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5359484/DxDiag.txt)
[sliding-bars.effect.txt](https://github.com/Xaymar/obs-StreamFX/files/5359604/sliding-bars.effect.txt)

**Comment by Xaymar** [comment]
This is likely caused by HLSL to GLSL transpiling that OBS Studio does. Eventually StreamFX moves to a Vulkan renderer so this won't be an issue anymore.

**Comment by SPIKEYPUP** [comment]
Awesome!  Thanks for taking the time to look into it :)  Hope you had a great Halloween and are setting up for a nice cozy holiday season! 🦃 🎄 🎅
