### ISSUE TITLE
Create Blend Mode "Screen"/ "Add" from Phototshop

### ISSUE THREAD

**Issue by kellertobias** [Xaymar/obs-StreamFX#358]
### Description
I am trying to make a Virtual Set kind of Music Live stream.
I am having a Live camera with a DJ or musician in a studio, with some lights to fake the lighting and a second source from a 3d visualizer for light shows.

I have played around in photoshop and tried to create this effect, its pretty simple, just using blending mode screen:
![WhatsApp Image 2020-10-16 at 19 08 33](https://user-images.githubusercontent.com/6940430/96300514-ea76f200-0ff5-11eb-9a4a-66ea586d4087.jpeg)

the DJ in the center is "stolen" from a google search for DJ images... and the rest is from a 3d visualizer

however wen I try to recreate this effect in OBS, I fail, because there is no blending mode "screen" (or no blending modes at all)

using a color key on black, I can create this:
![vlcsnap-2020-10-16-19h30m18s230](https://user-images.githubusercontent.com/6940430/96301046-e1d2eb80-0ff6-11eb-9c37-a079cad1cd69.png)

using a dynamic mask, I can create this:
![vlcsnap-2020-10-16-19h30m35s359](https://user-images.githubusercontent.com/6940430/96301066-ebf4ea00-0ff6-11eb-9c29-5b3fbfc37c63.png)

note that on every image, the colors are way darker than in the version from photoshop.

### System Information
- Software Version: StreamFX 0.9.0
- Operating System: Win 10
- Kernel Version: ??
- CPU: i7 10700K
- GPU: AMD RX5700
- RAM: 64GB

**Comment by Xaymar** [comment]
**Rejected.** Not possible with standard OBS, and you can already do something similar with Shaders or scripting.
