### ISSUE TITLE
Unicode characters causes configuration to fail to save

### ISSUE THREAD

**Issue by NazarRecovery** [Xaymar/obs-StreamFX#359]
Hey. The other day I had to reinstall your application and want to ask if what I will describe next is a bug.
In the screenshot I will show what happens every time I start OBS. Every time this window.

![Screenshot](https://user-images.githubusercontent.com/68765699/96690910-ef88c800-138c-11eb-8291-64e7d5e41df2.png)

You have to constantly agree, otherwise OBS just won't start.

System Information:
[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5414213/DxDiag.txt)

**Comment by skeletonbow** [comment]
Just for a data point, do you have a firewall or anti-malware software blocking access to the web by default?

**Comment by NazarRecovery** [comment]
> Просто для точки данных, есть ли у вас брандмауэр или антивирусное программное обеспечение, блокирующее доступ в Интернет по умолчанию?

There is no antivirus, Internet access is allowed in the firewall

**Comment by Xaymar** [comment]
**Not a bug, required by GDPR regulations.**

This window asks you if you want to allow StreamFX to perform automated update checks. If you click cancel here, it will disable automated update checks (as well as manual update checks) - if you click ok, it enables both. This is saved to a configuration file on a _clean OBS Studio exit_.

**Comment by NazarRecovery** [comment]
> **Это не ошибка, требуемая правилами GDPR.**
> 
> В этом окне вас спросят, хотите ли вы разрешить StreamFX выполнять автоматические проверки обновлений. Если вы нажмете «Отмена» здесь, это отключит автоматические проверки обновлений (а также ручные проверки обновлений) - если вы нажмете «ОК», они будут включены. Это сохраняется в файле конфигурации при _чистом выходе из OBS Studio_ .


https://youtu.be/lMZ-o8txygA

And it will appear regardless of the choice. Is that how it should be?

**Comment by NazarRecovery** [comment]
> **Not a bug, required by GDPR regulations.**
> 
> This window asks you if you want to allow StreamFX to perform automated update checks. If you click cancel here, it will disable automated update checks (as well as manual update checks) - if you click ok, it enables both. This is saved to a configuration file on a _clean OBS Studio exit_.

https://youtu.be/lMZ-o8txygA

And it will appear regardless of the choice. Is that how it should be?

**Comment by Xaymar** [comment]
Looking at the video, it seems your plugin configuration directory is corrupted or inaccessible. If you have previously run OBS Studio as an administrator, you will have to continue running OBS Studio as an administrator.

**Comment by NazarRecovery** [comment]
> Looking at the video, it seems your plugin configuration directory is corrupted or inaccessible. If you have previously run OBS Studio as an administrator, you will have to continue running OBS Studio as an administrator.

Yes, I use OBS by default as an administrator

**Comment by Xaymar** [comment]
I did not see a UAC prompt appear at all, so please verify that you actually still do.

**Comment by NazarRecovery** [comment]
> I did not see a UAC prompt appear at all, so please verify that you actually still do.

This is the only window i have seen

**Comment by NazarRecovery** [comment]
I'm talking about auto-update

**Comment by NazarRecovery** [comment]
I did not see UAC prompt

**Comment by NazarRecovery** [comment]
Or, I have disabled this function. I will check it

**Comment by NazarRecovery** [comment]
> I did not see a UAC prompt appear at all, so please verify that you actually still do.

Actually, I did some manipulations. Removed plugin. Reinstalled OBS. Installed the plugin to a clean program. As well as different degrees of the UAC. First, it was automatically installed via exe, and then removed and installed by manually installation. Below is a video of how everything "Changed"

https://youtu.be/Aymsuv2HxdA

**Comment by Xaymar** [comment]
This might be a unicode issue. Does your usanem contain cyrillic characters? If yes, do you mind telling me what the username (only the username, it's the `C:\Users\<username>\` part) is?

**Comment by NazarRecovery** [comment]
> This might be a unicode issue. Does your username contain cyrillic characters? If yes, do you mind telling me what the username (only the username, it's the `C:\Users\<username>\` part) is?

That's right, there are Cyrillic symbols along this path.
"C:\Users\Назар"
I don't know how to change it.

**Comment by NazarRecovery** [comment]
I will not change, as this can lead to a bunch of errors in different games / programs

**Comment by Xaymar** [comment]
No need to change, I just need something that is known to break to test with locally.

**Comment by NazarRecovery** [comment]
Okay

**Comment by Xaymar** [comment]
Managed to do some testing today and unfortunately could not confirm this being caused by Unicode characters in the name. The only reason for this happening would be if OBS Studio does not have the necessary rights to save the file to disk.

**Comment by NazarRecovery** [comment]
> Managed to do some testing today and unfortunately could not confirm this being caused by Unicode characters in the name. The only reason for this happening would be if OBS Studio does not have the necessary rights to save the file to disk.

Hmm... How can I check or fix this?

**Comment by Xaymar** [comment]
Try deleting the `C:\Users\<yourname>\AppData\Roaming\obs-studio\plugin_config\StreamFX\` directory. It is automatically created at launch and contains plugin information - if deleting the directory isn't possible, then the security descriptor for it was corrupted some time in the past.

**Comment by NazarRecovery** [comment]
![image](https://user-images.githubusercontent.com/68765699/97810553-c407b680-1c85-11eb-8982-b557ae4ad1a1.png)
Umm..
It was not here StreamFX

**Comment by Xaymar** [comment]
That would explain your issue. Normally it should automatically create that directory, but it seems that something is preventing it from doing so. This can be anything from antivirus to a malformed security descriptor on the directory, which might happen if a backup of an earlier system is just pasted onto the new system.

**Comment by NazarRecovery** [comment]
> That would explain your issue. Normally it should automatically create that directory, but it seems that something is preventing it from doing so. This can be anything from antivirus to a malformed security descriptor on the directory, which might happen if a backup of an earlier system is just pasted onto the new system.


Interesting. Indeed, after reinstalling the system, I had to transfer some files from the old to the new, but only a few. Can this affect even if the program is fully installed?
I do not even know

**Comment by Xaymar** [comment]
That is indeed possible, if the two systems used were Windows. The security descriptor might still be pointing at a user that no longer exists - in that case you can just replace the permissions on the entire obs-studio directory in AppData, and permanently fix the issue.

### Replacing Security Descriptors
Ensure that OBS Studio is closed completely before you do this.

1. Open the context menu on the "obs-studio" directory in %AppData% by right clicking onto it.
2. Click "Properties", which opens a new window.
3. Click "Security", to switch to the security information tab.
4. Click "Advanced" to open the advanced security editor.
5. Click "Change" to change the owner.
6. Type in your username
7. Click "Click names", it should fix the thing you typed in to a certain system specific entry.
8. Click "OK" to return to the security editor.
9. Check the first checkbox.
10. Check the 2nd checkbox.
11. Click "Add" which opens up a new window.
12. Click "Select Principal" ...
13. ... and perform the steps 6 to 8 again, this time only returning to the add window.
14. Give yourself "Full Control"
15. Check the checkbox
16. Click OK
17. Click OK
18. Click OK
19. Congratulations, you are now the owner of your own files and directories again.

![image](https://user-images.githubusercontent.com/437395/97811305-0e833600-1c7a-11eb-8482-4b90624f59d7.png)
![image](https://user-images.githubusercontent.com/437395/97811381-8d786e80-1c7a-11eb-87fe-0bce159bbc61.png)
![image](https://user-images.githubusercontent.com/437395/97811376-87828d80-1c7a-11eb-9c20-bb17b3fbc2bb.png)
![image](https://user-images.githubusercontent.com/437395/97811398-aa14a680-1c7a-11eb-916c-b8a2789ae001.png)
![image](https://user-images.githubusercontent.com/437395/97811467-1394b500-1c7b-11eb-83fc-952d5cd9f984.png)
![image](https://user-images.githubusercontent.com/437395/97811496-45a61700-1c7b-11eb-8266-3217140bf1d0.png)
![image](https://user-images.githubusercontent.com/437395/97811543-8c940c80-1c7b-11eb-8d22-7df8e15681f7.png)
![image](https://user-images.githubusercontent.com/437395/97811551-a03f7300-1c7b-11eb-92bd-62b10267d212.png)

**Comment by NazarRecovery** [comment]
Excellent! I was able to do it. To be honest, I'm already Awkward by this situation. After I performed this operation, What should have changed? Everything remained in place for me, and the StreamFX folder was not created in% AppData%.

Maybe I reinstall everything? Or extreme measures - reinstall OS?

=(

**Comment by Xaymar** [comment]
There's another user reporting this issue. So far the cause is unknown, all that's identical is that the directory is never created.

**Comment by NazarRecovery** [comment]
The OBS itself was able to create a library there, but the plugin cannot for some reason.

**Comment by NazarRecovery** [comment]
Good day. Recently I noticed one very interesting thing. It turns out that when exiting OBS, the plugin creates another user in the "Users" folder
![image](https://user-images.githubusercontent.com/68765699/99921174-5ce39c00-2d31-11eb-81b2-1271b2ac245e.png)
![image](https://user-images.githubusercontent.com/68765699/99921178-63721380-2d31-11eb-93f7-d81bf2735b7e.png)
This is most likely my problem.

**Comment by Xaymar** [comment]
Oh hey, that might actually be the problem. That looks like something isn't correctly converting between UTF-8 and the windows native calls, so my original guess of unicode was correct.

**Comment by Xaymar** [comment]
Problem seems to originate here, which assumes that the path is ASCII on Windows: https://github.com/Xaymar/obs-StreamFX/blob/master/source/configuration.cpp#L48

**Comment by NazarRecovery** [comment]
Oh, now it remains to deal with this

**Comment by Xaymar** [comment]
Please try one of these builds and see if the problem is fixed: https://github.com/Xaymar/obs-StreamFX/actions/runs/388746529

**Comment by Xaymar** [comment]
Local testing shows the directory is being correctly created, now all that's left is to figure out why it won't save config.json there.
