### ISSUE TITLE
Call to Action: Help translate StreamFX into other languages!

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#36]
All the translations for StreamFX are crowd sourced, and you can help translate StreamFX into your language too! Simply sign up to Crowdin, head over to [the StreamFX project](https://crowdin.com/project/obs-stream-effects), and start submitting translations.

**Comment by Xaymar** [comment]
The Pull Request #52 added new Text that needs to be translated, so if you have previously added translations to the project consider helping out again!

**Comment by DistantThunder** [comment]
This project looks exciting, I hope I can contribute for french as soon as I can build on Linux.

**Comment by Xaymar** [comment]
I've changed CrowdIn to require verified translations now. If you wish to be a proofreader for your language and have your translations included in future releases, [please message me on Discord](https://discordapp.com/invite/DaeJg7M).

Additionally all languages which have zero translated strings have been dropped. If your language was part of this, and you wish to be a translator for it, please contact me either on Github or Discord.

**Comment by tytan652** [comment]
I wish to be proofreader for the french language, but your discord link is dead.

**Comment by Xaymar** [comment]
@tytan652 Fixed the OP.

**Comment by mj2709** [comment]
Hi, I could support to translate to German.

**Comment by Xaymar** [comment]
> Hi, I could support to translate to German.

I've linked the Crowdin project link in the OP. Any help is appreciated.
