### ISSUE TITLE
Recording : Output to URL

### ISSUE THREAD

**Issue by hb9dug** [Xaymar/obs-StreamFX#362]
No worry, I am not reporting an issue !

You have, with StreamFX, added a very friendly interface + more options to manage NVIDIA GPU and FFmpeg comparing to the "Custom Output (FFmpeg)" in the Recording Mode of OBS Studio.

In our radio-amateur usage of OBS Studio with generate a TS which we send to our DVB-S/S2 modulator over IP using UDP with the FFmpeg Output Type : Output to URL .  

Unfortunately, this Output Type is not available in the Recording Type : standard .

Is it possible to override this directive through a maybe hidden setting in FFmpeg Options/Custom Settings of StreamFX ?

Most of us are using Window 10, a few Ubuntu also.

Looking forward for your comments.

Best regards,
Michel, HB9DUG

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
No, it is not possible to do this. StreamFX does not add the custom output mode.

**Comment by Xaymar** [comment]
**Rejected.** See above comment for why.
