### ISSUE TITLE
Desconexión de Twitch cada vez que abro OBS

### ISSUE THREAD

**Issue by Vikingard** [Xaymar/obs-StreamFX#378]
Error
 

### Description
 Cada vez que abro OBS la interfaz desaparece (chat, informacion de Steam), y tengo que desconectar la cuenta manual y volver a conectarla para que me aparezca y, además, volver a poner cada panel en su sitio. También me sale al iniciar un error que dice: "Error al cargar la información del canal para Twitch - Failed to get text from remote:" Y solo me deja darle a aceptar. Posterior a esto, aparece lo que comentaba que no están los paneles y debo desconectar de forma manual y volver a conectar, etc.
![Error OBS](https://user-images.githubusercontent.com/73620802/98485513-427ccf00-2217-11eb-9fbc-5e835d32e9d5.png)

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST] 26.0.2 (64bit)
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...] Windows 10 Home
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]  19042
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...] AMD Ryzen 9 3900X 12-Core PRocessor (24CPUs) 3.8GHz
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...] Nvidia 1660 GTX Gigabyte
- RAM: [e. g. 16GB, 32GB, 64GB, ...] 32GB

**Comment by Xaymar** [comment]
This is not the support or bug report form for OBS Studio, this is for StreamFX a plugin to OBS Studio. Your error is completely unrelated to the plugin itself.

-----
Este no es el formulario de soporte o informe de errores para OBS Studio, esto es para StreamFX, un complemento para OBS Studio. Su error no está relacionado en absoluto con el complemento en sí. (Traducido con Google Translate)
