### ISSUE TITLE
Duel Recording

### ISSUE THREAD

**Issue by dergie** [Xaymar/obs-StreamFX#380]
### Description
I'd like to suggest the idea of having the ability to Duel Record within a single instance of OBS (if possible). The first recording being the high quality footage (h264/h265)  and the second being low res proxy footage (prores proxy) that you can attach to the high quality footage inside of an NLE. This would be nice for creators with multiple hard drives and would save storage without having to record in lossless/prores 4:4:4, and it would also save them a step of having to create a proxy for that lossless footage later. I think it'd be a great way of improving workflow for content creators. 

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
This is an OBS Studio feature request, inside the StreamFX repo. I'm confused by what this would even achieve, as you would just be wasting disk space as well as CPU and GPU time.

**Comment by dergie** [comment]
> This is an OBS Studio feature request, inside the StreamFX repo. I'm confused by what this would even achieve, as you would just be wasting disk space as well as CPU and GPU time.

I wasn't sure on how in depth StreamFX went into obs. My bad for not knowing better. I just assumed that the way you've added other encoders into obs would be relatable, but I guess not. I know now though!

**Comment by Xaymar** [comment]
This isn't something that can be done with the libOBS API, I would have to reimplement the majority of the OBS Studio UI to make this even barely work - and write my own muxer and so on.

Needless to say, this process would be completely useless to creators. H264/H265 compresses far better than Apple ProRes Proxy, even at low resolution, so you would be wasting CPU time just for something that your GPU can decode in a matter of microseconds - literally, modern GPUs can decode around 40-50 1080p60 H264 and H265 encoded bitstreams. I don't really see a use for this, given all the overhead and other code it would need - you might be able to do this in other software already, but it most likely won't be possible in OBS.
