### ISSUE TITLE
Since installing StreamFX, OBS always crashes on exiting....

### ISSUE THREAD

**Issue by ProfMarc24** [Xaymar/obs-StreamFX#381]
### Description

Every time I exit from OBS Studio I get 'Not Responding' then I have to End Program, generating a crash log...
[Crash 2020-11-19 22-10-00.txt](https://github.com/Xaymar/obs-StreamFX/files/5570224/Crash.2020-11-19.22-10-00.txt)

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
- Please fill out the template completely.
- What does your scene setup look like? Do you use Source Mirror, Dynamic Mask, etc? What are their settings?

**Comment by ProfMarc24** [comment]
Hi Xaymar,
I think my crashing is resolved, I simply re-installed motion transition 2.01 and Stream FX and everything worked perfectly thereafter....
Great software...👍
R/ Marc

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
