### ISSUE TITLE
How to support H.265/HEVC encoding.

### ISSUE THREAD

**Issue by wps1215** [Xaymar/obs-StreamFX#383]
### Description

I just built obs with streamFX and a FFmpeg with NVIDIA HEVC, but I cannot get a "NVIDIA NVENC HEVC （via FFmpeg） in the coder port"

### System Information

- Software Version: [ NEVER LATEST]
- Operating System: [Windows.]
- Kernel Version: [1903 (Windows),]
- CPU: [e. g. Intel i7, .]
- GPU: [e. g. Nvidia RTX 3090]
- RAM: [32GB]

**Comment by Xaymar** [comment]
Can you try the whole thing again and actually explain your problem?

**Comment by Xaymar** [comment]
I'm assuming that that means no and that you don't actually need help.
