### ISSUE TITLE
Dynamic mask with unloaded source

### ISSUE THREAD

**Issue by orion78fr** [Xaymar/obs-StreamFX#384]
### Description
When I try to do a dynamic mask with a source or scene that isn't displayed in the current mix, the mask isn't animated.
Maybe I'm doing something wrong, but I think the scene should be loaded/rendered if added to a filter like this.

Here is a small video showing that if the scene in the filter isn't visible, the mask isn't animated
https://cdn.discordapp.com/attachments/307568025027084288/780815290631061514/2020-11-24_16-10-55.mp4

### System Information
- Software Version: 0.9.1.0-ad245401 / OBS 26.0.2
- Operating System: Windows 10
- Kernel Version: 20H2
- CPU: i7 4790k
- GPU: Nvidia RTX 2080 Ti
- RAM: 16GB

**Comment by skeletonbow** [comment]
What are the properties of the animated input source?

**Comment by orion78fr** [comment]
The input scene is just a gif.

![spirals](https://user-images.githubusercontent.com/8122888/100227369-574ca880-2f21-11eb-9c59-c6bfd56fdff8.gif)

![image](https://user-images.githubusercontent.com/8122888/100227331-49972300-2f21-11eb-953b-3808332bbd96.png)

![image](https://user-images.githubusercontent.com/8122888/100227475-8400c000-2f21-11eb-97b5-0705c7d93b56.png)

The mask only works if I put the Spiral scene visible in the Test cam scene (that's what I've shown in the video).

**Comment by orion78fr** [comment]
Note that it's the same if I chose the scene (Spiral) or the source (Spiral image) as input, it's only animated when the Spiral scene is visible.

**Comment by Xaymar** [comment]
**Confirmed as a bug.** Currently Dynamic Mask gathers a source reference as only that. It does not add it as an explicit child source, which would add to the visible counter of the referenced source.

**Comment by Xaymar** [comment]
It seems that child sources from filters are not considered by libOBS, which is technically an upstream bug. Though I have fixed it now, with a partial workaround.

**Comment by orion78fr** [comment]
Did you report it to upstream ?

**Comment by orion78fr** [comment]
Tested the above build and can confirm this fixes it for me.

(Was going to close the bug but it's both a workaround (so the issue may be useful to track when upstream fixes it) and it's not merged.)
