### ISSUE TITLE
Face Tracking to take source crop into account

### ISSUE THREAD

**Issue by paul-lrr** [Xaymar/obs-StreamFX#402]
### Description
Would it be possible for the face tracking effect to take into account the cropping of a source when attempting to keep the face in frame? This would be very useful in situations where a source is being cropped to a different aspect ratio or where you just need the face tracking to move in a single axis instead of both x and y. I guess this could also be accomplished by being able to zoom the x and y axis separately and cropping the source to change the aspect ratio so the image isn't distorted.

As an example, in the attached image, the upper source is the whole camera frame, the lower source is the cropped version I want to use on an overlay. I have applied face tracking to the lower source, but since the tracking is based on the full camera view, it doesn't keep the face in frame, even though there is more image  available.
![face tracking](https://i.ibb.co/BrSsnV5/Screenshot-2020-12-05-114736.png)

### Checklist
- [ ] I am willing to pay someone to implement this feature.
- [x] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
It is not possible to take into account things that happen _after_ the filter runs.

**Comment by paul-lrr** [comment]
Maybe the filter itself could do the cropping in addition to or as an alternative to the zoom setting?

**Comment by Xaymar** [comment]
It's already doing cropping. If you want to limit the axis, that might be possible in the future, but there's no real use for this in the first place.

**Comment by paul-lrr** [comment]
My use case for cropping on one axis would be for situations where I want to change the aspect ratio of the source from 16x9 (as shown in the image above). This is something I do all the time, both for individual streams and for group productions to make the players' facecams fit on the screen better. As it is, the filter would already help to keep the subject in frame, if the horizontal cropping was applied by the filter, presumably that would allow it to use that area to handle even larger head movements (in that axis, anyway)

**Comment by skeletonbow** [comment]
Apply the crop after the face tracking.

**Comment by paul-lrr** [comment]
@skeletonbow The problem with cropping afterwards is what you can see in the image above. The filter is getting the frame bounds from the original source so it is unaware that it has been cropped and the face is no longer in the frame.

**Comment by Xaymar** [comment]
The filter keeps the face in the center, so just crop to the center?

**Comment by paul-lrr** [comment]
Sorry if I'm not explaining myself well. You can see the issue in the image above, which shows two completely separate video instances, both with the face tracking filter applied. The lower source (which is how I want to use the facecam on my overlay) is cropped to the center. The filter does a good job of keeping my face in the center of the shot and therefore inside the cropped frame until it reaches the edge of the uncropped image. Since the lower source cropping was applied using the OBS transform controls, the filter doesn't know about it and doesn't know that it could continue panning the source over to keep the face in the frame. 

From what I understand, a solution would be to have the zoom control in the face tracking filter be able to zoom the x and y axis independently. Zooming the x axis would effectively be like cropping the source horizontally, but in a way that allows the filter to know about the extra image available for panning. Obviously zooming only one axis would distort the source, so it would have to also apply an appropriate transform to keep the source in the proper proportion.

**Comment by skeletonbow** [comment]
Still not completely clear what the problem is to me but it's probably just a matter of restructuring your scene and/or what the filter(s) get applied to and the order it is happening in.  Probably better to discuss this in the Discord support channel in realtime if you like.

**Comment by Xaymar** [comment]
It is not possible to split the zoom level at all. It's either both, or none.

> The filter does a good job of keeping my face in the center of the shot and therefore inside the cropped frame until it reaches the edge of the uncropped image.

Yes that's because there's nothing left to pan to. Where do you expect it to go if there's nothing left to pan to? The moon?

**Comment by Xaymar** [comment]
From what I understood of this mess of a description, you want to be able to customize the aspect ratio that it uses for the final rendering. This is not possible, as the filter itself _does not modify the output size by design_. It might be possible with 0.10, but that will be very far off - your best bet is to learn C++ and implement the thing you need.

**Comment by paul-lrr** [comment]
Ok, fair enough. Sorry my description was confusing. Thanks so much for all your work on the face tracking and all the other filters in the StreamFX suite.
