### ISSUE TITLE
Update notification prevents OBS usage.

### ISSUE THREAD

**Issue by nuggs** [Xaymar/obs-StreamFX#404]
### Description
When launching OBS with an older version of StreamFX and you are notified with the window telling you there's an update clicking either option just hides the Window but I'm assuming doesn't actually close it as you can't interact with OBS after it "closes".
I'd record video footage of this but since I can't use OBS with an out of date install of StreamFX there is no video.  Updating fixes this but I don't think having an outdated plugin should prevent usage of OBS.
OBS can't even be closed normally and has to be force killed because you can't even right click on the system tray icon to exit from OBS.
[2020-12-07 10-09-46.txt](https://github.com/Xaymar/obs-StreamFX/files/5654502/2020-12-07.10-09-46.txt)

### System Information
- Software Version: 26.0.2
- Operating System: Arch Linux with i3 Window Manager.
- Kernel Version: 5.9.12-1
- CPU: AMD Ryzen 2600
- GPU: AMD Vega56
- RAM: 16GB

**Comment by nuggs** [comment]
Just realized there was a closed issue with this, must have missed it when I was looking the first time so I'm assuming this is fixed with the latest version so sorry about that.

**Comment by nuggs** [comment]
Just realized there was a closed issue with this, must have missed it when I was looking the first time so I'm assuming this is fixed with the latest version so sorry about that.

**Comment by Xaymar** [comment]
Yes, this is what 0.9.2 fixes. I know the description of the fix isn't great, but it affected all of the Qt5 dialogs used and dominantly made itself visible with the GDPR dialog.
