### ISSUE TITLE
Dynamic mask prevents restarting the source

### ISSUE THREAD

**Issue by MrDogit** [Xaymar/obs-StreamFX#405]
### Description
If I add a dynamic mask to the source filters and tell it to use a specific source as a mask, then this same source is not restarted, if the "restart playback when the source becomes active" checkbox is checked.

Sorry for machine translation. if you need to describe the problem more clearly, I can send a video with this bug.

### System Information
[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5661576/DxDiag.txt)
Some LOGS: [2020-12-08 22-48-15.txt](https://github.com/Xaymar/obs-StreamFX/files/5661587/2020-12-08.22-48-15.txt)

**Comment by Xaymar** [comment]
That is because Dynamic Mask already activates the source while it's being referenced and shown.

**Comment by MrDogit** [comment]
> That is because Dynamic Mask already activates the source while it's being referenced and shown.

Oh ... Ok, I get it. This of course creates some difficulties, but I hope it will not cause problems. It would be nice if there was a checkbox that says "Do not send a signal about layer activity", but that's up to you.

**Comment by Xaymar** [comment]
That checkbox would break Dynamic Mask. The other source wouldn't know that it has to render, so it would show a freeze frame and do nothing. I recommend learning how to use the media controls in OBS to restart playback, as they are for this exact purpose.

**Comment by MrDogit** [comment]
Good advice. But I rather need to hide a certain source after a certain time. If to explain, then I have an animation and a text layer (on which the timer runs, using a script). I needed to hide the text layer during one animation and show it when the animation in the video reaches the desired point. The only way that popped into my head was to make 2 videos of the same length. The first is the animation itself, and the second works like a mask, and at the same time is synchronized with the animation. I put them in the same folder and they run at the same time, which allowed me to make the animation I want. 

If you know an easier way to do this, I would be very happy.  Oh ... and I almost forgot.  Thanks for your great plugin.
