### ISSUE TITLE
remote control?

### ISSUE THREAD

**Issue by HansElectrumpet** [Xaymar/obs-StreamFX#408]
### Description

The ability to control the filter with WEBsockets and consecutively with OSC through node.js.
Or maybe this is already implemented/possible? In which case I'll dive into the code.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
Obs-websocket is your friend

**Comment by HansElectrumpet** [comment]
Thanks, I'll pull it together then. Thanks for the good work.
