### ISSUE TITLE
System Tray Bug

### ISSUE THREAD

**Issue by Multimoon27** [Xaymar/obs-StreamFX#414]
Hello, I've downloaded your plugin yesterday and now when I try to hide OBS in the system tray, it only enable performance mode without reduce it. What can I do to resolve that ?

![bug](https://user-images.githubusercontent.com/76163482/102486871-fde02100-4069-11eb-929e-824febcbdafb.gif)

**Comment by Xaymar** [comment]
That's... not even something that StreamFX can affect.

**Comment by Xaymar** [comment]
Unable to reproduce this claimed bug. StreamFX does not affect the tray menu at all, that is all core OBS Studio behavior.
