### ISSUE TITLE
Nvidia Face Tracking doesn't work

### ISSUE THREAD

**Issue by RandomUserGem** [Xaymar/obs-StreamFX#415]
Hello!
I own RTX 3070, and i tested Face Tracking via Nvidia Broadcast Studio, face tracking works fine. I know that a few months ago, StreamFX's Nvidia Face Tracking Filter worked fine, but right now it doesn't work. I add filter, change values, nothing happens. 
I can't use Nvidia Broadcast, due to i need 2 same camera scenes - 1st without tracking, and 2nd - with tracking.

**Comment by Xaymar** [comment]
Please fill out the template instead of deleting it.
