### ISSUE TITLE
Provide 32-bit builds

### ISSUE THREAD

**Issue by Suppresed** [Xaymar/obs-StreamFX#419]
I have a camera that does not have 64-bit drivers for windows. Therefore I need to run OBS 32-bit. What is your excuse to not build 32-bit anyway? "You don't have an excuse to be on 32-bit anymore, hardware has gotten dirt cheap thanks to AMD Ryzen. You can get a barebone modern PC for around 260 €, or upgrade your existing one for around 140 €." goes both ways to tell devs that they can build faster for cheap too.

**Comment by Xaymar** [comment]
If you need 32-bit, build it yourself. It was dropped due to out-of-memory issues, and you really don't have any reason to use awful hardware.

**Comment by Suppresed** [comment]
> 
> 
> If you need 32-bit, build it yourself. It was dropped due to out-of-memory issues, and you really don't have any reason to use awful hardware.

it goes to 187 fps since 2006 how tf is it awful hardware? bitchmade dev
