### ISSUE TITLE
Crash with color format other than NV12

### ISSUE THREAD

**Issue by kiwixz** [Xaymar/obs-StreamFX#423]
### Description
Choosing a color format other than NV12 (in Settings/Advanced/Video) makes it impossible to start recording/streaming.

I tried with a blank new OBS profile to make sure it's the real cause.

### System Information
- Software Version: OBS 26.1.1 with StreamFX 0.9.2 (also tried 0.8.3)
- Operating System: Windows 10
- Kernel Version: 20H2
- CPU: Intel i7
- GPU: GTX Pascal
- RAM: 16GB

**Comment by Xaymar** [comment]
Please attach a log file as required by the template.

**Comment by kiwixz** [comment]
I don't want to, sorry.  The issue was happening when trying to set "B-Frame Reference Mode" to "Use only middle B-Frames as references".  Note that trying to launch it once produce makes it error out, and then StreamFX's encoder wont work until OBS is restarted (even if the setting is fixed).

I just put back "B-Frame Reference Mode" to the default (disabled) and it works now.
