### ISSUE TITLE
I downloaded the Zip file and extracted to OBS folder but it is not showing up.

### ISSUE THREAD

**Issue by That1guykaiser** [Xaymar/obs-StreamFX#424]
### Description
 I directly extracted the zip file into the program files folder for OBS and have even tried extracting them to other places in the OBS folder but nothing the plug in has shows up. at all. 
[log files.txt](https://github.com/Xaymar/obs-StreamFX/files/5828682/log.files.txt)

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System Microsoft Windows 10 Home

- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: Intel (R) Core (TM) i5-8400 Cpu @ 2.80 GHz
- GPU: MSI Geforce GTX 1050 TI
- RAM: 16.0

**Comment by Xaymar** [comment]
StreamFX.dll is not present in the loaded modules. Please follow the installation guide on the wiki.
