### ISSUE TITLE
xttfy.felip@gmail.com

### ISSUE THREAD

**Issue by felip311** [Xaymar/obs-StreamFX#429]
![Desktop Screenshot 2021 01 21 - 10 12 25 24](https://user-images.githubusercontent.com/77777747/105329203-2e6b2b80-5bd1-11eb-8bd8-1e6b10333543.png)

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Fill out the template.
