### ISSUE TITLE
No way to restart a media source used as dynamic mask in 0.9.2

### ISSUE THREAD

**Issue by benank** [Xaymar/obs-StreamFX#431]
### Description
When using an inactive source as a dynamic mask in 0.9.1, the media is restarted when it becomes visible (if that checkbox is checked). This no longer works in 0.9.2. I am trying to use a media source as a dynamic mask, but there is no way to restart the media source. I have tried toggling the media source as active/inactive and disabling/enabling the dynamic mask filter.

### System Information
- Software Version: 0.9.2 (works in 0.9.1)
- Operating System: Windows 10
- CPU: Inten i7 9700k
- GPU: GTX 1070 SUPER
- RAM: 32 G

**Comment by Xaymar** [comment]
The filters track the parent's visibility/activity, in addition to the filter itself. If you want to restart a media source, you should be using media controls for now.

**Comment by benank** [comment]
Thanks for the response. I'm trying to automate it using Lioranboard, but Lioranboard doesn't support media controls yet. I looked into custom packets using obs-websocket and didn't see anything that was able to trigger a restart.

I've also tried nesting the media source in a scene and then applying the dynamic mask to the scene - no luck on restarting it when it becomes visible there, either.
