### ISSUE TITLE
How to remove the main menu of Streamfx?

### ISSUE THREAD

**Issue by iesvme** [Xaymar/obs-StreamFX#432]
How to remove the main menu of Streamfx?

**Comment by Xaymar** [comment]
Uninstall StreamFX. Why would you remove the StreamFX menu in the first place.

**Comment by iesvme** [comment]
Sorry, sir. But I thougt it looks like intricacy very much.

**Comment by Xaymar** [comment]
I have no idea what this ticket is even for, so I'm closing it.
