### ISSUE TITLE
obs64.exe - Application error

### ISSUE THREAD

**Issue by gabuu20** [Xaymar/obs-StreamFX#433]
The Exception Breakpoint
A breakpoint has been reached.
 (0x80000003) occurred in the application at location
0x00007FFD3B7EF142.

Click on OK to terminate the program

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Please fill out the template as requested and attach a log and crash log.

**Comment by Xaymar** [comment]
Closing as the user has not updated the post.
