### ISSUE TITLE
Cost of native, built-in support for MacOS X

### ISSUE THREAD

**Issue by bryanrossUK** [Xaymar/obs-StreamFX#434]
### Description

The mainstream releasees of obs-StreamFx are currently focussed towards Windows and Linux.  Compiling a working solution for MacOS is beyond many users.  It has been said in other threads that better support for MacOS users (i.e. an easy to install binary) would require further investment.  How much capital is required to achieive this?  

Note - this would have to include long term support for MacOS.

### Checklist

- [x] I am willing to pay someone to implement this feature.
- [x] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
1. Primary cost is a MacOS machine for each architecture that should be supported (M1 and X86).
2. Secondary cost is upkeep for the machines, such as subscription costs for development tools if there are any.
3. Tertiary cost is my own time to spend on this. I do not use MacOS and have zero reason to use it.

These are the three costs I continuously have stated, which end up being ignored every single time.

**Comment by Xaymar** [comment]
These are the prices I found for the devices needed:

- [Apple Mac Mini](https://geizhals.de/apple-mac-mini-mgnr3d-a-a2422055.html?hloc=at&hloc=de) at 750,- €
- [Apple iMac](https://geizhals.de/apple-imac-21-5-a2017529.html?hloc=at&hloc=de) at ~1550,- €

This alone is about what I make in two months after all fixed expenses, so I think it's obvious why I'm not going for Mac and keep telling people that the ROI is negative.

**Comment by sapkra** [comment]
I'm using the [obs gstreamer plugin](https://github.com/fzwoch/obs-gstreamer) which is using docker to compile the macos version. Maybe this would be a good alternative.

It is using [osxcross](https://github.com/tpoechtrager/osxcross) which can target arm and x86.

**Comment by Xaymar** [comment]
The problem isn't building, that would be entirely covered by Github Actions. The problem is debugging, development, and time investment.

**Comment by sapkra** [comment]
Maybe the community could help with that. Additionally there are some cloud providers where you can rent mac os machines or you could also run a vm locally. I think temporary it would be fine to develop on x86 only. The community could test the M1 macs if they want to support it. But of course, time is always a key investment.

**Comment by Xaymar** [comment]
So nothing would change from what it already is, and we went full circle and looped right back to where we already are. Since the ROI is still below zero, I have no reason to spend _any_ money on a platform i don't use.

**Comment by Xaymar** [comment]
Thanks to Elgato sponsoring a machine, I now have a way to build and test StreamFX for MacOS. While it is ARM based, it does the job and even allows me to figure out how to deal with ARM in the future. #475 is one of many future PRs as I try and fix more and more issues.
