### ISSUE TITLE
OBS has crashed!

### ISSUE THREAD

**Issue by michelehub** [Xaymar/obs-StreamFX#435]
### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Please add a crash log.

**Comment by michelehub** [comment]
--
Inviato da Libero Mail per Android Sabato, 30 Gennaio 2021, 01:12PM +01:00 da Xaymar  notifications@github.com :

**Comment by Xaymar** [comment]
More than a week has passed and the user refused to provide any information of note. Closing.
