### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dannyt986** [Xaymar/obs-StreamFX#436]
Thank you for your work and support! Danny

### Description
I have installed the latest StreamFX over the latest OBS (reinstalls tested), I have also repair installed the [C++] libraries to ensure they were at the minimum recommended install level. 
Source is a logitech C920 HD camera direct to OBS, when I go to select the Filter.Blur effect OBS crashes repeatably, even with other filters and sources turned off.
OBS crash log file is attached.

### System Information
- Software Version: 0.9.2.0 on OBS 26.1.1
- Operating System: Windows 10
- Windows version: 10.0 build 19041 (release: 2004; revision: 746; 64-bit)
CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
- GPU: Nvidia GTX 1080ti 11gb
- RAM: 12gb
[OBSDump.txt](https://github.com/Xaymar/obs-StreamFX/files/5897994/OBSDump.txt)

**Comment by Xaymar** [comment]
The error you've encountered stems from an incorrect installation of StreamFX. [Please follow the instructions outlined on the Wiki for installation.](https://github.com/Xaymar/obs-StreamFX/wiki/Installation).

**Comment by dannyt986** [comment]
Thanks for the quick feedback.
Im being hard of understanding, installed as per the wiki from the exe without OBS running. Ive also tried unzipping the archives to the OBS C:\Program Files\obs-studio folder on my machine.
Only thing I see is my CPU maybe not upto the minimum requirement? Im not trying to run games at the same time, just do some picture processing to feed to Zoom etc

**Comment by Xaymar** [comment]
Looking at the crash log, you have an ancient version of the plugin installed called `obs-stream-effects.dll`. Please remove this version first before attempting anything else.

**Comment by dannyt986** [comment]
Awesome. Yes that was it! I didnt realize it was even the same plugin. Thank you!
