### ISSUE TITLE
Allow HEVC with Youtube HLS

### ISSUE THREAD

**Issue by Craftyawesome** [Xaymar/obs-StreamFX#450]
### Description

Youtube supports streaming HEVC with the HLS protocol. 
https://developers.google.com/youtube/v3/live/guides/hls-ingestion
Currently, you can only choose H.264 encoders. Please allow HEVC.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.
(this can technically be done in vanilla obs by recording custom output to the correct url, but this is silly)

**Comment by Xaymar** [comment]
StreamFX is not what's preventing you from streaming with HEVC - that is entirely up to OBS Studio.

**Comment by Craftyawesome** [comment]
> StreamFX is not what's preventing you from streaming with HEVC - that is entirely up to OBS Studio.

So there is something hardcoded to H264 that plugins cannot change? That's unfortunate.

Thanks for the quick reply.
