### ISSUE TITLE
Feature Request:  DNxHR

### ISSUE THREAD

**Issue by OnlyOneMoreHour** [Xaymar/obs-StreamFX#451]
Hello

For Windows Users DNxHR makes more sense than Pro Res (Apple Codec, Windows Codec version create due to reverse engineering and for me not 100% compatible with Video Editing Software (e.g. Adobe Premiere Smart Render).

Could anyone implement and DNxHR Option? I would contribute with a donation if anyonee was able to implement DNxHR successfully and stable. I need it preferably at 1440p solution.

**Comment by Xaymar** [comment]
Please do not delete the template.
