### ISSUE TITLE
Installing obs-StreamFX on Fedora

### ISSUE THREAD

**Issue by psads-git** [Xaymar/obs-StreamFX#453]
Dear Xaymar,

I would like to install obs-StreamFX on a machine running Fedora 33 Linux. Could you please give me some guidance about how to accomplish that?

Thanks in advance!

**Comment by Xaymar** [comment]
Please make sure to read the [Installation Guide](https://github.com/xaymar/obs-streamfx/wiki/Installation).

**Comment by psads-git** [comment]
Thanks, Xaymar. I was doubtful that the ubuntu zip file would work on Fedora -- that is why I came here. Fortunately, it does work nicely on Fedora -- now I have streamFX working perfectly on my OBS Studio.
