### ISSUE TITLE
Blurring no rectangular regions

### ISSUE THREAD

**Issue by psads-git** [Xaymar/obs-StreamFX#456]
Dear Xaymar,
 
I am using your obs-StreamFX blur filter to achieve a sort of blurred background for a virtual camera. Specifically, I am blurring everything around the image of the person who speaks, who appears inside a small rectangular non-blurred box. I am wondering whether it is possible to have a circular non-blurred region (instead of the rectangular one). Do you believe that combining obs-StreamFX with ideas developed at
 
https://www.versluis.com/2019/01/obs-round-cutout-mask/
 
will one be able to accomplish non-rectangular blurred regions?
 
Thanks in advance!

**Comment by Xaymar** [comment]
**Please don't delete the template when submitting features, issues or pull requests!**

You can already do the feature with everything StreamFX and OBS Studio has to offer, you just need to combine everything.
