### ISSUE TITLE
3D Transform Filter missing from installation

### ISSUE THREAD

**Issue by ronplaysgames** [Xaymar/obs-StreamFX#458]
### Description
 
When I select Effect Filters > Add > 3D transform doesn't show up but all the other Stream FX filters do?
 https://gyazo.com/6b5f3e0a67b40b1ec5012ef8d079e8ec

[2021-02-08 16-40-21.txt](https://github.com/Xaymar/obs-StreamFX/files/5941218/2021-02-08.16-40-21.txt)

### System Information

- Software Version: [StreamFX - 0.10.0.0a1-gfbe35d15 | OBS - 26.1.1]
- Operating System: [Microsoft Windows 10 Home]
- Kernel Version: [10.0.19041 N/A Build 19041]
- CPU: [AMD Ryzen 9 5900X 12-Core Processor]
- GPU: [NVIDIA GeForce RTX 3070]
- RAM: [32GB]

**Attached DxDia for system information - [DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5941222/DxDiag.txt)**

**Comment by Xaymar** [comment]
Please fill out the template. Without this information, I can't provide you any further help.

**Comment by ronplaysgames** [comment]
I did?
I just used screenshots as requested.

 
Cameron Black
Partnered Streamer, Twitch.tv
(+64) 272386028
P.O. Box 5084, Frankton Central NZ Post, Hamilton, 3204





 
"If you're not a little bit weird, you're probably quite a bit boring."

**Comment by Xaymar** [comment]
No, you've quite literally left the template as it is, only filling out one part. This is clearly visible by just looking at it.

Additionally, it seems that you are using a Testing release. Testing releases are not meant for Production usage, and should not be used if your use of OBS Studio depends on it. They're Testing/Prerelease for a good reason after all.

**Comment by ronplaysgames** [comment]
> No, you've quite literally left the template as it is, only filling out one part. This is clearly visible by just looking at it.
> 
> Additionally, it seems that you are using a Testing release. Testing releases are not meant for Production usage, and should not be used if your use of OBS Studio depends on it. They're Testing/Prerelease for a good reason after all.

I have updated the field, hope this helps. Could you please point me in the right direction for the up-to-date version please?

**Comment by ronplaysgames** [comment]
Ok so I found latest version and 3D transform is on there :)
