### ISSUE TITLE
Blur background while streaming live with web camera

### ISSUE THREAD

**Issue by jaryszek** [Xaymar/obs-StreamFX#459]
Hello,

i am trying to blur my background using StreamFX while broadcasting live using my web camera.
How can i do this?

Please help

**Comment by Xaymar** [comment]
**Please don't delete the template when submitting features, issues or pull requests!**

**Comment by Xaymar** [comment]
Additionally, for generic support or design help, ask your friends or join the [official discord](https://discord.gg/rjkxERs).

**Comment by jaryszek** [comment]
Thank you, 
how can i find design-general/design-help server there to ask my question?
