### ISSUE TITLE
mispelled FILTER_TRAN(S)FORM in make file

### ISSUE THREAD

**Issue by BadCisky** [Xaymar/obs-StreamFX#461]
https://github.com/Xaymar/obs-StreamFX/blob/fbe35d15c4b5eaff4f15fff95cfb66c0d262f454/CMakeLists.txt#L1188
missing an "S" in "TRANSFORM" word so 3d transform filter is not included in the latest release 0.10.0a1
code:
is_feature_enabled(FILTER_TRANFORM T_CHECK)

**Comment by BadCisky** [comment]
sorry, just noticed issue #460 was already open for the same issue

**Comment by Xaymar** [comment]
It looks like you are using pre-release versions, which are unsupported for production use. They are offered purely for testing, and as such receive no support. If you wish to go back to the last stable version, use the version provided by [this link](https://github.com/Xaymar/obs-StreamFX/releases/latest).
