### ISSUE TITLE
my streamFX obs does not have the 3D transform

### ISSUE THREAD

**Issue by babyfatina** [Xaymar/obs-StreamFX#462]
I downloaded the streamFX  bundle for obs because i needed the 3d transform plugin  but when i installed it i found out that i have the other plugins except the 3d transform. I tried to reinstall it, to look for update, to update obs, but still nothing to do.

10.0.19041
Windows 10 pro
AMD ryzen 5 3600 6 core processor
GeForce RTX 2060
32Gb Ram
![Immagine 2021-02-10 135211](https://user-images.githubusercontent.com/78856891/107512501-37836300-6ba7-11eb-9d3b-80a6fba31e21.jpg)

**Comment by MattyFresh68** [comment]
Looks like you are using a pre-release version. You should go back and install the latest stable full release version.

**Comment by Xaymar** [comment]
It looks like you are using pre-release versions, which are unsupported for production use. They are offered purely for testing, and as such receive no support. If you wish to go back to the last stable version, use the version provided by [this link](https://github.com/Xaymar/obs-StreamFX/releases/latest).
