### ISSUE TITLE
it is not showing up the transformation 3d filter

### ISSUE THREAD

**Issue by jorgelg08obs** [Xaymar/obs-StreamFX#463]
### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Please fill out the template. Without this information, I can't provide you any further help.

**Comment by Xaymar** [comment]
It looks like you are using pre-release versions, which are unsupported for production use. They are offered purely for testing, and as such receive no support. If you wish to go back to the last stable version, use the version provided by [this link](https://github.com/Xaymar/obs-StreamFX/releases/latest).
