### ISSUE TITLE
No 3D transform

### ISSUE THREAD

**Issue by AssoMania** [Xaymar/obs-StreamFX#469]
Hi there,

I have an issue after installing StreamFX (streamfx-windows-2019-0.10.0.0a1-gfbe35d15) on OBS 26.1.1 (64bits)
I can't find the 3D transform in the filter menu. 

Did I miss something ?

Thanks for your help

**Comment by Xaymar** [comment]
**Please don't delete the template when submitting features, issues or pull requests!**
