### ISSUE TITLE
SDF Filter doesn't run

### ISSUE THREAD

**Issue by tirpo** [Xaymar/obs-StreamFX#471]
### Description
Hello, unfortunately I can't get the SDF effect to run. All other filters work, but the most important one for me does not produce any results. I have already followed the instructions for reducing the texture size, but unfortunately neither shadows nor light frames are produced.
I used the Installer.

### System Information

- Software Version: 0.9.3
- Operating System: Win 10
- Kernel Version: Version 20H2 (Build 19042.631)
- CPU: AMD Ryzen 5 3600
- GPU: Radeon RX 470 (8 GB RAM)
- RAM: 16 GB

**Comment by Xaymar** [comment]
Does the source you attempt to use it on have transparent pixels/texels? If not, nothing can happen.

**Comment by tirpo** [comment]
Hello, first of all many thank you for your answer. It seems to have been the crux of the matter. I have now been able to successfully apply SDF to a graphic. But what I have seen is that streamers have applied it to the video source. And I don't know how to add a transparent area there. I know this doesn't really belong here, but I couldn't find help anywhere else. Is there a way to do this?

**Comment by Xaymar** [comment]
Crop/Pad with negative offset. Or they use fixed images for it instead. Or a greenscreen.

**Comment by tirpo** [comment]
Many thanks! I got it with Crop/Pad.
