### ISSUE TITLE
Hi, I just installed StreamFX and it seems everything is okay once I open OBS Studio but then the filters are the same as I had before. No 3D Transform or Blur

### ISSUE THREAD

**Issue by marquelsalazar** [Xaymar/obs-StreamFX#472]
### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Hello, it looks like you didn't read or understand all of the words on the release page. 0.10.x is currently an Alpha, and should not be used in Production environments. [Please use the latest release instead.](https://github.com/Xaymar/obs-StreamFX/releases/latest)

**Comment by marquelsalazar** [comment]
Thanks a lot for the quick answer
