### ISSUE TITLE
AMF ffmpeg options

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/obs-StreamFX#474]
### Description
hi, i dont know how to set custom FFMPEG settings:
-cabac=1 -sync-lookahead=0 -fast-pskip=0 -aq-mode=1 -aq-strength=0.7

i assume they are not implemented in AMF-ffmpeg
is there an equivalent option?

results in:
`16:18:56.052: [StreamFX] Option '-cabac=1' (key: 'cabac', value: '1') encountered error: Option not found`
`16:18:56.052: [StreamFX] Option '-sync-lookahead=0' (key: 'sync-lookahead', value: '0') encountered error: Option not found`
`16:18:56.052: [StreamFX] Option '-fast-pskip=0' (key: 'fast-pskip', value: '0') encountered error: Option not found`
`16:18:56.052: [StreamFX] Option '-aq-mode=1' (key: 'aq-mode', value: '1') encountered error: Option not found`
`16:18:56.052: [StreamFX] Option '-aq-strength=0.7' (key: 'aq-strength', value: '0.7') encountered error: Option not found`

### System Information
- Software Version: 0.10.0.0a2-g7829817f
- Operating System: Win10 20H2
- CPU: Ryzen 7 2700X
- GPU: RX 580 4G
- RAM: 32GB (4x 8GB) DDR4-3200CL14

**Comment by Xaymar** [comment]
For FFmpeg related help, please use the FFmpeg mailing list. StreamFX does nothing more but offer you to use FFmpeg encoders directly.
