### ISSUE TITLE
FFmpeg with AMF and non-AMF parameters compatible?

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/obs-StreamFX#477]
### Description
hi,

i use this settings to produce a good quality stream:

![image](https://user-images.githubusercontent.com/21282980/108564150-f3106980-7302-11eb-9363-019262aa359b.png)

FFmpeg options:
-usage=2 -quality=2 -profile=100 -level=42 -rc=1 -preanalysis=true -coder=1 -qmin=25 -qmax=46 -me_range=36 -subq=9 -me_half_pel=true -me_quarter_pel=true -vbaq=true -trellis=2 -intra_refresh_mb=170

LOG:

`22:43:50.259: Starting stream due to hotkey`
`22:43:50.263: [StreamFX] [h264_amf] Initializing...`
`22:43:50.263: [StreamFX] [h264_amf]   FFmpeg:`
`22:43:50.263: [StreamFX] [h264_amf]     Custom Settings: -usage=2 -quality=2 -profile=100 -level=42 -rc=1 -preanalysis=true -coder=1 -qmin=25 -qmax=46 -me_range=36 -subq=9 -me_half_pel=true -me_quarter_pel=true -vbaq=true -trellis=2 -intra_refresh_mb=170`
`22:43:50.263: [StreamFX] [h264_amf]     Standard Compliance: Experimental`
`22:43:50.263: [StreamFX] [h264_amf]     Threading: Slice & Frame (with 1 threads)`
`22:43:50.263: [StreamFX] [h264_amf]   Video:`
`22:43:50.263: [StreamFX] [h264_amf]     Texture: 1600x900 nv12 BT.709 tv`
`22:43:50.263: [StreamFX] [h264_amf]     Framerate: 50/1 (50.000000 FPS)`
`22:43:50.263: [StreamFX] [h264_amf]   Keyframes: `
`22:43:50.263: [StreamFX] [h264_amf]     Distance: 100 frames`
`22:43:50.263: [StreamFX] [h264_amf]   AMD AMF:`
`22:43:50.263: [StreamFX] [h264_amf]     Usage: lowlatency`
`22:43:50.263: [StreamFX] [h264_amf]     Preset: quality`
`22:43:50.263: [StreamFX] [h264_amf]     Rate Control: me_quarter_pel`
`22:43:50.263: [StreamFX] [h264_amf]       Look-Ahead: Enabled`
`22:43:50.263: [StreamFX] [h264_amf]       Frame Skipping: Disabled <Default>`
`22:43:50.263: [StreamFX] [h264_amf]       Filler Data: Enabled`
`22:43:50.263: [StreamFX] [h264_amf]       Bitrate:`
`22:43:50.263: [StreamFX] [h264_amf]         Target: 6000000 bits/sec`
`22:43:50.263: [StreamFX] [h264_amf]         Maximum: 0 bits/sec <Default>`
`22:43:50.263: [StreamFX] [h264_amf]         Buffer: 4000000 bits`
`22:43:50.263: [StreamFX] [h264_amf]       Quantization Parameters:`
`22:43:50.263: [StreamFX] [h264_amf]         I-Frame: -1  <Default>`
`22:43:50.263: [StreamFX] [h264_amf]         P-Frame: -1  <Default>`
`22:43:50.263: [StreamFX] [h264_amf]     Other:`
`22:43:50.263: [StreamFX] [h264_amf]       Reference Frames: -1 Frames`
`22:43:50.263: [StreamFX] [h264_amf]       Enforce HRD: Disabled <Default>`
`22:43:50.263: [StreamFX] [h264_amf]       VBAQ: Enabled`
`22:43:50.263: [StreamFX] [h264_amf]       Access Unit Delimiter: Disabled <Default>`
`22:43:50.263: [StreamFX] [h264_amf]         Maximum Size: 0  <Default>`
`22:43:50.263: [StreamFX] [h264_amf]       Half-Pel Motion Estimation: Enabled <Default>`
`22:43:50.263: [StreamFX] [h264_amf]       Quarter-Pel Motion Estimation: Enabled <Default>`
`22:43:50.263: [StreamFX] [h264_amf]     H.264/AVC:`
`22:43:50.263: [StreamFX] [h264_amf]       Profile: high`
`22:43:50.263: [StreamFX] [h264_amf]       Level: 4.2`
`22:43:50.301: ---------------------------------`
`22:43:50.302: [FFmpeg aac encoder: 'adv_stream_aac'] bitrate: 96, channels: 2, channel_layout: 3`
`22:43:50.303: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://server.tld...`
`22:43:50.305: [rtmp stream: 'adv_stream'] Interface: Intel(R) I211 Gigabit Network Connection (ethernet, 1000 mbps)`
`22:43:50.800: [rtmp stream: 'adv_stream'] Connection to rtmp://server.tld successful`
`22:43:50.805: ==== Streaming Start ===============================================`
`22:45:01.073: Stopping stream due to hotkey`
`22:45:01.380: [rtmp stream: 'adv_stream'] User stopped the stream`
`22:45:01.380: Output 'adv_stream': stopping`
`22:45:01.380: Output 'adv_stream': Total frames output: 3514`
`22:45:01.380: Output 'adv_stream': Total drawn frames: 3554`
`22:45:01.388: ==== Streaming Stop ================================================`

QUESTION:
The log shows it accepted ALL my custom parameters - but the thing is only part of them are AMF - some of them are native FFmpeg (for h.264 encoding).
Do parameters like: `-me_range=36 -subq=9 -trellis=2` actually work? are they calculated on OpenCL? or on CPU? or just not active?

especially `subq=9` and `trellis=2` would be heavy load on either OpenCL or CPU

but the quality looks ok so far for a hard to encode scene:
http://benmanshafen.de/obs/900p50_sFX.mp4 (flv2mp4 - orgfile only copy)

### System Information
- Software Version: 0.10.0.02-g7829817f
- Operating System: Win10
- Kernel Version: 20H2
- CPU: Ryzen 7 2700X
- GPU: RX 580 4G
- RAM: 32GB DDR4-3200CL14 (4x 8GB)

**Comment by Xaymar** [comment]
Parameters that are not supported by the AMF encoder in FFmpeg do not work, and do nothing. Any effect you may see from them is a purely a imagined effect. Refer to the FFmpeg-users mailing list to get more information about what parameters work and don't work.

**Comment by Benman2785** [comment]
ok - thank you for clarifying this ;)

**Comment by Benman2785** [comment]
so i think the benefit i got in quality is based on using "low latency mode" instead "transcoding" && the reduced "-intra_refresh_mb" && minQP
