### ISSUE TITLE
Install on macOS

### ISSUE THREAD

**Issue by marcscholl** [Xaymar/obs-StreamFX#480]
### Description

I'm trying to install StreamFX on macOS (Big Sur 11.2.1), following your installation instructions.
two issues arose:
1. (minor:) there is no "Latest Production" version for macOS, so I used the "Testing" one
2. (major:) as per instructions (steps 4 and 5) I have to allow loading the StreamFX.so library by right-click opening the file. *This does not work*, since macOS says it knows no program to open that kind of files (.so)

### System Information

macOS 11.2.1
OBS 26.1.2

**Comment by Xaymar** [comment]
1. As explained on the release itself, MacOS support is currently in testing, so there are no Production releases until 0.10 is ready.
2. I've added the missing step on 11.x to the Installation page on the wiki now, please try with those steps instead.
3. Please fill out the entire template next time, not just the parts you want to fill out. Normally I close Issues where users did not bother filling out the template without a second look at them, _even if the report may be valid_.

**Comment by marcscholl** [comment]
Xaymar,

(sorry about the template)

the missing step you added (start OBS once, cancelling the StreamFX dialog and quitting OBS) did not make any difference (macOS still does not know how to open .so libraries).

What *did* work out, though, was to right-click and "open with..." then select OBS (I was not able to select the obs.app from the Finder window, but did succeed to so in a different file manager. (Maybe "open -a obs.app StreamFX.so" in a terminal will also do...) So, the point really was about opening a .so library in macOS!

Anyway, thanks for your quick relply,

**Comment by Xaymar** [comment]
I've tested both the old and new steps on my MacBook Pro M1 after updating to 11.x, and both of them work if they're followed exactly as described. I think what went wrong with your setup is that you didn't pay attention to what MacOS finder was doing with the archive - it removes the top level directory, so you actually have to create the StreamFX directory in `/Library/Application Support/obs-studio/plugins`, and then extract into the StreamFX directory. This seems to be a new thing, as it didn't happen until updating to 11.x - no idea why Apple decides that being incorrect is better.

In any case, glad that it worked out anyway.
