### ISSUE TITLE
MacOS - OBS Crash after installing StreamFX

### ISSUE THREAD

**Issue by jshingler** [Xaymar/obs-StreamFX#481]
### Description

MacOS Installed StreamFX 0.10.0b1

Note: OBS 26.1.2 is normally stable

Added blur filter to camera source, it worked, ... then I turned it off a few seconds later OBS Crashed.

Sorry

Attaching dump
[process_dump.txt](https://github.com/Xaymar/obs-StreamFX/files/6032772/process_dump.txt)

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Looked at the crash log, the crash is from Qt5 and happens inside OBS Studio. As far as I can tell, it happened while reordering the filter list after removing the filter. You should head over to their Forums, Discord or Github to report this: https://obsproject.com/help

**Comment by jshingler** [comment]
K, ... Thanks. Generally OBS has been pretty stable, ... wasn't sure if the StreamFX caused it.
