### ISSUE TITLE
PROBLEM WITH MAC VERSION

### ISSUE THREAD

**Issue by 05277668** [Xaymar/obs-StreamFX#483]
### Description

Hello, I am trying to install the mac version of streamfx, after several attempts I have installed it, but it does not execute any function of the plugin in obs, I have tried several such as 3D transform and no controls appear or execute anything. Any advice? Thank you very much and congratulations on the development.
### System Information

- Software Version: OBS 26.1.2  + streamfx-macos-10.15-0.10.0.0b1-gafc09620.zip
- Operating System: CATALINA 10.15.7
- Kernel Version: Darwin MacBook-Pro-de-LUIS.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
- CPU: 8-Core Intel Core i9
- GPU: AMD Radeon Pro 5500M + Intel UHD Graphics 630
- RAM: 16 MB

**Comment by Xaymar** [comment]
Please make sure to read the [Installation Guide](https://github.com/xaymar/obs-streamfx/wiki/Installation) in its entirety. Almost all installation issues can be fixed by installing the required software.

**Comment by Mikeygravity** [comment]
I cannot find the mac os file.  Is it still available?

**Comment by asher-the-thrasher** [comment]
https://github.com/Xaymar/obs-StreamFX/releases you can find it at the bottom of the page here

**Comment by Mikeygravity** [comment]
thankyou

**Comment by Xaymar** [comment]
Assuming fixed, as there has been no reply from the original reporter.
