### ISSUE TITLE
“StreamFX.so” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by djmel88** [Xaymar/obs-StreamFX#484]
### Description
I'm installing on my mac but it's causing this message when I open up OBS “StreamFX.so” cannot be opened because the developer cannot be verified.

### System Information
OBS 26.1.2
MacOS Catalina
3.8 GHz Quad-Core Intel Core i5

**Comment by Xaymar** [comment]
This is quite literally covered in the installation guide?
