### ISSUE TITLE
Support for Vector enumeration types in Custom Shaders

### ISSUE THREAD

**Issue by Stealthii** [Xaymar/obs-StreamFX#485]
### Description
Currently enums in shaders allow you to apply a value to the base type. It would be nice to support single enum values for vector types, so that directional vectors can be pre-defined in a single drop-down list.

An example of a directional float2 vector:
```shader
uniform float2 direction<
    string name = "Direction";
    string field_type = "enum";
    float2 enum_0 = {1., 0.};
    float2 enum_1 = {-1., 0.};
    float2 enum_2 = {0., 1.};
    float2 enum_3 = {0., -1.};
    string enum_0_name = "Left";
    string enum_1_name = "Right";
    string enum_2_name = "Up";
    string enum_3_name = "Down";
> = {1., 0.};
```

This could be implemented as such where:
* If the enum variables use base type, keep current behaviour.
* If the enum variables use vector type, use single dropdown applying value to vector variable.

### Checklist
- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

**Comment by Xaymar** [comment]
Unfortunately this would most likely drive up the complexity of parameter parsing far beyond what I'm willing to actually support. Enumerations themselves are already a fluff/nice-to-have feature that wasn't in the original requirements either. It's not impossible, but it is very unlikely that I'll spend any time with this request.

**Comment by Xaymar** [comment]
#### Rejected
The added maintenance and complexity is not worth the benefits. If you need this kind of behavior, you really should look into OBS scripting or perhaps even make your own plugin.
