### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by gabuu20** [Xaymar/obs-StreamFX#486]
After 40-60 minutes the error message appears and the obs is closed

PC info: ![image](https://user-images.githubusercontent.com/69408931/110149818-7c687700-7dac-11eb-9e44-29a32327f8cd.png)

![obs error (3)](https://user-images.githubusercontent.com/69408931/110149340-eb919b80-7dab-11eb-9b7b-2c58958fca92.png)

![obs error gabuu profile](https://user-images.githubusercontent.com/69408931/110149342-ec2a3200-7dab-11eb-89cf-0cad59ab473b.png)

![obs error](https://user-images.githubusercontent.com/69408931/110149344-ec2a3200-7dab-11eb-9df0-4ec68c7f603e.png)

![error](https://user-images.githubusercontent.com/69408931/110149277-d87ecb80-7dab-11eb-9f4f-aa7c9d93f35b.png)

![obs error (2)](https://user-images.githubusercontent.com/69408931/110149287-dae12580-7dab-11eb-98a3-4a4d2d1c345e.png)

![crash obs](https://user-images.githubusercontent.com/69408931/110149244-cb61dc80-7dab-11eb-8371-07aa5c198e85.png)

**Comment by Xaymar** [comment]
**Please don't delete the template when submitting features, issues or pull requests!**
