### ISSUE TITLE
Can't start recording

### ISSUE THREAD

**Issue by DeveshDFG** [Xaymar/obs-StreamFX#489]
I tried following the guide for VBR-HQ for NVENC HEVC/H265
Whenever I attempt to change the Maximum B-Frames or enable temporal adaptive quantization, OBS will not start recording and says starting the output failed. This error seems different from other errors, so hopefully I can fix it

Note: The guide works perfectly for H264/AVC NVENC, so something in the config is wrong for H265/HEVC. The CQP guide works fine on HEVC as well.

OBS 26.1.1 (64-bit, windows) log file uploaded at 2021-03-15, 15:25:15

15:25:06.261: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
15:25:06.261: CPU Speed: 4008MHz
15:25:06.261: Physical Cores: 4, Logical Cores: 8
15:25:06.261: Physical Memory: 16314MB Total, 7707MB Free
15:25:06.261: Windows Version: 10.0 Build 19042 (release: 2009; revision: 867; 64-bit)
15:25:06.261: Running as administrator: true
15:25:06.261: Aero is Enabled (Aero is always on for windows 8 and above)
15:25:06.261: Windows 10 Gaming Features:
15:25:06.261: 	Game DVR: On
15:25:06.261: 	Game Mode: Off
15:25:06.264: Sec. Software Status:
15:25:06.266: 	Microsoft Defender Antivirus: enabled (AV)
15:25:06.266: 	Windows Firewall: enabled (FW)
15:25:06.267: Current Date/Time: 2021-03-15, 15:25:06
15:25:06.267: Browser Hardware Acceleration: true
15:25:06.267: Portable mode: false
15:25:06.543: OBS 26.1.1 (64-bit, windows)
15:25:06.543: ---------------------------------
15:25:06.543: ---------------------------------
15:25:06.543: audio settings reset:
15:25:06.543: 	samples per sec: 48000
15:25:06.543: 	speakers:        2
15:25:06.546: ---------------------------------
15:25:06.546: Initializing D3D11...
15:25:06.546: Available Video Adapters: 
15:25:06.549: 	Adapter 0: NVIDIA GeForce GTX 1070
15:25:06.549: 	  Dedicated VRAM: 4185915392
15:25:06.549: 	  Shared VRAM:    4258641920
15:25:06.549: 	  PCI ID:         10de:1b81
15:25:06.549: 	  Driver Version: 27.21.14.6172
15:25:06.550: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=144, name=Acer XB241H
15:25:06.554: Loading up D3D11 on adapter NVIDIA GeForce GTX 1070 (0)
15:25:06.635: D3D11 loaded successfully, feature level used: b000
15:25:06.635: DXGI increase maximum frame latency success
15:25:06.635: D3D11 GPU priority setup success
15:25:07.058: ---------------------------------
15:25:07.058: video settings reset:
15:25:07.058: 	base resolution:   1920x1080
15:25:07.058: 	output resolution: 1920x1080
15:25:07.058: 	downscale filter:  Bicubic
15:25:07.058: 	fps:               60/1
15:25:07.058: 	format:            NV12
15:25:07.058: 	YUV mode:          sRGB/Full
15:25:07.058: NV12 texture support enabled
15:25:07.059: Audio monitoring device:
15:25:07.059: 	name: Default
15:25:07.059: 	id: default
15:25:07.061: ---------------------------------
15:25:07.090: [CoreAudio encoder]: Adding CoreAudio AAC encoder
15:25:07.091: Failed to load 'en-US' text for module: 'decklink-captions.dll'
15:25:07.092: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
15:25:07.127: [AMF] Unable to load 'amfrt64.dll', error code 126.
15:25:07.129: [AMF] AMF Test failed due to one or more errors.
15:25:07.129: Failed to initialize module 'enc-amf.dll'
15:25:07.241: [obs-browser]: Version 2.9.1
15:25:07.241: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
15:25:07.252: NVENC supported
15:25:07.407: [StreamFX] Loading Version 0.9.3.0-2ecce522
15:25:07.426: [StreamFX] <NVIDIA Face Tracking Filter> Failed to load Nvidia AR SDK runtime.
15:25:07.426: [StreamFX] Loaded Version 0.9.3.0-2ecce522
15:25:07.438: Couldn't find VLC installation, VLC video source disabled
15:25:07.531: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
15:25:07.533: No blackmagic support
15:25:07.552: ---------------------------------
15:25:07.552:   Loaded Modules:
15:25:07.552:     win-wasapi.dll
15:25:07.552:     win-mf.dll
15:25:07.552:     win-dshow.dll
15:25:07.552:     win-decklink.dll
15:25:07.552:     win-capture.dll
15:25:07.552:     vlc-video.dll
15:25:07.552:     text-freetype2.dll
15:25:07.552:     StreamFX.dll
15:25:07.552:     rtmp-services.dll
15:25:07.552:     obs-x264.dll
15:25:07.552:     obs-vst.dll
15:25:07.552:     obs-transitions.dll
15:25:07.552:     obs-text.dll
15:25:07.552:     obs-qsv11.dll
15:25:07.552:     obs-outputs.dll
15:25:07.552:     obs-filters.dll
15:25:07.553:     obs-ffmpeg.dll
15:25:07.553:     obs-browser.dll
15:25:07.553:     image-source.dll
15:25:07.553:     frontend-tools.dll
15:25:07.553:     enc-amf.dll
15:25:07.553:     decklink-ouput-ui.dll
15:25:07.553:     decklink-captions.dll
15:25:07.553:     coreaudio-encoder.dll
15:25:07.553: ---------------------------------
15:25:07.553: ==== Startup complete ===============================================
15:25:07.569: All scene data cleared
15:25:07.569: ------------------------------------------------
15:25:08.131: [window-capture: 'Window Capture'] update settings:
15:25:08.131: 	executable: chrome.exe
15:25:08.131: 	method selected: Automatic
15:25:08.131: 	method chosen: WGC
15:25:08.131: 
15:25:08.132: [WASAPISource::WASAPISource] Device '{0.0.1.00000000}.{f3fa72b3-8617-4adc-b2c0-f26cfbda7530}' not found.  Waiting for device
15:25:08.132: [WASAPISource::WASAPISource] Device '{0.0.0.00000000}.{6e3a2481-6bc4-49ba-97a0-210c7091ba66}' not found.  Waiting for device
15:25:08.132: [WASAPISource::WASAPISource] Device '{0.0.0.00000000}.{86c98f5a-1874-4795-99a3-a36045956341}' not found.  Waiting for device
15:25:08.132: [WASAPISource::WASAPISource] Device '{0.0.0.00000000}.{86672b8a-6929-4b5e-bd8f-c9c8b55c313e}' not found.  Waiting for device
15:25:08.133: Switched to scene 'Scene'
15:25:08.135: ------------------------------------------------
15:25:08.135: Loaded scenes:
15:25:08.135: - scene 'Scene':
15:25:08.135:     - source: 'Google Audio' (wasapi_output_capture)
15:25:08.135:     - source: 'Discord Audio' (wasapi_output_capture)
15:25:08.135:     - source: 'Game Audio' (wasapi_output_capture)
15:25:08.135:     - source: 'Mic' (wasapi_input_capture)
15:25:08.135:     - source: 'Window Capture' (window_capture)
15:25:08.135:     - source: 'Game Capture' (game_capture)
15:25:08.135: ------------------------------------------------
15:25:08.464: [StreamFX] <updater> Automatic checks at launch are now enabled.
15:25:09.251: [StreamFX] [hevc_nvenc] Initializing...
15:25:09.251: [StreamFX] [hevc_nvenc]   FFmpeg:
15:25:09.251: [StreamFX] [hevc_nvenc]     Custom Settings: 
15:25:09.251: [StreamFX] [hevc_nvenc]     Standard Compliance: Strict
15:25:09.251: [StreamFX] [hevc_nvenc]     Threading: Slice & Frame (with 1 threads)
15:25:09.251: [StreamFX] [hevc_nvenc]   Video:
15:25:09.251: [StreamFX] [hevc_nvenc]     Texture: 1920x1080 nv12 BT.709 pc
15:25:09.251: [StreamFX] [hevc_nvenc]     Framerate: 60/1 (60.000000 FPS)
15:25:09.251: [StreamFX] [hevc_nvenc]   Keyframes: 
15:25:09.251: [StreamFX] [hevc_nvenc]     Distance: 30 frames
15:25:09.251: [StreamFX] [hevc_nvenc]   Nvidia NVENC:
15:25:09.251: [StreamFX] [hevc_nvenc]     Preset: hq
15:25:09.251: [StreamFX] [hevc_nvenc]     Rate Control: vbr_hq
15:25:09.251: [StreamFX] [hevc_nvenc]       Two Pass: Disabled
15:25:09.251: [StreamFX] [hevc_nvenc]       Look-Ahead: 32 Frames
15:25:09.251: [StreamFX] [hevc_nvenc]       Adaptive I-Frames: Enabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Bitrate:
15:25:09.251: [StreamFX] [hevc_nvenc]         Target: 0 bits/sec
15:25:09.251: [StreamFX] [hevc_nvenc]         Minimum: 0 bits/sec <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]         Maximum: 800000000 bits/sec
15:25:09.251: [StreamFX] [hevc_nvenc]         Buffer: 800000000 bits
15:25:09.251: [StreamFX] [hevc_nvenc]       Quality:
15:25:09.251: [StreamFX] [hevc_nvenc]         Target: 15 
15:25:09.251: [StreamFX] [hevc_nvenc]         Minimum: -1 
15:25:09.251: [StreamFX] [hevc_nvenc]         Maximum: 51 
15:25:09.251: [StreamFX] [hevc_nvenc]       Quantization Parameters:
15:25:09.251: [StreamFX] [hevc_nvenc]         I-Frame: -1  <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]         P-Frame: -1  <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]         B-Frame: -1  <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]     B-Frames: 0 Frames <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Reference Mode: disabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]     Adaptive Quantization:
15:25:09.251: [StreamFX] [hevc_nvenc]       Spatial AQ: Enabled
15:25:09.251: [StreamFX] [hevc_nvenc]         Strength: 7 
15:25:09.251: [StreamFX] [hevc_nvenc]       Temporal AQ: Enabled
15:25:09.251: [StreamFX] [hevc_nvenc]     Other:
15:25:09.251: [StreamFX] [hevc_nvenc]       Zero Latency: Disabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Weighted Prediction: Disabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Non-reference P-Frames: Disabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Strict GOP: Disabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Access Unit Delimiters: Disabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Bluray Compatibility: Disabled <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       DPB Size: <Error: Operation not permitted>
15:25:09.251: [StreamFX] [hevc_nvenc]     H.265/HEVC:
15:25:09.251: [StreamFX] [hevc_nvenc]       Profile: weighted_pred <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Level: weighted_pred <Default>
15:25:09.251: [StreamFX] [hevc_nvenc]       Tier: high
15:25:09.252: [StreamFX] [hevc_nvenc] Initializing...
15:25:09.252: [StreamFX] [hevc_nvenc]   FFmpeg:
15:25:09.252: [StreamFX] [hevc_nvenc]     Custom Settings: 
15:25:09.252: [StreamFX] [hevc_nvenc]     Standard Compliance: Strict
15:25:09.252: [StreamFX] [hevc_nvenc]     Threading: None (with 1 threads)
15:25:09.252: [StreamFX] [hevc_nvenc]   Video:
15:25:09.252: [StreamFX] [hevc_nvenc]     Input: 1920x1080 nv12 BT.709 Full
15:25:09.252: [StreamFX] [hevc_nvenc]     Output: 1920x1080 nv12 BT.709 Full
15:25:09.252: [StreamFX] [hevc_nvenc]     On GPU Index: -1
15:25:09.252: [StreamFX] [hevc_nvenc]     Framerate: 60/1 (60.000000 FPS)
15:25:09.252: [StreamFX] [hevc_nvenc]   Keyframes: 
15:25:09.252: [StreamFX] [hevc_nvenc]     Distance: 30 frames
15:25:09.252: [StreamFX] [hevc_nvenc]   Nvidia NVENC:
15:25:09.252: [StreamFX] [hevc_nvenc]     Preset: hq
15:25:09.252: [StreamFX] [hevc_nvenc]     Rate Control: vbr_hq
15:25:09.252: [StreamFX] [hevc_nvenc]       Two Pass: Disabled
15:25:09.252: [StreamFX] [hevc_nvenc]       Look-Ahead: 32 Frames
15:25:09.252: [StreamFX] [hevc_nvenc]       Adaptive I-Frames: Enabled <Default>
15:25:09.252: [StreamFX] [hevc_nvenc]       Bitrate:
15:25:09.252: [StreamFX] [hevc_nvenc]         Target: 0 bits/sec
15:25:09.252: [StreamFX] [hevc_nvenc]         Minimum: 0 bits/sec <Default>
15:25:09.252: [StreamFX] [hevc_nvenc]         Maximum: 800000000 bits/sec
15:25:09.252: [StreamFX] [hevc_nvenc]         Buffer: 800000000 bits
15:25:09.252: [StreamFX] [hevc_nvenc]       Quality:
15:25:09.252: [StreamFX] [hevc_nvenc]         Target: 15 
15:25:09.252: [StreamFX] [hevc_nvenc]         Minimum: -1 
15:25:09.253: [StreamFX] [hevc_nvenc]         Maximum: 51 
15:25:09.253: [StreamFX] [hevc_nvenc]       Quantization Parameters:
15:25:09.253: [StreamFX] [hevc_nvenc]         I-Frame: -1  <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]         P-Frame: -1  <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]         B-Frame: -1  <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]     B-Frames: 0 Frames <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Reference Mode: disabled <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]     Adaptive Quantization:
15:25:09.253: [StreamFX] [hevc_nvenc]       Spatial AQ: Enabled
15:25:09.253: [StreamFX] [hevc_nvenc]         Strength: 7 
15:25:09.253: [StreamFX] [hevc_nvenc]       Temporal AQ: Enabled
15:25:09.253: [StreamFX] [hevc_nvenc]     Other:
15:25:09.253: [StreamFX] [hevc_nvenc]       Zero Latency: Disabled <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Weighted Prediction: Disabled <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Non-reference P-Frames: Disabled <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Strict GOP: Disabled <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Access Unit Delimiters: Disabled <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Bluray Compatibility: Disabled <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       DPB Size: <Error: Operation not permitted>
15:25:09.253: [StreamFX] [hevc_nvenc]     H.265/HEVC:
15:25:09.253: [StreamFX] [hevc_nvenc]       Profile: weighted_pred <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Level: weighted_pred <Default>
15:25:09.253: [StreamFX] [hevc_nvenc]       Tier: high
15:25:09.338: [StreamFX] Unexpected exception in function '_create': Generic error in an external library.

**Comment by Xaymar** [comment]
As far as i know, Pascal GPUs do not support B-Frames in HEVC.

**Comment by DeveshDFG** [comment]
Darn, looks like I need to upgrade soon, thanks
