### ISSUE TITLE
OBS - StreamFX

### ISSUE THREAD

**Issue by WarriorHearted** [Xaymar/obs-StreamFX#490]
### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

I am having a user malfunction with installing StreamFX.  I followed the directions for MacOS as posted and needed to: If the window does not appear, you have to manually tell MacOS that OBS Studio will open it. This can be done with the Open With -> Other... menu, where you just select OBS and hit ok.  

It opened and installed UI.Menu at the top and not StreamFX.  When I looked at the OBS About, it came up with the attached ExtreamFX shot. 
WarriorHearted

MacOS Catalina, 10.15.7 
![image](https://user-images.githubusercontent.com/80798953/111401897-6f3e6880-8687-11eb-9f1c-ac6f1ef6b57e.png)
![image](https://user-images.githubusercontent.com/80798953/111401921-79606700-8687-11eb-9021-eaf2cc405a6a.png)

**Comment by Xaymar** [comment]
You did not follow the installation guide as written and made up your own path on where to extract the plugin.

**Comment by Xaymar** [comment]
Please make sure to read the [Installation Guide](https://github.com/xaymar/obs-streamfx/wiki/Installation) in its entirety, including the part of the [required Software](https://github.com/xaymar/obs-streamfx/wiki/Installation#software-requirements). Almost all installation issues can be fixed by installing the required software.

**Comment by WarriorHearted** [comment]
Thank you for your reply.
I checked my system and even updated it to MacOS Big Sur, 11.2.3.
As the saying goes, "It isn't you; it me." I think I did not correctly follow directions.
I checked the Library > Application Support > (there is not an obs-studio folder).
Here is what I have in OBS > Contents > Plugins >

Where did I take the wrong turn and can you set me right?

![Library](https://user-images.githubusercontent.com/80798953/111533508-183aa100-8724-11eb-8075-89c3d85f452c.jpg)
![StreamFX Plugin](https://user-images.githubusercontent.com/80798953/111533515-196bce00-8724-11eb-8d90-06b881cef073.jpg)

**Comment by Xaymar** [comment]
If the directory `/Library/Application Support/obs-studio/plugins` does not exist, you may have to create it. On my system it already existed. By extracting it into the OBS app itself, you broke the expected plugin format, and thus made it incapable to be loaded correctly.

**Comment by WarriorHearted** [comment]
Ok.  I trashed everything and downloaded ExtreamFX again after I created the directory.  Now it is: /Library/Application Support/obs-studio/plugins/StreamFX/bin.  I used OBS to open the StreamFX.so.  The program opened, but nothing installed.

**Comment by Xaymar** [comment]
Did you get a window about "untrusted developer" or similar? If not you might be running into the same issue another user is.

**Comment by WarriorHearted** [comment]
Yes.  I did get such a message then continued on.

**Comment by Xaymar** [comment]
I assume that by continued on you mean you followed the remaining steps, which should have resulted in a second window where you can select "Open", and then pressed open. In that case, please upload a log file (do not paste the log file here, upload it using the OBS menu).

**Comment by WarriorHearted** [comment]
That is correct.  Here is the link to the log file: https://obsproject.com/logs/CeigFGlKrfVo1nay

**Comment by Xaymar** [comment]
Same issue as the user in Discord then, OBS does not see StreamFX.so or the directory. To date we have no known fix, but your steps and their steps are identical, so it might be related to incorrectly editing the OBS application, which may cause weird problems.

**Comment by WarriorHearted** [comment]
Oh my.  Would you recommend uninstalling OBS and starting over?  If so, can you refer to any source that would negate unwanted user errors concerning the re-install?

**Comment by Xaymar** [comment]
I have no recommendation that I can make at this time, but you're free to try anything you want to try. Personally I tried the steps written in the [Installation Guide](https://github.com/Xaymar/obs-StreamFX/wiki/Installation#-macos) exactly as written and had no issues with it at all, every time I follow them they work as expected.

**Comment by WarriorHearted** [comment]
Thank you for your help.  Should I stumble upon a solution, I'll follow up with a post here.

**Comment by citosid** [comment]
FWIW, I installed it today but instead of extract the plug-in to /Library I did it to ~/Library

Other than that, everything was the same

**Comment by Xaymar** [comment]
This problem should be resolved with the inclusion of the .pkg installer, ensuring that users can no longer make mistakes.
