### ISSUE TITLE
Crash on OBS startup under OSX 10.14.x Mojave

### ISSUE THREAD

**Issue by gregkuhnert** [Xaymar/obs-StreamFX#505]
### Description
OBS crashes on startup if the plugin is installed on an OSX Mojave system. According to the crashlog, StreamFX.so was built for 10.15. However, I am forced to run Mojave (10.14.x) due to another application which is yet to release a Catalina version of their software. A mojave compatible build would be appreciated. If that will not be built, could you confirm if it SHOULD build for Mojave, and I would be willing to go down that path if required.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: __ZNSt3__14__fs10filesystem8__statusERKNS1_4pathEPNS_10error_codeE
  Referenced from: /Library/Application Support/obs-studio/*/StreamFX.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libc++.1.dylib
```

### System Information
- Software Version: 0.10.0b1
- Operating System: 10.14.6 (18G5033)
- Kernel Version: Darwin Kernel Version 18.7.0
- CPU: 4 GHz Intel Core i7
- GPU: MD Radeon R9 M395X 4 GB
- RAM: 32 GB 1867 MHz DDR3

**Comment by Xaymar** [comment]
StreamFX **requires MacOS 10.15 or higher**.

**Comment by Xaymar** [comment]
The code base for StreamFX is built upon C++17, which on MacOS requires 10.15 or higher, and in the future this will be upgraded to C++20 once it is supported across every platform. This minimum support requirement is the same across all platforms, and there are no plans to backport to older operating systems.

All my software has always followed the principle that the user should _always_ update to the latest version of everything. If you can't do so, then you will be forced to use an older version and will be barred from support. It's a pretty simple rule actually, and most of the time it "magically" fixes user issues.
