### ISSUE TITLE
stürtz öfters ab

### ISSUE THREAD

**Issue by DonFlappi** [Xaymar/obs-StreamFX#506]
### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by Xaymar** [comment]
Please fill out the template. Without this information, I can't provide you any further help.

**Comment by Xaymar** [comment]
The user has not provided any additional information, therefore this issue is now closed. If the user wishes to actually help us fix the problem, they're welcome to add this information, though sadly they have yet to do so.
