### ISSUE TITLE
Dual Filter Blur tooltip incorrect (copy of Gaussian tooltip)

### ISSUE THREAD

**Issue by skeletonbow** [Xaymar/obs-StreamFX#508]
### Description
This is a very minor issue, basically if you hover over the "?" when the Dual-Filter blur is selected to get the tooltip that describes what the blur is, it gives the tooltip for the Gaussian Blur, probably just a copy and paste error I presume.

### System Information

- Software Version: 0.9.3
- Operating System: Windows 10
- Kernel Version: 20H2
- CPU: Intel i7 7700HQ
- GPU: Nvidia GTX 1050 4GB
- RAM: 16GB

![image](https://user-images.githubusercontent.com/49483514/114257476-511a0e80-998e-11eb-9973-0adb420a7e06.png)

**Comment by Xaymar** [comment]
Fixed by #519, we no longer have tooltips.
