### ISSUE TITLE
YouTube Chat Causes Crash

### ISSUE THREAD

**Issue by nathanlejeune** [Xaymar/obs-StreamFX#509]
### Description

Once the stream goes live, the YouTube chat logs in and comes up in the chat window of OBS.live. When I go to respond and type something into that chat, it ask me to click to log in. When you try and log in, it causes OBS to crash. 

No screenshots but if needed, I can take one the next time I stream.

They have not been giving me logs, but I can try again if they are needed. 

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- 0.10.0.0a2.00000000
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- macOS Big Sur, Version 11.2.3
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- 2.3 GHz 8-Core Intel Core i9
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- AMD Radeon Pro 5500M 4GB
Intel UHD Graphics 630 1536 MB
- RAM: [e. g. 16GB, 32GB, 64GB, ...]
- 32 GB 2667 MHz DDR4

**Comment by Xaymar** [comment]
Uh, this is StreamFX. You're in the wrong repository.

**Comment by nathanlejeune** [comment]
Sorry to have made a post that you felt didn’t fit. This problem didn’t start until I added steamfx. 

-
Nate LeJeune
Disciple | Dreamer | Designer | Lifer
M. 337.842.0603 | Destrehan, LA 70047 | Answered from Mobile

**Comment by Xaymar** [comment]
As StreamFX does not modify any external plug-ins, your support contact is the creators of obs.live or the OBS project itself.
