### ISSUE TITLE
"Displacement Mapping" filter is undocumented.

### ISSUE THREAD

**Issue by fhars** [Xaymar/obs-StreamFX#511]
### Description

I'd like to read https://github.com/Xaymar/obs-StreamFX/wiki/Filter-Displacement-Mapping linked from the main wiki page to understand how that filter works, but that page doesn't exist.

### System Information

All / Any / Whatever

**Comment by skeletonbow** [comment]
I believe that filter is being removed in a future release due to being relatively unused, and can be effectively replaced by the Shader filter more or less.

**Comment by fhars** [comment]
OK, thanks. I fixed the dangling link in the wiki by creating a page with that information.
