### ISSUE TITLE
"SDF Effects" filter is undocumented

### ISSUE THREAD

**Issue by fhars** [Xaymar/obs-StreamFX#512]
### Description

I'd like to read https://github.com/Xaymar/obs-StreamFX/wiki/Filter-SDF-Effects linked from the main wiki page to understand how that filter works, but that page doesn't exist. I tried to apply that filter to some random source, and as far as I can tell none of the parameters of that filter has any visible effect on anything at all with that source, so it clearly needs some documentation on what it is for and how it is intended to be used. 

### System Information

All / Any / Whatever

**Comment by skeletonbow** [comment]
The filter can only be used with sources that contain transparent pixels (alpha channel) and do not fill the entire texture, as it operates on the boundary between opaque pixels and transparent ones, a common misunderstanding of this filter it seems.  So if you use it on a fully opaque texture, there are no transparent pixels and it can't do anything.  Once used on a transparent source, such as a chroma keyed webcam, or an image with a transparent background, the filter's effects become fairly obvious from tinkering with the controls however.

Note that the SDF filter can be quite GPU intensive so keep an eye on GPU usage in Task Manager or some other tool that can monitor usage, to ensure GPU usage of this effect is not overused as that can potentially interfere with games and/or OBS performance.

**Comment by Xaymar** [comment]
Most of the undocumented features have tooltips, but are still Experimental at best. As [explained in the FAQ](https://github.com/Xaymar/obs-StreamFX/wiki/Frequently-Asked-Questions#what-does---and--mean), experimental features are likely to break unexpectedly, so any documentation will be invalid by the time it's Unstable/Stable (if it even reaches that stage).

**Comment by Xaymar** [comment]
SDF Effects will most likely be removed or replaced with more efficient tools. As it is, SDF Effects have no chance of being GPU friendly due to their Scatter+Gather requirement.

**Comment by Xaymar** [comment]
SDF Effects will be deprecated with v0.12, and be replaced with better effects in v0.13. Closing as not planned.
