### ISSUE TITLE
Slide Show issue

### ISSUE THREAD

**Issue by Frank-N-Furter** [Xaymar/obs-StreamFX#514]
Hello,
please, there is issue with Drop Shadow, Outer glow and others used with Slide Show. The effect is applied not only to the images, but also to the bounding box. A good way to test this is to use different sized images in the Slide show.

Thanks for fix.

### System Information
MacOs 11.23
Obs Studio 27 PR2
StreamFX 0.10.0b2

**Comment by Xaymar** [comment]
Duplicate of #245, which is an upstream issue in OBS Studio. I have submitted a fix upstream [here](https://github.com/obsproject/obs-studio/issues/3794), which has yet to be merged.
