### ISSUE TITLE
Windows installer flagged as malicious

### ISSUE THREAD

**Issue by srkxt** [Xaymar/obs-StreamFX#535]
The Windows installer is flagged as malicious on https://www.virustotal.com/

https://www.virustotal.com/gui/file/7ee1ef600f3f1c741e6a63e1881b9071e067a5ae16b0ec2d422b14b88d90c348/detection

**Comment by tatunts** [comment]
Hey there! I'm glad to see people using virustotal service as it is really useful and reliable. Having said that, seeing those results, you should be fine when just one not very relevant engine finds something. I'm positive that it is a false-positive :). Thanks!

**Comment by Xaymar** [comment]
**It's a False-Positive.** Many Anti-Virus/Malware/Trojan solutions attempt to find bad actors based on which Windows DLLs they load and which functions they call, and this process is called heuristic scanning. The installer and uninstaller for StreamFX matches some of these heuristic checks ("Create .exe file", "Create .dll file", "Delete file"), and is marked by certain poorly implemented heuristic scans as a false-positive. 

If I wanted to infect anyone, it'd be with a Bitcoin miner. That is at least profitable for the effort to hide it past all but one AV engine. 🤣

**Comment by Xaymar** [comment]
**Please don't delete the template when submitting features, issues or pull requests!**
