### ISSUE TITLE
H264 Hi444PP Profile of streamfx generates invalid H264 stream by not using cabac

### ISSUE THREAD

**Issue by TheB1gG** [Xaymar/obs-StreamFX#547]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0 (including Release Candidates)

### StreamFX Version

0.10.0

### Expected Behavior

For a valid H264 video stream with profile H264 Hi444PP it is mandetory that cabac is used.

### Current Behavior

StreamFX does output a H264 stream without the usage of CABAC
![unknown](https://user-images.githubusercontent.com/33165056/116798204-8c22e400-aaed-11eb-90fe-874cfc7c8325.png)

### Steps to Reproduce the Bug

Set the Colorformat in OBS to I444 and record a video

### OBS Studio Log

[Log Upload](https://obsproject.com/logs/RH0KgmEHc5mwb5tT)

**Comment by Talyrius** [comment]
I wonder, is this perhaps why DaVinci Resolve refuses to import such videos? 🤔

**Comment by Xaymar** [comment]
> I wonder, is this perhaps why DaVinci Resolve refuses to import such videos? 🤔

Many Resolve features are paywalled, and require you to buy the product.

**Comment by Xaymar** [comment]
#### Rejected: Caused by other Software
Opted against implementing a forced switch, as MediaInfo is often wrong with metadata.
