### ISSUE TITLE
[BUG] UI.Menu but no StreamFX

### ISSUE THREAD

**Issue by IGIMedia** [Xaymar/obs-StreamFX#548]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

26.1

### StreamFX Version

0.10.0

### Expected Behavior

I expected the plugin to be installed. 
I followed the install guide to the letter. 
Upon not getting a proper installation, I un-installed all versions/applications/resources of OBS and created a clean install. 

Observations. The StreamFX exe places the plugin into the c:/. . / Programs files (x86) / OBS studio / plugins  . . .  folder, when the OBS installation is on my c:/ . . . / Programs files / OBS studio 

As the StreamFx page does not currently have a zip version, I tried copying the 2 StreamFX plugins over to the  c:/ . . . / Programs files / OBS studio / plugins of my system. 

### Current Behavior

OBS now has a UI.Menu menu item.
![StreamFX_UImenu](https://user-images.githubusercontent.com/83523916/116800023-f4100500-aac2-11eb-969e-154da0fd5ad1.png)

### Steps to Reproduce the Bug

I have performed the proper steps multiple times, including clean installs of OBS, the plugin installation and appropriate re-boots. 

### OBS Studio Log

N/A

### OBS Studio Crash Log

N/A

### Any additional Information we need to know?

Last Info: I had successfully used a previous version of this plugin in the past. 
At that time, I used the copy from *.zip file method to install.

**Comment by IGIMedia** [comment]
== [Resolved] ==
  It's not the plugin . . . IT'S THE INSTALLER

As I stated earlier, I had installed a prior version of the plugin, so I went back to version 9*
The installer for 9 allows me to choose the destination folder, whereas the installer for 10 bi-passes that step.

Note:L I have not used the plugin yet, but I at least have it installed. 

~Rod

**Comment by Xaymar** [comment]
The installer bypasses the step if it detects the is a direct upgrade possible.

**Comment by Xaymar** [comment]
@IGIMedia Did you at any point in the past move your OBS Studio installation without fully uninstalling it first?

**Comment by IGIMedia** [comment]
No I did not.

I always do a fresh /clean install
Version 9 is working good for me.

~Rod

**Comment by Xaymar** [comment]
Please note that version 0.9 receives no further updates, and any support requests from it will be met with an `Upgrade to the latest version` response. If this is fine with you, you can continue using that version until the end of time.

As far as a "bug" goes, this behavior is identical in 0.9.2 and up as it is in 0.10.0. The installer looks for a previous installation of StreamFX, and if it finds one, it will use that path to install the update. This has worked fine for any proper installations of OBS Studio so far

**Comment by IGIMedia** [comment]
Ok, thank you.

I figured as much.

Thanks for your time on this.

Cheers

~Rod
