### ISSUE TITLE
Installation 10.0 version (windows)

### ISSUE THREAD

**Issue by Xanesh** [Xaymar/obs-StreamFX#550]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

26.1

### StreamFX Version

0.10.0

### Expected Behavior

When i click to "finish" i expect the 10.0 version is install on my obs

### Current Behavior

When i click to "finish" the version 10.0 is not installed on my obs so STREAMFX remind me every time " a new version is available" 

### Steps to Reproduce the Bug

juiste use the windows stream fx installer and check the obs pluging file so you can check the date of the last update to see is you did install the last version or check the streamfx tab.

### OBS Studio Log

13:38:36.433: [StreamFX] Loading Version 0.9.3.0-2ecce522 13:38:36.456: [StreamFX] <NVIDIA Face Tracking Filter> Failed to load Nvidia AR SDK runtime. 13:38:36.457: [StreamFX] Loaded Version 0.9.3.0-2ecce522

### Any additional Information we need to know?

sorry if my english is bad :)

**Comment by Xaymar** [comment]
Please use [the Discord for support](discord.gg/rjkxers). Most likely your issue can be solved by asking in support chat.
