### ISSUE TITLE
[BUG] (WebSocket keeps disconnecting)

### ISSUE THREAD

**Issue by MermaidOutOfWater83** [Xaymar/obs-StreamFX#551]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

26.1

### StreamFX Version

0.10.0

### Expected Behavior

I have a blur effect on one of my scenes, I have it connected to my stream deck and it should add the blur. I've also tried it manually, not just using my stream deck

### Current Behavior

When switching scenes I get a notification from windows saying the websocket has disconnected. and the blur effect is not being activated. I checked in Tools > Wesocket Server Settings and "enable authentications" is unchecked, and unchecks itself straight after I check it.

### Steps to Reproduce the Bug

Not sure what's causing it, so I don't know how you'd reproduce it

### OBS Studio Log

https://obsproject.com/logs/qPDzKt-pwNpjsa2P

### Any additional Information we need to know?

It was working last week. I noticed the disconnections yesterday. But nothing I know of had changed.

**Comment by asher-the-thrasher** [comment]
How would this be caused by streamFX at all? The WebSocket is disconnecting, reach out to them for help.

**Comment by MermaidOutOfWater83** [comment]
I don't know who to reach out to. The only thing that was effected was stream FX so I clicked "Request Help & Support" on OBS and it brought me here

**Comment by Xaymar** [comment]
You selected "Request Help & Support" in the StreamFX menu. The obs-websocket plugin has its own Forum thread on, you most likely guessed it, the OBS forum: https://obsproject.com/forum/resources/obs-websocket-remote-control-obs-studio-from-websockets.466/
