### ISSUE TITLE
[BUG] (Replace this part including the brackets)

### ISSUE THREAD

**Issue by samthepro** [Xaymar/obs-StreamFX#552]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

26.1

### StreamFX Version

0.10.0a2

### Expected Behavior

filter of move value activate and desactivate mi camera laging obs studio

### Current Behavior

tetewfffdddgbfc

### Steps to Reproduce the Bug

rwrwqhtrbdgf

### OBS Studio Log

teww

### OBS Studio Crash Log

fewartZZr

### Any additional Information we need to know?

no

**Comment by Xaymar** [comment]
Move Value is not from StreamFX.

**Comment by Xaymar** [comment]
Please fill out the template. Without this information, I can't provide you any further help.
