### ISSUE TITLE
[BUG] (Replace this part including the brackets)

### ISSUE THREAD

**Issue by Johnystar** [Xaymar/obs-StreamFX#554]
### Operating System

Linux (like Arch Linux)

### OBS Studio Version?

26.1

### StreamFX Version

0.10.0

### Expected Behavior

Record via AMD AMF

### Current Behavior

> Starting the output failed. Please check the log for details.
>
> Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date.

### Steps to Reproduce the Bug

My setup is as follows:
- OBS 26.1.2-2 installed via pacman
- StreamFX 0.10.0.0-g5888c7d2 installed from AUR (yay helper)
- amf-amdgpu-pro 21.10_1247438-1 installed from AUR

### OBS Studio Log

https://obsproject.com/logs/f0ASyFIcRKKBt5sC

### Any additional Information we need to know?

Not sure if relevant, but my specific GPU is an RX 560 4GB OC

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data for failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
