### ISSUE TITLE
Link to High Quality Recording Guide for ProRes is down

### ISSUE THREAD

**Issue by raarts** [Xaymar/obs-StreamFX#557]
### Explain the Feature/Enhancement

This is just a doc issue, and I assume you are aware, just tracking status.
Did not want to report this as a bug/crash etc

https://github.com/Xaymar/obs-StreamFX/wiki/Encoder-FFmpeg-Apple-ProRes

### What makes this feature/enhancement useful for StreamFX and its users?

Really interested in ProRes recording

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data for failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.

**Comment by Xaymar** [comment]
Please double check that the linked resources are not currently under maintenance or similar. Temporary down time is not a reason to open an issue.
