### ISSUE TITLE
[BUG] Blur filter does not render

### ISSUE THREAD

**Issue by nella17** [Xaymar/obs-StreamFX#559]
### Operating System

MacOS 10.15 and higher

### OBS Studio Version?

26.1

### StreamFX Version

0.10.0

### Expected Behavior

blur filter on display capture

### Current Behavior

when I select some blur filter type (Box Linear, Gaussian, Gaussian Linear), this source turn to black.

### Steps to Reproduce the Bug

1. Add Display Capture to OBS source
2. Add Blur Filter
3. Select certain filter type (Box Linear, Gaussian, Gaussian Linear)

<img width="973" alt="image" src="https://user-images.githubusercontent.com/14134195/120120885-05882200-c1d3-11eb-9adb-0ddd8d13ebcb.png">

### OBS Studio Log

https://obsproject.com/logs/sbCE5_HrdyVfMZu5

**Comment by Xaymar** [comment]
https://github.com/Xaymar/obs-StreamFX/blob/master/data/effects/blur/box-linear.effect#L68

Bug caused by this "optimization".

**Comment by Xaymar** [comment]
Log file doesn't show any issues in Gaussian, only Gaussian Linear.

**Comment by KabobKid** [comment]
I have the same problem, how do I fix this?
