### ISSUE TITLE
Antialiasing for edges of 3D Transform filter

### ISSUE THREAD

**Issue by dexteritas** [Xaymar/obs-StreamFX#562]
### Explain the Feature/Enhancement

With the 3D Transform filter, there is a [mipmapping](https://github.com/Xaymar/obs-StreamFX/wiki/Filter-3D-Transform#mipmapping) option that greatly reduces aliasing within the image, but there is no antialiasing for the edges of the image. This problem becomes clearly visible, for example, when the source is downscaled and displayed at a slight angle. I have attached two screenshots (without and with the mipmapping option). In both variants the antialiasing problem exists at the edges (as you can see on the left and right of the screen).

without mipmapping:
<img width="247" alt="without_mipmapping" src="https://user-images.githubusercontent.com/19909936/120617742-b2c09b80-c45a-11eb-9a87-488ff5a6c323.png">

with mipmapping:
<img width="247" alt="with_mipmapping" src="https://user-images.githubusercontent.com/19909936/120617772-b81de600-c45a-11eb-9af0-9f41f76189fd.png">

Perhaps the antialiasing of the edges could also be done independently of the mipmapping option (possibly with another option), since this would be less computationally intensive compared to mipmapping, but would still make quite a difference visually, as can be seen in the image without mipmapping.

### What makes this feature/enhancement useful for StreamFX and its users?

Smoothing the edges (e.g. using transparency), would add the finishing touch to the mipmapping option for the 3D transformation.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
**Rejected.** You can already do this by just writing an FXAA shader for the Shaders filter, nothing I could do would be better than that.

**Comment by dexteritas** [comment]
So you mean I have to create an effect file myself, which is then used with the shader filter? Or is the FXAA filter already available for OBS or StreamFX and I just can't find it?

**Comment by skeletonbow** [comment]
FXAA antialiasing is available as open source from Nvidia free.  There are no antialiasing filters/shaders for OBS currently that I'm aware of however someone could modify that and convert it create an FXAA shader for OBS if they need to antialias something.  I don't have a link handy but if you search for "nvidia FXAA source code" it shouldn't be hard to find on nvidia's website if you (or anyone) wants to write a custom AA shader for OBS.  Hope this helps.
