### ISSUE TITLE
Windows zip please

### ISSUE THREAD

**Issue by VeGas-Gh0st** [Xaymar/obs-StreamFX#563]
### Explain the Feature/Enhancement

just as it says along with the exe, may we please have a zip for portable installs please.

### What makes this feature/enhancement useful for StreamFX and its users?

portable mode

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by skeletonbow** [comment]
Issue #542 will resolve this in the future.

**Comment by Xaymar** [comment]
Duplicate of #542. There will be no .zip or .7z files offered, just an extract option in the installer. And even that may be hidden behind a command line option to prevent the average YouTuber from suggesting it.
