### ISSUE TITLE
Corner Pin filter

### ISSUE THREAD

**Issue by skeletonbow** [Xaymar/obs-StreamFX#565]
### Explain the Feature/Enhancement

To be able to resize morph a source from its rectangular shape into the confines of an underlying picture frame or display bezel during compositing to give a realistic illusion the custom source is displayed in the frame.

### What makes this feature/enhancement useful for StreamFX and its users?

It is a common functionality present in a lot of video editors and image manipulation software for superimposing which is quite useful to content creators for giving a more professional 3D look to overlaid video insets, photo frames etc.

It is easier to configure a 2 dimensional corner pin to have all 4 corners align with an underlying image frame than it is to manipulate the properties of a filter like the 3D transform filter in 3D space for usage cases like this.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

### Any additional Information we need to know?

This obsoletes former request #281 as previously requested.

**Comment by skeletonbow** [comment]
https://github.com/Oncorporation/obs-shaderfilter/pull/6

**Comment by Xaymar** [comment]
I'll try to have this done by Sunday evening. At the moment there's an almost weekly testing release cycle.
