### ISSUE TITLE
[BUG] (Replace this part including the brackets)

### ISSUE THREAD

**Issue by EhRabz** [Xaymar/obs-StreamFX#567]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0 (including Release Candidates)

### StreamFX Version

0.10.0

### Expected Behavior

To be able to close OBS

### Current Behavior

When I close OBS with StreamFX installed, it crashes instead of closes, leaving an instance of OBS in my task manager, which if I forget to terminate, kills alerts my next stream.

### Steps to Reproduce the Bug

Install Stream FX. 
Close OBS.

### OBS Studio Log

huh?

### OBS Studio Crash Log

[2021-05-29 15-47-32.txt](https://github.com/Xaymar/obs-StreamFX/files/6603450/2021-05-29.15-47-32.txt)

**Comment by Xaymar** [comment]
The log file shows it having closed correctly, and even StreamFX is unloaded. Your issue is most likely with one of the third-party plugins, not StreamFX:

```
15:47:33.192:   Loaded Modules:
15:47:33.192:     soundtrack-plugin.dll
15:47:33.192:     logi_obs_plugin_x64.dll
```

**Comment by EhRabz** [comment]
it could be from a different log. ( not really sure what I'm looking for )  
But I know it's 100% from stream FX , this happens on a fresh install of OBS on a fresh install of windows with nothing but my game, stream fx, obs and lioran installed, even before I got my logitech mouse ( assuming thats what the logi obs plugin is ) 
and simply removing stream FX stops the problem, all reason leads me to believe its from stream FX. 
[2021-05-31 01-27-57.txt](https://github.com/Xaymar/obs-StreamFX/files/6604525/2021-05-31.01-27-57.txt)
[2021-05-31 09-33-13.txt](https://github.com/Xaymar/obs-StreamFX/files/6604526/2021-05-31.09-33-13.txt)
[2021-05-31 15-01-00.txt](https://github.com/Xaymar/obs-StreamFX/files/6604527/2021-05-31.15-01-00.txt)

**Comment by Xaymar** [comment]
Every single one of these has other plugins installed. StreamFX is completely unloaded in every single one of them.

**Comment by Xaymar** [comment]
For further support, use the [Discord](https://s.xaymar.com/streamfx-dc).
