### ISSUE TITLE
[BUG] (Nvenc HEVC recording not starting)

### ISSUE THREAD

**Issue by BuyMyMojo** [Xaymar/obs-StreamFX#568]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0 (including Release Candidates)

### StreamFX Version

0.10.0

### Expected Behavior

Records

### Current Behavior

Doesn't record, this error:
![obs64_uN6cRJaZLm](https://user-images.githubusercontent.com/46948241/120960835-fc352180-c79f-11eb-832c-5fbf136a5c8e.png)
![obs64_7k6shOGO9T](https://user-images.githubusercontent.com/46948241/120960840-fccdb800-c79f-11eb-8371-67c28f331512.png)

### Steps to Reproduce the Bug

update to latest SFX and OBS then apply these settings:
![obs64_fApz99aSjz](https://user-images.githubusercontent.com/46948241/120960918-24248500-c7a0-11eb-8fd2-cb5babad0e7c.png)

### OBS Studio Log

https://gist.github.com/BuyMyMojo/4f1dc210d0f729cb4eac4decf76d0388

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data for failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
