### ISSUE TITLE
[BUG] Audio gets distorted when recording

### ISSUE THREAD

**Issue by evilninjas** [Xaymar/obs-StreamFX#569]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0 (including Release Candidates)

### StreamFX Version

0.10.0

### Expected Behavior

Expect audio to be normal and not distorted and louder than the volume given. 

### Current Behavior

Whenever I record content, the audio is way off and is distorted. 

### Steps to Reproduce the Bug

Load anything with audio and record. The audio gets distorted. 

### OBS Studio Log

https://obsproject.com/logs/92aM6iKhuVEtM039

### Any additional Information we need to know?

PS: ONLY STREAMFX was installed other than the factory plugins from OBS. Nothing else caused the issue.

Image of the scene used during test recording
![image](https://user-images.githubusercontent.com/37690866/121051302-5970a900-c787-11eb-873c-20750b0e7726.png)

Plugins installed: 

![image](https://user-images.githubusercontent.com/37690866/121051504-82913980-c787-11eb-9f9d-c5dad4d68192.png)

I have gone through everything to see if the issue was not related to streamfx, but I installed the plugin on a fresh install of obs, and it still has the same issue. 

My sound settings on windows are 16-bit 48hz on all sound devices. I also have audio enhancements disabled.

**Comment by Xaymar** [comment]
Please attach a reproducible scene collection, then I'll change it back to bug.

**Comment by evilninjas** [comment]
Here you go.
[Good_Vibes.zip](https://github.com/Xaymar/obs-StreamFX/files/6611857/Good_Vibes.zip)

**Comment by Xaymar** [comment]
**Failed to reproduce with provided test case.**

There is no difference between StreamFX installed and uninstalled with the provided scene collection. All scenes (Start, Gaming, Review, Gaming 2, BRB, Talk, END, ...) are identical in volume. Please provide a working test case.

**Comment by evilninjas** [comment]
This is what I have set up. This is the setup I used when I got the issue. 

What else do you need to test it? 

The scenes didn't change when I had streamfx installed and uninstalled. 

The only thing that changed was I used FFMPEG Encoders (h.265)

**Comment by Xaymar** [comment]
With StreamFX: https://user-images.githubusercontent.com/437395/121086380-5c00ec00-c7e3-11eb-98a8-18757ce1c729.mp4  
Without StreamFX: https://user-images.githubusercontent.com/437395/121086399-6327fa00-c7e3-11eb-9150-aaad8e53ac1a.mp4

Both files are identical in volume. Your problem is not with StreamFX.

**Comment by evilninjas** [comment]
So, explain why it doesn't give me the issue of audio distortion without streamfx installed?


The issue is coming from streamfx. It is a bug within your plugin.

**Comment by Xaymar** [comment]
It is not a bug with StreamFX, you have two videos above showing it. They were created with your own scene collection, and neither of it has this bug. Volume is identical in both.

**Comment by evilninjas** [comment]
The final video has the audio distortion. None of the scenes or sources has the audio issue. 

***Whenever I record content, the audio is way off and is distorted.***

When I record content, the audio is way off and is distorted. This right here says recorded material or the end video is the part that has the results of audio distortion.

**Comment by Xaymar** [comment]
Neither of the two example videos provided has the proclaimed issue, as seen in a spectrogram:

* **Without StreamFX:** 
![image](https://user-images.githubusercontent.com/437395/121087135-548e1280-c7e4-11eb-8c04-3afc6278669a.png)
* **With StreamFX:** 
![image](https://user-images.githubusercontent.com/437395/121087162-5e177a80-c7e4-11eb-9b39-5b4b347b09c1.png)

Please make sure you have no third-party software, like DFX Audio Enhancer, interfereing with playback of files.

**Comment by Xaymar** [comment]
For further support, please contact the manufacturer of DFX Audio Enhacner.
