### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by Prof-pardal** [Xaymar/obs-StreamFX#591]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

26.1

### StreamFX Version

0.10.1

### OBS Studio Log

no properties available

### OBS Studio Crash Log

stopped working in OBS after atualization

### Current Behavior

blur is there but without any options of effect applied

### Expected Behavior

I expect a blur effect on camera

### Steps to Reproduce the Bug

just try to add blur to any camera

**Comment by Xaymar** [comment]
Please fill out the template. Without this information, I can't provide you any further help.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
