### ISSUE TITLE
cannot declare arrays

### ISSUE THREAD

**Issue by JamesEdSmith** [Xaymar/obs-StreamFX#602]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.10.0

### OBS Studio Log
<details>
17:03:30.850: CPU Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz 17:03:30.850: CPU Speed: 3696MHz 17:03:30.850: Physical Cores: 6, Logical Cores: 12 17:03:30.850: Physical Memory: 16337MB Total, 9401MB Free 17:03:30.850: Windows Version: 10.0 Build 19041 (release: 2004; revision: 1052; 64-bit) 17:03:30.850: Running as administrator: false 17:03:30.850: Aero is Enabled (Aero is always on for windows 8 and above) 17:03:30.850: Windows 10 Gaming Features: 17:03:30.850: 	Game DVR: On 17:03:30.851: Sec. Software Status: 17:03:30.852: 	Microsoft Defender Antivirus: enabled (AV) 17:03:30.852: 	Windows Firewall: enabled (FW) 17:03:30.853: Current Date/Time: 2021-07-05, 17:03:30 17:03:30.853: Browser Hardware Acceleration: true 17:03:30.853: Portable mode: false 17:03:31.007: OBS 27.0.1 (64-bit, windows) 17:03:31.007: --------------------------------- 17:03:31.008: --------------------------------- 17:03:31.008: audio settings reset: 17:03:31.008: 	samples per sec: 48000 17:03:31.008: 	speakers:        2 17:03:31.009: --------------------------------- 17:03:31.009: Initializing D3D11... 17:03:31.009: Available Video Adapters:  17:03:31.011: 	Adapter 0: NVIDIA GeForce RTX 2080 Ti 17:03:31.011: 	  Dedicated VRAM: 2994733056 17:03:31.011: 	  Shared VRAM:    4270442496 17:03:31.011: 	  PCI ID:         10de:1e07 17:03:31.011: 	  Driver Version: 27.21.14.5671 17:03:31.011: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=BenQ GW2265 17:03:31.011: 	  output 1: pos={-1280, 47}, size={1280, 1024}, attached=true, refresh=60, name=DELL 1905FP 17:03:31.013: Loading up D3D11 on adapter NVIDIA GeForce RTX 2080 Ti (0) 17:03:31.068: D3D11 loaded successfully, feature level used: b000 17:03:31.068: DXGI increase maximum frame latency success 17:03:31.068: D3D11 GPU priority setup failed (not admin?) 17:03:31.421: --------------------------------- 17:03:31.421: video settings reset: 17:03:31.421: 	base resolution:   1280x800 17:03:31.421: 	output resolution: 1280x800 17:03:31.421: 	downscale filter:  Lanczos 17:03:31.421: 	fps:               60/1 17:03:31.421: 	format:            NV12 17:03:31.421: 	YUV mode:          709/Partial 17:03:31.421: NV12 texture support enabled 17:03:31.422: Audio monitoring device: 17:03:31.422: 	name: Default 17:03:31.422: 	id: default 17:03:31.423: --------------------------------- 17:03:31.424: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin 17:03:31.427: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded 17:03:31.428: Failed to load 'en-US' text for module: 'decklink-captions.dll' 17:03:31.428: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll' 17:03:31.451: [AMF] Unable to load 'amfrt64.dll', error code 126. 17:03:31.452: [AMF] AMF Test failed due to one or more errors. 17:03:31.452: Failed to initialize module 'enc-amf.dll' 17:03:31.458: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin 17:03:31.463: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin 17:03:31.463: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin 17:03:31.467: [obs-browser]: Version 2.14.3 17:03:31.467: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100 17:03:31.470: NVENC supported 17:03:31.471: [noise suppress: Nvidia RTX denoiser disabled, redistributable not found] 17:03:31.583: [StreamFX] Loading Version 0.11.0.0a1-ga6da3f44 17:03:31.588: [StreamFX] <nvidia::cuda::cuda> Driver reported CUDA version: 11.1.0 17:03:31.705: [StreamFX] <NVIDIA Face Tracking Filter> Failed to load NVIDIA AR SDK runtime. 17:03:31.705: [StreamFX] Loaded Version 0.11.0.0a1-ga6da3f44 17:03:31.708: VLC found, VLC video source enabled 17:03:31.713: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 17:03:31.713: No blackmagic support 17:03:31.717: --------------------------------- 17:03:31.717:   Loaded Modules: 17:03:31.717:     win-wasapi.dll 17:03:31.717:     win-mf.dll 17:03:31.717:     win-dshow.dll 17:03:31.717:     win-decklink.dll 17:03:31.717:     win-capture.dll 17:03:31.717:     vlc-video.dll 17:03:31.717:     text-freetype2.dll 17:03:31.717:     StreamFX.dll 17:03:31.717:     rtmp-services.dll 17:03:31.717:     obs-x264.dll 17:03:31.717:     obs-vst.dll 17:03:31.717:     obs-virtualoutput.dll 17:03:31.717:     obs-transitions.dll 17:03:31.717:     obs-text.dll 17:03:31.717:     obs-qsv11.dll 17:03:31.717:     obs-outputs.dll 17:03:31.717:     obs-filters.dll 17:03:31.717:     obs-ffmpeg.dll 17:03:31.717:     obs-browser.dll 17:03:31.717:     image-source.dll 17:03:31.717:     frontend-tools.dll 17:03:31.717:     enc-amf.dll 17:03:31.717:     decklink-ouput-ui.dll 17:03:31.717:     decklink-captions.dll 17:03:31.717:     coreaudio-encoder.dll 17:03:31.717: --------------------------------- 17:03:31.717: ==== Startup complete =============================================== 17:03:31.728: All scene data cleared 17:03:31.728: ------------------------------------------------ 17:03:31.805: WASAPI: Device 'Speakers (Realtek(R) Audio)' [48000 Hz] initialized 17:03:31.805: [Loaded global audio device]: 'Desktop Audio' 17:03:31.851: WASAPI: Device 'Microphone (Scarlett Solo USB)' [176400 Hz] initialized 17:03:31.851: [Loaded global audio device]: 'Mic/Aux' 17:03:31.851: [Media Source 'music_sliders']: settings: 17:03:31.851: 	input:                   D:/backup/music for DR/super glove ball- stage theme 4.mp3 17:03:31.851: 	input_format:            (null) 17:03:31.851: 	speed:                   100 17:03:31.851: 	is_looping:              yes 17:03:31.851: 	is_linear_alpha:         no 17:03:31.851: 	is_hw_decoding:          no 17:03:31.851: 	is_clear_on_media_end:   yes 17:03:31.851: 	restart_on_activate:     yes 17:03:31.851: 	close_when_inactive:     no 17:03:31.888: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux) 17:03:31.888:  17:03:36.536: [Media Source 'BRB_music']: settings: 17:03:36.536: 	input:                   D:/backup/music for DR/ENJOY THE MUSIC Panic Restaurant #8.mp3 17:03:36.536: 	input_format:            (null) 17:03:36.536: 	speed:                   100 17:03:36.536: 	is_looping:              no 17:03:36.536: 	is_linear_alpha:         no 17:03:36.536: 	is_hw_decoding:          no 17:03:36.536: 	is_clear_on_media_end:   yes 17:03:36.536: 	restart_on_activate:     yes 17:03:36.536: 	close_when_inactive:     no 17:03:36.538: [window-capture: 'Window Capture 5'] update settings: 17:03:36.538: 	executable: mspaint.exe 17:03:36.538: 	method selected: Automatic 17:03:36.538: 	method chosen: BitBlt 17:03:36.538:  17:03:36.549: [Media Source 'Music']: settings: 17:03:36.549: 	input:                   D:/backup/music for DR/ENJOY THE MUSIC Panic Restaurant #1.mp3 17:03:36.549: 	input_format:            (null) 17:03:36.549: 	speed:                   100 17:03:36.549: 	is_looping:              yes 17:03:36.549: 	is_linear_alpha:         no 17:03:36.549: 	is_hw_decoding:          no 17:03:36.549: 	is_clear_on_media_end:   yes 17:03:36.549: 	restart_on_activate:     yes 17:03:36.549: 	close_when_inactive:     yes 17:03:36.557: [duplicator-monitor-capture: 'right_monitor'] update settings: 17:03:36.557: 	display: 1 (1920x1080) 17:03:36.557: 	cursor: true 17:03:36.557: 	method: DXGI 17:03:36.571: [duplicator-monitor-capture: 'Display Capture 2'] update settings: 17:03:36.571: 	display: 1 (1920x1080) 17:03:36.571: 	cursor: true 17:03:36.571: 	method: DXGI 17:03:36.582: [Media Source 'vid']: settings: 17:03:36.582: 	input:                   D:/backup/videos for Dr/owendeery_v7.mp4 17:03:36.582: 	input_format:            (null) 17:03:36.582: 	speed:                   100 17:03:36.582: 	is_looping:              yes 17:03:36.582: 	is_linear_alpha:         no 17:03:36.582: 	is_hw_decoding:          no 17:03:36.582: 	is_clear_on_media_end:   yes 17:03:36.582: 	restart_on_activate:     yes 17:03:36.582: 	close_when_inactive:     yes 17:03:36.587: [duplicator-monitor-capture: 'Display Capture'] update settings: 17:03:36.587: 	display: 1 (1920x1080) 17:03:36.587: 	cursor: true 17:03:36.587: 	method: DXGI 17:03:36.589: [window-capture: 'Window Capture 2'] update settings: 17:03:36.589: 	executable: chrome.exe 17:03:36.589: 	method selected: Automatic 17:03:36.589: 	method chosen: WGC 17:03:36.589:  17:03:36.596: --------------------------------- 17:03:36.596: [DShow Device: 'Video Capture Device'] settings updated:  17:03:36.596: 	video device: Logitech Webcam C210 17:03:36.596: 	video path: \\?\usb#vid_046d&pid_0819&mi_00#6&e3577c5&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083} 17:03:36.596: 	resolution: 640x480 17:03:36.596: 	flip: 0 17:03:36.596: 	fps: 30.00 (interval: 333333) 17:03:36.596: 	format: I420 17:03:36.603: [duplicator-monitor-capture: 'left monitor'] update settings: 17:03:36.603: 	display: 2 (1280x1024) 17:03:36.603: 	cursor: true 17:03:36.603: 	method: DXGI 17:03:36.603: [window-capture: 'Window Capture'] update settings: 17:03:36.603: 	executable: retroarch.exe 17:03:36.603: 	method selected: Automatic 17:03:36.603: 	method chosen: BitBlt 17:03:36.603:  17:03:36.604: [duplicator-monitor-capture: 'right_monitor_small'] update settings: 17:03:36.604: 	display: 1 (1920x1080) 17:03:36.604: 	cursor: true 17:03:36.604: 	method: DXGI 17:03:36.620: capture_card: data.GetDevice failed 17:03:36.620: capture_card: Video configuration failed 17:03:36.643: warning: deprecated pixel format used, make sure you did set range correctly 17:03:36.790: [window-capture: 'guest'] update settings: 17:03:36.790: 	executable: Discord.exe 17:03:36.790: 	method selected: Automatic 17:03:36.790: 	method chosen: WGC 17:03:36.790:  17:03:36.793: device_pixelshader_create (D3D11): Compiler warnings/errors for D:/backup/extrude.effect (Pixel shader, technique Draw, pass 0): 17:03:36.793: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(90,11): error X3000: syntax error: unexpected token '[' 17:03:36.793: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(97,16-18): error X3004: undeclared identifier 'ps4' 17:03:36.793:  17:03:36.793: Pass (0) <> missing pixel shader! 17:03:36.793: [StreamFX] Loading shader 'D' failed with error: Unknown error during effect compile. 17:03:36.799: device_pixelshader_create (D3D11): Compiler warnings/errors for D:/backup/extrude.effect (Pixel shader, technique Draw, pass 0): 17:03:36.799: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(90,11): error X3000: syntax error: unexpected token '[' 17:03:36.799: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(97,16-18): error X3004: undeclared identifier 'ps4' 17:03:36.799:  17:03:36.799: Pass (0) <> missing pixel shader! 17:03:36.799: [StreamFX] Loading shader 'D' failed with error: Unknown error during effect compile. 17:03:36.800: warning: deprecated pixel format used, make sure you did set range correctly 17:03:36.917: Switched to scene 'cam extrude' 17:03:36.917: ------------------------------------------------ 17:03:36.917: Loaded scenes: 17:03:36.917: - scene 'Retro Game Setup': 17:03:36.917:     - source: 'VLC Video Source 2' (vlc_source) 17:03:36.917:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'rachel_source' (vlc_source) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'right_monitor' (monitor_capture) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - source: 'justcam3' (scene) 17:03:36.918:         - filter: 'Color Grading' (streamfx-filter-color-grade) 17:03:36.918:         - filter: 'Image Mask/Blend' (mask_filter_v2) 17:03:36.918:         - filter: '3D Transform' (streamfx-filter-transform) 17:03:36.918:         - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - source: 'Window Capture' (window_capture) 17:03:36.918:     - source: 'Game Capture 3' (game_capture) 17:03:36.918:     - source: 'backgroundGameboy' (image_source) 17:03:36.918:     - source: 'background4_3' (image_source) 17:03:36.918:     - source: 'live_text' (text_gdiplus_v2) 17:03:36.918:     - source: 'nameplate0' (text_gdiplus_v2) 17:03:36.918: - scene 'Retro Game Conversation': 17:03:36.918:     - source: 'Window Capture' (window_capture) 17:03:36.918:     - source: 'VLC Video Source 2' (vlc_source) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - source: 'justcam3' (scene) 17:03:36.918:         - filter: 'Color Grading' (streamfx-filter-color-grade) 17:03:36.918:         - filter: 'Image Mask/Blend' (mask_filter_v2) 17:03:36.918:         - filter: '3D Transform' (streamfx-filter-transform) 17:03:36.918:         - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - source: 'guest' (window_capture) 17:03:36.918:     - source: 'background_2_faces' (image_source) 17:03:36.918:     - source: 'nameplate0' (text_gdiplus_v2) 17:03:36.918:     - source: 'nameplate1' (text_gdiplus_v2) 17:03:36.918: - scene 'blank': 17:03:36.918:     - source: 'Image' (image_source) 17:03:36.918: - scene 'Full Screen': 17:03:36.918:     - source: 'Display Capture' (monitor_capture) 17:03:36.918:     - source: 'background' (image_source) 17:03:36.918:     - source: 'Game Capture 2' (game_capture) 17:03:36.918:     - source: 'Window Capture 5' (window_capture) 17:03:36.918:         - filter: 'Chroma Key' (chroma_key_filter) 17:03:36.918: - scene 'full Screen with Head': 17:03:36.918:     - source: 'VLC Video Source 2' (vlc_source) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - source: 'Display Capture 2' (monitor_capture) 17:03:36.918:     - source: 'background2' (image_source) 17:03:36.918: - scene 'ANDROSS': 17:03:36.918:     - source: 'VLC Video Source 2' (vlc_source) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'background_face' (image_source) 17:03:36.918:         - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:     - source: 'Window Capture 2' (window_capture) 17:03:36.918:         - filter: 'Chroma Key' (chroma_key_filter) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - source: 'capture_card' (dshow_input) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918: - scene 'BRB': 17:03:36.918:     - source: 'BRB vid' (vlc_source) 17:03:36.918:     - source: 'title' (text_gdiplus) 17:03:36.918:     - source: 'Text (GDI+) 2 2' (text_gdiplus) 17:03:36.918:     - source: 'BRB_music' (ffmpeg_source) 17:03:36.918:     - source: 'credit music' (text_gdiplus) 17:03:36.918:     - source: 'newtext' (text_gdiplus_v2) 17:03:36.918: - scene 'END': 17:03:36.918:     - source: 'Music' (ffmpeg_source) 17:03:36.918:     - source: 'vid' (ffmpeg_source) 17:03:36.918:     - source: 'Text (GDI+) 2' (text_gdiplus) 17:03:36.918:     - source: 'title 2' (text_gdiplus) 17:03:36.918:     - source: 'credit music' (text_gdiplus) 17:03:36.918: - scene 'videos': 17:03:36.918:     - source: 'left monitor' (monitor_capture) 17:03:36.918:     - source: 'right_monitor' (monitor_capture) 17:03:36.918:     - source: 'VLC Video Source' (vlc_source) 17:03:36.918: - scene 'Begin STACKER': 17:03:36.918:     - source: 'VLC Video Source' (vlc_source) 17:03:36.918:     - source: 'left monitor' (monitor_capture) 17:03:36.918:     - source: 'Color Source' (color_source) 17:03:36.918:         - filter: 'Color Correction' (color_filter) 17:03:36.918:     - source: 'text2' (text_gdiplus) 17:03:36.918:     - source: 'text_top' (text_gdiplus) 17:03:36.918:     - source: 'Puzzle Depot' (text_gdiplus) 17:03:36.918: - scene 'Molehill': 17:03:36.918:     - source: 'Game Capture' (game_capture) 17:03:36.918: - scene 'metalgear': 17:03:36.918:     - source: 'octacon' (image_source) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - source: 'right_monitor_small' (monitor_capture) 17:03:36.918:     - source: 'mg_bg' (image_source) 17:03:36.918:         - filter: 'Color Correction' (color_filter) 17:03:36.918: - scene 'cam motorola': 17:03:36.918:     - source: 'computer' (image_source) 17:03:36.918:     - source: 'just cam' (scene) 17:03:36.918:         - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:         - filter: 'Color Grading' (streamfx-filter-color-grade) 17:03:36.918:         - filter: 'Image Mask/Blend' (mask_filter_v2) 17:03:36.918:         - filter: '3D Transform' (streamfx-filter-transform) 17:03:36.918:         - filter: 'Blur' (streamfx-filter-blur) 17:03:36.918: - scene 'cam sliders': 17:03:36.918:     - source: 'justcam2' (scene) 17:03:36.918:         - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:     - source: 'music_sliders' (ffmpeg_source) 17:03:36.918:     - source: 'starting_text' (text_gdiplus_v2) 17:03:36.918: - scene 'cam mainframe': 17:03:36.918:     - source: 'oldcomp' (image_source) 17:03:36.918:     - source: 'justcam3' (scene) 17:03:36.918:         - filter: 'Color Grading' (streamfx-filter-color-grade) 17:03:36.918:         - filter: 'Image Mask/Blend' (mask_filter_v2) 17:03:36.918:         - filter: '3D Transform' (streamfx-filter-transform) 17:03:36.918:         - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918: - scene 'just cam': 17:03:36.918:     - source: 'VLC Video Source 2' (vlc_source) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:     - filter: 'Color Grading' (streamfx-filter-color-grade) 17:03:36.918:     - filter: 'Image Mask/Blend' (mask_filter_v2) 17:03:36.918:     - filter: '3D Transform' (streamfx-filter-transform) 17:03:36.918:     - filter: 'Blur' (streamfx-filter-blur) 17:03:36.918: - scene 'justcam2': 17:03:36.918:     - source: 'VLC Video Source 2' (vlc_source) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918: - scene 'justcam3': 17:03:36.918:     - source: 'capture_card' (dshow_input) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:     - filter: 'Color Grading' (streamfx-filter-color-grade) 17:03:36.918:     - filter: 'Image Mask/Blend' (mask_filter_v2) 17:03:36.918:     - filter: '3D Transform' (streamfx-filter-transform) 17:03:36.918:     - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918:     - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918: - scene 'justcam4': 17:03:36.918:     - source: 'VLC Video Source 2' (vlc_source) 17:03:36.918:         - filter: 'Scaling/Aspect Ratio' (scale_filter) 17:03:36.918:     - source: 'Video Capture Device' (dshow_input) 17:03:36.918:         - filter: 'Color Correction' (color_filter_v2) 17:03:36.918:         - filter: 'Color Key' (color_key_filter_v2) 17:03:36.918:     - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918: - scene 'cam extrude': 17:03:36.918:     - source: 'justcam4' (scene) 17:03:36.918:         - filter: 'Shader' (streamfx-filter-shader) 17:03:36.918: ------------------------------------------------ 17:03:37.008: A sprite cannot be drawn without a width/height 17:03:37.112: [StreamFX] <updater> Automatic checks at launch are now enabled. 17:03:41.043: ==== Shutting down ================================================== 17:03:41.192: WASAPI: Device 'Speakers (Realtek(R) Audio)' Terminated 17:03:41.212: WASAPI: Device 'Microphone (Scarlett Solo USB)' Terminated 17:03:41.216: All scene data cleared 17:03:41.216: ------------------------------------------------ 17:03:41.278: [StreamFX] Unloading Version 0.11.0.0a1-ga6da3f44 17:03:41.283: [StreamFX] Unloaded Version 0.11.0.0a1-ga6da3f44 17:03:41.285: [Scripting] Total detached callbacks: 0 17:03:41.295: Freeing OBS context data 17:03:41.303: == Profiler Results ============================= 17:03:41.303: run_program_init: 6260.69 ms 17:03:41.303:  ┣OBSApp::AppInit: 14.373 ms 17:03:41.303:  ┃ ┗OBSApp::InitLocale: 1.792 ms 17:03:41.303:  ┗OBSApp::OBSInit: 6235.75 ms 17:03:41.303:    ┣obs_startup: 3.012 ms 17:03:41.303:    ┗OBSBasic::OBSInit: 6078.11 ms 17:03:41.303:      ┣OBSBasic::InitBasicConfig: 0.703 ms 17:03:41.303:      ┣OBSBasic::ResetAudio: 0.141 ms 17:03:41.303:      ┣OBSBasic::ResetVideo: 413.884 ms 17:03:41.303:      ┣OBSBasic::InitOBSCallbacks: 0.005 ms 17:03:41.303:      ┣OBSBasic::InitHotkeys: 0.036 ms 17:03:41.303:      ┣obs_load_all_modules: 293.836 ms 17:03:41.303:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 1.767 ms 17:03:41.303:      ┃ ┣obs_init_module(decklink-captions.dll): 0.021 ms 17:03:41.303:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 0.401 ms 17:03:41.303:      ┃ ┣obs_init_module(enc-amf.dll): 22.833 ms 17:03:41.303:      ┃ ┣obs_init_module(frontend-tools.dll): 3.404 ms 17:03:41.303:      ┃ ┣obs_init_module(image-source.dll): 0.005 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-browser.dll): 0.24 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 0.667 ms 17:03:41.303:      ┃ ┃ ┗nvenc_check: 0.636 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-filters.dll): 0.05 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-outputs.dll): 0.007 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-qsv11.dll): 100.525 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-text.dll): 0.172 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-transitions.dll): 0.006 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-virtualoutput.dll): 0.776 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-vst.dll): 0.001 ms 17:03:41.303:      ┃ ┣obs_init_module(obs-x264.dll): 0.001 ms 17:03:41.303:      ┃ ┣obs_init_module(rtmp-services.dll): 0.904 ms 17:03:41.303:      ┃ ┣obs_init_module(StreamFX.dll): 122.328 ms 17:03:41.303:      ┃ ┣obs_init_module(text-freetype2.dll): 0.052 ms 17:03:41.303:      ┃ ┣obs_init_module(vlc-video.dll): 1.311 ms 17:03:41.303:      ┃ ┣obs_init_module(win-capture.dll): 1.29 ms 17:03:41.303:      ┃ ┣obs_init_module(win-decklink.dll): 2.686 ms 17:03:41.303:      ┃ ┣obs_init_module(win-dshow.dll): 1.318 ms 17:03:41.303:      ┃ ┣obs_init_module(win-mf.dll): 0 ms 17:03:41.303:      ┃ ┣obs_init_module(win-wasapi.dll): 0.005 ms 17:03:41.303:      ┃ ┗reset_win32_symbol_paths: 0.213 ms 17:03:41.303:      ┣OBSBasic::ResetOutputs: 1.185 ms 17:03:41.303:      ┣OBSBasic::CreateHotkeys: 0.035 ms 17:03:41.303:      ┣OBSBasic::InitService: 2.411 ms 17:03:41.303:      ┣OBSBasic::InitPrimitives: 0.07 ms 17:03:41.303:      ┗OBSBasic::Load: 5197.27 ms 17:03:41.303: obs_hotkey_thread(25 ms): min=0.003 ms, median=0.004 ms, max=0.125 ms, 99th percentile=0.084 ms, 100% below 25 ms 17:03:41.303: audio_thread(Audio): min=0 ms, median=0.023 ms, max=0.216 ms, 99th percentile=0.12 ms 17:03:41.303: obs_graphics_thread(16.6667 ms): min=0.081 ms, median=0.454 ms, max=5033.72 ms, 99th percentile=14.112 ms, 99.3031% below 16.667 ms 17:03:41.303:  ┣tick_sources: min=0 ms, median=0.042 ms, max=548.054 ms, 99th percentile=0.595 ms 17:03:41.303:  ┣output_frame: min=0.07 ms, median=0.316 ms, max=3.309 ms, 99th percentile=1.494 ms 17:03:41.303:  ┃ ┗gs_context(video->graphics): min=0.069 ms, median=0.316 ms, max=3.309 ms, 99th percentile=1.493 ms 17:03:41.303:  ┃   ┣render_video: min=0.002 ms, median=0.216 ms, max=3.156 ms, 99th percentile=1.431 ms 17:03:41.303:  ┃   ┃ ┗render_main_texture: min=0.001 ms, median=0.214 ms, max=3.154 ms, 99th percentile=1.429 ms 17:03:41.303:  ┃   ┗gs_flush: min=0.044 ms, median=0.094 ms, max=0.612 ms, 99th percentile=0.37 ms 17:03:41.303:  ┗render_displays: min=0 ms, median=0.084 ms, max=2.468 ms, 99th percentile=0.407 ms 17:03:41.303: ================================================= 17:03:41.303: == Profiler Time Between Calls ================== 17:03:41.303: obs_hotkey_thread(25 ms): min=24.992 ms, median=25.924 ms, max=26.146 ms, 21.34% within ±2% of 25 ms (0% lower, 78.66% higher) 17:03:41.303: obs_graphics_thread(16.6667 ms): min=5.798 ms, median=16.667 ms, max=5033.73 ms, 98.6014% within ±2% of 16.667 ms (0.699301% lower, 0.699301% higher) 17:03:41.303: ================================================= 17:03:41.307: Number of memory leaks: 0
</details>

### Current Behavior

If you make an array it complains about the '[' symnol

### Expected Behavior

We should be able to use arrays

### Steps to Reproduce the Bug

create an array

**Comment by Xaymar** [comment]
Please follow the actual template which says to UPLOAD a log file, not paste it.

**Comment by Xaymar** [comment]
```
17:03:36.793: device_pixelshader_create (D3D11): Compiler warnings/errors for D:/backup/extrude.effect (Pixel shader, technique Draw, pass 0): 
17:03:36.793: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(90,11): error X3000: syntax error: unexpected token '[' 
17:03:36.793: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(97,16-18): error X3004: undeclared identifier 'ps4' 17:03:36.793: 17:03:36.793: Pass (0) <> missing pixel shader! 
17:03:36.793: [StreamFX] Loading shader 'D' failed with error: Unknown error during effect compile. 17:03:36.799: device_pixelshader_create (D3D11): Compiler warnings/errors for D:/backup/extrude.effect (Pixel shader, technique Draw, pass 0): 
17:03:36.799: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(90,11): error X3000: syntax error: unexpected token '[' 
17:03:36.799: D:\backup\extrude.effect (Pixel shader, technique Draw, pass 0)(97,16-18): error X3004: undeclared identifier 'ps4' 
17:03:36.799: 
17:03:36.799: Pass (0) <> missing pixel shader! 
17:03:36.799: [StreamFX] Loading shader 'D' failed with error: Unknown error during effect compile.
```

**Comment by Xaymar** [comment]
Errors caused by your Shader code are your own responsibility, and not a StreamFX bug.

**Comment by JamesEdSmith** [comment]
I'm just wondering why an array isn't allowed, that's not not really an "error caused by my shader code". What version of HLSL is it using???

**Comment by Xaymar** [comment]
For support, please head into the Discord instead of reporting it as a bug. This is not a bug.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
