### ISSUE TITLE
A Filter for Logical Branches

### ISSUE THREAD

**Issue by mattcalabrese** [Xaymar/obs-StreamFX#603]
### Explain the Feature/Enhancement

A new filter, "Branch", that has a few fields:

- "Value:" a boolean state that this filter introspects and manipulates
- "On False:" a reference to another filter, which is triggered when the boolean state is false
- "On False Duration:" an amount of time for "Branch" to stay enabled if enabled when in the false state
- "On True:" a reference to another filter, which is triggered when the boolean state is true
- "On True Duration:" an amount of time for "Branch" to stay enabled if enabled when in the "true" state

When you enable a "Branch" filter, it immediately does the following:

- If the "Value" field is false, enable the "On False" filter, immediately switch the "Value" field to true, and automatically disable "Branch" after "On False Duration" amount of time has passed.
- If the "Value" field is true enable the "On True" filter, immediately switch the "Value" field to false, and automatically disable "Branch" after "On True Duration" amount of time has passed.

Possible Future Direction:
- Branch on an integer value instead of strictly a boolean value. Each time the filter is enabled, it increments or decrements the value by 1 (depending on a separate field), until it hits a user-specified "End" value, in which case it will reset to 0. Each integer value in the range [0, End) would have a corresponding "Filter" field and "Duration".

### What makes this feature/enhancement useful for StreamFX and its users?

This filter is simple, but accomplishes a few things. I personally would use the simpler "boolean" form as a simple stopgap until your more proper animation system is completed. How this small filter would help is:

1. It makes it easy to have a single filter/hotkey do one thing or another based on automatically maintained internal state. At least for me, the most common case is one branch triggers a series of "Move Source" filters, and the other branch effectively does the "reverse", although "reverse" is frequently *not* just the everything in the opposite direction/order.
2. The duration fields make it so that if you have a hotkey to enable "Branch", and you press that hotkey while "Branch" is enabled, no further effect takes place. This means that if one of your "On True" or "On False" filters are a series of "Move Source" filters, you can easily guard against accidentally triggering "Branch" while the chain of other filters play out.

Though I would use this for animations, it seems as though this kind of feature is more generally useful. It allows users to directly toggle between different, complicated behaviors.

Example Integer Use-Case:
As mentioned, a generalization of this would be cycling through an integer range rather than just alternating between "true" and "false" values. An actual use-case I have for this particular functionality is a "Channel Changer".

In my scenes, I frequently have multiple mini displays, each of which I may want to display some fixed number of possible "channels". However, switching through the various channels for each display is currently rather tedious and confusing. However, if we had this integral "Branch" filter, I'd be able to set up a single hotkey for each mini display, where each time that hotkey is pressed, it changes the channel (and if there is a field in "Branch" for whether to "increment" or "decrement" the integer, I could use "Branch" in conjunction with a "Move Value" to easily enable "Channel Up" and "Channel Down" hotkeys corresponding to the same set of "Channels".

It seems that both of these forms of branching are useful in a variety of situations.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

### Any additional Information we need to know?

I say there is no other way to do this, however, I have come close to approximating this behavior with few "Move Source" filters that are enabled when other dummy sources become shown or hidden, but this is rather complicated to maintain and has other drawbacks.

**Comment by Xaymar** [comment]
**Rejected.**

This is entirely possible within OBS Studio's scripting system and better suited to it, and this will add needless complexity. It supports Python and Lua, and both are relatively easy to learn and support everything this feature request covers.
