### ISSUE TITLE
why obs number is Symbol word

### ISSUE THREAD

**Issue by Jameschuah** [Xaymar/obs-StreamFX#604]
### Operating System

MacOS 10.15 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.11.0a3

### OBS Studio Log

no

### OBS Studio Crash Log

why obs number is Symbol word
![WhatsApp Image 2021-07-16 at 9 12 18 PM](https://user-images.githubusercontent.com/63833784/125953571-4a8d655f-7332-4fdc-a43f-252d727ba25c.jpeg)

### Current Behavior

![WhatsApp Image 2021-07-16 at 9 12 18 PM](https://user-images.githubusercontent.com/63833784/125953814-13821739-cc25-4d17-b684-5bf1b734b501.jpeg)

### Expected Behavior

![WhatsApp Image 2021-07-16 at 9 12 18 PM](https://user-images.githubusercontent.com/63833784/125953799-356cabc3-eb81-490f-8a1b-7fafed6fe1cc.jpeg)

### Steps to Reproduce the Bug

![WhatsApp Image 2021-07-16 at 9 12 18 PM](https://user-images.githubusercontent.com/63833784/125953786-689b733e-a28d-4864-a53e-d18f738ebd36.jpeg)

### Any additional Information we need to know?

![Uploading WhatsApp Image 2021-07-16 at 9.12.18 PM.jpeg…]()

**Comment by Xaymar** [comment]
The StreamFX issue tracker is not for support related to OBS Studio.
