### ISSUE TITLE
Windows Defender and/or Edge flag latest binaries as potential security threats

### ISSUE THREAD

**Issue by f4bio** [Xaymar/obs-StreamFX#606]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.11.0a3

### OBS Studio Log

not applicable

### Current Behavior

not applicable

### Expected Behavior

not applicable

### Steps to Reproduce the Bug

download either of these:
* [v0.11.0.0a3](https://github.com/Xaymar/obs-StreamFX/releases/download/0.11.0a3/streamfx-windows-2019-0.11.0.0a3-g23207d04.exe)
*  [v0.10.1](https://github.com/Xaymar/obs-StreamFX/releases/download/0.10.1/streamfx-windows-2019-0.10.1.0-gc8484f65.exe)

### Any additional Information we need to know?

probably not a problem with StreamFX itself ([virustotal scans](https://www.virustotal.com/gui/url/5da15f603ea94a5fdf6ee918bf683fed93b248dbd5e1983819797524754fcae6/detection) seem fine) and maybe not much you can do about it anyways (I've [submitted the link](https://feedback.smartscreen.microsoft.com/feedback.aspx) for analysis to MS already)

Maybe see it more as a FYI rather then issue ;)

![wzeNdcfn0q](https://user-images.githubusercontent.com/4854092/128181996-a6ade9eb-cabf-4b90-a742-62487a3d341e.png)
![qYhIogth9r](https://user-images.githubusercontent.com/4854092/128182012-f277507d-e69c-4794-8d99-1caceb9150bd.png)

keep up the good work! ;)

**Comment by Xaymar** [comment]
This is covered in the installation guide.
