### ISSUE TITLE
AMD H.265 FFMpeg doesn't follow full color range when declared in advanced settings

### ISSUE THREAD

**Issue by Marocco2** [Xaymar/obs-StreamFX#613]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.10.1

### OBS Studio Log

https://cdn.discordapp.com/attachments/721122845475733544/879716156414513162/2021-08-24_14-47-35.txt

### Current Behavior

If I try to record an application/game using AMD H.265 FFMpeg encoder, OBS will force color gamma to partial instead of full. This doesn't happen with AMD H.264 FFMpeg encoder and same settings

### Expected Behavior

Encoder should follow specified color gamma OBS Settings

### Steps to Reproduce the Bug

- Set OBS Studio with this settings:
- 
![immagine](https://user-images.githubusercontent.com/3944248/130622395-b71db74b-0b1c-4e51-84d9-ce26cde7a127.png)
![immagine](https://user-images.githubusercontent.com/3944248/130622426-929e9182-fa31-449e-8bdb-4a0e6c2f2812.png)
![immagine](https://user-images.githubusercontent.com/3944248/130622462-bc63f1f7-7f51-427f-bd95-dbc983e87082.png)

Try record some gameplay footage. You will notice that output video will look very contrast

**Comment by Xaymar** [comment]
**This appears to be a bug upstream in OBS Studio!**  
The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.

**Comment by Xaymar** [comment]
The bug originates from OBS Studio choosing to use an old FFmpeg version, and is not caused by StreamFX. StreamFX provides all necessary information for encoders to correctly decide on how to encode content, as shown by ProRes and NVENC working perfectly fine.

**Comment by Marocco2** [comment]
> 
> 
> The bug originates from OBS Studio choosing to use an old FFmpeg version, and is not caused by StreamFX. StreamFX provides all necessary information for encoders to correctly decide on how to encode content, as shown by ProRes and NVENC working perfectly fine.

Thanks for quick response! Sucks that a possible solution will get delayed :(
