### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by ALETTERR** [Xaymar/obs-StreamFX#614]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.10.1

### OBS Studio Log

https://obsproject.com/logs/WUvaS7usFHkH7B0O

### Current Behavior

froze

### Expected Behavior

froze

### Steps to Reproduce the Bug

auto

**Comment by Xaymar** [comment]
Please fill out the template. Without this information, I can't provide you any further help.
