### ISSUE TITLE
Blur filter does not work when running OBS in admin mode

### ISSUE THREAD

**Issue by matthew-jumper** [Xaymar/obs-StreamFX#615]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.10.1

### OBS Studio Log

https://pastebin.com/NZmMKHw4

### Current Behavior

StreamFX blur filter doesn't work when running OBS as admin.  Blur filter blacks out the element.

### Expected Behavior

I expected blur to work as normal, such as in non-admin mode.

### Steps to Reproduce the Bug

Run OBS in admin mode.

**Comment by Xaymar** [comment]
Blur is working fine here as administrator. Ensure you followed the installation guide correctly.

**Comment by matthew-jumper** [comment]
Reinstalled via the Windows installer.  Everything works now.  Thanks!
