### ISSUE TITLE
error: [StreamFX] Unexpected exception in function '_create': Function not implemented.

### ISSUE THREAD

**Issue by williamroge** [Xaymar/obs-StreamFX#617]
### Operating System

Linux (like Arch Linux)

### OBS Studio Version?

27.0

### StreamFX Version

0.10.1

### OBS Studio Log

https://obsproject.com/logs/nhbXF-1oYiYhadkh

### OBS Studio Crash Log

[2021-08-30 22-05-04.txt](https://github.com/Xaymar/obs-StreamFX/files/7080833/2021-08-30.22-05-04.txt)

### Current Behavior

crashes or shows error about drivers might be out of date

### Expected Behavior

recording with amf encoder via ffmpeg

### Steps to Reproduce the Bug

select amf encoder press record fails

**Comment by Xaymar** [comment]
The attached "crash" log is not a crash log. Please attach a crash log if it actually crashed, otherwise this is a support case.

**Comment by williamroge** [comment]
Well I solved my issue with this terminal command "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json:/usr/share/vulkan/icd.d/amd_pro_icd32.json obs". The AMF encoder needed the amdgpu-pro vulkan driver but was using radv driver instead by default, so I needed to override it. Thanks for responding anyway, I appreciate it.

**Comment by dirtybeak** [comment]
Will thank you I been stuck for a week wrecking my brain what the issue was!!!!
