### ISSUE TITLE
OBS Crashes everytime I try to remove a filter because of StreamFX

### ISSUE THREAD

**Issue by snilan** [Xaymar/obs-StreamFX#619]
### Operating System

MacOS 10.15 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.10.1

### OBS Studio Log

20:02:00.615: CPU Name: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz 20:02:00.615: CPU Speed: 2000MHz 20:02:00.615: Physical Cores: 4, Logical Cores: 8 20:02:00.615: Physical Memory: 16384MB Total 20:02:00.615: OS Name: Mac OS X 20:02:00.615: OS Version: Version 10.15.5 (Build 19F101) 20:02:00.615: Kernel Version: 19.5.0 20:02:00.639: hotkeys-cocoa: Using layout 'com.apple.keylayout.US' 20:02:00.640: Current Date/Time: 2021-09-01, 20:02:00 20:02:00.640: Browser Hardware Acceleration: true 20:02:00.640: Portable mode: false 20:02:00.833: OBS 27.0.1 (mac) 20:02:00.833: --------------------------------- 20:02:00.834: --------------------------------- 20:02:00.834: audio settings reset: 20:02:00.834: 	samples per sec: 48000 20:02:00.834: 	speakers:        2 20:02:00.838: --------------------------------- 20:02:00.838: Initializing OpenGL... 20:02:00.877: Loading up OpenGL on adapter Intel Inc. Intel(R) Iris(TM) Plus Graphics OpenGL Engine 20:02:00.877: OpenGL loaded successfully, version 4.1 INTEL-14.6.18, shading language 4.10 20:02:01.120: --------------------------------- 20:02:01.120: video settings reset: 20:02:01.120: 	base resolution:   1920x1080 20:02:01.120: 	output resolution: 1280x720 20:02:01.120: 	downscale filter:  Bicubic 20:02:01.120: 	fps:               60/1 20:02:01.120: 	format:            NV12 20:02:01.120: 	YUV mode:          709/Partial 20:02:01.120: NV12 texture support not available 20:02:01.120: Audio monitoring device: 20:02:01.120: 	name: Default 20:02:01.120: 	id: default 20:02:01.121: --------------------------------- 20:02:01.124: Failed to load 'en-US' text for module: 'decklink-captions.so' 20:02:01.127: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so' 20:02:01.141: os_dlopen(libpython3.9.dylib->libpython3.9.dylib): dlopen(libpython3.9.dylib, 257): image not found 20:02:01.141:  20:02:01.141: [Python] Could not load library: libpython3.9.dylib 20:02:01.207: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 20:02:01.207: No blackmagic support 20:02:01.209: [mac-virtualcam] version=1.3.0 20:02:01.364: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders 20:02:01.369: [obs-browser]: Version 2.14.3 20:02:01.369: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121 20:02:01.534: VLC found, VLC video source enabled 20:02:01.537: Failed to load 'en-US' text for module: 'StreamDeckPlugin.so' 20:02:01.564: [StreamFX] Loading Version 0.10.1.0-gc8484f65 20:02:01.564: [StreamFX] Loaded Version 0.10.1.0-gc8484f65 20:02:01.566: [Move Transition] loaded version 2.5.0 20:02:01.567: [obs-ndi] hello ! (version 4.9.0) 20:02:01.567: [obs-ndi] Trying '' 20:02:01.567: [obs-ndi] Trying '/usr/lib' 20:02:01.567: [obs-ndi] Trying '/usr/local/lib' 20:02:01.568: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.4.dylib' 20:02:01.570: [obs-ndi] NDI runtime loaded successfully 20:02:01.571: [obs-ndi] NDI library initialized successfully (NDI SDK APPLE 11:50:41 Apr  1 2020 4.5.1) 20:02:01.584: [obs-websocket] you can haz websockets (version 4.9.1) 20:02:01.584: [obs-websocket] qt version (compile-time): 5.15.2 ; qt version (run-time): 5.15.2 20:02:01.586: [obs-websocket] module loaded! 20:02:01.587: [Transition Table] loaded version 0.2.1 20:02:01.587: --------------------------------- 20:02:01.587:   Loaded Modules: 20:02:01.587:     transition-table.so 20:02:01.587:     obs-websocket.so 20:02:01.587:     obs-shaderfilter.so 20:02:01.587:     obs-ndi.so 20:02:01.587:     move-transition.so 20:02:01.587:     StreamFX.so 20:02:01.587:     StreamDeckPlugin.so 20:02:01.587:     vlc-video.so 20:02:01.587:     text-freetype2.so 20:02:01.587:     rtmp-services.so 20:02:01.587:     obs-x264.so 20:02:01.587:     obs-vst.so 20:02:01.587:     obs-transitions.so 20:02:01.587:     obs-outputs.so 20:02:01.587:     obs-filters.so 20:02:01.587:     obs-ffmpeg.so 20:02:01.587:     obs-browser.so 20:02:01.587:     mac-vth264.so 20:02:01.587:     mac-virtualcam.so 20:02:01.587:     mac-syphon.so 20:02:01.587:     mac-decklink.so 20:02:01.587:     mac-capture.so 20:02:01.587:     mac-avcapture.so 20:02:01.588:     image-source.so 20:02:01.588:     frontend-tools.so 20:02:01.588:     decklink-ouput-ui.so 20:02:01.588:     decklink-captions.so 20:02:01.588:     coreaudio-encoder.so 20:02:01.588: --------------------------------- 20:02:01.588: ==== Startup complete =============================================== 20:02:01.628: All scene data cleared 20:02:01.628: ------------------------------------------------ 20:02:01.741: coreaudio: device 'MacBook Pro Microphone' initialized 20:02:01.741: [Loaded global audio device]: 'Mic/Aux' 20:02:01.805: [Media Source 'Instant Replay']: settings: 20:02:01.805: 	input:                   /Users/sean/Movies/Replay 2021-09-01 11-54-00.mkv 20:02:01.805: 	input_format:            (null) 20:02:01.805: 	speed:                   100 20:02:01.805: 	is_looping:              no 20:02:01.805: 	is_linear_alpha:         no 20:02:01.805: 	is_hw_decoding:          no 20:02:01.805: 	is_clear_on_media_end:   yes 20:02:01.805: 	restart_on_activate:     yes 20:02:01.805: 	close_when_inactive:     no 20:02:01.839: Error compiling shader: 20:02:01.839: ERROR: 0:40: ')' : syntax error: syntax error 20:02:01.839:  20:02:01.839:  20:02:01.839: device_pixelshader_create (GL) failed 20:02:01.839: Pass (0) <> missing pixel shader! 20:02:01.840: Error compiling shader: 20:02:01.840: ERROR: 0:41: ')' : syntax error: syntax error 20:02:01.840:  20:02:01.840:  20:02:01.840: device_pixelshader_create (GL) failed 20:02:01.840: Pass (0) <> missing pixel shader! 20:02:01.850: Error compiling shader: 20:02:01.850: ERROR: 0:41: ')' : syntax error: syntax error 20:02:01.850:  20:02:01.850:  20:02:01.850: device_pixelshader_create (GL) failed 20:02:01.850: Pass (0) <> missing pixel shader! 20:02:01.851: [StreamFX] Unexpected exception in function '_create': Unknown error during effect compile.. 20:02:01.851: Failed to create source 'Blur'! 20:02:01.861: Webcam: Selected device 'FaceTime HD Camera (Built-in)' 20:02:01.864: Webcam: Using preset 1280x720 20:02:01.977: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux) 20:02:01.977:  20:02:02.215: [Media Source 'Stinger (Stinger)']: settings: 20:02:02.215: 	input:                   /Users/sean/OBS/transitions/gael/Red Play.webm 20:02:02.215: 	input_format:            (null) 20:02:02.215: 	speed:                   100 20:02:02.215: 	is_looping:              no 20:02:02.215: 	is_linear_alpha:         no 20:02:02.215: 	is_hw_decoding:          yes 20:02:02.215: 	is_clear_on_media_end:   yes 20:02:02.215: 	restart_on_activate:     yes 20:02:02.215: 	close_when_inactive:     no 20:02:02.216: Switched to scene 'Coding' 20:02:02.217: ------------------------------------------------ 20:02:02.217: Loaded scenes: 20:02:02.217: - scene 'Intro': 20:02:02.217:     - source: 'Code' (scene) 20:02:02.217:         - filter: 'Blur' (streamfx-filter-blur) 20:02:02.217:         - filter: 'Blur On' (move_value_filter) 20:02:02.217:         - filter: 'Blur Off' (move_value_filter) 20:02:02.217:     - source: 'Webcam Scene' (scene) 20:02:02.217:         - filter: 'Shader' (streamfx-filter-shader) 20:02:02.217:         - filter: 'Move Source' (move_source_filter) 20:02:02.217:         - filter: 'Move Value' (move_value_filter) 20:02:02.217: - scene 'Coding': 20:02:02.217:     - source: 'Code' (scene) 20:02:02.217:         - filter: 'Blur' (streamfx-filter-blur) 20:02:02.217:         - filter: 'Blur On' (move_value_filter) 20:02:02.217:         - filter: 'Blur Off' (move_value_filter) 20:02:02.217:     - source: 'Webcam Scene' (scene) 20:02:02.217:         - filter: 'Shader' (streamfx-filter-shader) 20:02:02.217:         - filter: 'Move Source' (move_source_filter) 20:02:02.217:         - filter: 'Move Value' (move_value_filter) 20:02:02.217:     - source: 'Instant Replay' (ffmpeg_source) 20:02:02.217:     - source: 'Image' (image_source) 20:02:02.217:     - filter: 'WebcamBottomRight' (move_source_filter) 20:02:02.217:     - filter: 'Move Web Cam' (move_value_filter) 20:02:02.217:     - filter: 'Move Source' (move_source_filter) 20:02:02.217: - scene 'SinglePageView': 20:02:02.217:     - source: 'Code' (scene) 20:02:02.217:         - filter: 'Blur' (streamfx-filter-blur) 20:02:02.217:         - filter: 'Blur On' (move_value_filter) 20:02:02.217:         - filter: 'Blur Off' (move_value_filter) 20:02:02.217:     - source: 'Webcam Scene' (scene) 20:02:02.217:         - filter: 'Shader' (streamfx-filter-shader) 20:02:02.217:         - filter: 'Move Source' (move_source_filter) 20:02:02.217:         - filter: 'Move Value' (move_value_filter) 20:02:02.217:     - source: 'Web1' (scene) 20:02:02.217:     - filter: 'WebcamBottomRight' (move_source_filter) 20:02:02.217: - scene 'BrowserView': 20:02:02.217:     - source: 'Web1' (scene) 20:02:02.217:     - source: 'Code' (scene) 20:02:02.217:         - filter: 'Blur' (streamfx-filter-blur) 20:02:02.217:         - filter: 'Blur On' (move_value_filter) 20:02:02.217:         - filter: 'Blur Off' (move_value_filter) 20:02:02.217:     - source: 'Webcam Scene' (scene) 20:02:02.217:         - filter: 'Shader' (streamfx-filter-shader) 20:02:02.217:         - filter: 'Move Source' (move_source_filter) 20:02:02.217:         - filter: 'Move Value' (move_value_filter) 20:02:02.217:     - filter: 'WebcamBottomRight' (move_source_filter) 20:02:02.217: - scene 'MultiPageView': 20:02:02.217:     - source: 'Code' (scene) 20:02:02.217:         - filter: 'Blur' (streamfx-filter-blur) 20:02:02.217:         - filter: 'Blur On' (move_value_filter) 20:02:02.217:         - filter: 'Blur Off' (move_value_filter) 20:02:02.217:     - source: 'Webcam Scene' (scene) 20:02:02.217:         - filter: 'Shader' (streamfx-filter-shader) 20:02:02.217:         - filter: 'Move Source' (move_source_filter) 20:02:02.217:         - filter: 'Move Value' (move_value_filter) 20:02:02.217:     - source: 'Web1' (scene) 20:02:02.217:     - source: 'Web2' (scene) 20:02:02.217:     - filter: 'WebcamBottomRight' (move_source_filter) 20:02:02.217: - scene 'PageComparison': 20:02:02.217:     - source: 'Web1' (scene) 20:02:02.217:     - source: 'Web2' (scene) 20:02:02.217:     - source: 'Webcam Scene' (scene) 20:02:02.217:         - filter: 'Shader' (streamfx-filter-shader) 20:02:02.217:         - filter: 'Move Source' (move_source_filter) 20:02:02.217:         - filter: 'Move Value' (move_value_filter) 20:02:02.217: - scene 'Webcam Scene': 20:02:02.217:     - source: 'Webcam' (av_capture_input) 20:02:02.217:         - filter: 'CircleMask' (mask_filter_v2) 20:02:02.217:     - source: 'MYBROWSER' (browser_source) 20:02:02.217:     - filter: 'Shader' (streamfx-filter-shader) 20:02:02.217:     - filter: 'Move Source' (move_source_filter) 20:02:02.217:     - filter: 'Move Value' (move_value_filter) 20:02:02.217: - scene 'Code': 20:02:02.217:     - source: 'VSCode' (window_capture) 20:02:02.217:     - filter: 'Blur' (streamfx-filter-blur) 20:02:02.217:     - filter: 'Blur On' (move_value_filter) 20:02:02.218:     - filter: 'Blur Off' (move_value_filter) 20:02:02.218: - scene 'Web1': 20:02:02.218:     - source: 'Chrome1' (window_capture) 20:02:02.218: - scene 'Web2': 20:02:02.218:     - source: 'Chrome2' (window_capture) 20:02:02.218: ------------------------------------------------ 20:02:02.293: [obs-websocket] WSServer::start: Not locked to IPv4 bindings 20:02:02.293: [obs-websocket] server started successfully on port 4444 20:02:02.293: [obs-websocket] IO thread started. 20:02:02.460: [StreamFX] <updater> Automatic checks at launch are now enabled. 20:02:02.723: [obs-websocket] Update << '{"item-id":1,"item-name":"Webcam","scene-name":"Webcam Scene","transform":{"bounds":{"alignment":0,"type":"OBS_BOUNDS_NONE","x":0.0,"y":0.0},"crop":{"bottom":0,"left":0,"right":0,"top":0},"height":1080.0,"locked":false,"position":{"alignment":5,"x":0.0,"y":0.0},"rotation":0.0,"scale":{"filter":"OBS_SCALE_DISABLE","x":1.5,"y":1.5},"sourceHeight":720,"sourceWidth":1280,"visible":true,"width":1920.0},"update-type":"SceneItemTransformChanged"}' 20:02:13.442: [obs-websocket] Update << '{"duration":1600,"from-scene":"Coding","name":"Move","to-scene":"SinglePageView","type":"move_transition","update-type":"TransitionBegin"}' 20:02:13.442: User switched to scene 'SinglePageView' 20:02:15.509: [obs-websocket] Update << '{"duration":1600,"from-scene":"Coding","name":"Move","to-scene":"SinglePageView","type":"move_transition","update-type":"TransitionVideoEnd"}' 20:02:15.521: [obs-websocket] Update << '{"duration":1600,"name":"Move","to-scene":"SinglePageView","type":"move_transition","update-type":"TransitionEnd"}' 20:02:15.785: [obs-websocket] Update << '{"scene-name":"SinglePageView","sources":[{"alignment":5,"cx":792.72296142578125,"cy":445.8812255859375,"id":3,"locked":false,"muted":false,"name":"Web1","render":true,"source_cx":1920,"source_cy":1080,"type":"scene","volume":1.0,"x":1221.0,"y":0.0},{"alignment":5,"cx":459.0,"cy":258.0,"id":2,"locked":false,"muted":false,"name":"Webcam Scene","render":true,"source_cx":1920,"source_cy":1080,"type":"scene","volume":1.0,"x":1606.0,"y":822.0},{"alignment":5,"cx":1920.0,"cy":1080.0,"id":1,"locked":false,"muted":false,"name":"Code","render":true,"source_cx":1920,"source_cy":1080,"type":"scene","volume":1.0,"x":0.0,"y":0.0}],"update-type":"SwitchScenes"}' 20:02:24.619: [obs-websocket] Update << '{"item-id":1,"item-name":"Code","scene-name":"SinglePageView","update-type":"SceneItemSelected"}'

### OBS Studio Crash Log

<img width="677" alt="Screen Shot 2021-09-01 at 8 04 29 PM" src="https://user-images.githubusercontent.com/319573/131761502-c5ce2e96-2fe7-46b1-88cf-ac5a93f38644.png">

### Current Behavior

I was trying to add a filter and a shader to a couple scenes, but they weren't working. But now everytime I try to remove them from the scenes, OBS crashes.
<img width="677" alt="Screen Shot 2021-09-01 at 8 04 29 PM" src="https://user-images.githubusercontent.com/319573/131761354-2587b2ad-4c07-433d-8546-b411a41a6668.png">

### Expected Behavior

See above

### Steps to Reproduce the Bug

See above

**Comment by Xaymar** [comment]
Please attach a proper crash log.

**Comment by snilan** [comment]
[obs-crash.txt](https://github.com/Xaymar/obs-StreamFX/files/7095321/obs-crash.txt)

**Comment by Xaymar** [comment]
**This appears to be a bug upstream in OBS Studio!**  
The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.

**Comment by Xaymar** [comment]
At no point in the stack is StreamFX present, it is entirely within OBS Studio and libobs. This is not something StreamFX can fix or prevent.
