### ISSUE TITLE
Output To Other FFMPEG Binary

### ISSUE THREAD

**Issue by jasonmvp** [Xaymar/obs-StreamFX#624]
### Explain the Feature/Enhancement

This may already exist, and if so I apologize; just point me in the right direction!  The request is to somehow take the composition from OBS Studio and pipe it to a user-provided/selected ffmpeg binary instead of the included OBS plugin.  I don't know if that's even possible, but maybe present the user with the dialog:

- Path to custom ffmpeg binary
- options, etc

### What makes this feature/enhancement useful for StreamFX and its users?

This will help folks trying to use features on newer(?) ffmpeg builds such as proper h.265 hardware encoding on the Mac (OBS' plugin doesn't do it properly).

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
This is not something StreamFX can or will aim to do. You will have to suggest this to the OBS maintainers.
