### ISSUE TITLE
AMF/NVENC H.265 (via FFmpeg) for Streaming on YouTube

### ISSUE THREAD

**Issue by DarkeriumD** [Xaymar/obs-StreamFX#627]
### Explain the Feature/Enhancement

Since YouTube now allows streaming in H.265 via HLS, it would be cool if we could have the same AMF/NVENC H.265 (via FFmpeg) option under the Streaming tab in OBS Studio. It works wonders for recording, but is missing for streaming.

To avoid users accidentally using H.265 for streaming on other platforms (where H.265 isn't supported), this option could be made to be invisible unless YouTube is selected under Stream > Service.

From my point of view, this shouldn't be hard to add since StreamFX already has this very thing implemented for recording with OBS Studio, it just needs to be added under Streaming encoders as well.

### What makes this feature/enhancement useful for StreamFX and its users?

It would allow users to stream in higher quality at the same bitrate or perhaps even allow more people with slower internet speeds to start streaming without big compromises in stream quality.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
**This appears to be a bug upstream in OBS Studio!**  
The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.

**Comment by Xaymar** [comment]
StreamFX only provides Sources, Transitions, Filters and Encoders to libOBS. It has no way to affect what OBS Studio does, that is something you will have to take up with the maintainers of that project. This has been answered 5 times just in the last year.

**Comment by DarkeriumD** [comment]
> **This appears to be a bug upstream in OBS Studio!**
> The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.

So, OBS Studio should show AMF/NVENC H.265 (via FFmpeg) as an encoder option for streaming, but doesn't due to a bug or some other reason? I'll ask about it over on Discord.

> StreamFX only provides Sources, Transitions, Filters and Encoders to libOBS. It has no way to affect what OBS Studio does, that is something you will have to take up with the maintainers of that project. This has been answered 5 times just in the last year.

I get that, don't worry. I wasn't asking that exact question, only if it's StreamFX that isn't providing AMF/NVENC H.265 for streaming since it seemed that it only allowed it for recording. Since that doesn't appear to be the case, it has to be something with OBS Studio that isn't showing the H.265 option under streaming encoders.

All in all, many thanks for your time.
