### ISSUE TITLE
StreamFX does not load with disconnected eGPU

### ISSUE THREAD

**Issue by funarg** [Xaymar/obs-StreamFX#628]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.11.0a3

### OBS Studio Log

https://obsproject.com/logs/BAs93OaHyD83uHM7

### Current Behavior

StreamFX does not load inside OBS when Nvidia driver is installed but GPU is disconnected.
In my case it's a 3060 Ti in a Thunderbolt 3 eGPU enclosure connected to a laptop that doesn't otherwise have a discrete GPU.

```
17:40:21.066: [StreamFX] Loading Version 0.11.0.0a3-g23207d04
17:40:21.072: [StreamFX] <nvidia::cuda::cuda> Driver reported CUDA version: 11.4.0
17:40:21.093: [StreamFX] <nvidia::cuda::cuda> Driver reported CUDA version: 11.4.0
17:40:21.100: [StreamFX] Unexpected exception in function 'obs_module_load'.
17:40:21.100: Failed to initialize module 'StreamFX.dll'
```

If I uninstall Nvidia drivers and reboot then StreamFX will load and work as expected with just integrated Intel GPU. But installing and uninstalling drivers every time the laptop is undocked is not a very practical workaround.

### Expected Behavior

StreamFX detects absence of Nvidia GPU and falls back to integrated GPU.

### Steps to Reproduce the Bug

1. Disconnect Nvidia GPU
2. Start OBS Studio
3. StreamFX is missing

**Comment by Xaymar** [comment]
The bug you are describing has already been fixed in the current code. Note that Testing releases are not for Production usage, and will behave unpredictably in many situations.
