### ISSUE TITLE
NVIDIA NVENC H.254 / H.256 via FFmpeg "Failed to start recording"

### ISSUE THREAD

**Issue by JustCryen** [Xaymar/obs-StreamFX#633]
### Operating System

Linux (like Arch Linux)

### OBS Studio Version?

27.0

### StreamFX Version

0.11.0a3

### OBS Studio Log

https://obsproject.com/logs/qJz0NXT3xtiyAF2u

### Current Behavior

Trying to start recording while Encoder is set as any "via FFmpeg" encoder (H.264 / H.265) results in "failed to start encoding" message.

### Expected Behavior

I was able to use H.265 via FFmpeg in 9.3 StreamFX 9.3 back when 10 wasn't stable yet.
It worked just fine, recorded everything and encoded to H.265. Now it just fails.

### Steps to Reproduce the Bug

1. Set encoder to either `NVIDIA NVENC H.264/AVC (via FFmpeg)` or `NVIDIA NVENC H.265/HEVC (via FFmpeg)`
2. Click "Start Recording"

### Any additional Information we need to know?

**nvidia-dkms** / **nvidia-vulkan-dkms** *470.62.02-1* (I've tried a couple of drivers and nothing worked)
I'm on a laptop so additionally I use **nvidia-prime** *1.6-4*
System sound implementation: **pipewire** *1:0.3.36-1*
**obs-studio** *27.0.1-2*
**xorg-server** *1.20.13-2*
DE: **gnome-shell** *1:40.4-1*
Known StreamFX Versions affected: *0.10.1* and *0.11.0a3*
OS: Archlinux
Kernel: *5.14.6-zen1-1-zen*

Log message I think is the most valuable: `[StreamFX] Unexpected exception in function '_create': Invalid argument.`

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.

**Comment by Xaymar** [comment]
The log file shows no bug, only a misconfiguration of the encoder on your hardware.
