### ISSUE TITLE
DynamicMask: add an additional source input and blend modes.

### ISSUE THREAD

**Issue by acorderob** [Xaymar/obs-StreamFX#656]
### Explain the Feature/Enhancement

Adding a second (optional) input source (with corresponding channels) and blend modes (at the very least, addition).

The use case i am interested in is just to add an animated border/frame to the webcam source, by blending the webcam with the border source using the mask as an alpha channel for the webcam and its reverse for the border source. This would make it unnecessary to create a scene just for this.

But this would also allow a lot more effects than that, and even blending more sources.

Or maybe this could be a different Blending filter instead of adding the functionality to the Dynamic Mask.

### What makes this feature/enhancement useful for StreamFX and its users?

StreamFX already has a number of effects filters and this would expand its capabilities. The Image Mask/Blend filter only allows for images and it is very limited.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
Dynamic Mask is complex enough as it is.

**Comment by Xaymar** [comment]
Are you willing to implement and maintain it? Otherwise it'll just sit here, as it is possible to implement this with the Shader filter already.

**Comment by Xaymar** [comment]
At the moment, you need to vertically or horizontally stack sources in a group and apply the filter to the group. 0.11 will have texture inputs for shaders.

**Comment by Xaymar** [comment]
You can now do this entirely within shaders. Closing since the feature request has been fulfilled through a different feature.
