### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by breezlebit** [Xaymar/obs-StreamFX#694]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.10.1

### OBS Studio Log

https://obsproject.com/logs/kYGQ8rI35lY-6DG_

### OBS Studio Crash Log

https://obsproject.com/logs/kYGQ8rI35lY-6DG_

### Current Behavior

Lagging then "encoder overload" then crash

### Expected Behavior

IT NOT TO CRASH

### Steps to Reproduce the Bug

STREAMING WITH OBS STUDIO

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
