### ISSUE TITLE
Transform3D does nothing after last release

### ISSUE THREAD

**Issue by willyk0** [Xaymar/obs-StreamFX#696]
### Operating System

MacOS 10.15 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0a7

### OBS Studio Log

https://obsproject.com/logs/xyYudxaBi54dOS_w

### OBS Studio Crash Log

09:42:44.855: ---------------------------------
09:42:44.856: ==== Startup complete ===============================================
09:42:44.873: All scene data cleared
09:42:44.873: ------------------------------------------------
09:42:44.924: Error compiling shader:
09:42:44.924: ERROR: 0:23: 'InputA' : syntax error: syntax error
09:42:44.924: 
09:42:44.924: 
09:42:44.924: device_pixelshader_create (GL) failed
09:42:44.924: Pass (0) <> missing pixel shader!
09:42:44.926: Error compiling shader:
09:42:44.926: ERROR: 0:23: 'InputA' : syntax error: syntax error
09:42:44.926: 
09:42:44.926: 
09:42:44.926: device_pixelshader_create (GL) failed
09:42:44.926: Pass (0) <> missing pixel shader!
09:42:44.927: Error compiling shader:
09:42:44.927: ERROR: 0:23: 'InputA' : syntax error: syntax error
09:42:44.927: 
09:42:44.927: 
09:42:44.927: device_pixelshader_create (GL) failed
09:42:44.927: Pass (0) <> missing pixel shader!
09:42:44.927: [StreamFX] Error loading '/Library/Application Support/obs-studio/plugins/StreamFX/data/effects/standard.effect' from disk: Unknown error during effect compile.
09:42:44.930: Error compiling shader:
09:42:44.930: ERROR: 0:27: 'InputA' : syntax error: syntax error
09:42:44.930: 
09:42:44.930: 
09:42:44.930: device_pixelshader_create (GL) failed
09:42:44.930: Pass (0) <> missing pixel shader!
09:42:44.930: [StreamFX] Error loading '/Library/Application Support/obs-studio/plugins/StreamFX/data/effects/transform.effect' from disk: Unknown error during effect compile.
09:42:44.930: Switched to scene 'Escena'
09:42:44.931: [adv-ss] trying to reconnect to  in 10 seconds.
09:42:44.931: ------------------------------------------------
09:42:44.931: Loaded scenes:
09:42:44.931: - scene 'Escena':
09:42:44.931:     - source: 'Daco_1509050.png' (image_source)
09:42:44.931:         - filter: 'Transformación 3D' (streamfx-filter-transform)
09:42:44.931: ------------------------------------------------

### Current Behavior

After updateing to 0.11.0a7, Transform3D does nothing, giving the errors I provided (the scene is a simple PNG for testing). Neither good old orthographic/perspective nor new Corner Pin, the image is not transformed at all. I can handle the knobs but nothing happens to the source.

### Expected Behavior

Image with transform :)

### Steps to Reproduce the Bug

Just installed 0.11a7 on my Mac.

### Any additional Information we need to know?

If I downgrade to 0.11.0a6 it works flawlessly (obvioulsy without Corner Pin feature). I tried updating again but first deleting plugin directory to ensure nothing old was interfering, but happens the same thing. 

My apologies if I missed something protocolary opening this issue, I'm a noob on github :)

![Captura de pantalla 2021-11-04 a las 9 58 47](https://user-images.githubusercontent.com/36780515/140285923-f5cf1e8e-996c-4cc6-8c0b-70dc6f420576.png)

**Comment by Xaymar** [comment]
There doesn't appear to be anything wrong with the shader files itself. Are you on the latest OS version available for your machine?

**Comment by willyk0** [comment]
Yes I am. As I said, previous versions work perfect, so I guess it's something added in this release.

**Comment by Xaymar** [comment]
Investigating this on Windows, which appears to run into this issue too. The OBS shader parser converts the shader to this:

```
#include "shared.effect"

uniform texture2D InputA<
	bool automatic = true;
>;
uniform texture2D InputB<
	bool automatic = true;
>;

 
 
 
 
 

float4 PSTexture(VertexData vtx) : TARGET {
	return InputA.Sample(BlankSampler, vtx.uv);
};

technique Draw
{
	pass
	{
		vertex_shader = DefaultVertexShader(vtx);
		pixel_shader = PSTexture(vtx);
	};
};
technique Texture
{
	pass
	{
		vertex_shader = DefaultVertexShader(vtx);
		pixel_shader = PSTexture(vtx);
	};
};

 
 
 
 
 

float4 PSTextureColor(VertexColorData vtx) : TARGET {
	return InputA.Sample(BlankSampler, vtx.uv) * vtx.clr;
};

technique TextureColor
{
	pass
	{
		vertex_shader = ColorVertexShader(vtx);
		pixel_shader = PSTextureColor(vtx);
	};
};

 
 
 
 
 

float4 PSTexturePremultiplied(VertexData vtx) : TARGET {
	float4 rgba = InputA.Sample(BlankSampler, vtx.uv);
	rgba.rgb /= rgba.a > (1. / 1024.) ? rgba.a : 1.0;
	return rgba;
};

technique DrawPremultiplied
{
	pass
	{
		vertex_shader = DefaultVertexShader(vtx);
		pixel_shader = PSTexturePremultiplied(vtx);
	};
};
technique TexturePremultiplied
{
	pass
	{
		vertex_shader = DefaultVertexShader(vtx);
		pixel_shader = PSTexturePremultiplied(vtx);
	};
};

 
 
 
 
 
 

float4 PSRestoreAlpha(VertexData vtx) : TARGET {
	float4 rgbx = InputA.Sample(BlankSampler, vtx.uv);
	float4 xxxa = InputB.Sample(BlankSampler, vtx.uv);
	rgbx.a = xxxa.a;
	return rgbx;
};

technique RestoreAlpha
{
	pass
	{
		vertex_shader = DefaultVertexShader(vtx);
		pixel_shader = PSRestoreAlpha(vtx);
	};
};

 
 
 
 

float4 PSColor(VertexColorData vtx) : TARGET {
	return vtx.clr;
};

technique Color
{
	pass
	{
		vertex_shader = ColorVertexShader(vtx);
		pixel_shader = PSColor(vtx);
	};
};
```

`#include` is not a valid preprocessor keyword, so I'll have to add my own preprocessor on top of the existing preprocessor to handle a line starting with `#include`. Or I duplicate a lot of code across many shaders.

**Comment by Xaymar** [comment]
A bit more digging reveals the culprit is libOBS-OpenGL which compares case sensitive: https://github.com/obsproject/obs-studio/blob/master/libobs-opengl/gl-shaderparser.c#L59-L92

This is probably a case of libOBS using an odd pseudo-HLSL and me forgetting about it entirely, expecting it to just be normal HLSL. At some point I really have to figure out Vulkan integration so this won't be an issue anymore.

**Comment by Xaymar** [comment]
Confirmed to be caused by `#include`.
