### ISSUE TITLE
Github update check dialogue: "Remember choice" button/checkbox

### ISSUE THREAD

**Issue by Sakata-MC** [Xaymar/obs-StreamFX#697]
### Explain the Feature/Enhancement

It'd be nice to not have the dialogue boxes pop up every start of OBS - I'd like to see a checkbox that reads something like "Remember my choice" and just have a dialogue if there is an actual update.

### What makes this feature/enhancement useful for StreamFX and its users?

It'd be part of the StreamFX code, but it'd be useful if OBS/PC crashes, to get back to streaming a few seconds faster.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
The update dialog is only shown if there is an actual update available, as it checks the remote version number against the local version number. As it is meant to annoy users to update their software, it will not be removed and no "Remember my Choice" checkbox will be added. Update or deal with it until the heat death of Github.

**Comment by Sakata-MC** [comment]
Does the update check actually do the update, or is it just an annoying
dialogue? It has appeared since first run seconds after download and had
persisted.
The dialogue just says that it is requesting to check for updates, days
absolutely nothing about an update being available.
I'll download latest again, and see if the dialogue is needlessly
displaying again.

**Comment by Xaymar** [comment]
Are you talking about the first run dialog that will be shown if you want to enable update checks by agreeing to GitHub's privacy policy? That one will also only be shown once, unless something is preventing writes to the appropriate configuration location.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
