### ISSUE TITLE
Found a typo in:  base.effect

### ISSUE THREAD

**Issue by skeletonbow** [Xaymar/obs-StreamFX#698]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

(Other)

### StreamFX Version

0.11.0a7

### OBS Studio Log

N/A

### Current Behavior

Found a typo in:  https://github.com/Xaymar/obs-StreamFX/blob/master/data/examples/shaders/base.effect

// e (Eulers Constant)
#define EULERS_CONSTANT 2,7182818284590452353602874713527

Comma present instead of a decimal point.   I don't know of any actual problems caused in SFX by it, I just happened to be reading the code and stumbled upon it so thought I should file a report as it could be an obscure hard to find bug.

### Expected Behavior

N/A

### Steps to Reproduce the Bug

N/A

**Comment by Xaymar** [comment]
I'm not sure if that constant is used by anything, but good spot.
