### ISSUE TITLE
Corner Pin for 3D Transform is not showing live the

### ISSUE THREAD

**Issue by juergenschubert** [Xaymar/obs-StreamFX#703]
### Operating System

MacOS 10.15 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0a8

### OBS Studio Log

no log as it is not crashing

### OBS Studio Crash Log

No crash it isi just not showing in the filter when I move the slider. Not while I change and nothing when I hit return

### Current Behavior

Opening a camera source an add the filter, choose the corner pin and started changing the values. Nothing is happening neither while I change nor after I hit return

### Expected Behavior

After changing the values I expect at east to see something happening

### Steps to Reproduce the Bug

Add new scene
Add new camera source
Filter for the new camera source
Add 3D Filer
Choose Corner Pin

started to change the values but nothing is happen in OBS on my screen

**Comment by Xaymar** [comment]
Please include a log file.

**Comment by Xaymar** [comment]
Turn off Mip-mapping. It's not supported on OpenGL.
