### ISSUE TITLE
Updating to newest test version resets all 3d transforms to corner pins breaking them

### ISSUE THREAD

**Issue by ItsJustJake** [Xaymar/obs-StreamFX#707]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0a8

### OBS Studio Log

Not needed

### Current Behavior

When updating to the newest test version all current perspective 3d transform effects have been changed to corner pin effects. This has wiped the settings that were saved previously 

### Expected Behavior

Corner pin would act as a new option for 3d transform and not replace current settings

### Steps to Reproduce the Bug

Set up an example scene with a perspective 3d transformation effect in a version before 0.11.0a7 and then update StreamFX to a version above 0.11.0a7 and the settings will be wiped and replaced with default corner pin settings.

**Comment by Xaymar** [comment]
This is fixed by #704 already.
