### ISSUE TITLE
Replace Me Or Have Your Request Closed

### ISSUE THREAD

**Issue by harizac** [Xaymar/obs-StreamFX#709]
### Explain the Feature/Enhancement

my source. Mirror canot blur

### What makes this feature/enhancement useful for StreamFX and its users?

- [ ] 

### Checklist

- [X] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
