### ISSUE TITLE
Request to use NVIDIA Real-Time Denoiser

### ISSUE THREAD

**Issue by varencilator** [Xaymar/obs-StreamFX#713]
### Explain the Feature/Enhancement

Honestly, not sure if it's possible but making a filter using NVIDIA Real-Time Denoiser (NRD)

https://developer.nvidia.com/nvidia-rt-denoiser

### What makes this feature/enhancement useful for StreamFX and its users?

Nvidia broadcast only works with RTX capable gpus but this says it works with DX11, 12, and Vulcan meaning pretty much any gpu can utilize it. I think.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
That is for ray-tracing, not generic video. StreamFX already includes a video denoiser from NVIDIA Maxine.

**Comment by Xaymar** [comment]
https://github.com/Xaymar/obs-StreamFX/wiki/Filter-Denoising

**Comment by Xaymar** [comment]
#### Rejected
The suggested feature is pointless, as OBS does not do any ray-tracing. A feature for generic video already exists as linked above.
