### ISSUE TITLE
StreamFX fails to start recording

### ISSUE THREAD

**Issue by JatickYT** [Xaymar/obs-StreamFX#714]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0a8

### OBS Studio Log

12:20:31.810: CPU Name: AMD FX(tm)-6300 Six-Core Processor              12:20:31.811: CPU Speed: 3763MHz 12:20:31.811: Physical Cores: 3, Logical Cores: 6 12:20:31.811: Physical Memory: 12287MB Total, 4696MB Free 12:20:31.811: Windows Version: 10.0 Build 19043 (release: 2009; revision: 1348; 64-bit) 12:20:31.811: Running as administrator: false 12:20:31.811: Aero is Enabled (Aero is always on for windows 8 and above) 12:20:31.811: Windows 10 Gaming Features: 12:20:31.811: 	Game DVR: On 12:20:31.814: Sec. Software Status: 12:20:31.816: 	Microsoft Defender Antivirus: enabled (AV) 12:20:31.817: 	Windows Firewall: disabled (FW) 12:20:31.818: Current Date/Time: 2021-11-21, 12:20:31 12:20:31.818: Browser Hardware Acceleration: true 12:20:31.818: Portable mode: false 12:20:32.184: OBS 27.1.3 (64-bit, windows) 12:20:32.184: --------------------------------- 12:20:32.242: --------------------------------- 12:20:32.242: audio settings reset: 12:20:32.242: 	samples per sec: 48000 12:20:32.242: 	speakers:        2 12:20:32.244: --------------------------------- 12:20:32.244: Initializing D3D11... 12:20:32.244: Available Video Adapters:  12:20:32.248: 	Adapter 0: Radeon RX 570 Series 12:20:32.248: 	  Dedicated VRAM: 4273434624 12:20:32.248: 	  Shared VRAM:    2147082240 12:20:32.248: 	  PCI ID:         1002:67df 12:20:32.248: 	  Driver Version: 30.0.13037.1003 12:20:32.248: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=59, name=MACROSILICON 12:20:32.253: Loading up D3D11 on adapter Radeon RX 570 Series (0) 12:20:32.311: D3D11 loaded successfully, feature level used: b000 12:20:32.311: DXGI increase maximum frame latency success 12:20:32.311: D3D11 GPU priority setup failed (not admin?) 12:20:33.060: --------------------------------- 12:20:33.060: video settings reset: 12:20:33.060: 	base resolution:   1920x1080 12:20:33.060: 	output resolution: 1920x1080 12:20:33.060: 	downscale filter:  Bicubic 12:20:33.060: 	fps:               30/1 12:20:33.060: 	format:            NV12 12:20:33.060: 	YUV mode:          709/Partial 12:20:33.061: NV12 texture support enabled 12:20:33.062: Audio monitoring device: 12:20:33.062: 	name: Default 12:20:33.062: 	id: default 12:20:33.062: --------------------------------- 12:20:33.062: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin 12:20:33.067: Failed to load 'en-GB' text for module: 'coreaudio-encoder.dll' 12:20:33.071: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded 12:20:33.072: Failed to load 'en-US' text for module: 'decklink-captions.dll' 12:20:33.073: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll' 12:20:33.189: [AMF] Querying Version failed, error code 1. 12:20:33.192: [AMF] AMF Test failed due to one or more errors. 12:20:33.192: Failed to initialize module 'enc-amf.dll' 12:20:33.205: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin 12:20:33.215: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin 12:20:33.216: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin 12:20:33.225: Failed to load 'en-GB' text for module: 'obs-browser.dll' 12:20:33.225: [obs-browser]: Version 2.16.3 12:20:33.225: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100 12:20:33.232: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found 12:20:33.236: Failed to load 'en-GB' text for module: 'obs-qsv11.dll' 12:20:33.770: Failed to load 'en-GB' text for module: 'obs-vst.dll' 12:20:33.772: Failed to load 'en-GB' text for module: 'obs-x264.dll' 12:20:33.775: Failed to load 'en-GB' text for module: 'rtmp-services.dll' 12:20:33.782: [StreamFX] Loading Version 0.11.0.0a8-g68877ee0 12:20:33.794: [StreamFX] <filter::autoframing> Failed to make NVIDIA providers available due to error: The specified module could not be found. 12:20:33.794:  12:20:33.794: [StreamFX] <filter::autoframing> All supported providers failed to initialize, disabling effect. 12:20:33.795: [StreamFX] <filter::video_denoising> Failed to make NVIDIA providers available due to error: The specified module could not be found. 12:20:33.795:  12:20:33.795: [StreamFX] <filter::video_denoising> All supported providers failed to initialize, disabling effect. 12:20:33.795: [StreamFX] <filter::video_superresolution> Failed to make NVIDIA Super-Resolution available due to error: The specified module could not be found. 12:20:33.795:  12:20:33.795: [StreamFX] <filter::video_superresolution> All supported Super-Resolution providers failed to initialize, disabling effect. 12:20:33.795: [StreamFX] <filter::virtual_greenscreen> Failed to make NVIDIA Greenscreen available due to error: The specified module could not be found. 12:20:33.795:  12:20:33.795: [StreamFX] <filter::virtual_greenscreen> All supported Virtual Greenscreen providers failed to initialize, disabling effect. 12:20:33.795: [StreamFX] Loaded Version 0.11.0.0a8-g68877ee0 12:20:33.801: Couldn't find VLC installation, VLC video source disabled 12:20:33.803: Failed to load 'en-GB' text for module: 'win-capture.dll' 12:20:33.809: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 12:20:33.811: No blackmagic support 12:20:33.820: Failed to load 'en-GB' text for module: 'win-wasapi.dll' 12:20:33.820: --------------------------------- 12:20:33.820:   Loaded Modules: 12:20:33.820:     win-wasapi.dll 12:20:33.820:     win-mf.dll 12:20:33.820:     win-dshow.dll 12:20:33.820:     win-decklink.dll 12:20:33.820:     win-capture.dll 12:20:33.820:     vlc-video.dll 12:20:33.820:     text-freetype2.dll 12:20:33.820:     StreamFX.dll 12:20:33.820:     rtmp-services.dll 12:20:33.820:     obs-x264.dll 12:20:33.820:     obs-vst.dll 12:20:33.820:     obs-transitions.dll 12:20:33.820:     obs-text.dll 12:20:33.821:     obs-qsv11.dll 12:20:33.821:     obs-outputs.dll 12:20:33.821:     obs-filters.dll 12:20:33.821:     obs-ffmpeg.dll 12:20:33.821:     obs-browser.dll 12:20:33.821:     image-source.dll 12:20:33.821:     frontend-tools.dll 12:20:33.821:     enc-amf.dll 12:20:33.821:     decklink-ouput-ui.dll 12:20:33.821:     decklink-captions.dll 12:20:33.821:     coreaudio-encoder.dll 12:20:33.821: --------------------------------- 12:20:33.821: ==== Startup complete =============================================== 12:20:33.834: All scene data cleared 12:20:33.834: ------------------------------------------------ 12:20:33.917: WASAPI: Device 'Headphones (High Definition Audio Device)' [48000 Hz] initialized 12:20:33.917: [Loaded global audio device]: 'Desktop Audio' 12:20:33.971: WASAPI: Device 'Microphone (High Definition Audio Device)' [44100 Hz] initialized 12:20:33.971: [noise suppress: 'Noise Suppression'] NVAFX redist is not installed. 12:20:33.972: [Loaded global audio device]: 'Mic/Aux' 12:20:33.972:     - filter: 'Noise Suppression' (noise_suppress_filter_v2) 12:20:33.972: [window-capture: 'Window Capture'] update settings: 12:20:33.972: 	executable: Teams.exe 12:20:33.972: 	method selected: Automatic 12:20:33.972: 	method chosen: WGC 12:20:33.972:  12:20:33.973: [duplicator-monitor-capture: 'Display Capture'] update settings: 12:20:33.973: 	display: 1 (1920x1080) 12:20:33.973: 	cursor: true 12:20:33.973: 	method: DXGI 12:20:34.008: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux) 12:20:34.008:  12:20:34.472: [duplicator-monitor-capture: 'Anime'] update settings: 12:20:34.472: 	display: 1 (1920x1080) 12:20:34.472: 	cursor: true 12:20:34.472: 	method: DXGI 12:20:34.473: Switched to scene 'Scene' 12:20:34.474: [game-capture: 'Game Capture'] attempting to hook process: javaw.exe 12:20:34.479: ------------------------------------------------ 12:20:34.479: Loaded scenes: 12:20:34.479: - scene 'Scene': 12:20:34.479:     - source: 'Game Capture' (game_capture) 12:20:34.479:     - source: 'Display Capture' (monitor_capture) 12:20:34.479:     - source: 'Anime' (monitor_capture) 12:20:34.479:     - source: 'Crab Game' (game_capture) 12:20:34.479:     - source: 'Window Capture' (window_capture) 12:20:34.479: ------------------------------------------------ 12:20:34.528: [game-capture: 'Game Capture'] gl shared texture capture successful 12:20:34.532: [game-capture: 'Game Capture'] shared texture capture successful 12:20:34.881: [StreamFX] <updater> Automatic checks at launch are now enabled. 12:20:36.554: [StreamFX] [h264_amf] Initializing... 12:20:36.554: [StreamFX] [h264_amf]   FFmpeg: 12:20:36.554: [StreamFX] [h264_amf]     Custom Settings:  12:20:36.554: [StreamFX] [h264_amf]     Standard Compliance: Normal 12:20:36.554: [StreamFX] [h264_amf]     Threading: Slice & Frame (with 1 threads) 12:20:36.554: [StreamFX] [h264_amf]   Video: 12:20:36.554: [StreamFX] [h264_amf]     Texture: 1920x1080 nv12 BT.709 tv 12:20:36.554: [StreamFX] [h264_amf]     Framerate: 30/1 (30.000000 FPS) 12:20:36.554: [StreamFX] [h264_amf]   Keyframes:  12:20:36.554: [StreamFX] [h264_amf]     Distance: 60 frames 12:20:36.554: [StreamFX] [h264_amf]   AMD AMF: 12:20:36.554: [StreamFX] [h264_amf]     Usage: transcoding <Default> 12:20:36.554: [StreamFX] [h264_amf]     Preset: balanced 12:20:36.554: [StreamFX] [h264_amf]     Rate Control: cbr 12:20:36.554: [StreamFX] [h264_amf]       Look-Ahead: Disabled <Default> 12:20:36.554: [StreamFX] [h264_amf]       Frame Skipping: Disabled <Default> 12:20:36.554: [StreamFX] [h264_amf]       Filler Data: Enabled 12:20:36.554: [StreamFX] [h264_amf]       Bitrate: 12:20:36.554: [StreamFX] [h264_amf]         Target: 6000000 bits/sec 12:20:36.554: [StreamFX] [h264_amf]         Maximum: 0 bits/sec <Default> 12:20:36.554: [StreamFX] [h264_amf]         Buffer: 12000000 bits 12:20:36.554: [StreamFX] [h264_amf]       Quantization Parameters: 12:20:36.554: [StreamFX] [h264_amf]         I-Frame: -1  <Default> 12:20:36.554: [StreamFX] [h264_amf]         P-Frame: -1  <Default> 12:20:36.554: [StreamFX] [h264_amf]     Other: 12:20:36.554: [StreamFX] [h264_amf]       Reference Frames: -1 Frames 12:20:36.554: [StreamFX] [h264_amf]       Enforce HRD: Disabled <Default> 12:20:36.554: [StreamFX] [h264_amf]       VBAQ: Disabled <Default> 12:20:36.554: [StreamFX] [h264_amf]       Access Unit Delimiter: Disabled <Default> 12:20:36.554: [StreamFX] [h264_amf]         Maximum Size: 0  <Default> 12:20:36.554: [StreamFX] [h264_amf]       Half-Pel Motion Estimation: Enabled <Default> 12:20:36.554: [StreamFX] [h264_amf]       Quarter-Pel Motion Estimation: Enabled <Default> 12:20:36.554: [StreamFX] [h264_amf]     H.264/AVC: 12:20:36.555: [StreamFX] [h264_amf]       Profile: constrained_baseline 12:20:36.555: [StreamFX] [h264_amf]       Level: auto <Default> 12:20:36.557: [StreamFX] [h264_amf] Initializing... 12:20:36.557: [StreamFX] [h264_amf]   FFmpeg: 12:20:36.557: [StreamFX] [h264_amf]     Custom Settings:  12:20:36.557: [StreamFX] [h264_amf]     Standard Compliance: Normal 12:20:36.557: [StreamFX] [h264_amf]     Threading: None (with 1 threads) 12:20:36.557: [StreamFX] [h264_amf]   Video: 12:20:36.557: [StreamFX] [h264_amf]     Input: 1920x1080 nv12 BT.709 Partial 12:20:36.557: [StreamFX] [h264_amf]     Output: 1920x1080 nv12 BT.709 Partial 12:20:36.557: [StreamFX] [h264_amf]     On GPU Index: -1 12:20:36.557: [StreamFX] [h264_amf]     Framerate: 30/1 (30.000000 FPS) 12:20:36.557: [StreamFX] [h264_amf]   Keyframes:  12:20:36.557: [StreamFX] [h264_amf]     Distance: 60 frames 12:20:36.557: [StreamFX] [h264_amf]   AMD AMF: 12:20:36.557: [StreamFX] [h264_amf]     Usage: transcoding <Default> 12:20:36.557: [StreamFX] [h264_amf]     Preset: balanced 12:20:36.557: [StreamFX] [h264_amf]     Rate Control: cbr 12:20:36.557: [StreamFX] [h264_amf]       Look-Ahead: Disabled <Default> 12:20:36.557: [StreamFX] [h264_amf]       Frame Skipping: Disabled <Default> 12:20:36.557: [StreamFX] [h264_amf]       Filler Data: Enabled 12:20:36.557: [StreamFX] [h264_amf]       Bitrate: 12:20:36.557: [StreamFX] [h264_amf]         Target: 6000000 bits/sec 12:20:36.557: [StreamFX] [h264_amf]         Maximum: 0 bits/sec <Default> 12:20:36.558: [StreamFX] [h264_amf]         Buffer: 12000000 bits 12:20:36.558: [StreamFX] [h264_amf]       Quantization Parameters: 12:20:36.558: [StreamFX] [h264_amf]         I-Frame: -1  <Default> 12:20:36.558: [StreamFX] [h264_amf]         P-Frame: -1  <Default> 12:20:36.558: [StreamFX] [h264_amf]     Other: 12:20:36.558: [StreamFX] [h264_amf]       Reference Frames: -1 Frames 12:20:36.558: [StreamFX] [h264_amf]       Enforce HRD: Disabled <Default> 12:20:36.558: [StreamFX] [h264_amf]       VBAQ: Disabled <Default> 12:20:36.558: [StreamFX] [h264_amf]       Access Unit Delimiter: Disabled <Default> 12:20:36.558: [StreamFX] [h264_amf]         Maximum Size: 0  <Default> 12:20:36.558: [StreamFX] [h264_amf]       Half-Pel Motion Estimation: Enabled <Default> 12:20:36.558: [StreamFX] [h264_amf]       Quarter-Pel Motion Estimation: Enabled <Default> 12:20:36.558: [StreamFX] [h264_amf]     H.264/AVC: 12:20:36.558: [StreamFX] [h264_amf]       Profile: constrained_baseline 12:20:36.558: [StreamFX] [h264_amf]       Level: auto <Default> 12:20:36.559: [StreamFX] Unexpected exception in function '_create': Unknown error occurred. 12:20:37.904: ==== Shutting down ================================================== 12:20:37.912: [game-capture: 'Game Capture'] capture stopped 12:20:37.913: WASAPI: Device 'Headphones (High Definition Audio Device)' Terminated 12:20:37.917: WASAPI: Device 'Microphone (High Definition Audio Device)' Terminated 12:20:37.922: All scene data cleared 12:20:37.922: ------------------------------------------------ 12:20:38.086: [StreamFX] Unloading Version 0.11.0.0a8-g68877ee0 12:20:38.094: [StreamFX] Unloaded Version 0.11.0.0a8-g68877ee0 12:20:38.097: [Scripting] Total detached callbacks: 0 12:20:38.097: Freeing OBS context data 12:20:38.111: == Profiler Results ============================= 12:20:38.111: run_program_init: 3031.1 ms 12:20:38.111:  ┣OBSApp::AppInit: 29.029 ms 12:20:38.111:  ┃ ┗OBSApp::InitLocale: 4.132 ms 12:20:38.111:  ┗OBSApp::OBSInit: 2977.92 ms 12:20:38.111:    ┣obs_startup: 7.31 ms 12:20:38.111:    ┗OBSBasic::OBSInit: 2546.98 ms 12:20:38.111:      ┣OBSBasic::InitBasicConfig: 1.002 ms 12:20:38.111:      ┣OBSBasic::ResetAudio: 0.255 ms 12:20:38.111:      ┣OBSBasic::ResetVideo: 819.071 ms 12:20:38.111:      ┣OBSBasic::InitOBSCallbacks: 0.009 ms 12:20:38.111:      ┣OBSBasic::InitHotkeys: 0.057 ms 12:20:38.111:      ┣obs_load_all_modules: 758.44 ms 12:20:38.111:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 3.839 ms 12:20:38.111:      ┃ ┣obs_init_module(decklink-captions.dll): 0.032 ms 12:20:38.111:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 0.834 ms 12:20:38.111:      ┃ ┣obs_init_module(enc-amf.dll): 115.063 ms 12:20:38.111:      ┃ ┣obs_init_module(frontend-tools.dll): 6.759 ms 12:20:38.111:      ┃ ┣obs_init_module(image-source.dll): 0.01 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-browser.dll): 0.467 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 0.545 ms 12:20:38.111:      ┃ ┃ ┗nvenc_check: 0.522 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-filters.dll): 0.073 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-outputs.dll): 0.012 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-qsv11.dll): 525.241 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-text.dll): 0.351 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-transitions.dll): 0.011 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-vst.dll): 0.003 ms 12:20:38.111:      ┃ ┣obs_init_module(obs-x264.dll): 0.003 ms 12:20:38.111:      ┃ ┣obs_init_module(rtmp-services.dll): 2.241 ms 12:20:38.112:      ┃ ┣obs_init_module(StreamFX.dll): 13.235 ms 12:20:38.112:      ┃ ┣obs_init_module(text-freetype2.dll): 0.105 ms 12:20:38.112:      ┃ ┣obs_init_module(vlc-video.dll): 0.09 ms 12:20:38.112:      ┃ ┣obs_init_module(win-capture.dll): 2.184 ms 12:20:38.112:      ┃ ┣obs_init_module(win-decklink.dll): 3.407 ms 12:20:38.112:      ┃ ┣obs_init_module(win-dshow.dll): 3.133 ms 12:20:38.112:      ┃ ┣obs_init_module(win-mf.dll): 0 ms 12:20:38.112:      ┃ ┣obs_init_module(win-wasapi.dll): 0.096 ms 12:20:38.112:      ┃ ┗reset_win32_symbol_paths: 0.322 ms 12:20:38.112:      ┣OBSBasic::ResetOutputs: 2.929 ms 12:20:38.112:      ┣OBSBasic::CreateHotkeys: 0.375 ms 12:20:38.112:      ┣OBSBasic::InitService: 2.734 ms 12:20:38.112:      ┣OBSBasic::InitPrimitives: 1.122 ms 12:20:38.112:      ┗OBSBasic::Load: 663.071 ms 12:20:38.112: obs_hotkey_thread(25 ms): min=0.006 ms, median=0.011 ms, max=1.249 ms, 99th percentile=0.594 ms, 100% below 25 ms 12:20:38.112: audio_thread(Audio): min=0 ms, median=0.089 ms, max=1.883 ms, 99th percentile=0.506 ms 12:20:38.112: obs_graphics_thread(33.3333 ms): min=0.049 ms, median=0.668 ms, max=475.674 ms, 99th percentile=36.978 ms, 98.5401% below 33.333 ms 12:20:38.112:  ┣tick_sources: min=0.001 ms, median=0.022 ms, max=475.59 ms, 99th percentile=5.758 ms 12:20:38.112:  ┣output_frame: min=0.039 ms, median=0.212 ms, max=3.339 ms, 99th percentile=1.792 ms 12:20:38.112:  ┃ ┗gs_context(video->graphics): min=0.039 ms, median=0.212 ms, max=3.339 ms, 99th percentile=1.792 ms 12:20:38.112:  ┃   ┣render_video: min=0.008 ms, median=0.041 ms, max=0.258 ms, 99th percentile=0.141 ms 12:20:38.112:  ┃   ┃ ┗render_main_texture: min=0.004 ms, median=0.037 ms, max=0.254 ms, 99th percentile=0.136 ms 12:20:38.112:  ┃   ┗gs_flush: min=0.026 ms, median=0.168 ms, max=1.758 ms, 99th percentile=0.628 ms 12:20:38.112:  ┗render_displays: min=0 ms, median=0.401 ms, max=36.715 ms, 99th percentile=22.444 ms 12:20:38.112: ================================================= 12:20:38.112: == Profiler Time Between Calls ================== 12:20:38.112: obs_hotkey_thread(25 ms): min=24.244 ms, median=25.973 ms, max=27.186 ms, 38.2716% within ±2% of 25 ms (0.411523% lower, 61.3169% higher) 12:20:38.112: obs_graphics_thread(33.3333 ms): min=16.712 ms, median=33.333 ms, max=475.679 ms, 93.3824% within ±2% of 33.333 ms (2.94118% lower, 3.67647% higher) 12:20:38.112: ================================================= 12:20:38.117: Number of memory leaks: 0

### Current Behavior

I put the recording encoder as the AMD AMF H.264/AVC, then tried to start recording but it came up with the error shown in the picture, even though I just updated my AMD drivers to the latest ones.
![image](https://user-images.githubusercontent.com/78139018/142758151-6837614a-1deb-4bf4-9eb5-de6dc0915f05.png)

### Expected Behavior

I expected it to start recording normally.

### Steps to Reproduce the Bug

I cannot really tell how since I don't understand what the issue is in the first place

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
