### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by andreashe** [Xaymar/obs-StreamFX#750]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

no crash

### Current Behavior

The about dialog never goes away. It creates the config file with this content:

{"UI.HaveShownAboutStreamFX":true,"Version":34359803904}

But it shows it on each startup.

Using Windows 10.

### Expected Behavior

Check the config file and do not show popup again.

### Steps to Reproduce the Bug

use Windows?

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.

**Comment by Xaymar** [comment]
Something on your system is preventing writing an updated configuration file, as evidenced by your config file having the version `0.8.1.0`.
