### ISSUE TITLE
Shader Problem

### ISSUE THREAD

**Issue by Bonboon229** [Xaymar/obs-StreamFX#751]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.10.1

### OBS Studio Log

09:16:28.564: CPU Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
09:16:28.564: CPU Speed: 3392MHz
09:16:28.564: Physical Cores: 4, Logical Cores: 8
09:16:28.564: Physical Memory: 8146MB Total, 4492MB Free
09:16:28.564: Windows Version: 10.0 Build 19043 (release: 2009; revision: 1348; 64-bit)
09:16:28.564: Running as administrator: true
09:16:28.565: Aero is Enabled (Aero is always on for windows 8 and above)
09:16:28.565: Windows 10 Gaming Features:
09:16:28.565: 	Game DVR: On
09:16:28.566: Sec. Software Status:
09:16:28.567: 	Microsoft Defender Antivirus: enabled (AV)
09:16:28.567: 	Windows Firewall: enabled (FW)
09:16:28.568: Current Date/Time: 2021-12-18, 09:16:28
09:16:28.568: Browser Hardware Acceleration: true
09:16:28.568: Portable mode: false
09:16:28.729: OBS 27.1.3 (64-bit, windows)
09:16:28.729: ---------------------------------
09:16:28.730: ---------------------------------
09:16:28.730: audio settings reset:
09:16:28.730: 	samples per sec: 48000
09:16:28.730: 	speakers:        2
09:16:28.731: ---------------------------------
09:16:28.731: Initializing D3D11...
09:16:28.731: Available Video Adapters: 
09:16:28.733: 	Adapter 0: NVIDIA Quadro K2000
09:16:28.734: 	  Dedicated VRAM: 2116747264
09:16:28.734: 	  Shared VRAM:    4271077376
09:16:28.734: 	  PCI ID:         10de:ffe
09:16:28.734: 	  Driver Version: 23.21.13.8816
09:16:28.734: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=VA2447-FHD
09:16:28.736: Loading up D3D11 on adapter NVIDIA Quadro K2000 (0)
09:16:28.779: D3D11 loaded successfully, feature level used: b000
09:16:28.779: DXGI increase maximum frame latency success
09:16:28.790: D3D11 GPU priority setup success
09:16:29.234: ---------------------------------
09:16:29.234: video settings reset:
09:16:29.234: 	base resolution:   1280x720
09:16:29.234: 	output resolution: 1280x720
09:16:29.234: 	downscale filter:  Bicubic
09:16:29.234: 	fps:               30/1
09:16:29.234: 	format:            NV12
09:16:29.234: 	YUV mode:          709/Partial
09:16:29.234: NV12 texture support enabled
09:16:29.235: Audio monitoring device:
09:16:29.235: 	name: Default
09:16:29.235: 	id: default
09:16:29.235: ---------------------------------
09:16:29.235: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
09:16:29.239: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
09:16:29.239: Failed to load 'en-US' text for module: 'decklink-captions.dll'
09:16:29.240: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
09:16:29.279: [AMF] Unable to load 'amfrt64.dll', error code 126.
09:16:29.280: [AMF] AMF Test failed due to one or more errors.
09:16:29.280: Failed to initialize module 'enc-amf.dll'
09:16:29.288: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
09:16:29.292: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
09:16:29.293: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
09:16:29.296: [obs-browser]: Version 2.16.3
09:16:29.296: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
09:16:29.299: NVENC supported
09:16:29.300: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
09:16:29.368: [StreamFX] Loading Version 0.10.1.0-gc8484f65
09:16:29.374: [StreamFX] <NVIDIA Face Tracking Filter> Failed to load 'cuDevicePrimaryCtxRelease' from 'nvcuda.dll'.
09:16:29.374: [StreamFX] Loaded Version 0.10.1.0-gc8484f65
09:16:29.375: Couldn't find VLC installation, VLC video source disabled
09:16:29.382: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
09:16:29.383: No blackmagic support
09:16:29.387: ---------------------------------
09:16:29.387:   Loaded Modules:
09:16:29.387:     win-wasapi.dll
09:16:29.387:     win-mf.dll
09:16:29.387:     win-dshow.dll
09:16:29.387:     win-decklink.dll
09:16:29.387:     win-capture.dll
09:16:29.387:     vlc-video.dll
09:16:29.387:     text-freetype2.dll
09:16:29.387:     StreamFX.dll
09:16:29.387:     rtmp-services.dll
09:16:29.387:     obs_shaderfilter_plus_windows_x64.dll
09:16:29.387:     obs-x264.dll
09:16:29.387:     obs-vst.dll
09:16:29.387:     obs-transitions.dll
09:16:29.387:     obs-text.dll
09:16:29.387:     obs-qsv11.dll
09:16:29.387:     obs-outputs.dll
09:16:29.387:     obs-filters.dll
09:16:29.387:     obs-ffmpeg.dll
09:16:29.387:     obs-browser.dll
09:16:29.387:     image-source.dll
09:16:29.387:     frontend-tools.dll
09:16:29.387:     enc-amf.dll
09:16:29.387:     decklink-ouput-ui.dll
09:16:29.387:     decklink-captions.dll
09:16:29.387:     coreaudio-encoder.dll
09:16:29.387: ---------------------------------
09:16:29.387: ==== Startup complete ===============================================
09:16:29.394: All scene data cleared
09:16:29.394: ------------------------------------------------
09:16:29.449: WASAPI: Device 'VA2447-FHD (NVIDIA High Definition Audio)' [48000 Hz] initialized
09:16:29.449: [Loaded global audio device]: 'Desktop Audio'
09:16:29.479: WASAPI: Device 'Microphone (Razer Seiren Mini)' [48000 Hz] initialized
09:16:29.479: [noise suppress: 'Noise Suppression'] NVAFX redist is not installed.
09:16:29.479: [Loaded global audio device]: 'Mic/Aux'
09:16:29.479:     - filter: 'Noise Suppression' (noise_suppress_filter_v2)
09:16:29.480: [duplicator-monitor-capture: 'Display Capture'] update settings:
09:16:29.480: 	display: 1 (1920x1080)
09:16:29.480: 	cursor: false
09:16:29.480: 	method: DXGI
09:16:29.525: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
09:16:29.525: 
09:16:29.808: Switched to scene 'Scene'
09:16:29.812: device_pixelshader_create (D3D11): Compiler warnings/errors for C:/Users/Goji Goodra/Documents/Shaders/sunset.glsl (Pixel shader, technique Draw, pass 0):
09:16:29.812: C:\Users\Goji Goodra\Documents\Shaders\sunset.glsl (Pixel shader, technique Draw, pass 0)(10,12-26): error X3004: undeclared identifier 'render'
09:16:29.812: 
09:16:29.812: Pass (0) <> missing pixel shader!
09:16:29.813: ------------------------------------------------
09:16:29.813: Loaded scenes:
09:16:29.813: - scene 'Scene':
09:16:29.814:     - source: 'MDS' (game_capture)
09:16:29.814:     - source: 'MGBA' (game_capture)
09:16:29.814:         - filter: 'Shader' (streamfx-filter-shader)
09:16:29.814:     - source: 'Display Capture' (monitor_capture)
09:16:29.814:         - filter: 'Shader' (obs-shaderfilter-plus)
09:16:29.814: ------------------------------------------------
09:16:35.770: [duplicator-monitor-capture: 'Display Capture'] update settings:
09:16:35.770: 	display: 1 (1920x1080)
09:16:35.770: 	cursor: false
09:16:35.770: 	method: DXGI
09:16:44.163: User removed filter 'Shader' (obs-shaderfilter-plus) from source 'Display Capture'
09:16:48.858: User added filter 'Shader' (streamfx-filter-shader) to source 'Display Capture'
09:17:02.071: gs_effect_loop: Technique 'Draw' not found.
09:17:02.103: gs_effect_loop: Technique 'Draw' not found.
09:17:02.137: gs_effect_loop: Technique 'Draw' not found.
09:17:02.170: gs_effect_loop: Technique 'Draw' not found.
09:17:02.203: gs_effect_loop: Technique 'Draw' not found.
09:17:02.237: gs_effect_loop: Technique 'Draw' not found.
09:17:02.270: gs_effect_loop: Technique 'Draw' not found.
09:17:02.303: gs_effect_loop: Technique 'Draw' not found.
09:17:02.337: gs_effect_loop: Technique 'Draw' not found.
09:17:02.370: gs_effect_loop: Technique 'Draw' not found.
09:17:02.404: gs_effect_loop: Technique 'Draw' not found.
09:17:02.437: gs_effect_loop: Technique 'Draw' not found.
09:17:02.470: gs_effect_loop: Technique 'Draw' not found.
09:17:02.504: gs_effect_loop: Technique 'Draw' not found.
09:17:02.537: gs_effect_loop: Technique 'Draw' not found.
09:17:02.570: gs_effect_loop: Technique 'Draw' not found.
09:17:02.604: gs_effect_loop: Technique 'Draw' not found.
09:17:02.637: gs_effect_loop: Technique 'Draw' not found.
09:17:02.670: gs_effect_loop: Technique 'Draw' not found.
09:17:02.703: gs_effect_loop: Technique 'Draw' not found.
09:17:02.737: gs_effect_loop: Technique 'Draw' not found.
09:17:02.770: gs_effect_loop: Technique 'Draw' not found.
09:17:02.803: gs_effect_loop: Technique 'Draw' not found.
09:17:02.837: gs_effect_loop: Technique 'Draw' not found.
09:17:02.870: gs_effect_loop: Technique 'Draw' not found.
09:17:02.903: gs_effect_loop: Technique 'Draw' not found.
09:17:02.937: gs_effect_loop: Technique 'Draw' not found.
09:17:02.970: gs_effect_loop: Technique 'Draw' not found.
09:17:03.003: gs_effect_loop: Technique 'Draw' not found.
09:17:03.037: gs_effect_loop: Technique 'Draw' not found.
09:17:03.071: gs_effect_loop: Technique 'Draw' not found.

### Current Behavior

Black screen on OBS when shader filter was used. Problem went away when shader Filter was removed.

### Expected Behavior

Filter should have been applied normally.

### Steps to Reproduce the Bug

Use any type of shader. Shader I used was a GLSL Shader.

**Comment by Xaymar** [comment]
The Shader filter requires that you actually write a shader that fulfills the requirements of a shader compatible with the Shader filter. See the Manual for further information.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
