### ISSUE TITLE
Request: Add new AMD AMF Auto LTR encoder mode introduced in AMF 1.4.23 and 21.12.1 gpu driver

### ISSUE THREAD

**Issue by gutko** [Xaymar/obs-StreamFX#753]
### Explain the Feature/Enhancement

Long-Term Reference frames can improve visual quality of encoded content and save the transfer bandwidth

Explanation of LTR on Intel website
https://www.intel.com/content/www/us/en/developer/articles/technical/improve-encoding-efficiency-and-video-quality-with-adaptive-ltr.html

### What makes this feature/enhancement useful for StreamFX and its users?

Improved visual quality of encoded (recorded) material and reduced size of recording

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

### Any additional Information we need to know?

From https://github.com/GPUOpen-LibrariesAndSDKs/AMF :

Version 1.4.23: AMD Radeon Software Adrenalin Edition 21.12.1 (21.40.11.03) or newer. Added new Auto LTR encoder mode, additional encoder usage presets and encoder statistics/feedback.

**Comment by Xaymar** [comment]
##### Rejected
StreamFX relies on FFmpeg for the encoder integration of AMF, NVENC and ProRES. As it is right now, such a feature has not been added to FFmpeg, and as such can't be exposed in the UI.

**Comment by tal0nmallorca** [comment]
Can you post please a full listt of options I can put in the custom settings line for AMD 6700XT driver 21.10.2.

Thank you!! Awwesome work!

**Comment by tal0nmallorca** [comment]
> Can you post please a full listt of options I can put in the custom settings line of your AMD AMF via ffmpeg plugin for OBS.
> 
> I am using AMD 6700XT driver 21.10.2.
> 
> Thank you!! Awwesome work!

Please, help me, I can not find this information, two weeks from now searching.

Thanks for your awesome work.
