### ISSUE TITLE
Preset settings?

### ISSUE THREAD

**Issue by Pimmal** [Xaymar/obs-StreamFX#754]
### Explain the Feature/Enhancement

Hey i´m using https://github.com/sorayuki/obs-multi-rtmp for multistreaming, and if i select a encoder i have a lot if ffmpeg settings (example: NVIDIA NVENC H.246 encoder nvenc_h264 via ffmpeg) from StreamFX.
How can i see which settings are used in these presets?

### What makes this feature/enhancement useful for StreamFX and its users?

Hey i´m using https://github.com/sorayuki/obs-multi-rtmp for multistreaming, and if i select a encoder i have a lot if ffmpeg settings (example: NVIDIA NVENC H.246 encoder nvenc_h264 via ffmpeg) from StreamFX.
How can i see which settings are used in these presets?

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
Please don't abuse the Issue tracker for support or questions. It explicitly linked you to alternative ways to ask questions, which you intentionally ignored. Additonally, the wiki explains all settings to the best of the community's ability, for the rest you'll have to look into FFmpeg.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
