### ISSUE TITLE
Wrong color format when RGB selected

### ISSUE THREAD

**Issue by qo4on** [Xaymar/obs-StreamFX#755]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

https://obsproject.com/logs/TnO4fPtxzxgU9kDf

### Current Behavior

In your [article about nvenc](https://blog.xaymar.com/guides/high-quality-recordings/nvidia-nvenc/) you said that it is better to use these settings for lossless results:
![image](https://user-images.githubusercontent.com/35609308/147396984-bfb3fab9-cec9-48df-b912-051fad4fb48c.png)
But these settings combined with nvenc_hevc return `yuvj420p(pc, bt709/bt709/iec61966-2-1)`. Chroma subsampling changes from 444 to 420.

### Expected Behavior

These settings should return 8-bit 444. A good solution would be to add ffmpeg command before the codec to fix the issue:
```
-vf scale=out_color_matrix=bt709,format=yuv444p
```

Besides, you were wrong when you said that exact true lossless was not possible. It is possible. Take some 8-bit png images and convert them to video:
```
ffmpeg -y -r 60 -i %01d.png -vf scale=out_color_matrix=bt709,format=yuv444p10le -c:v hevc_nvenc -tune lossless out.mov
```
Then back to images:
```
ffmpeg -i out.mov -vf scale=in_color_matrix=bt709,format=rgb24 img/out-%03d.png
```
After that compare the results:
```
ffmpeg -i img/out-%03d.png -i %01d.png -filter_complex ssim -f null -
```
You will see that the final images are exactly the same as the original images.

### Steps to Reproduce the Bug

Set the above settings and record the screen.

**Comment by Xaymar** [comment]
The log file you provided shows correct behavior on every step of the way. `bgr0` is the least lossy conversion from `rgba`, and as such was provided to NVENC as `bgr0`. What NVENC does from then out is not StreamFX's problem or responsibility - if you wanted YUV 4:4:4 you should have selected YUV 4:4:4 in OBS.

> A good solution would be to add ffmpeg command before the codec to fix the issue:

StreamFX does not use FFmpeg command line, but the library, and it already uses `swscale` to convert between `rgba` and `bgr0` as expected. Which is what you've literally told it to do in your own configuration, which you uploaded in a log file.

> Besides, you were wrong when you said that exact true lossless was not possible. It is possible. Take some 8-bit png images and convert them to video:

No, as written in the article it is still correct. True Lossless is not possible within H.264 and H.265, up until the recent addition of RGB plane support which NVENC does not support in current hardware. You've even proven it yourself that True Lossless isn't possible, as your own answer requires you to go up to 10 bits per pixel to remain similar. RGB to YUV conversion has aliasing, motion estimation has aliasing, and even quantization has aliasing. You can get extremely close to the point it doesn't matter, but you're never at True Lossless.

**Comment by Xaymar** [comment]
https://github.com/Xaymar/obs-StreamFX/blob/master/source/encoders/encoder-ffmpeg.cpp#L434-L482

The source code matches the log file output, thus there is no actual bug here. It found the correct least lossy conversion format and flagged it according to the information given. What FFmpeg and NVENC do with this information is not StreamFX's responsibility. Closing as false positive.

**Comment by qo4on** [comment]
> StreamFX does not use FFmpeg command line, but the library, and it already uses `swscale` to convert between `rgba` and `bgr0` as expected. Which is what you've literally told it to do in your own configuration, which you uploaded in a log file.

How can I change StreamFX's `swscale` from `bgr0` to `yuv444p10le`?

**Comment by Xaymar** [comment]
You don't, that's the point. If you select RGBA in OBS Studio, it will pass something as close to RGBA into the encoder. Since `yuv444p10le` is more lossy than `bgr0` is, it was automatically picked. If you wanted `yuv444`, you'd have selected `I444` in OBS Studio.

**Comment by qo4on** [comment]
> Since `yuv444p10le` is more lossy than `bgr0`

Are you sure? When I try to encode with `nvenc_hevc` to `bgr0` I get `yuvj420p`, which is more lossy than `yuv444p10le`.

**Comment by Xaymar** [comment]
Yes, I am sure. Swapping the byte order is less lossy than attempting to convert colors in limited space between color spaces, no matter how many bits the output has. `bgr0` requires zero conversion, just swapping bytes around, while `yuv444p` and `yuv444p10le` require color conversion - and are correctly marked by avcodec as worse options.

**Comment by qo4on** [comment]
You are right, `bgr0` requires zero conversion (`rgb` to `rgb`, not `rgb` to `yuv`). But also `bgr0` changes the pixel format from `444` to `420`. You are confusing `bgr0` with `gbrp` or `rgb24`, [take a look at comment:2 by Carl Eugen Hoyos](https://trac.ffmpeg.org/ticket/8635#comment:2).
For example, this thing returns `gbrp`, that requires zero conversion:
```
ffmpeg -y -r 60 -i %01d.png -c:v libx265 -x265-params lossless=1 out.mov
Video: hevc (hev1 / 0x31766568), gbrp(pc, gbr/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 15360 tbn

ffprobe out.mov
Video: hevc (Rext) (hev1 / 0x31766568), gbrp(pc, gbr/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 34808 kb/s, 60 fps, 60 tbr, 15360 tbn, 60 tbc (default)
```
But `nvenc` uses `bgr0`, that implies conversion from `444` to `420`:
```
ffmpeg -y -r 60 -i %01d.png -c:v hevc_nvenc -tune lossless out.mov
Video: hevc (Main) (hev1 / 0x31766568), rgb0(pc, gbr/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 2000 kb/s, 60 fps, 15360 tbn

ffprobe out.mov
Video: hevc (Main) (hev1 / 0x31766568), yuvj420p(pc, gbr/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23721 kb/s, 60 fps, 60 tbr, 15360 tbn, 60 tbc (default)
```
`420` is by definition more lossy than `444`.

**Comment by Xaymar** [comment]
The definition of `bgr0` is a 32-bit wide format with the following data in the order listed here: Blue, Green, Red, Zero. Alpha is dropped, as it is not useful for encoding anything, and StreamFX correctly drops it. This requires zero conversion, and as such is the correct choice here. Your own link even proves this, yet you keep arguing against your own provided information.

If you want YUV 4:4:4 from NVENC, you will actually have to specify I444 in OBS Studio. Anything else is correct behavior, and working as expected.

**Comment by qo4on** [comment]
I didn't make myself clear, sorry. In fact, we're talking about the same thing. NVENC does not support RGB output. So, when NVENC gets RGB input it outputs [`yuvj420p`](https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/pixfmt.h#L78), not `bgr0`.

Yes, we can fix it by specifying `I444` in OBS Studio. In this case we get an [`rgb-yuv` conversion rounding error](https://forum.videohelp.com/threads/399846-Not-able-to-change-any-advanced-video-playback-settings-in-VLC-or-Potplayer?highlight=rgb+yuv+cube#post2603522).

And technically, what NVENC does is not StreamFX's responsibility. But we can fix this conversion rounding error by simply stretching `yuv444p` to `yuv444p10le` before sending it to NVENC. So you can write that StreamFX provides true lossless, low bitrate, low CPU usage screen captures for all owners of nVidia GPUs starting with the Pascal GeForce 10 series.

My tests show mathematically lossless results when `nvenc_hevc` has `yuv444p10le` input. The bitrate starts from `50 Mb/s` for simple graphics to `600 Mb/s` for `1080p` gameplay capture.
```
ffmpeg -i img/out-%03d.png -i %01d.png -filter_complex ssim -f null -
SSIM R:1.000000 (inf) G:1.000000 (inf) B:1.000000 (inf) All:1.000000 (inf)
```

**Comment by Xaymar** [comment]
There's still nothing to fix, or nothing to work-around in StreamFX. StreamFX behaves correctly, FFmpeg behaves correctly, NVENC is misbehaving. You either select `I444`, or you deal with the result you get from `RGBA` and live with it. Alternatively, create your own fork, maintain it, and do whatever you want - it's open source.

**Comment by qo4on** [comment]
> Also note that by upcasting to 10 bits per channel, you only avoid aliasing. This does not make it lossless

Could you please share an 8-bit rgb image that cannot be encoded losslessly with my settings? I believe such images do not exist.

**Comment by Xaymar** [comment]
Would you kindly read the entirety of what I said? Instead of just what fits your narrative? It appears that the answer to that is no, so I am locking this issue. If you open a new issue for this, I will block you from submitting anything to this repository.
