### ISSUE TITLE
AV1 does not record properly to file.

### ISSUE THREAD

**Issue by Bits360** [Xaymar/obs-StreamFX#757]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

11:34:10.017: CPU Name: AMD Ryzen 9 3900X 12-Core Processor             11:34:10.017: CPU Speed: 3800MHz 11:34:10.017: Physical Cores: 12, Logical Cores: 24 11:34:10.017: Physical Memory: 16288MB Total, 7325MB Free 11:34:10.017: Windows Version: 10.0 Build 19043 (release: 2009; revision: 1415; 64-bit) 11:34:10.017: Running as administrator: false 11:34:10.017: Aero is Enabled (Aero is always on for windows 8 and above) 11:34:10.017: Windows 10 Gaming Features: 11:34:10.017: 	Game Bar: Off 11:34:10.017: 	Game DVR: Off 11:34:10.017: 	Game DVR Background Recording: Off 11:34:10.017: 	Game Mode: On 11:34:10.031: 	Hardware GPU Scheduler: On 11:34:10.033: Sec. Software Status: 11:34:10.033: 	Microsoft Defender Antivirus: enabled (AV) 11:34:10.034: 	Windows Firewall: enabled (FW) 11:34:10.034: Current Date/Time: 2021-12-28, 11:34:10 11:34:10.034: Browser Hardware Acceleration: true 11:34:10.034: Portable mode: false 11:34:10.202: OBS 27.1.3 (64-bit, windows) 11:34:10.202: --------------------------------- 11:34:10.203: --------------------------------- 11:34:10.203: audio settings reset: 11:34:10.203: 	samples per sec: 44100 11:34:10.203: 	speakers:        2 11:34:10.204: --------------------------------- 11:34:10.204: Initializing D3D11... 11:34:10.204: Available Video Adapters:  11:34:10.207: 	Adapter 0: NVIDIA GeForce RTX 2060 11:34:10.207: 	  Dedicated VRAM: 1975517184 11:34:10.207: 	  Shared VRAM:    4244879360 11:34:10.207: 	  PCI ID:         10de:1f08 11:34:10.207: 	  Driver Version: 30.0.14.9729 11:34:10.207: 	  output 0: pos={0, 0}, size={3840, 2160}, attached=true, refresh=60, name=SAMSUNG 11:34:10.210: Loading up D3D11 on adapter NVIDIA GeForce RTX 2060 (0) 11:34:10.297: D3D11 loaded successfully, feature level used: b000 11:34:10.297: DXGI increase maximum frame latency success 11:34:10.297: D3D11 GPU priority setup failed (not admin?) 11:34:10.679: --------------------------------- 11:34:10.679: video settings reset: 11:34:10.679: 	base resolution:   3840x2160 11:34:10.679: 	output resolution: 3840x2160 11:34:10.679: 	downscale filter:  Bilinear 11:34:10.679: 	fps:               60/1 11:34:10.679: 	format:            NV12 11:34:10.679: 	YUV mode:          709/Partial 11:34:10.679: NV12 texture support enabled 11:34:10.680: Audio monitoring device: 11:34:10.680: 	name: Default 11:34:10.680: 	id: default 11:34:10.680: --------------------------------- 11:34:10.680: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin 11:34:10.685: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded 11:34:10.686: Failed to load 'en-US' text for module: 'decklink-captions.dll' 11:34:10.686: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll' 11:34:10.720: [AMF] Unable to load 'amfrt64.dll', error code 126. 11:34:10.721: [AMF] AMF Test failed due to one or more errors. 11:34:10.721: Failed to initialize module 'enc-amf.dll' 11:34:10.731: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin 11:34:10.735: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin 11:34:10.736: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin 11:34:10.742: [obs-browser]: Version 2.16.3 11:34:10.742: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100 11:34:10.745: NVENC supported 11:34:10.746: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found 11:34:10.876: [StreamFX] Loading Version 0.11.0.0-g31d56703 11:34:10.930: [StreamFX] <gfx::opengl> Version 0.0 initialized. 11:34:10.932: [StreamFX] <nvidia::cuda::cuda> Driver reported CUDA version: 11.5.0 11:34:11.061: [StreamFX] <nvidia::cuda::context> Initialized CUDA on device 'NVIDIA GeForce RTX 2060' (262efb75-fce6-40ec-aae5-3f6b84da959b, 00010e2a, 1). 11:34:11.065: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'. 11:34:11.065: [StreamFX] <filter::autoframing> Failed to make NVIDIA providers available due to error: Failed to load 'NVCVImage.dll'. 11:34:11.065: [StreamFX] <filter::autoframing> All supported providers failed to initialize, disabling effect. 11:34:11.066: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'. 11:34:11.066: [StreamFX] <filter::video_denoising> Failed to make NVIDIA providers available due to error: Failed to load 'NVCVImage.dll'. 11:34:11.066: [StreamFX] <filter::video_denoising> All supported providers failed to initialize, disabling effect. 11:34:11.066: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'. 11:34:11.066: [StreamFX] <filter::video_superresolution> Failed to make NVIDIA Super-Resolution available due to error: Failed to load 'NVCVImage.dll'. 11:34:11.066: [StreamFX] <filter::video_superresolution> All supported Super-Resolution providers failed to initialize, disabling effect. 11:34:11.066: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'. 11:34:11.066: [StreamFX] <filter::virtual_greenscreen> Failed to make NVIDIA Greenscreen available due to error: Failed to load 'NVCVImage.dll'. 11:34:11.066: [StreamFX] <filter::virtual_greenscreen> All supported Virtual Greenscreen providers failed to initialize, disabling effect. 11:34:11.066: [StreamFX] Loaded Version 0.11.0.0-g31d56703 11:34:11.097: VLC found, VLC video source enabled 11:34:11.103: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 11:34:11.103: No blackmagic support 11:34:11.109: --------------------------------- 11:34:11.109:   Loaded Modules: 11:34:11.109:     win-wasapi.dll 11:34:11.109:     win-mf.dll 11:34:11.109:     win-dshow.dll 11:34:11.109:     win-decklink.dll 11:34:11.109:     win-capture.dll 11:34:11.109:     vlc-video.dll 11:34:11.109:     text-freetype2.dll 11:34:11.109:     StreamFX.dll 11:34:11.109:     rtmp-services.dll 11:34:11.109:     obs-x264.dll 11:34:11.109:     obs-vst.dll 11:34:11.109:     obs-transitions.dll 11:34:11.109:     obs-text.dll 11:34:11.109:     obs-qsv11.dll 11:34:11.109:     obs-outputs.dll 11:34:11.109:     obs-filters.dll 11:34:11.109:     obs-ffmpeg.dll 11:34:11.109:     obs-browser.dll 11:34:11.109:     image-source.dll 11:34:11.109:     frontend-tools.dll 11:34:11.109:     enc-amf.dll 11:34:11.109:     decklink-ouput-ui.dll 11:34:11.109:     decklink-captions.dll 11:34:11.109:     coreaudio-encoder.dll 11:34:11.109: --------------------------------- 11:34:11.109: ==== Startup complete =============================================== 11:34:11.115: All scene data cleared 11:34:11.115: ------------------------------------------------ 11:34:11.156: WASAPI: Device 'Speakers (HyperX Cloud Alpha S Game)' [48000 Hz] initialized 11:34:11.156: [Loaded global audio device]: 'Desktop Audio' 11:34:11.180: WASAPI: Device 'Microphone (HyperX Cloud Alpha S Chat)' [48000 Hz] initialized 11:34:11.180: [noise suppress: 'Noise Suppression'] NVAFX redist is not installed. 11:34:11.181: [Loaded global audio device]: 'Mic/Aux' 11:34:11.181:     - filter: 'Noise Suppression' (noise_suppress_filter) 11:34:11.217: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux) 11:34:11.217:  11:34:11.756: [duplicator-monitor-capture: 'Display Capture'] update settings: 11:34:11.756: 	display: 1 (3840x2160) 11:34:11.756: 	cursor: true 11:34:11.756: 	method: DXGI 11:34:11.756: Switched to scene 'Game capture' 11:34:11.756: ------------------------------------------------ 11:34:11.756: Loaded scenes: 11:34:11.756: - scene 'Game capture': 11:34:11.756:     - source: 'Game Capture' (game_capture) 11:34:11.756: - scene 'Display capture': 11:34:11.756:     - source: 'Display Capture' (monitor_capture) 11:34:11.756: ------------------------------------------------ 11:34:12.183: [StreamFX] <updater> Automatic checks at launch are now enabled. 11:34:14.131: [game-capture: 'Game Capture'] attempting to hook fullscreen process: FSD-Win64-Shipping.exe 11:34:14.149: [game-capture: 'Game Capture'] d3d12_init: device=0x23FDECDFEF0 11:34:14.149: [game-capture: 'Game Capture'] We're DXGI1.4 boys! 11:34:14.149: [game-capture: 'Game Capture'] Buffer count: 3, swap effect: 4 11:34:14.149: [game-capture: 'Game Capture'] d3d12_init_11on12: creating 11 device: queue=0x23FDEE0C400 11:34:14.310: [game-capture: 'Game Capture'] d3d12 shared texture capture successful 11:34:14.315: [game-capture: 'Game Capture'] shared texture capture successful 11:34:14.322: [game-capture: 'Game Capture'] Remembering D3D12 queue from first direct submit after present: queue=0x23FDEE0C400 11:34:14.387: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ---------------- 11:34:14.430: [game-capture: 'Game Capture'] Found D3D12 device on swap chain: swap=0x23FDEF242F0, device=0x23FDECDFEF0 11:34:14.431: [game-capture: 'Game Capture'] Remembering D3D12 queue from first direct submit after present: queue=0x23FDEE0C400 11:34:14.443: [game-capture: 'Game Capture'] Found D3D12 device on swap chain: swap=0x23FDEF242F0, device=0x23FDECDFEF0 11:34:14.443: [game-capture: 'Game Capture']     queue=0x23FDEE0C400 11:34:14.443: [game-capture: 'Game Capture'] d3d12_init: device=0x23FDECDFEF0 11:34:14.443: [game-capture: 'Game Capture'] We're DXGI1.4 boys! 11:34:14.443: [game-capture: 'Game Capture'] Buffer count: 3, swap effect: 4 11:34:14.443: [game-capture: 'Game Capture'] d3d12_init_11on12: creating 11 device: queue=0x23FDEE0C400 11:34:14.518: [game-capture: 'Game Capture'] d3d12 shared texture capture successful 11:34:14.520: [game-capture: 'Game Capture'] Remembering D3D12 queue from first direct submit after present: queue=0x23FDEE0C400 11:34:14.531: [game-capture: 'Game Capture'] shared texture capture successful 11:34:15.877: [StreamFX] <encoder::aom::av1> Color-format 'NV12' is not supported, forcing 'I420'... 11:34:15.899: [StreamFX] <encoder::aom::av1> AOM AV1: 11:34:15.899: [StreamFX] <encoder::aom::av1>   Video: 1920x1080@60.00fps (60/1) 11:34:15.899: [StreamFX] <encoder::aom::av1>   Color: I420/Bt.709/Partial 11:34:15.899: [StreamFX] <encoder::aom::av1>   Rate Control: Constant Bitrate (CBR) 11:34:15.899: [StreamFX] <encoder::aom::av1>     Look-Ahead: 0 11:34:15.899: [StreamFX] <encoder::aom::av1>     Buffers: -1 ms / -1 ms / -1 ms 11:34:15.899: [StreamFX] <encoder::aom::av1>     Bitrate: 6000 kbit/s (--1% - +-1%) 11:34:15.899: [StreamFX] <encoder::aom::av1>     Quality: 20 11:34:15.899: [StreamFX] <encoder::aom::av1>     Quantizer: -1 - -1 11:34:15.899: [StreamFX] <encoder::aom::av1>   Key-Frames: Automatic 11:34:15.899: [StreamFX] <encoder::aom::av1>     Distance: 300 - 300 frames 11:34:15.899: [StreamFX] <encoder::aom::av1>   Advanced:  11:34:15.899: [StreamFX] <encoder::aom::av1>    Threads: 24 11:34:15.899: [StreamFX] <encoder::aom::av1>    Row-Multi-Threading: Enabled 11:34:15.899: [StreamFX] <encoder::aom::av1>    Tiling: -1x-1 11:34:15.899: [StreamFX] <encoder::aom::av1>    Tune: PSNR (Metric), Default (Content) 11:34:15.899: --------------------------------- 11:34:15.900: [FFmpeg aac encoder: 'Game'] bitrate: 160, channels: 2, channel_layout: 3 11:34:15.900:  11:34:15.900: --------------------------------- 11:34:15.901: [FFmpeg aac encoder: 'Voice'] bitrate: 96, channels: 2, channel_layout: 3 11:34:15.901:  11:34:15.905: [StreamFX] <encoder::aom::av1> Color-format 'NV12' is not supported, forcing 'I420'... 11:34:15.910: ==== Recording Start =============================================== 11:34:15.910: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/user/Desktop/Videos/Raw/2021-12-28 11-34-15.mkv'... 11:34:15.946: [StreamFX] <encoder::aom::av1> AOM AV1: 11:34:15.946: [StreamFX] <encoder::aom::av1>   Video: 1920x1080@60.00fps (60/1) 11:34:15.946: [StreamFX] <encoder::aom::av1>   Color: I420/Bt.709/Partial 11:34:15.946: [StreamFX] <encoder::aom::av1>   Rate Control: Constant Bitrate (CBR) 11:34:15.946: [StreamFX] <encoder::aom::av1>     Look-Ahead: 0 11:34:15.946: [StreamFX] <encoder::aom::av1>     Buffers: -1 ms / -1 ms / -1 ms 11:34:15.946: [StreamFX] <encoder::aom::av1>     Bitrate: 6000 kbit/s (--1% - +-1%) 11:34:15.946: [StreamFX] <encoder::aom::av1>     Quality: 20 11:34:15.946: [StreamFX] <encoder::aom::av1>     Quantizer: -1 - -1 11:34:15.946: [StreamFX] <encoder::aom::av1>   Key-Frames: Automatic 11:34:15.946: [StreamFX] <encoder::aom::av1>     Distance: 300 - 300 frames 11:34:15.946: [StreamFX] <encoder::aom::av1>   Advanced:  11:34:15.946: [StreamFX] <encoder::aom::av1>    Threads: 24 11:34:15.946: [StreamFX] <encoder::aom::av1>    Row-Multi-Threading: Enabled 11:34:15.946: [StreamFX] <encoder::aom::av1>    Tiling: -1x-1 11:34:15.946: [StreamFX] <encoder::aom::av1>    Tune: PSNR (Metric), Default (Content) 11:34:36.601: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Users/user/Desktop/Videos/Raw/2021-12-28 11-34-15.mkv' stopped 11:34:36.601: Output 'adv_file_output': stopping 11:34:36.601: Output 'adv_file_output': Total frames output: 611 11:34:36.601: Output 'adv_file_output': Total drawn frames: 1242 11:34:36.601: ==== Recording Stop ================================================ 11:34:42.942: Video stopped, number of skipped frames due to encoding lag: 724/755 (95.9%)

### Current Behavior

The recording maxes out at 25% cpu usage, drops almost all frames, and does not play video when recording at all, only audio.

### Expected Behavior

The video plays properly, like other AV1 files, generated with AV1AN.

### Steps to Reproduce the Bug

Step 1: Install completely new copy of OBS and StreamFX 0.11.0
Step 2: Record in AV1

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.

**Comment by Xaymar** [comment]
Please read the manual before opening an issue or asking support: https://github.com/Xaymar/obs-StreamFX/wiki/Encoder-AOM-AV1
