### ISSUE TITLE
NVENC FFMPEG encoder not reporting stream buffering correctly

### ISSUE THREAD

**Issue by TheXev** [Xaymar/obs-StreamFX#759]
### Operating System

Windows 11 22000.376

### OBS Studio Version?

27.1.3

### StreamFX Version

0.11.0.0-g31d56703

### OBS Studio Log

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FzyyS4xiCY9VHqnUC

### Current Behavior

When streaming with NVENC ffmpeg encoder, dropped frames and buffering are not displayed on Stats window correctly.  Status will show as all green with no dropped frames until Stream is stopped.

### Expected Behavior

That any stream buffering or dropped frames will be shown correctly and in a timely manor. 

### Steps to Reproduce the Bug

Start streaming.
Run stream for any amount of time.
When ending stream, the stats in the Stats menu will finally update to their correct values.

### Any additional Information we need to know?

This issue does not occur with any other encoders tested: (built in OBS NVENC H264, AMD AMF FFMPEG H264, CPU x264).

This issue also did not occur with StreamFX 0.10.  I am currently using release 0.11.0.0-g31d56703

If there are any settings changes I need to make that might be the cause, I would love to know more!  I know a two GPU solution isn't ideal, but generally this setup runs very well.

**Comment by Xaymar** [comment]
This is not something StreamFX can even affect.

**Comment by Xaymar** [comment]
1. [Stream Elements OBS.live is not supported by StreamFX and should be replaced with regular OBS Studio.](https://github.com/Xaymar/obs-StreamFX/wiki/Frequently-Asked-Questions#streamelements-obslive)
2. You have multiple GPUs in your system, with your RX 6800 XT being the main GPU. This can lead to weird behavior from cross-GPU encoding, such as a drastic increase in encoding usage.
3. The log file correctly lists all statistics as expected.
