### ISSUE TITLE
Virtual Greenscreen filter does not initialize if Source is 0x0

### ISSUE THREAD

**Issue by adjstreams** [Xaymar/obs-StreamFX#760]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0a1

### OBS Studio Log

https://obsproject.com/logs/ze6AL_A8Cb-sJz64

### Current Behavior

After an OBS restart, a source mirror (of a camera) with virtual greenscreen filter applied is still present in the filter list and enabled with "quality" selected, but doesn't actually apply the greenscreen effect at all, until you go into the filter and toggle the dropdown value to performance, then it becomes re-enabled. It appears to forget, or perhaps has a failure to enable the virtual greenscreen filter properly after the restart.

### Expected Behavior

At the point of restarting OBS, the source mirror should retain the virtual greenscreen effect that was previously applied, without the need to open the filter and toggle the quality/performance mode.

### Steps to Reproduce the Bug

1) Add video capture device
2) Add a Source Mirror source
3) Add the virtual green screen effect to that source mirror, set it to "quality" mode. Behaviour as expected.
4) Close OBS and reopen it.
5) The source mirror greenscreen filter is present in the filter list and enabled but doesn't actually apply the greenscreen effect until you go into the filter and toggle the dropdown value to performance, then it becomes re-enabled.

**Comment by austins** [comment]
Same here.

**Comment by Xaymar** [comment]
#### Confirmed
Problem is not tied to Source Mirror, but any source that can have 0x0 as resolution when it is created.

**Comment by coelhoricardo** [comment]
Hi, is there any known workaround ?

**Comment by spectangulation** [comment]
> Hi, is there any known workaround ?

set it to performance and then back to quality.

confirming i have this issue too.

**Comment by inconsx** [comment]
spectangulation ***@***.***> schrieb am Mo., 24. Jän. 2022,
05:19:

**Comment by skeletonbow** [comment]
If anyone needs any kind of support with StreamFX, the support channels are on the Discord server.  Be sure to carefully read the #rules channel and #support-hub channel to gain access to the proper channel for your platform.  You need to respond at the bottom with an emote for your operating system.  Hope this helps.

**Comment by OsiMood** [comment]
Same issue with OBS 27.2 and StreamFX 0.11.1

**Comment by HunterAP23** [comment]
> Same issue with OBS 27.2 and StreamFX 0.11.1

That's to be expected - if you read the changelog for StreamFX 0.11.1 Alpha 1, it says the only changes were made to the ffmpeg libraries: "Add support for FFmpeg versions other than 4.2."

**Comment by Xaymar** [comment]
Please do not flood the message thread with "I have this issue too". If you have the same issue, just react with a 👍.

**Comment by EliottGaboreau** [comment]
In case this helps, when running obs from a shell I get this error message : 
```
Caught exception: cudaErrorInvalidPitchValue: cudaMemcpy2DFromArrayAsync(...)
```
