### ISSUE TITLE
Disable updater dialog on startup

### ISSUE THREAD

**Issue by alessionossa** [Xaymar/obs-StreamFX#761]
### Explain the Feature/Enhancement

Similar to #279, it would be useful to prevent Updater Dialog from showing up at startup.

### What makes this feature/enhancement useful for StreamFX and its users?

It would be useful in setups where users using the program are not tech savvy and any unexpected pop-ups can cause workflow problems.
The update of the plugin in this case is carried out by the system administrator and users do not need information about the availability of a new update.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
Then turn off the automatic update dialog?!
