### ISSUE TITLE
Encoder does not load on CBR_HQ

### ISSUE THREAD

**Issue by 4p3rtur3** [Xaymar/obs-StreamFX#764]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

13:01:02.689: ------------------------------------------------
13:01:04.744: [StreamFX] [h264_nvenc] Configuration:
13:01:04.744: [StreamFX] [h264_nvenc]   FFmpeg:
13:01:04.744: [StreamFX] [h264_nvenc]     Custom Settings: 
13:01:04.744: [StreamFX] [h264_nvenc]     Standard Compliance: Normal
13:01:04.744: [StreamFX] [h264_nvenc]     Threading: Slice & Frame (with 1 threads)
13:01:04.744: [StreamFX] [h264_nvenc]   Video:
13:01:04.744: [StreamFX] [h264_nvenc]     Texture: 1920x1080 nv12 BT.709 tv
13:01:04.744: [StreamFX] [h264_nvenc]     Framerate: 60/1 (60.000000 FPS)
13:01:04.744: [StreamFX] [h264_nvenc]   Keyframes: 
13:01:04.744: [StreamFX] [h264_nvenc]     Distance: 120 frames
13:01:04.744: [StreamFX] [h264_nvenc]   NVIDIA NVENC:
13:01:04.744: [StreamFX] [h264_nvenc]     Preset: hq
13:01:04.744: [StreamFX] [h264_nvenc]     Rate Control: ll_2pass_size
13:01:04.744: [StreamFX] [h264_nvenc]       Two Pass: Enabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Look-Ahead: 32 Frames
13:01:04.744: [StreamFX] [h264_nvenc]       Adaptive I-Frames: Disabled
13:01:04.744: [StreamFX] [h264_nvenc]       Adaptive B-Frames: Disabled
13:01:04.744: [StreamFX] [h264_nvenc]       Bitrate:
13:01:04.744: [StreamFX] [h264_nvenc]         Target: 6000000 bits/sec
13:01:04.744: [StreamFX] [h264_nvenc]         Minimum: 6000000 bits/sec
13:01:04.744: [StreamFX] [h264_nvenc]         Maximum: 6000000 bits/sec
13:01:04.744: [StreamFX] [h264_nvenc]         Buffer: 0 bits <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Quality:
13:01:04.744: [StreamFX] [h264_nvenc]         Target: 0  <Default>
13:01:04.744: [StreamFX] [h264_nvenc]         Minimum: -1 
13:01:04.744: [StreamFX] [h264_nvenc]         Maximum: -1 
13:01:04.744: [StreamFX] [h264_nvenc]       Quantization Parameters:
13:01:04.744: [StreamFX] [h264_nvenc]         I-Frame: -1  <Default>
13:01:04.744: [StreamFX] [h264_nvenc]         P-Frame: -1  <Default>
13:01:04.744: [StreamFX] [h264_nvenc]         B-Frame: -1  <Default>
13:01:04.744: [StreamFX] [h264_nvenc]     B-Frames: -1 Frames
13:01:04.744: [StreamFX] [h264_nvenc]       Reference Mode: disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]     Adaptive Quantization:
13:01:04.744: [StreamFX] [h264_nvenc]       Spatial AQ: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]         Strength: 8  <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Temporal AQ: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]     Other:
13:01:04.744: [StreamFX] [h264_nvenc]       Zero Latency: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Weighted Prediction: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Non-reference P-Frames: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Reference Frames: 0 Frames
13:01:04.744: [StreamFX] [h264_nvenc]       Strict GOP: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Access Unit Delimiters: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       Bluray Compatibility: Disabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       A53 Closed Captions: Enabled <Default>
13:01:04.744: [StreamFX] [h264_nvenc]       DPB Size: 0 Frames <Default>
13:01:04.744: [StreamFX] [h264_nvenc]     H.264/AVC:
13:01:04.744: [StreamFX] [h264_nvenc]       Profile: high
13:01:04.744: [StreamFX] [h264_nvenc]       Level: auto <Default>
13:01:04.744: warning: The selected preset is deprecated. Use p1 to p7 + -tune or fast/medium/slow.
13:01:04.745: warning: Defined rc_lookahead requires more surfaces, increasing used surfaces 36 -> 41
13:01:04.745: warning: Specified rc mode is deprecated.
13:01:04.745: warning: Use -rc constqp/cbr/vbr, -tune and -multipass instead.
13:01:04.757: error:   InitializeEncoder failed: invalid param (8): Presets P1 to P7 are not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelay.
13:01:04.757: Enable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding a
13:01:04.760: [StreamFX] [h264_nvenc] Configuration:
13:01:04.760: [StreamFX] [h264_nvenc]   FFmpeg:
13:01:04.760: [StreamFX] [h264_nvenc]     Custom Settings: 
13:01:04.760: [StreamFX] [h264_nvenc]     Standard Compliance: Normal
13:01:04.760: [StreamFX] [h264_nvenc]     Threading: None (with 1 threads)
13:01:04.760: [StreamFX] [h264_nvenc]   Video:
13:01:04.760: [StreamFX] [h264_nvenc]     Input: 1920x1080 nv12 BT.709 Partial
13:01:04.760: [StreamFX] [h264_nvenc]     Output: 1920x1080 nv12 BT.709 Partial
13:01:04.760: [StreamFX] [h264_nvenc]     On GPU Index: -1
13:01:04.760: [StreamFX] [h264_nvenc]     Framerate: 60/1 (60.000000 FPS)
13:01:04.760: [StreamFX] [h264_nvenc]   Keyframes: 
13:01:04.760: [StreamFX] [h264_nvenc]     Distance: 120 frames
13:01:04.760: [StreamFX] [h264_nvenc]   NVIDIA NVENC:
13:01:04.760: [StreamFX] [h264_nvenc]     Preset: hq
13:01:04.760: [StreamFX] [h264_nvenc]     Rate Control: ll_2pass_size
13:01:04.760: [StreamFX] [h264_nvenc]       Two Pass: Enabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Look-Ahead: 32 Frames
13:01:04.760: [StreamFX] [h264_nvenc]       Adaptive I-Frames: Disabled
13:01:04.760: [StreamFX] [h264_nvenc]       Adaptive B-Frames: Disabled
13:01:04.760: [StreamFX] [h264_nvenc]       Bitrate:
13:01:04.760: [StreamFX] [h264_nvenc]         Target: 6000000 bits/sec
13:01:04.760: [StreamFX] [h264_nvenc]         Minimum: 6000000 bits/sec
13:01:04.760: [StreamFX] [h264_nvenc]         Maximum: 6000000 bits/sec
13:01:04.760: [StreamFX] [h264_nvenc]         Buffer: 0 bits <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Quality:
13:01:04.760: [StreamFX] [h264_nvenc]         Target: 0  <Default>
13:01:04.760: [StreamFX] [h264_nvenc]         Minimum: -1 
13:01:04.760: [StreamFX] [h264_nvenc]         Maximum: -1 
13:01:04.760: [StreamFX] [h264_nvenc]       Quantization Parameters:
13:01:04.760: [StreamFX] [h264_nvenc]         I-Frame: -1  <Default>
13:01:04.760: [StreamFX] [h264_nvenc]         P-Frame: -1  <Default>
13:01:04.760: [StreamFX] [h264_nvenc]         B-Frame: -1  <Default>
13:01:04.760: [StreamFX] [h264_nvenc]     B-Frames: -1 Frames
13:01:04.760: [StreamFX] [h264_nvenc]       Reference Mode: disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]     Adaptive Quantization:
13:01:04.760: [StreamFX] [h264_nvenc]       Spatial AQ: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]         Strength: 8  <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Temporal AQ: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]     Other:
13:01:04.760: [StreamFX] [h264_nvenc]       Zero Latency: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Weighted Prediction: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Non-reference P-Frames: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Reference Frames: 0 Frames
13:01:04.760: [StreamFX] [h264_nvenc]       Strict GOP: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Access Unit Delimiters: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       Bluray Compatibility: Disabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       A53 Closed Captions: Enabled <Default>
13:01:04.760: [StreamFX] [h264_nvenc]       DPB Size: 0 Frames <Default>
13:01:04.760: [StreamFX] [h264_nvenc]     H.264/AVC:
13:01:04.760: [StreamFX] [h264_nvenc]       Profile: high
13:01:04.760: [StreamFX] [h264_nvenc]       Level: auto <Default>
13:01:04.760: warning: The selected preset is deprecated. Use p1 to p7 + -tune or fast/medium/slow.
13:01:04.950: warning: Defined rc_lookahead requires more surfaces, increasing used surfaces 36 -> 41
13:01:04.950: warning: Specified rc mode is deprecated.
13:01:04.950: warning: Use -rc constqp/cbr/vbr, -tune and -multipass instead.
13:01:04.995: error:   InitializeEncoder failed: invalid param (8): Presets P1 to P7 are not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelay.
13:01:04.995: Enable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding a
13:01:05.030: [StreamFX] Unexpected exception in function '_create': Invalid argument.
13:01:05.030: Stream output type 'rtmp_output' failed to start!

### OBS Studio Crash Log

None

### Current Behavior

The Encoder fails to start
![OBS_1](https://user-images.githubusercontent.com/33102632/149137571-3e15d082-25b2-463b-ad60-9e355e5bb3e0.png)
"Failed to start the application. Please check the log file for details.[...]"

### Expected Behavior

Just start streaming(encoding).

### Steps to Reproduce the Bug

Set the Rate Controle Mode to "High Quality, Constant Bitrate"
![OBS_2](https://user-images.githubusercontent.com/33102632/149138185-e5926553-729a-4c3d-b4f9-4163ad96e1ae.png)

### Any additional Information we need to know?

12:25:52.958: ---------------------------------
12:25:52.958: Initializing D3D11...
12:25:52.958: Available Video Adapters: 
12:25:52.960: 	Adapter 0: NVIDIA GeForce GTX 1060 6GB
12:25:52.960: 	  Dedicated VRAM: 2051014656
12:25:52.960: 	  Shared VRAM:    4256548864
12:25:52.960: 	  PCI ID:         10de:1c03
12:25:52.961: 	  Driver Version: 30.0.14.9729
12:25:52.961: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, space=RGB_FULL_G22_NONE_P709, sdr_white_nits=80, refresh=70, name=VS278
12:25:52.961: 	  output 1: pos={1920, 0}, size={1920, 1080}, attached=true, space=RGB_FULL_G22_NONE_P709, sdr_white_nits=80, refresh=60, name=GF246
12:25:52.963: Loading up D3D11 on adapter NVIDIA GeForce GTX 1060 6GB (0)
12:25:53.046: D3D11 loaded successfully, feature level used: b000
12:25:53.046: DXGI increase maximum frame latency success
12:25:53.046: D3D11 GPU priority setup failed (not admin?)
12:25:53.616: ---------------------------------
12:25:53.616: video settings reset:
12:25:53.616: 	base resolution:   1920x1080
12:25:53.616: 	output resolution: 1920x1080
12:25:53.616: 	downscale filter:  Lanczos
12:25:53.616: 	fps:               60/1
12:25:53.616: 	format:            NV12
12:25:53.616: 	YUV mode:          709/Partial
12:25:53.616: NV12 texture support enabled
12:25:53.623: Audio monitoring device:
12:25:53.623: 	name: Standard
12:25:53.623: 	id: default
12:25:53.624: ---------------------------------
12:25:53.654: Failed to initialize module 'aja-output-ui.dll'
12:25:53.684: No AJA devices found, skipping loading AJA plugin
12:25:53.684: Failed to initialize module 'aja.dll'
12:25:53.718: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
12:25:53.742: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
12:25:53.764: Failed to load 'en-US' text for module: 'decklink-captions.dll'
12:25:53.786: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
12:25:53.904: [AMF] Unable to load 'amfrt64.dll', error code 126.
12:25:53.906: [AMF] AMF Test failed due to one or more errors.
12:25:53.906: Failed to initialize module 'enc-amf.dll'
12:25:54.047: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
12:25:54.084: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
12:25:54.132: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
12:25:54.191: [obs-browser]: Version 2.17.6
12:25:54.191: [obs-browser]: CEF Version 95.0.0-MediaHandler.2462+g95e19b8+chromium-95.0.4638.69
12:25:54.301: NVENC supported
12:25:54.325: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
12:25:54.692: [StreamFX] Loading Version 0.11.0.0-g31d56703
12:25:54.755: [StreamFX] <gfx::opengl> Version 0.0 initialized.
12:25:54.846: [StreamFX] <nvidia::cuda::cuda> Driver reported CUDA version: 11.5.0
12:25:54.949: [StreamFX] <nvidia::cuda::context> Initialized CUDA on device 'NVIDIA GeForce GTX 1060 6GB' (1ac5e8bd-1a33-047e-d9eb-67946abb4524, 0000f726, 1).
12:25:54.971: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'.
12:25:54.971: [StreamFX] <filter::autoframing> Failed to make NVIDIA providers available due to error: Failed to load 'NVCVImage.dll'.
12:25:54.971: [StreamFX] <filter::autoframing> All supported providers failed to initialize, disabling effect.
12:25:54.971: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'.
12:25:54.971: [StreamFX] <filter::video_denoising> Failed to make NVIDIA providers available due to error: Failed to load 'NVCVImage.dll'.
12:25:54.971: [StreamFX] <filter::video_denoising> All supported providers failed to initialize, disabling effect.
12:25:54.971: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'.
12:25:54.971: [StreamFX] <filter::video_superresolution> Failed to make NVIDIA Super-Resolution available due to error: Failed to load 'NVCVImage.dll'.
12:25:54.971: [StreamFX] <filter::video_superresolution> All supported Super-Resolution providers failed to initialize, disabling effect.
12:25:54.972: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'.
12:25:54.972: [StreamFX] <filter::virtual_greenscreen> Failed to make NVIDIA Greenscreen available due to error: Failed to load 'NVCVImage.dll'.
12:25:54.972: [StreamFX] <filter::virtual_greenscreen> All supported Virtual Greenscreen providers failed to initialize, disabling effect.
12:25:54.972: [StreamFX] Loaded Version 0.11.0.0-g31d56703
12:25:55.054: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
12:25:55.224: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
12:25:55.225: No blackmagic support
12:25:55.303: ---------------------------------
12:25:55.303:   Loaded Modules:
12:25:55.303:     win-wasapi.dll
12:25:55.303:     win-mf.dll
12:25:55.303:     win-dshow.dll
12:25:55.303:     win-decklink.dll
12:25:55.303:     win-capture.dll
12:25:55.303:     vlc-video.dll
12:25:55.303:     text-freetype2.dll
12:25:55.303:     StreamFX.dll
12:25:55.303:     rtmp-services.dll
12:25:55.303:     obs-x264.dll
12:25:55.303:     obs-vst.dll
12:25:55.303:     obs-transitions.dll
12:25:55.303:     obs-text.dll
12:25:55.303:     obs-qsv11.dll
12:25:55.303:     obs-outputs.dll
12:25:55.303:     obs-filters.dll
12:25:55.303:     obs-ffmpeg.dll
12:25:55.303:     obs-browser.dll
12:25:55.303:     image-source.dll
12:25:55.303:     frontend-tools.dll
12:25:55.303:     enc-amf.dll
12:25:55.303:     decklink-ouput-ui.dll
12:25:55.303:     decklink-captions.dll
12:25:55.303:     coreaudio-encoder.dll
12:25:55.303:     aja.dll
12:25:55.303:     aja-output-ui.dll
12:25:55.303: ---------------------------------
12:25:55.303: aja main card manager: 4190844864
12:25:55.303: NUM CARDS: 0
12:25:55.303: ==== Startup complete ===============================================

**Comment by Xaymar** [comment]
```
13:01:04.744: warning: The selected preset is deprecated. Use p1 to p7 + -tune or fast/medium/slow.
```

You're using an FFmpeg version newer than 4.2, which requires different parameters.

**Comment by 4p3rtur3** [comment]
But I did not intentionally install a different FFMPEG version. I only have OBS and the plugin on the system. Which version would I need/downgrade to?

**Comment by Xaymar** [comment]
StreamFX only works with stable versions of OBS Studio, which is currently still 27.1.x. If you followed the FFmpeg update guide on the wiki, or installed the beta versions of OBS Studio, you did indeed intentionally install a newer version of FFmpeg.
