### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by emilysacharose** [Xaymar/obs-StreamFX#765]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

N/A

### Current Behavior

A few days ago, StreamFX was working flawlessly (even on my 970GTX) but suddenly, over the past few days when applied to a camera feed it just stops working and kills the source.

Any idea? It's stable, just not displaying anything.

### Expected Behavior

Using shaders on video source no problem before

### Steps to Reproduce the Bug

Not sure. When I apply a Shader filter to a webcam it won't show the source.

### Any additional Information we need to know?

The only big change I've made is installing NDI plugin to enable over-the-network dual PC streaming.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
