### ISSUE TITLE
request: image on face

### ISSUE THREAD

**Issue by thecodsman** [Xaymar/obs-StreamFX#767]
### Explain the Feature/Enhancement

this should be super easy to implement (idk tho maybe its harder than I think) but anyways the feature I want is that basically you can use autoframing (or a new filter) to put on image on your face and it will track to your face. please bro

### What makes this feature/enhancement useful for StreamFX and its users?

it make funni. (and could be used for cool stuff. but mostly funni)

There is no other way to currently do this in StreamFX or OBS Studio.

### Any additional Information we need to know?

I put "there is no other way to currently do this in StreamFX or OBS studio" because if there is one I dont know about (and I googled it and everything) so if there is a way to do this already (a simple one preferably) please tell me :)

**Comment by Xaymar** [comment]
If it's super easy, pick an IDE of your choice and start coding. Besides, this already exists as a plugin if someone extracts it from Streamlabs' client.

**Comment by Xaymar** [comment]
#### Rejected
Apparently it's not "super easy to implement", as the author of this request has neither replied nor made any efforts on their own to make this "super easy" feature happen.
