### ISSUE TITLE
Issue with installer not installing

### ISSUE THREAD

**Issue by CJWicked** [Xaymar/obs-StreamFX#769]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

N/A

### Current Behavior

The installer would not open when I double clicked it. I shutdown all firewalls and attempted to reinstall StreamFX with the new one but it didn't install. I also am opening the program as administrator. 

### Expected Behavior

I expected it to install. 

### Steps to Reproduce the Bug

Just attempt to use the installer.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
