### ISSUE TITLE
NVENC Encoder Not Working with OBS 27.2

### ISSUE THREAD

**Issue by nwoltman** [Xaymar/obs-StreamFX#774]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.2

### StreamFX Version

0.11.0.0-g31d56703

### OBS Studio Log

https://pastebin.com/Qq8n1MfS

### Current Behavior

When attempting to stream or record, OBS shows an error dialog saying there was an error with the encoder. 

### Expected Behavior

Encoding should work

### Steps to Reproduce the Bug

Update to OBS 27.2, try recording with StreamFX/NVENC (High Quality preset, High Quality Variable Bitrate mode, Two-Pass disabled).

### Any additional Information we need to know?

I tried to include only the relevant log lines in the log paste. If you need more information I can provide it.

**Comment by TheOpponent** [comment]
In my experience, the NVENC encoder still works in 27.2, but performance is far worse. Over 3% of frames are lost to encoding and rendering lag, which does not occur in 27.1.3.

**Comment by Xaymar** [comment]
```
20:59:09.875: warning: The selected preset is deprecated. Use p1 to p7 + -tune or fast/medium/slow.
20:59:09.876: warning: Defined rc_lookahead requires more surfaces, increasing used surfaces 41 -> 42
20:59:09.876: warning: Specified rc mode is deprecated.
20:59:09.876: warning: Use -rc constqp/cbr/vbr, -tune and -multipass instead.
20:59:09.899: error:   InitializeEncoder failed: invalid param (8): Presets P1 to P7 are not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelay.
20:59:09.899: Enable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding a
```

This is a user configuration issue. If you want to use the newer FFmpeg in OBS Studio 27.2, you will have to adjust your configuration correctly. StreamFX v0.11 was made for OBS Studio 27.1, and as such the FFmpeg-based features are also for an older FFmpeg version.
