### ISSUE TITLE
Request: Option to change corners to middle point

### ISSUE THREAD

**Issue by abishur** [Xaymar/obs-StreamFX#776]
### Explain the Feature/Enhancement

I was looking to give a capture a bowed look like an old TV screen, but to do it I would need expand the middle point of each side outward while leaving the corners alone.  Is it possible to change the flex point from the corner to a middle point?

### What makes this feature/enhancement useful for StreamFX and its users?

I suppose it would help anyone who wanted another option for transforming a capture?

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
Are you talking about the example shaders? Anything is possible in Shaders, as long as you write the code for it.

**Comment by abishur** [comment]
Oh wow, there's a whole filter that I've never looked at before with a ton of options!  Yeah, that's exactly what I was looking for, thanks!
