### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by Zidakuh** [Xaymar/obs-StreamFX#779]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.2

### StreamFX Version

0.11.0

### OBS Studio Log

https://obsproject.com/logs/gUm9kwTAzOrk3C1T

### Current Behavior

After pressing "Start Recording/Streaming", OBS proceeds to record/stream for about 5 seconds, then drops bitrate to zero and hangs after pressing "Stop Recording/Streaming"
Setting "Level" to anything other than "Automatic" results in "Failed to create encoder. Make sure your GPU has encoder support" message. 
This has happened before when using new FFmpeg dependencies version 4.4 shared GPLv3 on previous OBS versions. 

### Expected Behavior

Same as OBS 27.1 behavior. 

Starting and stopping stream/recording works fine, and OBS doesn't drop bitrate or hang after 5 seconds.
Manually setting "Level" to 4.2 for e.g. 1080p60 or 4.1 for 720p60 works as intended.

### Steps to Reproduce the Bug

After updating FFmpeg dependencies, or updating to OBS version 27.2

StreamFX NVENC settings are as follows:

Preset: Slow
Profile: High
Level: Automatic
Mode: High Quality Constant Bitrate
Two Pass: Enabled
Lookahead: 32
Adaptive I-Frames: Enabled 
Adaptive B-Frames: Enabled
Target Bitrate: 6000
Target Buffersize: 9000
Minimum QP: -1
Maximun QP: -1
Spatial Adaptive Quantization: Enabled
Spatial Adaptive Quantization Strength: 5 
Temporal Adaptive Quantization: Enabled
Maximum B-Frames: 3
B-Frame Referance Mode: Use only middle B-Frames as reference
Zero Latency: Disabled
Weighted Prediction: Disabled
Non-reference P-Frames: Disabled
Reference Frames: 4
Keyframe Interval Type: Seconds
Interval: 2.00
Custom FFmpeg options: -rc=cbr -preset=18 -tune=1 -multipass=2 -coder=1 -refs=5 -mv-precision=qpel -deblock=2:2 -adapt-transform=1 -direct=temporal -partitions=all -surfaces=48
GPU: -1

Output tab in OBS Settings

Canvas resolution: 1920x1080p
Scaled resolution: 1920x1080p
Scaling filter: Bicubic
Framerate: 59.94

### Any additional Information we need to know?

This has been tested on Intel 10700k with an RTX 3080 TI, as well as an RTX 2080 Super.
Same issue and behavior has happened on an AMD R7 2700 based system, tested with both cards and same OBS and FFmpeg versions.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.

**Comment by Xaymar** [comment]
To be exact, you've messed with so many settings for no reason at all that you'll be lucky to see any help at all from anyone.
