### ISSUE TITLE
Getting Encoder Overload Constantly with OBS Update 27.2.1

### ISSUE THREAD

**Issue by cwattyeso** [Xaymar/obs-StreamFX#782]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.2

### StreamFX Version

0.11.1b1

### OBS Studio Log

https://obsproject.com/logs/-KnzR0aVX4mAeUcR

### Current Behavior

Been using StreamFX with version 27.1.3 of OBS and with Streaming and Recording Settings taken from Xaymar's guides on High Quality Recordings with Nvenc and High Quality Streaming with Nvenc. I've been happily streaming and recording at 4K 60FPS for the last two months with no issues at all.

I then got the prompt in OBS on Tuesday Evening to update to the newest 27.2 version. I installed it and found since then that I can not record at all with my previous settings which have been working perfectly. As soon as I start recording I immediately get the "Encoder Overloaded" issue and start noticing frames are getting dropped from the recordings and on one recording I lost over 80% of the video because of this. I did open a support thread on the OBS Forum and was basically told to stop using the StreamFX Encoder and revert back to using the OBS One instead.

However I opted to uninstall 27.2 from my system and re-install 27.1.3 instead and immediately my recording worked fine again.

However one thing I have noticed since Tuesday with both 27.1.3 and 27.2 and referencing Xaymar's Guide found here https://www.xaymar.com/guides/obs/high-quality-recording/nvenc/ in my case when I go to the recording settings whether I'm using the Nvenc via FFmpeg encoder provided by StreamFX or if I try using the OBS Nvenc New encoder, I'm noticing I do not have these new Preset Options like P1-P7 when I try setting up the encoders but still only have the older format presets like Fast, Quality, High Quality, Performance, Low Latency etc. How do I get the new presets as I notice the OBS log tells me the preset I'm using is depreciated but can't see how to change it.

### Expected Behavior

I'd expect after installing to the new 27.2 version of OBS I would still be able to record using my existing settings which have worked for several months without running into this 'Encoder Overload' issue immediately. If anything I thought I'd see better performance with a new and improved version of OBS with the list of fixes and improvements added.

### Steps to Reproduce the Bug

For me it was as simple as installing the new version of OBS, installing StreamFX, setting up my recording settings for a High/Good Quality 4K recording which I've used for a couple of months now and instantly find that I get Encoder Overload when starting to record, sometimes even without a game running or being captured even.

**Comment by Xaymar** [comment]
#### Rejected: User Error
You will have to adjust your FFmpeg encoder configuration to the updated FFmpeg. This is not a bug in StreamFX, as StreamFX only provides a user-friendly UI for the settings, the encoder is provided by FFmpeg.
