### ISSUE TITLE
MacOS installation blocks with error regarding unidentified developer

### ISSUE THREAD

**Issue by MichaelRWolf** [Xaymar/obs-StreamFX#790]
### Explain the Feature/Enhancement

Double-clicking on the downloaded file from github.com produces a dialog box with following 

> “streamfx-macos-10.15-0.11.1.0-g81a96998.pkg” cannot be opened because it is from an unidentified developer.

In the Preferences -> Security & Privacy -> "Allow apps downloaded from", I have selected "App Store and identified developers" (instead of default "App Store").

I _can_ bypass the security block by clicking "Open Anyway", but it would be simpler to NOT be blocked.  Does this require a signed certificate?  Or registering w/ Apple?  Or something else that other downloads seem to do WITHOUT having to go through the App Store?

See: https://support.apple.com/guide/mac-help/protect-your-mac-from-malware-mh40596/12.0/mac/12.2.1

<img width="261" alt="image" src="https://user-images.githubusercontent.com/2851070/156218121-82a1ccb0-13b3-428d-90f9-5a82cf1ff339.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/2851070/156218251-7165278a-3eb1-46be-bbbc-3bcce8b6928e.png">

### What makes this feature/enhancement useful for StreamFX and its users?

Frictionless installation would enhance the UX for everyone.

It would also increase the number of users by not drive off novice users to StreamFX and OBS who rely on built-in security measures to keep them safe.  This class of users is not comfortable knowing if it is OK to click the "Open Anyway" button.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
#### Rejected: User Error
The Installation Guide explicitly instructs you on how to install StreamFX, and if you do not follow the installation guide you simply do not get any support. As code signing is a money-grabbing business with no basis in actual security, I will not waste any money on this stupid practice on any platform.

**Comment by MichaelRWolf** [comment]
OK, then.  It's clear you have thought this through.  So be it...

I do understand your reluctance to do a stupid practice, waste money, and perform an action with no basis in actual security.

AND... I _did_ Read The Fine Manual, and did follow the [Installation Guide](https://github.com/Xaymar/obs-StreamFX/wiki/Installation).  There is no mention of the blocking dialog box, either in the instructions or the FAQ.  *I* know how to get around this, but many users may not.

I propose wording along the lines of
> When MacOS blocks the installation with a dialog box warning of unidentified developer, you must get around it by....
(See description above....  System Preferences -> ... -> Open Anyway)

<img width="989" alt="image" src="https://user-images.githubusercontent.com/2851070/156222360-37db5553-85be-48bd-9e8e-73ac020ac7de.png">

**Comment by Xaymar** [comment]
The current text:

> Option-Click on the .pkg file, then select Open With and then select Installer. Don't double click it.
>    This will cause a window to appear, asking you to confirm that you want to trust this file. To continue with the guide, you have to select Open.

has been working just well, with no users showing up and having problems in Discord.

**Comment by MichaelRWolf** [comment]
I did re-read the instructions.  Again and again.  And, I do see that "Don't double click it" is crucial to the success.  (I had NOT double-clicked, but did the moral equivalent from the command line "open file_name.pkg").  The method (hidden in plain sight) mentioned in the docs *does* work, but it is not what many folks might do.  And, lacking the mention of the security dialog, I expect that many will leave without accomplishing the task that would allow them to use the update.

I learned something.  Left-mouse->Open with is not identical to double-click or open(1).  Thanks for the insight.  After using MacOS for over a decade, I learned something new.  I bet most folks don't know this.

That is non-standard!  I did not see it the first, second, and third time I read it.  This is likely for others, too.  I am so used to reading stuff like this that I read "Download the...." and stopped reading because my muscle memory just knows what to do.  Unfortunately, years of experience installing OTHER packages did not inform me of the correct way to install THIS package.

Proposal -- Highlight/Embolden the phrase that directs folks to violate their muscle-memory instinct to double-click.

**Comment by MichaelRWolf** [comment]
**Lack of proof** of discord posts from users with a problem

is not the same as

**Proof of a lack** of users with a problem

**Comment by Xaymar** [comment]
> Proposal -- Highlight/Embolden the phrase that directs folks to violate their muscle-memory instinct to double-click.

If people do not read the installation guide as written and follow it as written, then they receive no support. The story would be different if StreamFX was paid software, but it isn't. As StreamFX is for power users, this reading comprehension barrier actually helps us out by filtering out the unwanted from the wanted users. It's very effective too!

**Comment by MichaelRWolf** [comment]
I invested much of my time out of a sense of trying to improve this product.

I am not doubting the effectiveness of the tool.

I don't feel heard or valued.

**Comment by MichaelRWolf** [comment]
And... I would like to commend you on your rapid response to my issue.  Many products have multi-day, multi-month, or multi-year response times.  Your quick reply indicates that you care about this product.

**Comment by Xaymar** [comment]
You appear to have an extreme misunderstanding of what StreamFX, who it is for and why it exists:

1. I created StreamFX to fill out my own personal needs, or the needs of close friends, and noone else.
2. I published StreamFX to make sure that at any point in time I would not be in breach of the GPL license, as I was not sure if friends would share the binary by accident. 
3. StreamFX is and always will be aimed at power users who are able to ["Read the fucking Manual"](https://en.wikipedia.org/wiki/RTFM), a very important skill if you want to do anything in life.
4. There is no financial backing or benefit for maintaining or improving StreamFX, nor is there a return on investment. In total StreamFX has cost around 175000 € to maintain and improve, while only barely breaking the 15000 € mark in returns.

So with that information out of the way, I'll ask you: What possible reason could I have to extend the user base past what it already is? What financial reason do I have to entertain your enhancement request, which would drain even more money to maintain? The answer is I have none.

**Comment by robmen** [comment]
@Xaymar, as a fellow OSS developer, I wanted to say I appreciate the work you've provided us for free. I couldn't recreate what you've done. Thank you. I also admire your respect for the license. Well done, on both fronts.

@MichaelRWolf, if you think you can improve the documentation for people that might read it the same way you did, then make the changes to the documentation and submit a pull request. @Xaymar may or may not accept those changes for any number of reasons. If they are not accepted, then you could choose to take your documentation improvements and publish them on the internet for others to find. Then you are (possibly) providing value to the StreamFX project, instead of trying to guilt the developers who wrote the tool into doing more work than they chose to do... for free.

**Comment by MichaelRWolf** [comment]
@robmen - Nice proposal.  And reframing.  I had not _intended_ to create a Guilt Trip(tm), but I see that it had that effect.

@Xaymar -  Yes.  I did have a misunderstanding of StreamFx.  I'm new to OBS.  When the StreamFx update message appeared, I thought it was part of the bigger OBS community project.  I now see that StreamFx is a huge project, but a small "community".  Although I'm too much of a newbie in both communities to know the specifics, I am not a newbie to Open Source (and Free Software before that), so I do recognize the anti-pattern of punishing well-intentioned contributors/leaders for taking initiative.   Thanks for taking initiative in support of a much larger community.  I apologize for my part in that anti-pattern.  
 
Insert Failure Bow here-->>

https://hbr.org/2013/04/go-ahead-take-a-failure-bow#:~:text=One%20of%20my%20favorite%20techniques,dog%2C%20and%20then%20move%20on.
 
https://www.youtube.com/watch?v=cXuD2zHVeB0
