### ISSUE TITLE
Feature Request: Downscaling filter with anti-aliasing

### ISSUE THREAD

**Issue by LuminairPrime** [Xaymar/obs-StreamFX#794]
### Explain the Feature/Enhancement

I've tried suggesting this to the OBS team with no response. It might be too technical an algorithm problem for them. 

We've all seen people on Twitch with ugly, shimmering, aliased webcams due to 1080p or 4k video downscaled to a little 300x300 box. OBS already has a "scale" feature with various algorithms that don't do much. Funnily enough, scaling with OBS has the counter-intuitive effect of making more-expensive high-resolution cameras look worse, while the worse cameras with low-resolution video (properly scaled internally) can look better.

I was reading this review of downscaling algorithms in popular libraries: https://blog.zuru.tech/machine-learning/2021/08/09/the-dangers-behind-image-resizing

And it's incredible how many of those libraries fail to produce a good anti-aliased image: https://blog.zuru.tech/images/image-resizing/circle_comparison.png

Only bilinear and bicubic TensorFlow looked right, and bilinear, bicubic, and lanczos Pillow looked right. The latency cost and computer science complexity of all of this is over my head, but I want to get a feature request on the record just in case this problem is interesting.

Keep up the good work, Xaymar.

### What makes this feature/enhancement useful for StreamFX and its users?

This is a low priority and difficult problem. But I think aliasing in downscaled webcams is a visible problem in streamer video. To demonstrate the problem, I searched for a clip with some shimmering on the streamer's face and glasses, which are not visible when the scene changes and the camera isn't downscaled: [https://www.twitch.tv/saltemike/clip/TalentedExcitedSharkPanicVis-g2pMcgR7jGo6Txf_](https://www.twitch.tv/saltemike/clip/TalentedExcitedSharkPanicVis-g2pMcgR7jGo6Txf_)

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
It is not possible to add new downscaling methods to OBS itself through plugins.

**Comment by LuminairPrime** [comment]
That's cool too, thank you for letting me know :) I'm happy to get the word out there a little bit, even though we can't fix the problem right now. Keep up the good work!
