### ISSUE TITLE
When a Source Mirror is Mirroring a Scene, clearly indicate that Audio is not mirrored

### ISSUE THREAD

**Issue by Gorexxar** [Xaymar/obs-StreamFX#795]
### Explain the Feature/Enhancement

When the Source Mirror is mirroring a Scene Item of type "Scene",
- If possible, prevent Audio from a mirrored Scene from appearing in the Audio Mixer.
- If possible, display a Warning Label that Audio from the selected item will not be mirrored because it is a Scene.
- Update the Manual Entry on "Source Mirror" to indicate that Audio is not mirrored for scenes.

### What makes this feature/enhancement useful for StreamFX and its users?

Currently when a Source mirror is mirroring a scene, OBS displays the Scenes Audio in the Audio Mixer, and will be heard by the Streamer if set for Audio Monitoring. This is counter intuitive, as sound is not actually broadcasted to the Screen Recording or the Stream but it is visible in the Audio Mixer. 

This is to improve the UX of the Source Mirror tool.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
> If possible, prevent Audio from a mirrored Scene from appearing in the Audio Mixer.

Not possible. Audio Mixing is entirely controlled by OBS and Source Mirror has no ability to change it.

> If possible, display a Warning Label that Audio from the selected item will not be mirrored because it is a Scene.

Not possible, see https://obsproject.com/docs/reference-properties.html .

> Update the Manual Entry on "Source Mirror" to indicate that Audio is not mirrored for scenes.

The wiki is open to the public to edit, and not locked down.

**Comment by Xaymar** [comment]
> Not possible, see https://obsproject.com/docs/reference-properties.html .

OBS Studio 28.0 includes a property for this exact purpose.

**Comment by Xaymar** [comment]
Source Mirror will be deprecated with v0.12, and be replaced with a new feature in v0.13. Closing this as not planned for that reason.
