### ISSUE TITLE
zip release for windows

### ISSUE THREAD

**Issue by f1-outsourcing** [Xaymar/obs-StreamFX#800]
### Explain the Feature/Enhancement

Just easier in some circumstances. Same arguments apply as for having a ubuntu zip. ;)

### What makes this feature/enhancement useful for StreamFX and its users?

 Same arguments apply as for having a ubuntu zip. ;)

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
#### Rejected: Same Reason as before
In the entire time of StreamFX being available, having a .zip release has only caused extra support work, never less. If you wish to install for portable, select the portable options ("For Me") in the Windows installer.

**Comment by Xaymar** [comment]
Ubuntu's .zip releases will eventually be replaced by a .sh file as well, just don't quite know when it will happen. It'll hopefully also reduce issues that can occur there.
