### ISSUE TITLE
Crowdin project: StreamFX (for OBS Studio) | Suggested translation strings left in non-approved state

### ISSUE THREAD

**Issue by Ricky-Tigg** [Xaymar/obs-StreamFX#801]
### Operating System

(Other)

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

not related

### Current Behavior

Hello _Michael Fabian Dirks (Xaymar)_ – owner of the [Crowdin](https://crowdin.com/) project OBS Studio.

Mails sent by me to the owners of public projects hosted on Crowdin have invariably not been replied, which leads me to conclude that the service may not be operational as owners would most likely be willing to reply. Have you even received anything from me there?

Here is the common subject of those emails: Suggested translations for Finnish locale which are part of newly contributed translations, are invariably left in pending status, since they rely on approval. I translate but i have not been granted such right. Could it be that you were not aware of that situation? Unknown is the protocol observed by Github in regard to translation strings being in non-approved state. Do those strings are eligible to be merged to the present platform or are all efforts applied to translations been vain? That would be a worth knowing information to me.

### Expected Behavior

Assignment of a user granted with **approval right** of suggested translation strings on Crowdin platform for **Finnish** locale

### Steps to Reproduce the Bug

1. Visit Crowdin platform for your project
2. Inspect suggested translation strings in non-approved state

**Comment by Xaymar** [comment]
The project on Crowdin relies on a voting process, not an approval process. If you see any approved strings that are invalid, use the reporting system and they'll show up as a QA failure during export.

**Comment by Ricky-Tigg** [comment]
The more useless a complication is the less it is likely to be used. I know, we know like so many others. Yes Crowdin does not stand the comparison with Weblate; it even lacks a key feature – a search tool dedicated to source/target translations strings. Nevertheless it has Poedit integration and built-in communication service among others beneficial features. Wiser would have been to suggest me using that last instead of your bad suggestion just because you aimed to please your partner's service despite its tool is most unappropriated for that prupose. That very report illustrates clearly if needed how developers like you are part of the problem by leading user to waste their time here.

**Comment by Ricky-Tigg** [comment]
The more useless a complication is the less it is likely to be used. I know, we know like so many others. Yes Crowdin does not stand the comparison with Weblate; it even lacks a key feature – a search tool dedicated to source/target translations strings. Nevertheless it has _Poedit_ integration and built-in communication service among other beneficial features. Wiser would have been to suggest me using that last instead of your bad suggestion just because you aimed at pleasing your partner's service despite its tool is most unappropriated for that purpose. That very report illustrates clearly if needed how developers like you are part of the problem by leading user to waste their time here.

**Comment by Xaymar** [comment]
You're welcome to fork StreamFX if you don't like how it is being run.
