### ISSUE TITLE
Face retouch/smooth/beautify

### ISSUE THREAD

**Issue by summerrelax** [Xaymar/obs-StreamFX#803]
### Explain the Feature/Enhancement

Recently I used Snap Camera without lenses, just with default "Apply retouching to video stream when no Lens is activated" feature. It makes face looking much better. Is it possible to achieve same effect using StreamFX?

### What makes this feature/enhancement useful for StreamFX and its users?

Snap Camera is heavy, proprietary. Snap Camera alternatives are same heavy and have lots of feature, while there is no lightweight solution for just face retouch task. StreamFX can be good and elegant solution for this

### Checklist

- [X] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [ ] There is no other way to currently do this in StreamFX or OBS Studio.

### Any additional Information we need to know?

Snap Camera's "Apply retouching to video stream when no Lens is activated" switch is in Settings

**Comment by Xaymar** [comment]
Do you know of an open source compatible library that does this?

**Comment by summerrelax** [comment]
I've checked GitHub and founded these repos:

https://github.com/puhach/skin-smoothing
https://github.com/Gnimuc/FabSoften
https://github.com/caohe/Face-Detection-and-Skin-Retouching

You also can look for similar repos by queries like "skin smoother", " face retouch", etc. Not too much, but enough to discover. I'm not sure if this is it because I'm not strong in CG. By some reason I thought that face smoothing is possible by shaders (am I right?)

**Comment by summerrelax** [comment]
Also check Zoom's beautify filter at Settings->Video->Touch up my appearance. Can I achieve similar effect with StreamFX?

**Comment by Xaymar** [comment]
Probably if you apply gaussian blur selectively to the frame in question. There isn't really a reason for StreamFX to have this at all.

**Comment by r4j4h** [comment]
Yep, and the selectively part could be dictated by face detection algorithm to aid in locating facial features to blur or rather using math to locate regions between the features probably

Here is example showing adding lipstick for "digital make-up" https://github.com/ageitgey/face_recognition#find-and-manipulate-facial-features-in-pictures with its corresponding code https://github.com/ageitgey/face_recognition/blob/master/examples/digital_makeup.py

**Comment by Xaymar** [comment]
I still do not see what StreamFX gains from this feature. It's not widely useful like current features, nor does it appear to be anything new given that apps for this exact purpose already exist. It'll be unlikely to be accepted into StreamFX, and I'll reject the request based on this judgement.

**Comment by summerrelax** [comment]
I've checked GitHub and founded these repos:
https://github.com/puhach/skin-smoothing
https://github.com/Gnimuc/FabSoften
https://github.com/caohe/Face-Detection-and-Skin-Retouching
You also can look for similar repos by queries like "skin smoother", " face
retouch", etc. Not too much, but enough to discover. I'm not sure if this
is it because I'm not strong in CG. By some reason I thought that face
smoothing possible by shaders (am I right?)

чт, 21 квіт. 2022, 02:14 користувач Xaymar ***@***.***> пише:
