### ISSUE TITLE
Audio Move Not Appearing in Audio Filters

### ISSUE THREAD

**Issue by GomiSensai** [Xaymar/obs-StreamFX#804]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

Don't have

### Current Behavior

I'm trying to apply the Audio Move filter and it isn't appearing in the drop down

### Expected Behavior

To be able to use this filter, all filters for images come up fine.

### Steps to Reproduce the Bug

restarting OBS doesn't fix

**Comment by TheB1gG** [comment]
That filter is not part of this plugin.

**Comment by GomiSensai** [comment]
My bad then, I saw a video that said that it was I'm sorry

**Comment by Xaymar** [comment]
#### Rejected: User Error
StreamFX features are explicitly listed on the wiki.
