### ISSUE TITLE
Configuration is not saved if OBS Studio crashes before exit.

### ISSUE THREAD

**Issue by ethaniel** [Xaymar/obs-StreamFX#805]
### Operating System

Linux (like Debian/Ubuntu)

### OBS Studio Version?

27.2.4

### StreamFX Version

0.11.1.0

### OBS Studio Log

No log needed.

### Current Behavior

Every time I restart OBS, a welcome window pops up:
<img width="549" alt="Screen Shot 2022-04-30 at 23 05 02" src="https://user-images.githubusercontent.com/941973/166113290-39d95df3-ddce-4054-9feb-5aeeced95e08.png">

### Expected Behavior

Pop up once and then go away on next restart.

### Steps to Reproduce the Bug

Follow Linux installations from https://github.com/Xaymar/obs-StreamFX/wiki/Installation

### Any additional Information we need to know?

I tried creating `~/.config/obs-studio/plugin_config/StreamFX/config.json` (since it wasn't mentioned in the installation instructions, but was mentioned in another [issue](https://github.com/Xaymar/obs-StreamFX/issues/279)), but the problem still persists.

**Comment by Xaymar** [comment]
Please provide a log file as required by the form.

**Comment by ethaniel** [comment]
[hello.txt](https://github.com/Xaymar/obs-StreamFX/files/8597389/hello.txt)

Attached.

**Comment by Xaymar** [comment]
The option `-p` launches OBS Studio in portable mode, which places the entirely OBS Studio data structure somewhere else than `~/.config/`. You will have to verify that you have both create and modify rights for the directory OBS Studio is attempting to store information in, as well as that your system-wide libstdc++ is up to date.

**Comment by ethaniel** [comment]
Well, it's correctly picking up the StreamFX from `~/.config/obs-studio/plugins/StreamFX`, so I don't see a reason why it wouldn't load/put the config from `~/.config/obs-studio/plugin_config/StreamFX`.

Besides, I have obs-browser correctly dumping cache files into `~/.config/obs-studio/plugin_config/obs-browser`:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/941973/166117459-728cfe7b-a02f-43b9-a541-0bd9775a67ab.png">

**Comment by Xaymar** [comment]
Seems like the behavior for OBS Studio built with OBS_UNIX_STRUCTURE is different and instead always prefers `os_get_config_path`. Without that define present, the behavior would be to have the configuration, log files etc all stored near the binary instead. So going by the code, the `-p` flag does nothing with the OBS Studio version you have, since it is ignored by anything but the window title.

That leaves the question why `obs_data_save_json_safe` or `std::filesystem::create_directories` is failing unexpectedly. Usually this hints at overly restrictive jails or permissions set up, or a broken libstdc++ on the system. Not much I can debug anyway, as it works flawlessly on my end.

**Comment by ethaniel** [comment]
I ran an strace on the OBS process. I stopped the strace after closing the welcome popup. What I noticed is that it did read the config.json file correctly, but still decided to popup the welcome and github alerts. Strangely enough it didn't try to save config.json again afterards.

`DISPLAY=:0 sudo -u obs-sala strace obs -p 2>&1 | grep StreamFX`

Here is what I got:
```
getcwd("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", 4096) = 57
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/platforms/.", F_OK) = -1 ENOENT (No such file or directory)
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/platformthemes/.", F_OK) = -1 ENOENT (No such file or directory)
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/platforminputcontexts/.", F_OK) = -1 ENOENT (No such file or directory)
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/styles/.", F_OK) = -1 ENOENT (No such file or directory)
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/iconengines/.", F_OK) = -1 ENOENT (No such file or directory)
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/imageformats/.", F_OK) = -1 ENOENT (No such file or directory)
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/xcbglintegrations/.", F_OK) = -1 ENOENT (No such file or directory)
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/accessible/.", F_OK) = -1 ENOENT (No such file or directory)
getcwd("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", 1024) = 57
stat("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 36
getcwd("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", 1024) = 57
stat("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getcwd("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", 1024) = 57
stat("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/obs-sala/.config/obs-studio/plugins/StreamFX", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
access("/home/obs-sala/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so", F_OK) = 0
access("/home/obs-sala/.config/obs-studio/plugins/StreamFX/data", F_OK) = 0
openat(AT_FDCWD, "/home/obs-sala/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so", O_RDONLY|O_CLOEXEC) = 43
access("/home/obs-sala/.config/obs-studio/plugins/StreamFX/data/locale/en-US.ini", F_OK) = 0
openat(AT_FDCWD, "/home/obs-sala/.config/obs-studio/plugins/StreamFX/data/locale/en-US.ini", O_RDONLY) = 43
write(1, "info: [StreamFX] Loading Version"..., 52info: [StreamFX] Loading Version 0.11.1.0-g81a96998
write(13, "01:31:59.587: [StreamFX] Loading"..., 60) = 60
stat("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/config.json", {st_mode=S_IFREG|0777, st_size=70, ...}) = 0
stat("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/config.json", {st_mode=S_IFREG|0777, st_size=70, ...}) = 0
openat(AT_FDCWD, "/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/config.json", O_RDONLY) = 43
read(43, "{\n    \"UI.HaveShownAboutStreamFX"..., 70) = 70
write(1, "info: [StreamFX] <gfx::opengl> V"..., 56info: [StreamFX] <gfx::opengl> Version 3.3 initialized.
write(13, "01:31:59.706: [StreamFX] <gfx::o"..., 64) = 64
write(1, "info: [StreamFX] Loaded Version "..., 51info: [StreamFX] Loaded Version 0.11.1.0-g81a96998
write(13, "01:31:59.713: [StreamFX] Loaded "..., 59) = 59
write(1, "info:     StreamFX.so\n", 22info:     StreamFX.so
write(13, "01:31:59.713:     StreamFX.so\n", 30) = 30
stat("/home/obs-sala/.config/obs-studio/plugins/StreamFX/data/thanks.json", {st_mode=S_IFREG|0755, st_size=17931, ...}) = 0
openat(AT_FDCWD, "/home/obs-sala/.config/obs-studio/plugins/StreamFX/data/thanks.json", O_RDONLY) = 76
writev(3, [{iov_base="\22\0\24\0T\0\240\3'\1\0\0\30\1\0\0\10\0\0\0007\0\0\0StreamFX"..., iov_len=80}], 1) = 80
writev(3, [{iov_base="\22\0\24\0T\0\240\3'\0\0\0\37\0\0\0\10ptr7\0\0\0StreamFX"..., iov_len=80}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 80
writev(3, [{iov_base="\22\0\24\0T\0\240\3'\0\0\0\37\0\0\0\10ptr7\0\0\0StreamFX"..., iov_len=80}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 80
write(1, "info: [StreamFX] <updater> Autom"..., 71info: [StreamFX] <updater> Automatic checks at launch are now enabled.
write(13, "01:32:00.547: [StreamFX] <update"..., 79) = 79
write(1, "info: [StreamFX] <updater> User "..., 64info: [StreamFX] <updater> User allowed the processing of data.
write(13, "01:32:02.676: [StreamFX] <update"..., 72) = 72
access("/home/obs-sala/.config/obs-studio/plugin_config/StreamFX/accessiblebridge/.", F_OK) = -1 ENOENT (No such file or directory)
```

**Comment by Xaymar** [comment]
At the current time, `config.json` is saved when [streamfx::configuration](https://github.com/Xaymar/obs-StreamFX/blob/master/source/configuration.cpp#L44-L64) is destroyed. This happens when [`obs_module_unload` is called](https://github.com/Xaymar/obs-StreamFX/blob/master/source/plugin.cpp#L324) and should happen every time you close OBS Studio. So the interesting information happens when you fully close OBS Studio.

**Comment by ethaniel** [comment]
Upon stracing, i've noticed that the `config.json` file is generated only once the StreamFX module is properly unloaded (when obs is closed). 

In my case, OBS gets killed most of the time by a monitoring script once watchdog timeouts are reached.

Perhaps it would be wise to consider creating `config.json` once the welcome window is closed instead?

**Comment by Xaymar** [comment]
It's probably wiser to fix whatever is causing your OBS Studio to freeze. As it is right now, the behavior is correct even if it does not work in your particular setup. In the future, I might opt for a delayed save to prevent many sequential writes from suddenly causing high disk load (OBS Studio is sensitive to that for unknown reasons).

**Comment by ethaniel** [comment]
Ha! I wish. I use obs-gstreamer which pulls the whole gstreamer box of worms with it. Most freezes are related to unresolved bugs in the gstreamer modules. But can’t live without them in my case.

**Comment by Xaymar** [comment]
Will fix this with a debounced save happening up to 100ms after the last write. This will prevent not saving on crashes, unless the crash happens before the first save is made.
