### ISSUE TITLE
OBS disconnecting from internet even if i have a very fast internet connection

### ISSUE THREAD

**Issue by YoshinoArt** [Xaymar/obs-StreamFX#808]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

(Other)

### StreamFX Version

0.10.1

### OBS Studio Log

https://drive.google.com/file/d/18PHeBXn8YXu2_ntjxkA1aFlqEbadN4x9/view?usp=sharing

### Current Behavior

It has now happened more than once that at some point of my Twitch stream, OBS disconnects from my internet and so makes my stream crash. Even if my internet is very good, i have in fact tried to open Chrome and check the Twitch chat WHILE OBS was disconnected and it all was working perfectly. I have found that the only way to make it work is to restart OBS, which makes me lose a lot of viewers and obviously interrupts my stream. 
My internet generally runs at 700-850 Mbps Download and 400-500 Mbps Upload.

I have tried to rescale the output video to 1270 but it has not solved the problem.
I also tried to enable the automatic Bitrate adjusting but it still didn't fix the problem since during an event of OBS anomaly, it makes my bitrate drop very low, so the stream still gets interrupted.

### Expected Behavior

Before i update OBS everything worked fine, this problem seemed to arise after i updates OBS.

### Steps to Reproduce the Bug

I have not find the cause actually. It happened randomly, right at the start of the stream as well as in the middle of it (after 2 hours).

**Comment by Xaymar** [comment]
#### Rejected: Caused by other Software
Based on the data reported, the problem is caused by third-party Software (or Plugins to Software), and as such can't (and won't) be supported here. Please seek the proper help channels for the problem you encountered.
