### ISSUE TITLE
Enable "NVIDIA NVENC H.265/HEVC (via FFmpeg)" as output encoder

### ISSUE THREAD

**Issue by Dade94** [Xaymar/obs-StreamFX#809]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

https://obsproject.com/logs/k5qBiV4wc2fMFSi5

### Current Behavior

In Settings -> Output -> Advanced - > Streaming the encoder dropdown doesn't show the "NVIDIA NVENC H.265/HEVC (via FFmpeg)" entry.

![OBS output](https://user-images.githubusercontent.com/8791021/169815627-f72af812-1cef-4ec5-aafa-f51643efff9b.png)

### Expected Behavior

The dropdown should contain "NVIDIA NVENC H.265/HEVC (via FFmpeg)" entry.

I tryed to find a reason reading the source code of the encoder handlers and i found that nvenc_hevc encoding should be possible through streamfx plugin:
https://github.com/Xaymar/obs-StreamFX/blob/master/source/encoders/handlers/nvenc_hevc_handler.hpp
https://github.com/Xaymar/obs-StreamFX/blob/master/source/encoders/handlers/nvenc_hevc_handler.cpp

https://github.com/Xaymar/obs-StreamFX/blob/master/source/encoders/handlers/nvenc_h264_handler.hpp
https://github.com/Xaymar/obs-StreamFX/blob/master/source/encoders/handlers/nvenc_h264_handler.cpp

Looking at the code of nvenc encoder handlers I cannot find structural differences, can you help me understand why nvenc hevc encoder is not available in my setup? 
Thankyou

### Steps to Reproduce the Bug

Install OBS and StreamFX plugin.
Open Settings -> Output -> Advanced - > Streaming

### Any additional Information we need to know?

PC configuration:
OS: Windows 10 21H2 fresh installation
OBS Version: 27.2.4 (tryed also 27.2.3, 27.1.3, 27.0.1)
StreamFX Version: 0.11.1.0 (tryed also 10.11.0.0)
GPU: NVIDIA RTX A2000

**Comment by Xaymar** [comment]
#### Rejected: Caused by other Software
Based on the data reported, the problem is caused by third-party Software (or Plugins to Software), and as such can't (and won't) be supported here. Please seek the proper help channels for the problem you encountered.

StreamFX does not leave this limit, nor has it the ability to lift this limit.

**Comment by Dade94** [comment]
Ok, thankyou for now. I will search in obs documentation
