### ISSUE TITLE
Wrong #include <obs.h>

### ISSUE THREAD

**Issue by yurivict** [Xaymar/obs-StreamFX#828]
### Operating System

(Other)

### OBS Studio Version?

(Other)

### StreamFX Version

0.11.1

### OBS Studio Log

n/a

### OBS Studio Crash Log

n/a

### Current Behavior

```
/disk-samsung/freebsd-ports/multimedia/obs-streamfx/work/.build/generated/module.cpp:5:10: fatal error: 'obs.h' file not found
#include <obs.h>
         ^~~~~~~
```

obs-studio installs ```/usr/local/include/obs/obs.h```and pkg-config says that it should be included as ```<obs/obs.h>```:
```
$ pkg-config --cflags libobs
-I/usr/local/include -D_THREAD_SAFE -pthread 
```

### Expected Behavior

n/a

### Steps to Reproduce the Bug

n/a

**Comment by yurivict** [comment]
> Please build StreamFX with CMake configuration files, not pkg-config.

pkg-config's output should match cmake's output. It is built with cmake and breaks.

I'm not sure why did you close it.

**Comment by Xaymar** [comment]
This appears to have been due to a yet unreleased (in development) change for OBS Studio 28.0. StreamFX by default does not support in-development versions of OBS Studio or any of the libaries, and always targets certain versions. Anyway, with #870 this will be resolved.
