### ISSUE TITLE
Direct integration of Intel QSV encoder

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#859]
### Discussion Thread

https://github.com/Xaymar/obs-StreamFX/discussions/858

### Provide a summary of the Improvement

StreamFX currently lacks integration of the Intel QSV encoders entirely.

### Completion Requirements
- Code should have a reasonable amount of comments to be understood, but not an excessive amount. Code itself is not documentation, documentation is documentation.
- Supports Zero-Copy (same-GPU) and Multi-GPU encoding with low to no performance impact.
- Supports Windows and Linux (Debian, Ubuntu).
- Support for the following codecs: H.264/AVC, H.265/HVEC, VP9
    - Optional support for AV1, if Intel Arc GPUs actually exist.
- User Interface similar to the existing FFmpeg encoders.
    - Options which do not make sense in OBS Studio should not be exposed, but Options that do make sense should be exposed in a user-friendly way.
    - Users should be able to override UI options using a similar style to the command line overrides provided in FFmpeg encoders.
- Support for NV12, I422, I444 and RGB encoding.
- Performance impact similar if not better compared to the already implemented QSV encoder. Memory (RAM/VRAM) is secondary priority.

**Comment by towneh** [comment]
Has any progress been made with this? I built an Intel ARC 380M dedicated streaming machine the other week, and was wondering what the options were for hardware encoding AV-1.  :O
