### ISSUE TITLE
StreamFX master/git compilation broken by commit a78037d on Fedora

### ISSUE THREAD

**Issue by GloriousEggroll** [Xaymar/obs-StreamFX#864]
### Operating System

(Other)

### OBS Studio Version

OBS 28 git/beta

### StreamFX Version

StreamFX git/master

### OBS Studio Log

N/A

### Current and Expected Behavior

reverting commit a78037d0fc9f2bbb81179192cf59ec1466ae9953 allows compilation.  Compiled using Fedora's mock build system (used for all Fedora packages). log attached shows version error.

[build.log](https://github.com/Xaymar/obs-StreamFX/files/9266286/build.log)

### Steps to Reproduce the Problem

The steps to compile on Fedora are lengthy to explain, I'd suggest attempting to rebuild on Arch to see if the issue is reproducible. I reproduced the issue while building streamfx as part of obs without the gui.

**Comment by Xaymar** [comment]
Yep, this is true for _all_ platforms, see PRs #837, #830, #843. StreamFX's CMake build system is undergoing major changes.

**Comment by Xaymar** [comment]
This should be fixed by #837 being merged into master. Please verify.

**Comment by GloriousEggroll** [comment]
Thanks for the quick fix/response! Can confirm it compiles fine now with latest git
