### ISSUE TITLE
NVENC doesn't work properly when OBS running on other GPU

### ISSUE THREAD

**Issue by Mishasama** [Xaymar/obs-StreamFX#892]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version

Other

### StreamFX Version

0.11.1

### OBS Studio Log

[2022-08-25 01-59-08.txt](https://github.com/Xaymar/obs-StreamFX/files/9418230/2022-08-25.01-59-08.txt)

### Current and Expected Behavior

When I start recording or streaming, it always output a green screen video. Looks like copy error.

### Steps to Reproduce the Problem

1. Set the OBS using iGPU under Windows graphics settings.
2. Run OBS.
3. Start recording.
4. Stop recording.
5. Check the video file.
6. See problem.

### Any additional Information we need to know?

I'm using the [OBS-ME](https://github.com/pkviet/obs-studio/releases/tag/v27.2.5). But I think it doesn't matter for this problem.

When I switched back to using NV GPU to run OBS, this issue was gone.
But even when my OBS running on iGPU, the build in NVENC encoder still works. So, I think I should file a bug here.

**Comment by Xaymar** [comment]
Please try this without any custom settings and with the normal OBS Studio.

**Comment by Mishasama** [comment]
> Please try this without any custom settings and with the normal OBS Studio.

Okay, thanks.
