### ISSUE TITLE
Does not load on Debian based systems

### ISSUE THREAD

**Issue by ZerkerEOD** [Xaymar/obs-StreamFX#900]
### Operating System

Linux (like Debian/Ubuntu)

### OBS Studio Version

OBS 27.2.4+dfsg1-2+b3

### StreamFX Version

12.0.77

### OBS Studio Log

Attempted path: share/obs/obs-studio/locale/en-US.ini Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini Attempted path: share/obs/obs-studio/locale.ini Attempted path: /usr/share/obs/obs-studio/locale.ini Attempted path: share/obs/obs-studio/themes/Dark.qss Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss info: CPU Name: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz info: CPU Speed: 1800.000MHz info: Physical Cores: 4, Logical Cores: 8 info: Physical Memory: 31838MB Total, 871MB Free info: Kernel Version: Linux 5.18.0-kali5-amd64 info: Distribution: "Kali GNU/Linux" "2022.3" info: Session Type: x11 info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1 info: Qt Version: 5.15.4 (runtime), 5.15.4 (compiled) info: Portable mode: false Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int) QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered() QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered() info: OBS 27.2.4+dfsg1-2+b3 (linux) info: --------------------------------- info: --------------------------------- info: audio settings reset: 	samples per sec: 48000 	speakers:        2 info: --------------------------------- info: Initializing OpenGL... info: Loading up OpenGL on adapter Intel Mesa Intel(R) Xe Graphics (TGL GT2) info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 22.2.0-rc1, shading language 4.60 info: --------------------------------- info: video settings reset: 	base resolution:   1920x1080 	output resolution: 1280x720 	downscale filter:  Bicubic 	fps:               30/1 	format:            NV12 	YUV mode:          709/Partial info: NV12 texture support not available info: Audio monitoring device: 	name: Default 	id: default info: --------------------------------- warning: Failed to load 'en-US' text for module: 'decklink-captions.so' warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so' libDeckLinkAPI.so: cannot open shared object file: No such file or directory warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed info: No blackmagic support info: NVENC supported info: FFMPEG VAAPI supported info: [vlc-video]: VLC 3.0.17.4 Vetinari found, VLC video source enabled error: os_dlopen(/home/aaron/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so->/home/aaron/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so): libswscale.so.5: cannot open shared object file: No such file or directory  warning: Module '/home/aaron/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so' not loaded info: --------------------------------- info:   Loaded Modules: info:     vlc-video.so info:     text-freetype2.so info:     rtmp-services.so info:     obs-x264.so info:     obs-transitions.so info:     obs-outputs.so info:     obs-filters.so info:     obs-ffmpeg.so info:     linux-v4l2.so info:     linux-pulseaudio.so info:     linux-jack.so info:     linux-decklink.so info:     linux-capture.so info:     linux-alsa.so info:     image-source.so info:     frontend-tools.so info:     decklink-ouput-ui.so info:     decklink-captions.so info: --------------------------------- info: ==== Startup complete =============================================== info: All scene data cleared info: ------------------------------------------------

### Current and Expected Behavior

Expect it to load

### Steps to Reproduce the Problem

Follow installation instructions for linux, start obs, get nothing.

### Any additional Information we need to know?

Tells me can't find libswscale.so.5. I can't install 5 as the only options I have is 6 and dev which 6 was already installed and I installed dev and still nothing.

**Comment by Xaymar** [comment]
Quite literally read the system requirements...

**Comment by ZerkerEOD** [comment]
Hey @Xaymar, thanks for getting back to me. I was hoping for a little more as I have read the system requirements for both and believe my systems fall under them. But per your sarcastic remark, I did go back and look and still feel the same. I don't see anything in the system requirements mentioning libswscale.so.5 libraries or anything about the issue I am having. Maybe you could extrapolate and tell me what I am missing as I am not an expert in your code or the requirements.

**Comment by Xaymar** [comment]
[As you can clearly see on the release page for v0.12.0a77](https://github.com/Xaymar/obs-StreamFX/releases/tag/0.12.0a77), at minimum you will need to have OBS Studio 28.0.0-rc1 or later. Additionally, only Ubuntu is officially supported and you can pick between 20.04 and 22.04 - both Ubuntu LTS versions. So if you pick one of those versions, your system needs to match up with the Ubuntu distribution of packages.

As you seem to have used a prepackaged version of obs-studio for Debian, perhaps you want to build from source? Instructions for doing this are [on the wiki](https://github.com/Xaymar/obs-StreamFX/wiki/Building#building-standalone), and should be easy to follow. Alternatively, contribute the necessary code to automatically publish versions to the Debian package repository.

PS: That was very clearly annoyance and not sarcasm.

**Comment by Xaymar** [comment]
#### Rejected: User Error
The official releases support the LTS versions of Ubuntu 20.04 and Ubuntu 22.04, which mostly match up with Debian-like distros. As the end user here is using a non-stable version of their OS, no further support is given.
