### ISSUE TITLE
Replace Me Or Have Your Request Closed

### ISSUE THREAD

**Issue by shinoni69** [Xaymar/obs-StreamFX#904]
### Discussion Thread

OBS just updated, Now the plugin seems to be outdated and will not work.

### Provide a summary of the Improvement

OBS now has a recent new update 09/01/2022. The updated added a few new things and one change is a new look. Problem I have to deal with is that the plugin doesn't work now with it, it's outdated. I don't know when it will be updated but I would appreciate it if it's looked into updating the software to the newest obs update. Because the plugin is something I heavily use on my obs, seeing the work to angle gets resetted is very sad for me.

**Comment by Xaymar** [comment]
The latest versions already support OBS Studio 28.0.0, and building from Source already supported the newer OBS Studio versions from the beginning.

**Comment by Xaymar** [comment]
#### Rejected: User Error
The user has not looked at the latest versions of StreamFX.

**Comment by shinoni69** [comment]
Ok thank you! Sorry didn't see the release page. That was quick though, 4 hours ago huh? Thank you for the quick reply.
