### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by Foexle11** [Xaymar/obs-StreamFX#910]
### Operating System

Linux (like Debian/Ubuntu)

### OBS Studio Version

28.0.0

### StreamFX Version

0.11.1

### OBS Studio Log

Yes, it crashed. Dunno what to exactly post here

### OBS Studio Crash Log

[2022-09-03 09-35-04.txt](https://github.com/Xaymar/obs-StreamFX/files/9482161/2022-09-03.09-35-04.txt)

### Current and Expected Behavior

OBS Starts, I can shortly see some black and grey boxes, then the program terminates.

### Steps to Reproduce the Problem

Install OBS and the StreamFX on Mint 21 Cinnamon.
Run OBS.

### Any additional Information we need to know?

Using the OBS-repository on a Linux Mint 21 Cinnamon with 5.15.0-47-generic kernel. Doesn't happen with OBS 27.

**Comment by Xaymar** [comment]
You've attached a normal log as a crash log. This doesn't help.

**Comment by Xaymar** [comment]
#### Rejected: User Error
It is not possible for things in the past to know and support things that happened in the future relative to it. v0.11 was released significantly earlier than obs v28.0.
