### ISSUE TITLE
obs can not load StreamFX plugin after update

### ISSUE THREAD

**Issue by csBlackWolf** [Xaymar/obs-StreamFX#939]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version

28.0.1

### StreamFX Version

0.11.1

### OBS Studio Log

https://obsproject.com/logs/UgmraeOqgJM_H3oy

### OBS Studio Crash Log

No crash.

### Current and Expected Behavior

Currently: Error window what is informing me about StreamFX has not been loaded.
Expecting: Just loading the StreamFX plugin.

### Steps to Reproduce the Problem

Using OBS 28.0.1 with StreamFX 0.11.1 ?

**Comment by Nerxxy** [comment]
same but for the this [pre-release](https://github.com/Xaymar/obs-StreamFX/releases/tag/0.12.0a134) it wont even show in obs

**Comment by Xaymar** [comment]
#### Rejected: User Error
As is hopefully clear to anyone, things in the past can't support things that release in the future.

**Comment by Xaymar** [comment]
Duplicat of https://github.com/Xaymar/obs-StreamFX/issues/910 https://github.com/Xaymar/obs-StreamFX/issues/905 https://github.com/Xaymar/obs-StreamFX/issues/904
