### ISSUE TITLE
StreamFX needs an update for Obs

### ISSUE THREAD

**Issue by Ksx-C** [Xaymar/obs-StreamFX#941]
### Discussion Thread

Obs Studio 28.0.2 (64 bit)

### Provide a summary of the Improvement

StreamFX doesn't work anymore with the latest version of Obs Studio, it needs an update.

**Comment by Wryyyong** [comment]
Do tell, what version of StreamFX are you currently using?

**Comment by Ksx-C** [comment]
> 

Using the latest one there is on Github, 0.11.1

streamfx-windows-2019-0.11.1.0-g81a96998.exe

**Comment by Wryyyong** [comment]
Unless you're actively using StreamFX for production/livestreaming purposes, give the latest alpha version a try.

The latest alpha as of posting is [0.12.0a134](https://github.com/Xaymar/obs-StreamFX/releases/tag/0.12.0a134).
