### ISSUE TITLE
Replace Me Or Have Your Report Closed

### ISSUE THREAD

**Issue by chriskorosu** [Xaymar/obs-StreamFX#951]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version

28.0.3 (64 bit)

### StreamFX Version

0.11.1.0

### OBS Studio Log

Don't know where to find the log file

### Current and Expected Behavior

I wasn't able to use StreamFX. As soon as I loaded up OBS Studio, I encountered an error message about StreamFX having failed to load.

### Steps to Reproduce the Problem

Install StreamFX (tried both static and portable installs with same result)

### Any additional Information we need to know?

![image](https://user-images.githubusercontent.com/47898552/194109543-1eaa5510-9181-43ae-9d30-3613d927a6ca.png)

**Comment by Xaymar** [comment]
#### Rejected: User Error
<The Problem is caused by the User>
