### ISSUE TITLE
Not working (OBS standard error msg when launching OBS)

### ISSUE THREAD

**Issue by 4Sol** [Xaymar/obs-StreamFX#954]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version

28.0.3.

### StreamFX Version

StreamFX 0.12.0 Alpha 134

### OBS Studio Log

https://obsproject.com/logs/4KXkiL8C_gZ3SMAV

### Current and Expected Behavior

I launched OBS and get an erorr:
![image](https://user-images.githubusercontent.com/52103769/194706808-d80621b0-07df-4823-8ece-c376a798dbe3.png)

### Steps to Reproduce the Problem

Portable OBS studio > portable StreamFX installation

**Comment by 4Sol** [comment]
All good now

**Comment by CitizenPrayer** [comment]
This seems to be happening again. StreamFX is not loading on boot with OBS 28 (newest update) and StreamFX (newest stable release).

**Comment by Xaymar** [comment]
OBS Studio 28.x is not yet supported, there is no stable release for it yet.
