### ISSUE TITLE
Does not load in Ubuntu 22.10

### ISSUE THREAD

**Issue by Zahrun** [Xaymar/obs-StreamFX#969]
### Operating System

Linux (like Debian/Ubuntu)

### OBS Studio Version

28.0.1.11-3

### StreamFX Version

0.12.0 Alpha 134

### OBS Studio Log

[2022-10-30 14-54-38.txt](https://github.com/Xaymar/obs-StreamFX/files/9895517/2022-10-30.14-54-38.txt)

```
14:54:39.723: os_dlopen(/home/aroun/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so->/home/aroun/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so): libavutil.so.56: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
14:54:39.723: 
14:54:39.723: Module '/home/aroun/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so' not loaded
```

### Current and Expected Behavior

Does not load, should load

### Steps to Reproduce the Problem

Use Ubuntu 22.10 and StreamFX 0.12.0 Alpha 134

### Any additional Information we need to know?

libavutil56 is not available in kinetic repos, it was replaced by libavutil57

**Comment by Xaymar** [comment]
#### Rejected: User Error
Currently only Ubuntu 20.04 (Focal) and 22.04 (Jammy) are supported. For other versions of the OS, you will need to build from source.
