### ISSUE TITLE
Flatpak version not found

### ISSUE THREAD

**Issue by TechXero** [Xaymar/obs-StreamFX#970]
### Operating System

Linux (like Arch Linux)

### OBS Studio Version

28.1

### StreamFX Version

Flatpak

### OBS Studio Log

N/A

### Current and Expected Behavior

To find Flatpak version of StreamFX

### Steps to Reproduce the Problem
```
flatpak install com.obsproject.Studio.Plugin.StreamFX
```
### Any additional Information we need to know?

Get error 
```
error: No remote refs found for ‘com.obsproject.Studio.Plugin.StreamFX’
```

**Comment by Xaymar** [comment]
StreamFX does not provide a Flatpak release.

**Comment by TechXero** [comment]
On the install page shows way to install via Flatpak. I know it's community run but why mention it if it's no longer there ?

**Comment by Xaymar** [comment]
It's not "no longer there". If you use the search functionality, you will find a work in progress of a Flatpak release.
