### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by ThePooN** [Xaymar/obs-StreamFX#98]
### Description
Doing a standalone build or as a built-in OBS plugin fails.  
First, `cmake` fails due to a capitalization issue in CMakeFiles.txt, that is easily fixed by this patch: [fix-cmake.patch.txt](https://github.com/Xaymar/obs-StreamFX/files/4003909/fix-cmake.patch.txt)  
After that is fixed, there are two remaining distinct errors: 
[build-issue.log](https://github.com/Xaymar/obs-StreamFX/files/4003937/build-issue.log)  

It seems like these methods should be supported by everything on my system and the project's configuration, so I'm confused.

### Expected Behavior
To build with no error.

### Reproduction Steps
```bash
#!/bin/sh
mkdir build && cd build
cmake ..

echo "# LANG=C make source/obs/gs/gs-effect-parameter.o"
LANG=C make source/obs/gs/gs-effect-parameter.o
echo ""

echo "# LANG=C make source/obs/gs/gs-effect-pass.o"
LANG=C make source/obs/gs/gs-effect-pass.o
echo ""

echo "# LANG=C make source/obs/gs/gs-effect-technique.o"
LANG=C make source/obs/gs/gs-effect-technique.o
echo ""

echo "# LANG=C make source/gfx/shader/gfx-shader-param.cpp.o"
LANG=C make source/gfx/shader/gfx-shader-param.cpp.o
echo ""
```

### System Information
- Software Version: StreamFX 0.8.0 Alpha 1
- Operating System: Arch Linux
- Kernel Version: 5.4.6-arch3-1
- CPU: AMD Ryzen Threadripper 1950X 
- GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
- RAM: 32GB

### Additional Notes
I have been able to build StreamFX by replacing `strnlen_s` by `strnlen` and re-implementing `clamp` and building it as a built-in plugin, as suggested by the wiki. I haven't tried a "standalone" build.

OBS and the plugin started fine. I am not very experienced with the plugin so I just tried a few filters and Source Mirror. Filters were successful, Source Mirror only worked on a Media Source (Desktop and Window capture were black or transparent, can't remember).

I joined the Discord, by the way!

### Checklist:
- [X] I have read the contribution guidelines.
- [X] I can reproduce the issue with the exact reproduction steps I have provided.
- [X] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
> re-implementing clamp and

`std::clamp` is part of `<algorithm>`. If it is not, update your GCC/clang compiler, as C++17 is not that new and required by the code.

**Comment by ThePooN** [comment]
My system is up-to-date though, so I'm clueless :|

Will continue looking around.

**Comment by mikesmiffy128** [comment]
> `strnlen_s` is part of C11 in `<string.h>` which IIRC is automatically included in MSVC.

Hi, just passing by with a quick note: the `_s` functions were added as an optional part of C11 which no libc other than Microsoft's actually implements, to my knowledge. Based on documentation it looks like the only difference between `strnlen_s` and `strnlen` is that `strnlen_s` treats a null pointer as length 0, so depending on whether this case comes up it should be easy enough to either write a wrapper for non-Windows or just use `strnlen` instead.

Nice plugin btw! :+1:

**Comment by Xaymar** [comment]
> Based on documentation it looks like the only difference between strnlen_s and strnlen is that strnlen_s treats a null pointer as length 0

That is incorrect. strnlen_s contains a fail-safe if there is no NUL in the x bytes defined by the 2nd parameter. Any modern compiler should have C11 implemented, especially GCC and Clang.

A possible alternative is to build a custom strnlen_s which does the same, but the current plugin focus is getting 1.0 out - as a solo developer I can't work on multiple things at the same time, so I have to choose which I feel is more important.

**Comment by mikesmiffy128** [comment]
> strnlen_s contains a fail-safe if there is no NUL in the x bytes defined by the 2nd parameter.

So does regular `strlen`. From the Linux man page:

> The strnlen() function returns strlen(s), if that is less than maxlen, or maxlen if there is no null terminating ('\0') among the first maxlen characters pointed to by s.

> Any modern compiler should have C11 implemented, especially GCC and Clang.

As I said, this function isn't a required part of C11, it's part of Annex K, which glibc devs have refused to implement time and time again, for better or for worse. Furthermore, removal of these functions from later C standards has been proposed, although I'm not sure if this has happened yet as of C18.

> as a solo developer I can't work on multiple things at the same time, so I have to choose which I feel is more important.

Of course, this is perfectly reasonable. The goal of the my last comment was just to suggest an easy fix for this portability issue in case anyone who does use OBS on Linux who wants to take a crack at a PR.

**Comment by Xaymar** [comment]
> So does regular strnlen. From the Linux man page:

`strnlen` doesn't show up as standard in C89, C99 or C11 at all. The only references to it I can find are POSIX, and that means that it would require a conditional define in `plugin.hpp`. Since I don't know which compiler are all affected by the nonsense some open source developers once again have subjected themselves to, I won't be doing it myself.

**Comment by mikesmiffy128** [comment]
Oh, it's POSIX, alright. Seems that it also exists on Windows anyway, though. But yeah, no need to do it yourself, thought I'd just put the info here. I could probably also just write the patch myself but I really have no use for OBS on Linux either, so...

**Comment by cyclopsian** [comment]
Hi all, I was able to get this to compile on Ubuntu Linux using this branch here: [cyclopsian:linux-port](https://github.com/Xaymar/obs-StreamFX/compare/master...cyclopsian:linux-port). I had to disable the ffmpeg encoder plugin because it has a dependency on D3D11. Is that encoder plugin needed at all? I never tried it so I can't tell how useful it is. I can add some CMake conditionals to disable the encoder plugin on non-windows platforms and then submit that branch as a PR, if that sounds good.

**Comment by Xaymar** [comment]
The D3D11 stuff of ffmpeg-encoder is going to be conditional in the future. The part of the plugin is needed, as obs-ffmpeg-encoders has been archived and merged with obs-streamfx.

**Comment by RarogCmex** [comment]
Ok, in my side ffmpeg-encoder is critically needed for Linux because of lack of other hardware options. So I'll wait untill it's ported to Linux

**Comment by Xaymar** [comment]
Linux building should now work as expected again. Some features are currently disabled on Linux until someone spends time implementing them correctly, such as FFmpeg Encoder and Mipmapping.
