### ISSUE TITLE
hangs when closing in with obs 28+

### ISSUE THREAD

**Issue by mesmerx** [Xaymar/obs-StreamFX#982]
### Operating System

Linux (like Arch Linux)

### OBS Studio Version

OBS Studio - 29.0.0-beta1-5-ge72aa91a6-modified (linux)

### StreamFX Version

0.12.0a151-g0f114f56

### OBS Studio Log

https://obsproject.com/logs/VydlM14ZqWE7BmPU

### Current and Expected Behavior

works normally, but when closing it hangs 
in 

```
info: [StreamFX] Unloading Version 0.12.0a151-g0f114f56
info: [StreamFX] <gfx::opengl> Finalized.
```

and need to be killed by a pkill or simillar

uninstalling fx it closes normally again

### Steps to Reproduce the Problem

have osb 28+ install streamfx from git version and try to close

**Comment by mesmerx** [comment]
overall its not a big problem, but its a paint o kill everytime i need to restart the obs or i have the "already open" popup

**Comment by Xaymar** [comment]
#### Rejected: User Error
Please read the release notes. Thank you.

**Comment by Xaymar** [comment]
Also read the system requirements. Only Ubuntu :)

**Comment by zxsdklfhskyrvk** [comment]
Any plans to update the OBS download page (https://obsproject.com/forum/resources/streamfx-for-obs%C2%AE-studio.578/) to not mention OBS 28 as supported?  I went by that and tried installing the app, to only find out it isn't supported.

Minimum OBS Studio Version 28.0.0

**Comment by Xaymar** [comment]
The resources page is updated with stable releases, and can't be set to something that it doesn't support. All information about a release is in the release notes for the given version. Not wanting to read them isn't something i can fix.
