### ISSUE TITLE
Cannot use Source Mirror on Game Capture

### ISSUE THREAD

**Issue by RibShark** [Xaymar/obs-StreamFX#99]
### Description
On the latest pre-release/artifact, attempting to use source mirror on a Game Capture source produces just transparency.

### Expected Behavior
The game capture source is mirrored.

### Reproduction Steps

1. Make a game capture source.
2. Make a source mirror, and set the source to the game capture/

### System Information

- Software Version: 0.8.0 Alpha 1
- Operating System: Windows 10
- Kernel Version: 1909
- CPU: Intel 4th Gen Core i5 (4690)
- GPU: NVIDIA GTX 970
- RAM: 8GB

### Checklist:

- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
This might be related to https://github.com/obsproject/obs-studio/issues/2223

**Comment by RibShark** [comment]
> 
> 
> This might be related to [obsproject/obs-studio#2223](https://github.com/obsproject/obs-studio/issues/2223)

The issue still occurs on the latest dev build of OBS, so I doubt it is the same issue.

**Comment by Xaymar** [comment]
I'm unsure of what the reason for this is, but the behavior seems to be:

- Source Mirror points at Game Capture.
- Game Capture pretends it isn't active, despite getting all notifications to be active.

**Comment by Xaymar** [comment]
**The bug has been fixed, please verify that you no longer get the bug in question using [the bleeding-edge build for the fix](https://github.com/Xaymar/obs-StreamFX/actions/runs/39173415).** Please note that these builds include other possibly incomplete features, so they are not to be used for production setups.

**Comment by Xaymar** [comment]
Other user confirmed that it is fixed, and testing on my own also considers it fixed. Closing as there is a lack of response from OP.
