### ISSUE TITLE
0.12.0 Beta 164 StreamFX.dll not loading in OBS 28.1.2

### ISSUE THREAD

**Issue by MasterEvilAce** [Xaymar/obs-StreamFX#991]
### OBS Studio Logs

14:18:29.940: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
14:18:29.940: CPU Speed: 4008MHz
14:18:29.940: Physical Cores: 4, Logical Cores: 8
14:18:29.940: Physical Memory: 16322MB Total, 10962MB Free
14:18:29.940: Windows Version: 10.0 Build 19045 (release: 2009; revision: 2311; 64-bit)
14:18:29.940: Running as administrator: true
14:18:29.940: Aero is Enabled (Aero is always on for windows 8 and above)
14:18:29.940: Windows 10/11 Gaming Features:
14:18:29.940: 	Game Bar: Off
14:18:29.940: 	Game DVR: Off
14:18:29.940: 	Game DVR Background Recording: Off
14:18:29.940: 	Game Mode: Off
14:18:29.941: 	Hardware GPU Scheduler: Off
14:18:29.942: Sec. Software Status:
14:18:29.943: 	Microsoft Defender Antivirus: enabled (AV)
14:18:29.943: 	Windows Firewall: disabled (FW)
14:18:29.943: Current Date/Time: 2022-12-03, 14:18:29
14:18:29.943: Browser Hardware Acceleration: true
14:18:29.943: Hide OBS windows from screen capture: true
14:18:29.943: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
14:18:29.943: Portable mode: false
14:18:29.975: OBS 28.1.2 (64-bit, windows)
14:18:29.975: ---------------------------------
14:18:30.020: ---------------------------------
14:18:30.020: audio settings reset:
14:18:30.020: 	samples per sec: 48000
14:18:30.020: 	speakers:        2
14:18:30.020: 	max buffering:   960 milliseconds
14:18:30.020: 	buffering type:  dynamically increasing
14:18:30.021: ---------------------------------
14:18:30.021: Initializing D3D11...
14:18:30.021: Available Video Adapters: 
14:18:30.022: 	Adapter 0: NVIDIA GeForce RTX 3070
14:18:30.022: 	  Dedicated VRAM: 4126146560
14:18:30.022: 	  Shared VRAM:    4262735872
14:18:30.022: 	  PCI ID:         10de:2484
14:18:30.023: 	  Driver Version: 31.0.15.2737
14:18:30.023: 	  output 0:
14:18:30.023: 	    name=ZOWIE XL LCD
14:18:30.023: 	    pos={0, 0}
14:18:30.023: 	    size={1920, 1080}
14:18:30.023: 	    attached=true
14:18:30.023: 	    refresh=144
14:18:30.023: 	    space=RGB_FULL_G22_NONE_P709
14:18:30.023: 	    sdr_white_nits=80
14:18:30.023: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
14:18:30.023: 	  output 1:
14:18:30.023: 	    name=BenQ XL2430T
14:18:30.023: 	    pos={-1920, 3}
14:18:30.023: 	    size={1920, 1080}
14:18:30.023: 	    attached=true
14:18:30.023: 	    refresh=144
14:18:30.023: 	    space=RGB_FULL_G22_NONE_P709
14:18:30.023: 	    sdr_white_nits=80
14:18:30.023: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
14:18:30.024: Loading up D3D11 on adapter NVIDIA GeForce RTX 3070 (0)
14:18:30.099: D3D11 loaded successfully, feature level used: b000
14:18:30.099: DXGI increase maximum frame latency success
14:18:30.099: D3D11 GPU priority setup success
14:18:31.419: ---------------------------------
14:18:31.419: video settings reset:
14:18:31.419: 	base resolution:   1920x1080
14:18:31.419: 	output resolution: 1280x720
14:18:31.419: 	downscale filter:  Bicubic
14:18:31.419: 	fps:               60/1
14:18:31.419: 	format:            NV12
14:18:31.419: 	YUV mode:          Rec. 709/Partial
14:18:31.419: NV12 texture support enabled
14:18:31.419: P010 texture support not available
14:18:31.421: Audio monitoring device:
14:18:31.421: 	name: Default
14:18:31.421: 	id: default
14:18:31.421: ---------------------------------
14:18:31.424: No AJA devices found, skipping loading AJA UI plugin
14:18:31.424: Failed to initialize module 'aja-output-ui.dll'
14:18:31.425: No AJA devices found, skipping loading AJA plugin
14:18:31.425: Failed to initialize module 'aja.dll'
14:18:31.425: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
14:18:31.428: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
14:18:31.429: Failed to load 'en-US' text for module: 'decklink-captions.dll'
14:18:31.430: Failed to load 'en-US' text for module: 'decklink-output-ui.dll'
14:18:31.432: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
14:18:31.432: Failed to initialize module 'decklink.dll'
14:18:31.457: [AMF] Unable to load 'amfrt64.dll', error code 126.
14:18:31.459: [AMF] AMF Test failed due to one or more errors.
14:18:31.459: Failed to initialize module 'enc-amf.dll'
14:18:31.471: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
14:18:31.471: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
14:18:31.471: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
14:18:31.490: [obs-browser]: Version 2.18.7
14:18:31.490: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2591+g4204d54+chromium-103.0.5060.134 (compiled)
14:18:31.494: NVENC supported
14:18:31.627: [NVENC] AV1 is not supported
14:18:31.755: [noise suppress]: NVIDIA RTX AUDIO FX enabled
14:18:31.772: [NVIDIA RTX VIDEO FX]: enabled, redistributable found
14:18:32.013: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.0.1 | RPC Version: 1)
14:18:32.014: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1
14:18:32.014: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
14:18:32.022: [obs-websocket] [obs_module_load] Module loaded.
14:18:32.027: [vlc-video]: VLC 3.0.17.4 Vetinari found, VLC video source enabled
14:18:32.051: Module 'C:\ProgramData\obs-studio/plugins/StreamFX/bin/64bit/StreamFX.dll' not loaded
14:18:32.051: ---------------------------------
14:18:32.051:   Loaded Modules:
14:18:32.051:     win-wasapi.dll
14:18:32.051:     win-mf.dll
14:18:32.051:     win-dshow.dll
14:18:32.051:     win-capture.dll
14:18:32.051:     vlc-video.dll
14:18:32.051:     text-freetype2.dll
14:18:32.051:     rtmp-services.dll
14:18:32.051:     obs-x264.dll
14:18:32.051:     obs-websocket.dll
14:18:32.051:     obs-vst.dll
14:18:32.051:     obs-transitions.dll
14:18:32.051:     obs-text.dll
14:18:32.051:     obs-qsv11.dll
14:18:32.051:     obs-outputs.dll
14:18:32.051:     obs-filters.dll
14:18:32.051:     obs-ffmpeg.dll
14:18:32.051:     obs-browser.dll
14:18:32.051:     image-source.dll
14:18:32.051:     frontend-tools.dll
14:18:32.051:     decklink-output-ui.dll
14:18:32.051:     decklink-captions.dll
14:18:32.051:     coreaudio-encoder.dll
14:18:32.051: ---------------------------------
14:18:32.052: ==== Startup complete ===============================================

### Current and Expected Behavior

Windows 10 64bit. OBS 28.1.2 64bit.
StreamFX 0.12.0 alpha 151 installs and works fine using the ALL USERS option.
StreamFX 0.12.0 beta 164 installs but does not load in OBS using the same ALL USERS option. The StreamFX menu option does not appear and OBS log indicates StreamFX.dll did not load.

I've uninstalled previous versions each time before installing the other. I can go between 151 and 164... 151 always loads while 164 always fails to load.

### Steps to Reproduce the Problem

I can reproduce this issue infinitely just by installing the specific version and launching OBS. I have not tried the other install options (current user/portable)

### Any additional Information we need to know?

I do NOT use any other third-party plugins for OBS. I DO have the nVidia audio and video effects SDKs installed and updated to the latest versions.
Here is what the StreamFX 151 log shows (expected output when DLL loads):

14:15:22.772: [StreamFX] Loading Version 0.12.0a151-g0f114f56
14:15:22.829: [StreamFX] <gfx::opengl> Version 0.0 initialized.
14:15:22.829: [StreamFX] <nvidia::cuda::cuda> Driver reported CUDA version: 12.0.0
14:15:22.892: [StreamFX] <nvidia::cuda::context> Initialized CUDA on device 'NVIDIA GeForce RTX 3070' (3eddc32a-2c22-11c6-65d2-951294bab50a, 0000ce63, 1).
14:15:22.895: [StreamFX] <nvidia::ar::ar> No supported NVIDIA SDK is installed to provide 'nvARPose.dll'.
14:15:22.895: [StreamFX] <filter::autoframing> Failed to make NVIDIA providers available due to error: Failed to load 'nvARPose.dll'.
14:15:22.895: [StreamFX] <filter::autoframing> All supported providers failed to initialize, disabling effect.
14:15:22.895: [StreamFX] Loaded Version 0.12.0a151-g0f114f56

**Comment by Xaymar** [comment]
Read the Release Notes.
