### ISSUE TITLE
Plugin doesn't load in OBS Studio 28.1.2 on Windows 11 Home version

### ISSUE THREAD

**Issue by yarsalanpk** [Xaymar/obs-StreamFX#996]
### OBS Studio Logs

I am using windows 11 home version. I have the latest version of OBS Studio as of date 13/12/2022 (dd/mm/yyyy) and i have installed obs-streamFX version 0.12.0 but the plulgin doesnt load in OBS Studio environment and nor it gives any error.

Regards

### Current and Expected Behavior

I am using windows 11 home version. I have the latest version of OBS Studio as of date 13/12/2022 (dd/mm/yyyy) and i have installed obs-streamFX version 0.12.0 but the plulgin doesnt load in OBS Studio environment and nor it gives any error.

Regards

### Steps to Reproduce the Problem

1. On Windows 11 home, install obs studio 28.1.2
2. install obs-streamFx 0.12.0 using .exe file
3. run OBS studio
4. StreamFx neither loads in OBS environment and nor it gives any error

**Comment by Xaymar** [comment]
#### Rejected: User Error
Read the release notes.
