### ISSUE TITLE
StreamFX 0.12.0 Beta 164 does not loadon OBS 28.1.2

### ISSUE THREAD

**Issue by KaleidonKep99** [Xaymar/obs-StreamFX#998]
### OBS Studio Logs

11:43:29.511: CPU Name: AMD Ryzen 9 5900X 12-Core Processor            
11:43:29.511: CPU Speed: 3700MHz
11:43:29.511: Physical Cores: 12, Logical Cores: 24
11:43:29.511: Physical Memory: 32689MB Total, 26170MB Free
11:43:29.511: Windows Version: 10.0 Build 22621 (release: 2009; revision: 963; 64-bit)
11:43:29.511: Running as administrator: false
11:43:29.511: Aero is Enabled (Aero is always on for windows 8 and above)
11:43:29.511: Windows 10/11 Gaming Features:
11:43:29.511: 	Game DVR: On
11:43:29.511: 	Game Mode: Probably On (no reg key set)
11:43:29.511: 	Hardware GPU Scheduler: Off
11:43:29.513: Sec. Software Status:
11:43:29.514: 	Windows Firewall: enabled (FW)
11:43:29.514: Current Date/Time: 2022-12-22, 11:43:29
11:43:29.514: Browser Hardware Acceleration: true
11:43:29.514: Hide OBS windows from screen capture: false
11:43:29.514: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
11:43:29.514: Portable mode: false
11:43:29.661: OBS 28.1.2 (64-bit, windows)
11:43:29.661: ---------------------------------
11:43:29.661: ---------------------------------
11:43:29.661: audio settings reset:
11:43:29.661: 	samples per sec: 48000
11:43:29.661: 	speakers:        2
11:43:29.661: 	max buffering:   960 milliseconds
11:43:29.661: 	buffering type:  dynamically increasing
11:43:29.662: ---------------------------------
11:43:29.662: Initializing D3D11...
11:43:29.662: Available Video Adapters: 
11:43:29.664: 	Adapter 0: NVIDIA GeForce GTX 1660 SUPER
11:43:29.664: 	  Dedicated VRAM: 1975517184
11:43:29.664: 	  Shared VRAM:    4253552640
11:43:29.664: 	  PCI ID:         10de:21c4
11:43:29.665: 	  Driver Version: 31.0.15.2756
11:43:29.665: 	  output 0:
11:43:29.665: 	    name=LG ULTRAGEAR
11:43:29.665: 	    pos={0, 0}
11:43:29.665: 	    size={2560, 1440}
11:43:29.665: 	    attached=true
11:43:29.665: 	    refresh=180
11:43:29.665: 	    space=RGB_FULL_G22_NONE_P709
11:43:29.665: 	    sdr_white_nits=80
11:43:29.665: 	    nit_range=[min=0.391500, max=408.760010, max_full_frame=408.760010]
11:43:29.665: 	  output 1:
11:43:29.665: 	    name=SyncMaster
11:43:29.665: 	    pos={1188, -1080}
11:43:29.665: 	    size={1920, 1080}
11:43:29.665: 	    attached=true
11:43:29.665: 	    refresh=60
11:43:29.665: 	    space=RGB_FULL_G22_NONE_P709
11:43:29.665: 	    sdr_white_nits=80
11:43:29.665: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
11:43:29.665: 	  output 2:
11:43:29.665: 	    name=HP 23xi
11:43:29.665: 	    pos={-1920, 352}
11:43:29.665: 	    size={1920, 1080}
11:43:29.665: 	    attached=true
11:43:29.665: 	    refresh=75
11:43:29.665: 	    space=RGB_FULL_G22_NONE_P709
11:43:29.665: 	    sdr_white_nits=80
11:43:29.665: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
11:43:29.665: 	Adapter 1: NVIDIA GeForce GTX 750 Ti
11:43:29.665: 	  Dedicated VRAM: 4248764416
11:43:29.665: 	  Shared VRAM:    4253552640
11:43:29.665: 	  PCI ID:         10de:1380
11:43:29.665: 	  Driver Version: 31.0.15.2756
11:43:29.668: Loading up D3D11 on adapter NVIDIA GeForce GTX 1660 SUPER (0)
11:43:29.717: D3D11 loaded successfully, feature level used: b000
11:43:29.717: DXGI increase maximum frame latency success
11:43:29.717: D3D11 GPU priority setup failed (not admin?)
11:43:30.756: ---------------------------------
11:43:30.756: video settings reset:
11:43:30.756: 	base resolution:   2560x1440
11:43:30.756: 	output resolution: 2560x1440
11:43:30.756: 	downscale filter:  Bilinear
11:43:30.756: 	fps:               60/1
11:43:30.756: 	format:            NV12
11:43:30.756: 	YUV mode:          Rec. 709/Partial
11:43:30.756: NV12 texture support enabled
11:43:30.756: P010 texture support not available
11:43:30.758: Audio monitoring device:
11:43:30.758: 	name: Kenwood Hi-Fi System (Realtek(R) Audio)
11:43:30.758: 	id: {0.0.0.00000000}.{63d3356d-070b-47f1-ba24-88d3e99e03c8}
11:43:30.758: ---------------------------------
11:43:30.759: Skipping module '../../obs-plugins/64bit/advanced-scene-switcher-lib.dll', not an OBS plugin
11:43:30.762: [adv-ss] version: 1.19.2
11:43:30.762: [adv-ss] version: 9bcced524bc456f3095b977f3af5966dfe14703e
11:43:30.762: [adv-ss] curl loaded successfully
11:43:30.762: [adv-ss] found curl library
11:43:30.762: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.dll"
11:43:30.765: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.dll"
11:43:30.765: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-openvr.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-openvr.dll"
11:43:30.766: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d460.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_calib3d460.dll"
11:43:30.766: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core460.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_core460.dll"
11:43:30.766: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d460.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_features2d460.dll"
11:43:30.766: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann460.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_flann460.dll"
11:43:30.766: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc460.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_imgproc460.dll"
11:43:30.766: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect460.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/opencv_objdetect460.dll"
11:43:30.766: [adv-ss] attempting to load "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/openvr_api.dll"
11:43:30.766: [adv-ss] successfully loaded "C:/Program Files/obs-studio/obs-plugins/64bit/adv-ss-plugins/openvr_api.dll"
11:43:30.809: No AJA devices found, skipping loading AJA UI plugin
11:43:30.809: Failed to initialize module 'aja-output-ui.dll'
11:43:30.810: No AJA devices found, skipping loading AJA plugin
11:43:30.810: Failed to initialize module 'aja.dll'
11:43:30.811: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
11:43:30.813: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
11:43:30.814: Failed to load 'en-US' text for module: 'decklink-captions.dll'
11:43:30.814: Failed to load 'en-US' text for module: 'decklink-output-ui.dll'
11:43:30.816: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
11:43:30.816: Failed to initialize module 'decklink.dll'
11:43:30.833: [AMF] Unable to load 'amfrt64.dll', error code 126.
11:43:30.834: [AMF] AMF Test failed due to one or more errors.
11:43:30.834: Failed to initialize module 'enc-amf.dll'
11:43:30.839: [Python] Could not load library: C:/Users/bribi/AppData/Local/Programs/Python/Python36/
11:43:30.840: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
11:43:30.840: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
11:43:30.840: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
11:43:30.848: [obs-browser]: Version 2.18.7
11:43:30.848: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2591+g4204d54+chromium-103.0.5060.134 (compiled)
11:43:30.851: NVENC supported
11:43:30.940: [NVENC] AV1 is not supported
11:43:30.941: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
11:43:30.943: [NVIDIA RTX VIDEO FX]: FX disabled, redistributable not found.
11:43:31.272: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.0.1 | RPC Version: 1)
11:43:31.272: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1
11:43:31.272: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
11:43:31.277: [obs-websocket] [obs_module_load] Module loaded.
11:43:31.283: [vlc-video]: VLC 3.0.18 Vetinari found, VLC video source enabled
11:43:31.284: Failed to load 'en-US' text for module: 'win-capture-audio.dll'
11:43:31.284: [win-capture-audio] Version 2.2.3 (74323e6)
11:43:31.297: Module 'C:/Users/bree/AppData/Local/Programs/obs-studio/plugins/StreamFX/bin/StreamFX.dll' not loaded <<<<<<<<<<<<<

### Current and Expected Behavior

The plugin is expected to load.

### Steps to Reproduce the Problem

1. Install StreamFX 0.12.0 beta 164 on OBS 28.1.2
2. Run OBS

### Any additional Information we need to know?

Downgrading to StreamFX 0.12.0 alpha 151 fixes the problem, the plugin loads as expected.
The computer is running Windows 11 22H2 22621.963.

**Comment by skeletonbow** [comment]
According to the StreamFX 0.12.0 beta 164 release notes, the minimum OBS version required is OBS 29.0.0beta presently.

**Comment by driahva** [comment]
While I can accept the answer above, neither stable nor two of the beta versions appear to be working.  Is there a current built (experimental or otherwise) which works with 28.1.2?

**Comment by Xaymar** [comment]
#### Rejected: User Error
**PLEASE READ THE RELEASE NOTES.**

**Comment by Xaymar** [comment]
They're extremely clear though. There's the minimum version, and a recommended version. If you mismatch either one, it's going to cause issues, and you'll fall out of support. Simply as that.

**Comment by KaleidonKep99** [comment]
Oops! My fault for not being careful while reading. I apologize.
